### PR TITLE
Allow using matomo prefixed parameters for campaigns such as matomo_campaig/mtm_campaign

### PR DESCRIPTION
**Pull request by sgiehl**
Shall we maybe also add something like `mtm_campaign`?

refs #12420

### CODE REVIEW

**Comment by diosmosis** [comment]
Seems strange to not use allow mtm_ prefix as well.

**Comment by tsteur** [comment]
btw `mtm` stands for `matomo tag manager`. Of course could also stand for `matomo` :) I have not really and preference but maybe wouldn't provide too many options. I can't really think of a reason why it would be an issue for people to still use `pk_` but could also allow `mtm` additionally

**Comment by sgiehl** [comment]
also added the mtm_ prefixes. We maybe should update the documentation for Matomo 4 later so we suggest to use the new parameter names...

**Comment by diosmosis** [comment]
Weird, the build didn't run for this PR?

**Comment by sgiehl** [comment]
build js

**Comment by sgiehl** [comment]
> Weird, the build didn't run for this PR?

It actually did, but it's not linked here 🤷

**Pull request merged**
