### PR TITLE
New Piwik Ini component

### PR DESCRIPTION
**Pull request by mnapoli**
This PR is a suggestion for a new Piwik component to read and write INI configurations.

The new component contains 2 classes:
- `IniReader`: content extracted from the shim in `upgrade.php` that makes it work even if the native PHP function is disabled
- `IniWriter`: content extracted from `Config` (so it clears up this class a little bit)

Just like _Symfony Yaml_, I think this INI component could be interesting to be shipped as a standalone component. It's a good example of a small reusable one.

Here is the advantages of this component that I would write in its README:
- allows to read _and_ write (no native PHP function to write INI files)
- the classes are mockable in unit tests
- works even if `parse_ini_file()` is disabled
- throws exceptions instead of errors (can be easily catched, less `if ( === false)`…)
- boolean support when parsing: `true`, `yes`, `on` are actually converted to `true` instead of `1`, same for `false`, `no`, `off`

Here is the advantage for us:
- we can mock in tests (I needed it for https://github.com/PiwikPRO/plugin-EnterpriseAdmin/issues/10)
- less clutter in `Config`
- one new good component that people can reuse :)

Thoughts?

### CODE REVIEW

**Comment by mattab** [comment]
Great idea, this change makes our code less cluttered and cleaner, and also will benefit the community, it is a great move :+1:

**Comment by Globulopolis** [comment]
@mnapoli you say "works even if parse_ini_file() is disabled" - maybe we need to add some checks if function exists instead of writing own function, because native function much faster.

And $array = @parse_ini_string($ini, true, INI_SCANNER_RAW); what is it? Suppress an error output is bad idea I'm think.

**Comment by mnapoli** [comment]
@Globulopolis thanks for the feedback.

It does use the native PHP function, the shim is just used if the function is disabled.

Regarding `@parse_ini_string(...)` suppressing an error would be bad if it was just suppressed, but:

```php
$array = @parse_ini_string($ini, true, INI_SCANNER_RAW);

if ($array === false) {
    $e = error_get_last();
    throw new IniReadingException('Syntax error in INI configuration: ' . $e['message']);
}
```

I'm actually checking for the error just afterwards and turning it into an exception. So the error is not silenced, it's turned into an exception.

**Comment by mnapoli** [comment]
The new component is here: https://github.com/piwik/component-ini

**Comment by mattab** [comment]
Nice, gotta love new small reusable components keeping the core lean :+1:

**Pull request merged**
