### PR TITLE
Don't force enable low population when using all columns table

### PR DESCRIPTION
**Pull request by tsteur**
Please issue pull request against the `3.x-dev` branch as the `master` branch currently represents our `2.X` version which is in LTS mode. 

Important fixes will be merged into `master` if needed after it was merged to `3.x-dev`.

Not sure why it is enabled there but seems buggy and it doesn't allow plugin developers to disable it

### CODE REVIEW

**Comment by mattab** [comment]
It seems to have regressed this: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/20336/ViewDataTableTest_4_exclude_low_population.png

**Comment by tsteur** [comment]
The change is supposed to be. It does not exclude low population anymore as it is disabled for that report

**Comment by tsteur** [comment]
This is actually a fix

**Comment by mattab** [comment]
Ok so the UI test needs to be updated for the "exclude low population" to be UI tested in another report which enables the feature

**Comment by tsteur** [comment]
I have updated the test

**Pull request merged**
