### PR TITLE
Fix super-admin website IDs check

### LINKED ISSUE #8697: do not allow to set access to non existing websites
As a Super User, currently I can set user access to websites that don't exist yet.

Reproduce:
- go to: http://localhost.com/piwik-master/index.php?date=yesterday&module=API&format=json&method=UsersManager.setUserAccess&period=day&userLogin=user1&access=view&idSites=1,4,2,5&token_auth=xyz
- when setting permission by setting idSites = non existent values (eg. `4,5`)  the user will get access to non existing sites. When these new sites will be added t,he user will have access already on these new websites.
- Expected: it should not be possible to assign access to a website that does not yet exist.

reported by Haseeb

### PR DESCRIPTION
**Pull request by Valair**
Force website IDs existence check even for super-admin.
Resolve https://github.com/matomo-org/matomo/issues/8697

### CODE REVIEW

**Comment by tsteur** [comment]
@Valair thanks for this 👍 
As I thought a LOT of tests are now failing see eg https://travis-ci.org/matomo-org/matomo/jobs/528746645
https://travis-ci.org/matomo-org/matomo/jobs/528746646 and https://travis-ci.org/matomo-org/matomo/jobs/528746647

In our test fixtures a lot of tests will need to be corrected.

I see it complains eg that in an AnnotationTest the user doesn't have view access to idSite 2. Looking at https://github.com/matomo-org/matomo/blob/3.10.0-b1/tests/PHPUnit/Fixtures/TwoSitesWithAnnotations.php#L27 the two websites seem actually created. So not sure if the tests needs adjusting or if there are more things to change in the `Access` class itself.

Fixing all those tests can take quite a long time and possibly also some debugging etc. Please let us know if you're keen looking into it or not.

**Comment by Valair** [comment]
Ok, I will try to setup e dev/test environment to look into those failed tests.

**Comment by mattab** [comment]
Hi @Valair Thank you for the PR! Do you think you will be able to setup the test environment to adjust tests? Be awesome if you can. We'd like to merge the PR :+1:

**Comment by Valair** [comment]
Hi @mattab, I've setup a test environment and I'm slowly working on fixing tests

**Comment by tsteur** [comment]
@Valair closing this PR for now. Let me know if you're planning to work on it again and I can reopen. Cheers

**Pull request closed without merging**
