### PR TITLE
ProxySite related changes to let comparisons work properly

### PR DESCRIPTION
**Pull request by diosmosis**
Changes:
- Make sure ProxySite will disable post processor in Visualization where API Proxy is called directly. Otherwise the target.
- Use `Request::process()` for `SegmentEditor.getAll` calls.

### CODE REVIEW

**Comment by tsteur** [comment]
@diosmosis looks good in general but wondering if https://builds-artifacts.matomo.org/matomo-org/matomo/3.x-dev/37332/UIIntegrationTest_goals_individual_goal_updated.png
and 
https://travis-ci.org/matomo-org/matomo/jobs/624430881#L992
 is maybe failing because of this change? Or another change?

**Comment by diosmosis** [comment]
Yes it's failing due to `disable_datatable_post_processing` since it will get propagated to other requests. We'll probably want to get rid of this on staging.

**Comment by diosmosis** [comment]
Modified the parameter to only apply to the top level API request.

**Comment by diosmosis** [comment]
Tried a different approach, if the tests pass, would be useful to have on staging.

**Comment by tsteur** [comment]
@diosmosis this tests is still failing and not sure it's due to this PR ? https://travis-ci.org/matomo-org/matomo/jobs/625560724#L923

**Comment by tsteur** [comment]
@diosmosis the change is on staging

**Comment by diosmosis** [comment]
The updated changes seem to work.

**Review by tsteur — APPROVED** [review]

**Comment by tsteur** [comment]
Looks like tests are passing now?

BTW do you know why those tests are failing? Must be from some previous change? https://travis-ci.org/matomo-org/matomo/jobs/628335284#L1176-L1439

**Comment by diosmosis** [comment]
That's from another PR, shouldn't be related to this one (plugin builds not updated).

Tests are passing, but I changed the code a bit to do that, can you take another look?

**Comment by tsteur** [comment]
Looks good @diosmosis

**Pull request merged**
