### PR TITLE
Add new category profiles plus new visitors report

### PR DESCRIPTION
**Pull request by tsteur**
We could also add a Real-Time section as the current real time widgets are not exposed in the UI...

image

Real-Time Map etc may be still better under "Visitors".

Renamed "Visitor Log" to "Visits Log" as this is more accurate, but could also keep the original name.

The "Visitors" report is queried live and not archived as we would otherwise need to archive thousands or millions of rows to make this usable properly.

### CODE REVIEW

**Comment by mattab** [comment]
:+1: for adding real time menu, also embedding the map would be awesome.

**Comment by mattab** [comment]
Real time Map in the real time page

**Comment by tsteur** [comment]
Menu currently looking like this:

image

* Real time visitors is tweaked a little bit to optimize for the available space we have there... (could be done more potentially but is tricky)
* For visitors report we would need to fix the row action icons see https://github.com/matomo-org/matomo/issues/13419 
* Quite useful in visitors report the "show profile" button but also the "segmented visitor log" to view all visits of a visitor within a certain range...

**Comment by mattab** [comment]
See discussion on this PR in https://github.com/matomo-org/matomo/issues/13419#issuecomment-424198508 (I commented on the wrong issue...)

**Comment by tsteur** [comment]
Todo: Need to add "revenue" info but I think this may not be present in visits table and maybe need to add it in Matomo 4

**Comment by tsteur** [comment]
FYI: We will keep this issue open for now as we want to see how we can make the profiles report useful as a real time report at some point. For regular report it wouldn't be fast enough unless we created archives for each sort column etc and kept eg only 1000 rows.

menu changes are now in 
https://github.com/matomo-org/matomo/pull/13518

**Comment by diosmosis** [comment]
Moving out of this milestone.

**Comment by diosmosis** [comment]
@tsteur has some conflicts that need to be resolved (tried myself but wasn't able to determine what to change).

**Comment by tsteur** [comment]
@mattab not sure if we still want to have this in Matomo 4 or not? I think we wanted to have a look once we start Matomo 4 or so but not sure. 

It's difficult decision... adds yet another menu item, at the same time not everything is 100% profiles maybe?  Personally, I'm not yet 100% convinced.

**Comment by mattab** [comment]
agreed that adding yet another menu is an issue. Here is an idea: we could show `Visits log` menu only, and when people click it shows the visits log. then there would be a link/button/tab  (above fold) labelled `Visitors log` and when clicked, it would replace the Visits log with the Visitors log?

**Comment by tsteur** [comment]
@mattab from a usability point of view not so great either. Personally, thinking to simply not add this report for now. Not seeing users asking for it? Or maybe there is an issue with some interest? Of course it's a nice to have, but maybe not really really super needed and just cluttering the UI. Also from a privacy point of view it starts making things complicated maybe. (eg once we have feature to disable visitor profile then it also needs to disable this button etc etc. not too much of an issue though).

**Comment by tsteur** [comment]
closing this for now

**Pull request closed without merging**
