### PR TITLE
Fixes row evolution for rows containing encoded entities

### LINKED ISSUE #19485: Fixes Goal row evolution with double quotes in the goal name resulting in an error
If a goal has double quotes in its name, then Matomo cannot plot the conversion lines in the Row evolution graph. A javascript error occurs on the console.

## Current Behavior to reproduce
1. Choose a goal with conversions
2. Rename the goal and insert double quote in the name. F.e. _Newsletter "Sport"_
3. Select the goal and go to "Goals by Referrers"
4. Select any row with a conversion
5. Open row evolution (see screenshot 1)
6. Select line with conversion (see screenshot 2)

In step 6 a javascript error will occur and no line will be drawn.

screenshot 1
grafik

screenshot 2
grafik

* Matomo Version: 4.10.1
* Browser: Firefox

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #19485

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — CHANGES_REQUESTED** [review]
I've tested the original issue again and it is fixed with this PR :+1:

I did notice that the goal name is broken on the goal overview screen and on the evolution chart legend, it's not part of the original issue but it would probably make sense to fix it here too.

m19485-2


m19485-1

**Comment by sgiehl** [comment]
@bx80 Those double encoding is actually a side effect of having the goal data automatically sanitized before being stored in the database (See e.g. https://github.com/matomo-org/matomo/issues/4231). I've now adjusted the Goals API so it unsanitizes the data before it's returned. I've tried to check & adjust all usages of the goals to ensure this won't open up any security issues. (There were at least some tooltips where it was possible to inject html code using html in the goal name).
So when reviewing the new changes you should also look through all places where goals are being used.

**Review by bx80 — APPROVED** [review]
I've spent some time checking all the places where goal names are used, I can't see any issues. There is one UI screenshot `Goals_action_goals_row_evolution.png` which needs updating but other than that it all looks good :+1:

**Comment by MatomoForumNotifications** [comment]
This pull request has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-plugins-goals-api-php-117/47716/2

**Pull request merged**
