### PR TITLE
Ensure all file handles to GeoIP databases are closed before replacing the file

### LINKED ISSUE #17023: Starting with php 7.3 on windows OS the geoip2php Update procedure is not working anymore.
I enable geoip2php, download the file and save the settings, 

then after at least one week it disables automatically and when navigating to the geo configuration page it shows this error message in red:

`The configured geolocation provider geoip2php is not available anymore, please configure another one.`

I need then to download the file again and start from beginning.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #17023

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by diosmosis — APPROVED** [review]
code looks good, I would personally but the cleanup logic in a explicit method to close the file handles rather than rely on php calling __destruct (in case there ends up being a strange case where it doesn't get called), but I think it will work regardless.

**Comment by mstenz** [comment]
let me test the code and give you feedback

**Comment by mstenz** [comment]
it works for me.

**Comment by sgiehl** [comment]
@mstenz thanks for confirming

**Pull request merged**
