### PR TITLE
ManageGoals text edits, add (non-editable) Goal table

### LINKED ISSUE #7836: Manage Goals shows "Create a new goal" when not having enough permission
On demo.piwik.org when clicking on Goals => Manage Goals this is what I see:

manage_goals

Instead I would expect to see a title "Manage Goals" and instead of the description saying "...can add Goals for a given website..." I would expect something with "... manage goals ...". 

Moving it to short term as this is happening for anonymous users on demo.piwik.org (potential new users) and it might give them a bit of a negative (buggy) impression.

### PR DESCRIPTION
**Pull request by spacenate**
fixes #7836 

The text changes proposed in #7836 were fairly simple. I added one new translation key, `Goals_NeedAccess`, because the existing translation key (`Goals_NoGoalsNeedAccess`) assumes you don't have a Goal for a given website.

I also duplicated _addEditGoal.twig and _listGoalEdit.twig, and modified them to make _viewGoal.twig and _listGoalView.twig. This included removing the last two columns of the table (edit/delete), and the "Add a new Goal" button. There's some Javascript at the bottom of _listGoalView.twig that is probably unnecessary, but I haven't taken a peek at what that does yet.

manage_goals_table

### CODE REVIEW

**Comment by mattab** [comment]
Hi there,

Thanks for the pull request!

> I also duplicated _addEditGoal.twig and _listGoalEdit.twig, and modified them to make _viewGoal.twig and _listGoalView.twig.

In general duplicated code is not something we can accept at any cost in Piwik. Duplicated code is a common anti pattern of software engineering and there is always a better way to solve a problem by refactoring the code. If you understand this, please feel free to modify the pull request accordingly. Cheers

**Comment by spacenate** [comment]
Hi @mattab,

Thank you for your feedback! I have modified my pull request to avoid the duplicate code, and also added some logic to load only the templates and Javascript necessary for non-admin users.

Please let me know if you have any other comments, I appreciate anything that helps me contribute higher-quality code :)

**Comment by mattab** [comment]
Thanks @spacenate for updating your PR :-) we will review it for 2.15.0

**Comment by diosmosis** [comment]
Looks good to me. @spacenate Can you rebase your branch? I will merge afterwards.

**Comment by spacenate** [comment]
Hi @diosmosis, happy to!

**Pull request merged**
