### PR TITLE
[Vue] migrate segment generator directive to Vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:

* Migrate piwik-segment-generator directive and related model to Vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
@diosmosis Overall looks good to me, but I notice when you have a segment that does not exist, it popup the error in the back. The old version doesn't show any info at all. I guess that's an improvement, but should that error banner `z-index` be higher than the popup? 

https://user-images.githubusercontent.com/3783072/160307864-d0a62678-f1db-4568-9e7f-c671b3e7eedf.mp4

**Comment by diosmosis** [comment]
@peterhashair The notification probably shouldn't have a higher z-index, otherwise it'll look strange. I'm not sure how to fix that UX issue. If it's the same for 4.x-dev perhaps it should be in a new issue. If not, it's some sort of bug.

So I can reproduce it, can you tell me if you have Ecommerce disabled?

**Comment by peterhashair** [comment]
@diosmosis that feature wasn't existing in 4.x-dev, but that is a UX issue, not related to this PR. But there is a JS error on the test see here https://app.travis-ci.com/github/matomo-org/matomo/jobs/564782879

**Comment by diosmosis** [comment]
@peterhashair those are the tests for the tracker JavaScript, this PR shouldn't relate to those.

**Review by peterhashair — APPROVED** [review]
looks good to me

**Comment by peterhashair** [comment]
> @peterhashair those are the tests for the tracker JavaScript, this PR shouldn't relate to those.

@diosmosis sorry, wasn't looking through details.

**Pull request merged**
