### PR TITLE
New segment 'languageCode'

### LINKED ISSUE #3950: New segment 'language'
We should have a segment for "user language". Maybe this involves rewriting the data and storing only one language, instead of storing the whole string as we do now in location_browser_lang

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #3950

### CODE REVIEW

**Comment by mattab** [comment]
@sgiehl a couple System tests are failing, here is some background info:
- this system test AutoSuggestAPITest is testing that all segments work
- it tests that the "Auto complete suggests" will return values for that segment
- for the segment to have "auto complete suggestions" we need to track visits with segment values in the test fixture. the fixture is: https://github.com/piwik/piwik/blob/master/tests/PHPUnit/Fixtures/ManyVisitsWithGeoIP.php#L191-191 - maybe if you edit it to set `setBrowserLanguage` on the fixture visits, then the test may pass

**Comment by sgiehl** [comment]
@mattab system tests are ok now

**Comment by tsteur** [comment]
Can you maybe try to add `$dataTable->filter('AddSegmentValue');` similar as done here: https://github.com/piwik/piwik/blob/master/plugins/DevicesDetection/API.php#L237 in `UserLanguage\API` for those reports?

This might add the "One-click-segment feature" to those reports. If it works you will see in the language report on row hover an icon that opens a popup showing the visitor log with all the users having the same language. Unfortunately, we still have to add this manually each time. It's not guaranteed it works as easy as that though. If not, we could create a new issue to add it for those reports.

**Comment by sgiehl** [comment]
@tsteur seems to work

**Comment by tsteur** [comment]
:+1:

**Comment by mattab** [comment]
@sgiehl I found a minor issue, see previous comment.

otherwise :+1:

**Comment by sgiehl** [comment]
Ok. I'll have a look

**Comment by sgiehl** [comment]
I've checked that and push it to master later. Correct segment is ```languageCode==fr,languageCode=@fr-``` to avoid matches for language codes like ```de-fr```

**Comment by mattab** [comment]
> Correct segment is ```languageCode==fr,languageCode=@fr-``` to avoid matches for language codes like ```de-fr```

oh that's smart! :+1:

**Comment by mgonera** [comment]
@mattab @sgiehl Please confirm if this will be included in 2.14 or in which other version?

**Comment by sgiehl** [comment]
Should be in 2.14 or in any of the latest beta versions

**Comment by mattab** [comment]
@mgonera Here is a useful github trick. if you click on the commit, you will arrive on commit page. there Github shows which tag already contains this commit. For this particular commit you can see: 
commit

-> this change is available since 2.14.0-b4

**Comment by mgonera** [comment]
@mattab very cool, thanks! this for sure will come in handy

**Comment by mattab** [comment]
Note: the new segment is actually `languageCode`. Added to developer changelog in https://github.com/piwik/piwik/commit/980c12bbe40f1225a895da1f4efa4d1d3d4dcd0c

**Pull request merged**
