### PR TITLE
Update intl cldr 39

### PR DESCRIPTION
**Pull request by Findus23**
followup to #15607

While looking into the translations, I noticed that this hasn't been updated in a while and the URLs were pointing to the old archived repositories.
I also updated the URLs to not point to the master branch (containing beta versions), but at a stable release.

I replaced VEF with VES (see https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar)

Lastly I ran the script once with the latest 39 release and checking the English, German and French strings the changes are quite minor.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by Findus23** [comment]
The largest change I noticed while scrolling through the files (as far as I can see without understanding most languages) is that Spanish now doesn't have any dots anymore after short day/week/etc. names (so `lun` instead of `lun.`)

Also a large fraction of the Georgian file has changed as words like `აზია` have been replaced with `Აზია` with the first letter now being a `GEORGIAN MTAVRULI CAPITAL LETTER AN`. Mtavruli seems to be a concept similar to uppercasing, is used in titles and a rather recent addtion to unicode 11 in 2018.

**Comment by tsteur** [comment]
@Findus23 @sgiehl do we have a command to generate this? Should this be executed periodically say every 6 months? If that's the case be great to know then we can document this internally and create a process for it.

**Comment by Findus23** [comment]
@tsteur Apart from the first two commits this is just a run of `php console translations:generate-intl-data` (and the next time updating `$CLDRVersion`)

**Comment by tsteur** [comment]
how often should this happen?

**Comment by Findus23** [comment]
I added a short description on how to update to https://github.com/matomo-org/developer-documentation/pull/523

I'd say at most this needs to be updated ever major release of CLDR (which is every few months), but in this PR we are skipping three major releases and the changes are still pretty minor. 
So I'd say to do this every 1-2 years or when a country/language/currency in the world changes its name (like with North Macedonia and Eswatini in the last PR).

And when a new Language is added to Matomo, I think this also needs to be done to fetch the strings for this language.

**Comment by tsteur** [comment]
Thanks I've documented this process also internally and set up a reminder every 6 months for us to look into this.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
