### PR TITLE
fixed an issue that display incorrect in Chrome

### PR DESCRIPTION
**Pull request by Aqours**
fixed an issue that display incorrect in Chrome

### CODE REVIEW

**Comment by MinonHeart** [comment]
I still have this problem.
-------------------------------------
Google Chrome: 40.0.2214.111 (Stable) m
Piwik: Version 2.10.0

**Comment by MinonHeart** [comment]
The blue triangle should be control of the code（CSS）
```
.menuDropdown .title:after {
    ...; 
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid #4183C4;
    ...;
}
```

I don't understand the function of this code（CSS）①
```
.menuDropdown .title:after { 
   ...;
   content: " \25BC";
   ...;
}
```.
① Can display in Chrome, but don't display in Firefox or IE. And I use simple code to test that.
The code
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mytest</title>
    <style>
        .t:after {
          content: '';
          top: 5px;
          right: -15px;
          color: #4183C4;
          display: inline;
          content: " \25BC";
          font-size: 1px;
          height: 0px;
          width: 0px;
          border-left: 4px solid transparent;
          border-right: 4px solid transparent;
          border-top: 5px solid #4183C4;
        }
    </style>
</head>
<body>
    <div class="t">mytest</div>
</body>
</html>
```
The screenshot of different browser displayed.
Chrome ↓↓↓
![2015-02-16_220539](https://cloud.githubusercontent.com/assets/8586286/6213190/155c26b2-b628-11e4-86f5-57d8195058e5.png)

Firefox ↓↓↓
![2015-02-16_220600](https://cloud.githubusercontent.com/assets/8586286/6213205/3bf2242a-b628-11e4-8c6b-ccda8c21cdfc.png)

**Comment by mattab** [comment]
@MinonHeart which version are you using? can you try with 2.11.0-RC if you are not using this yet? http://forum.piwik.org/read.php?2,124222,124222#msg-124222

**Comment by MinonHeart** [comment]
@mattab I'm using piwik-2.10.0.
@mnapoli The problem still exist when I try piwik-2.11.0-RC or visit http://demo.piwik.org on another PC.

**Comment by mattab** [comment]
@MinonHeart Can you please create an issue with the screenshot and browser used ? thanks

**Pull request closed without merging**
