### PR TITLE
fix: change description for segments visitEndServer*

### PR DESCRIPTION
**Pull request by toredash**
visitEndServer* does not show when a visits ends, but when the last action for the visit was. 

Modifications for other languages should be done as well

### CODE REVIEW

**Comment by toredash** [comment]
closes #15179

**Comment by tsteur** [comment]
👍 @mattab can you have a quick look here?
@toredash we'll need to fix some tests like the ones failing here. https://travis-ci.org/matomo-org/matomo/jobs/646313431?utm_medium=notification&utm_source=github_status  Have you done this before? We might be able to merge it and then fix the tests in a separate PR

**Comment by toredash** [comment]
@tsteur  No I haven't done this before. Looked at the builds and I altered one test that is related to this PR. Waiting for the build results now

**Comment by toredash** [comment]
@tsteur I'm not sure where I go in the code to resolve these;
https://travis-ci.org/matomo-org/matomo/jobs/647297552#L966

If you could point me to the correct location that would probably help, thanks

**Comment by mattab** [comment]
@toredash to fix this test, you can do the same as you did for the other test ie. overwrite the files within the folder `plugins/Live/tests/System/expected/test_actionSegment__*.xml`  by the files that were in the `plugins/Live/tests/System/processed` folder on your machine after you ran the tests and generated the new correct responses.

**Comment by tsteur** [comment]
@toredash I'll merge this now in a branch on our side so I can fix the tests afterwards. THanks for this 👍

**Pull request merged**
