### PR TITLE
Update notify list for github stale actions

### PR DESCRIPTION
**Pull request by justinvelluppillai**
### Description:

Add justinvelluppillai and remove flamisz to stale issue/PR notification

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by justinvelluppillai** [comment]
Maybe later we can create a stale notifications team to make this easier but updating individuals for now

**Review by sgiehl — APPROVED** [review]

**Comment by Findus23** [comment]
Wouldn't it be easier to just ping a team like in `@matomo-org/core-team` and then just update the people on the team as needed?

For this we would either need to change the core-team list or create a new team.

**Comment by sgiehl** [comment]
as @justinvelluppillai also mentioned. But would be good to have a new team for that, so not all core team members are mentioned. 
@tsteur @mattab could you maybe create a new team for that?

**Comment by tsteur** [comment]
@sgiehl created a team `matomo-org/core-reviewers`

**Comment by Findus23** [comment]
@sgiehl,  @justinvelluppillai Sorry, I totally missed that message above

**Pull request merged**
