### PR TITLE
Make old Sparkline Library support PHP 7.2

### PR DESCRIPTION
**Pull request by Findus23**
Quick fix for #12065 until #12066 is ready to merge.
Refs #11936

Also fixed a typo in the library (but I guess that code isn't executed, otherwise we should have noticed in the last 10 years (since https://github.com/piwik/piwik/commit/e8700c0c7dd08869b93ed1d092d90bb7cd3716e3))

### CODE REVIEW

**Review by sgiehl — APPROVED** [review]
Code looks good and works with PHP 7.1. (don't have a running 7.2 atm.)

**Comment by Findus23** [comment]
I also don’t have a running php 7.2 system, so I haven’t tested it. 
And travis doesn’t seem to like me, as it either runs for 6 hours or fails at Cloning into 'submodules/browser-logos'... (a submodule of my piwik icons repo)

Maybe we shouldn’t clone submodules recursively.

**Comment by sgiehl** [comment]
Seems travis had some problems or so. I've restarted the builds and now it succeeded.

**Comment by mattab** [comment]
:+1:

**Pull request merged**
