### PR TITLE
on Mobile Device, let users drag and drop items such as segments, using touchpunch library

### PR DESCRIPTION
**Pull request by wronan**
A fix for this https://github.com/piwik/piwik/issues/9196 issue.
Vide http://touchpunch.furf.com/ for more details.

### CODE REVIEW

**Comment by mattab** [comment]
Thank you for the pull request!

**Comment by tsteur** [comment]
@mattab can we maybe test this tmrw by deploying it to demo2?

@wronan there are currently 155 open issues and 30 pending pull requests for this one project see https://github.com/furf/jquery-ui-touch-punch/issues and https://github.com/furf/jquery-ui-touch-punch/pulls and code haven't been updated in 2 years. Maybe there is a better plugin or so? Also have you clicked through the whole UI to see if there are any regressions and whether the UI becomes maybe slower?

**Comment by wronan** [comment]
@tsteur I haven't clicked through the whole UI (like 100% - all subpages) but I haven't notice any regression.
On the other hand I keep my Piwik's test env on CentOS and somehow it's rather slow by default. Demo is light speed compared to my Piwik. If you like I may provide you access to my instance.

And regarding the package: I've seen that it hasn't been updated for two years but it's highly recommended through the community. On the other hand there are at least (I think) forks that can be taken under consideration.

**Comment by tsteur** [comment]
I was more wondering whether eg scrolling performance slowed down or when touching the screen as it is listening to some more events but might be fine. I will try to deploy it on a server for a test later and have a look. If there's any more up to date fork that would be great.

**Comment by tsteur** [comment]
I tested it with a Samsung Galaxy S4 and it did make some UI actions slower but it should be still ok but laggy etc. It's not super usable but the drag & drop kind of worked after figuring out how to use it. 

What needs to be tested is what happens on devices that support touch and mouse eg like the MS Surface see 
http://stackoverflow.com/questions/14406161/listening-to-mousedown-and-touchstart-on-devices-that-use-touch-and-a-mouse-e-g

The library installs itself on all devices that support the touch API see https://github.com/furf/jquery-ui-touch-punch/blob/master/jquery.ui.touch-punch.js#L14-L18 . Do you maybe have a device with touch and mouse support and see if events are eg triggered twice?

**Comment by wronan** [comment]
Hmm... I don't have access to such device at the moment but it's not a bad idea to check it. I will think of something.
For now I will set up another instance without that lib and try to compare user experience on both of them. I noticed that drag'n'drop is a little bit laggy, but to be hones, I mostly use my smartphone for emails and Slack so I can't compare it to other applications. I also have GalaxyTab (somewhere around, have to find it first :) ), will check that also.

**Comment by sgiehl** [comment]
I can test that on my laptop at work the next days. It has a touch display ;)

**Comment by wronan** [comment]
Ohh... that would be great. I was thinking of visiting my old friend who has touch screen on his notebook but I won't have an occasion for at least 2 weeks.

There is also this:
https://github.com/Bantam/jquery-ui-touch-punch-improved
Will try that out.

**Comment by adaqus** [comment]
@sgiehl Have you maybe tested that on your laptop?

**Comment by sgiehl** [comment]
Sorry, I was too busy, but I'll try to test that at the weekend

**Comment by sgiehl** [comment]
Just did a quick test with my laptop with touch display. Besides the problem, that Piwik isn't responsible at all (widget / segment menu is opened outside of visible screen) most parts seem to be usable.
Drag and drop works for segment editor and widgets aswell. 
Some stuff isn't working because of the missing hover effect: e.g. Widgets can't be closed / removed / resized, as the icons only show on hover and various tooltips and details aren't displayed. But that shouldn't be a problem of the library.

**Comment by tsteur** [comment]
OK so as this was specifically for segment selector we can merge it maybe. We might just need to remove it again in case users experience other issues.

BTW: I'm working on making Piwik 3 a bit more responsible but it'll take a few weeks or months.

**Comment by mattab** [comment]
I'm merging it, and we can take a few days to test it out :+1: 
(it will be deployed on demo.piwik.org as soon as a new beta will be released this week)

**Comment by tsteur** [comment]
In https://github.com/piwik/piwik/issues/10376 someone else reported as well that it makes the UI slower. Maybe we need to revert this patch and find a better solution that fixes only this issue and not tries to solve it in general

**Comment by Glisse1** [comment]
In any mobile site, trying to scroll down works regardless of the point on screen where you touch down. That could be a link, a blank text, a photo, anything, if you then move the finger, the page scrolls, always.
 
On Piwik after this upgrade you need to be careful not to touch the screen on widget s top-bars, because it wont scroll but rather move the widget. Because only Piwik is different, I would never remember this, hence the hit-miss lottery. Either revert this, or introduce the long press for moving. And important, we also need widget buttons back for refreshing, closing, etc, which I believe they are also related to  this PR

**Comment by mattab** [comment]
> Maybe we need to revert this patch and find a better solution that fixes only this issue and not tries to solve it in general

+1 - what do you think about reverting this patch in 3.0.0 but leaving it in LTS ?

**Pull request merged**
