### PR TITLE
 	Warn users (in all admin pages) when the PHP version is not recent enough to upgrade Piwik to latest major version

### PR DESCRIPTION
**Pull request by mattab**
refs #8847 #8156 https://github.com/piwik/piwik/pull/9144  #9047

### CODE REVIEW

**Comment by mattab** [comment]
# It looks like this

warning when php is not recent enough to use latest major piwik version


Also added a note to keep this up to date when we switch major versions in our wiki page about switching major versions checklist: https://github.com/piwik/piwik/wiki/New-major-releases

**Comment by utrenkner** [comment]
@mattab The warning is good - but it does not seem to work correctly. 

On one server we still run Debian 7 with PHP 5.4.x. I just updated Piwik to 2.16.4 but on the "System Check" page, I get contradicting warning messages: One says, I could not update to the LATEST major release. One says that 5.4 will not be supported in the NEXT major release, and the current PHP requirements are listed as `PHP version >= 5.3.3`... Here is the screenshot:

php-version-warning-screenshot

**Comment by mattab** [comment]
It's kinda correct it seems:  your current version requires 5.3.3 but the next one will require 5.5.9

**Comment by utrenkner** [comment]
@mattab The second warning seems correct, as it warns about the next major version.

However, the first one is obviously wrong: It says I cannot install the latest major version unless I upgrade PHP. But the latest version is the one I have already installed.

**Comment by mattab** [comment]
> But the latest version is the one I have already installed.

OK indeed. We are a little too pro-active, but soon there will be a Piwik 3 beta release and hopefully soon the stable release, and we didn't want to have to upgrade the message later, so we "pretend" it's already released. Maybe we should make this better, but it's not too important for me now

**Pull request merged**
