### PR TITLE
Added One-Click Increment-Decrement Arrows to the Calendar

### LINKED ISSUE #4365: UX: add  Prev - Next Buttons next to Calendar
to get a good "feeling" for things that happen on your site, I'm sometimes switching from day to day, week to week or month to month instead of choosing the larger period.

It would be great to have a previous and next button beside the period selector to directly be able to choose the previous or following period (with the same duration: day,week,month..)

please see attachment.

further enhancement:
if you use this function very often, it would be awesome to be able to activate a performance mode, where period before and next would be preprocessed in the background so one could switch very fast...

### PR DESCRIPTION
**Pull request by jimddavis**
### Description:

Not related to an issue.  Adds increment and decrement arrows to the date PeriodSelector.  Allows one-click single period movement without having to open the calendar and select the previous/next day, week, month or year.

The arrow images use the HTML UTF-8 codes  &#11160;   and  &#11162;

Does nothing with the range period, and the arrow buttons are disabled.  For each period type, checks are done against PiwikMinDate and PiwikMaxDate, and the arrows are disabled if an increment or decrement would move beyond those dates.

On small screens, < 600px, the arrows are not shown.  Getting a nice layout would have required significant change to the existing layout css, and the choice was made to simply not have this feature available on small screens.

File Changes:
PeriodSelector.less - Added class .period-increment
PeriodSelector.vue - Added methods incrementPeriod, setIncrementDisabled, canIncrementPeriod, and getWeek.

The getWeek method returns the week of year number. The algorithm was derived from the one at https://www.w3resource.com/javascript-exercises/javascript-date-exercise-24.php, modified to work with TypeScript.

Screen shots of UI in different states:

Small Screens
SmallScreen

Range Period
Range

Day with actions in past and future
DaysMiddle

Day with actions in past and future showing Calendar
DaysMiddleCalendar

Day at PiwikMaxDate
DaysMax

Day at PiwikMinDate showing Calendar
DaysMinCalendar

Week at PiwikMaxDate showing Calendar
YearMaxCalendar

Month in Middle
MonthMiddle

Month at PiwikMinDate showing Calendar
MonthMinCalendar

Year
YearMin

Year at PiwikMaxDate showing Calendar
YearMaxCalendar

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Hi @jimddavis, thank you for taking the time and opening an enhancement PR!
We value your contribution and it surely sounds like a handy addition to have!

If you don't mind, I have a few suggestions on how to improve the code a bit:
- use `<button>` elements instead of `span`
- use `disabled` state instead of grey class
- have both `increment` and `decrement` methods that may reuse code rather than incrementing by a negative value
- the `#increment-period-arrow` and `#decrement-period-arrow` IDs are not needed, in the less file you can just do `&:hover`

If you could also add a screenshot how the UI looks for you with the newly added controls, it would certainly help to see the value in the addition.

**Comment by jimddavis** [comment]
Appreciate the rapid feedback and will make the recommended UI updates.  I do have a problem running the tests.  First, I do not have a dataset that includes all use cases and the Visitor Generator plugin does not work with 5.0.  Is there a downloadable database compatible with the forked 5.x-dev code that I can use for testing?

**Comment by michalkleiner** [comment]
Apologies, I can't really help with your particular setup around the tests @jimddavis.
When I asked how the UI looks with the addition I meant just a screenshot from your browser when you did the change as I imagine you tested it locally?
We can then look at the UI tests after the change is submitted and the UI screenshots generated by Github actions.
We didn't receive any bug reports on the visitor generator not working, that might be a separate thing.

**Comment by jimddavis** [comment]
I made significant changes, so updated the original request.  I hope this was appropriate.

**Comment by michalkleiner** [comment]
Thank you a lot for your contribution, @jimddavis, we truly appreciate it!

I've created a new PR within this repo (#21824) where we can finish the work and get it merged.

We will credit you in the changelog for Matomo 5.1 where we expect this to be released.

**Comment by jimddavis** [comment]
Thrilled you guys decided to include this feature.  I have been re-implementing this in my dev environment with every significant release, and then deploying just those changes to my live server.  Been holding off any any updates the past 6 months, and will wait till 5.1 is released before I upgrade from 4.16.

Not sure how many users will make use of it, but in my simple scenario, a quick glance at how things change day to day in various reports is very helpful.

Thanks again for taking up the slack where my skill set was just not enough to get it done!

**Pull request closed without merging**
