### PR TITLE
Show city / country in visitor details

### LINKED ISSUE #12015: Visitor log should display country/city information without having to hover on the country flag
3.1.0 RC1: visitor log: no more information about country/city visible
e.g. : flag, country, city

was nicely optimized not that long ago: https://github.com/piwik/piwik/issues/9705

2017-09-08_15h45_43

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12015

### CODE REVIEW

**Comment by diosmosis** [comment]
I see two flags now, if that's ok, then LGTM

**Review by mattab — CHANGES_REQUESTED** [review]
Review

* Visitor log: Let's remove the flag in the middle column, and leave only the flag in the first column next to country/city name.
* Visitor profile: let's remove the flag in each visit on hover, and only show the flag in the top left profile, as well as when the visit is expanded to show detailed visit info.
* When the geolocation is Unknown, do not display the flag+text. For privacy reasons it may be more common in the future not to collect accurate geo location data and we can simply not show it then.

**Comment by sgiehl** [comment]
Updated the PR accordingly... UI files need an update before merging.

**Comment by mattab** [comment]
@sgiehl Looks good :+1: can you update the UI tests/rebase and merge this?

**Comment by Findus23** [comment]
@sgiehl Is it intentional that the flag is now only 16x12 instead of 20.66x16 as before?

**Pull request merged**
