### PR TITLE
remove acceptedValues from PageUrl

### LINKED ISSUE #15322: Segments do not work with encoded URL's as advised.
When creating a segment using encoding as advised in the help text, no results are shown. 

image

For example `https%3A%2F%2Fexample.com` yields no results in the visits log where as `https://example.com` does.

### PR DESCRIPTION
**Pull request by geekdenz**
fixes #15322

### Description:

Remove the PageUrl->acceptedValues property to effectively remove it from the tooltip (title attribute).

Does this have knock-on effects elsewhere?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@geekdenz There's a test that needs to be updated. See https://app.travis-ci.com/github/matomo-org/matomo/jobs/531879021#L763

**Comment by geekdenz** [comment]
> @geekdenz There's a test that needs to be updated. See https://app.travis-ci.com/github/matomo-org/matomo/jobs/531879021#L763

Sorry for the delay. It was a simple fix by copying the processed to expected xml. The difference is expected. I checked.

**Review by sgiehl — APPROVED** [review]
Looks good now.
@mattab I'm not fully sure what the intention of the original issue was. Is it fine that this hint will be removed from UI, but I guess also from 
https://developer.matomo.org/api-reference/reporting-api-segmentation

**Comment by tsteur** [comment]
@sgiehl yes it was meant to remove it from both places.

**Pull request merged**
