### PR TITLE
Regression test for themes

### PR DESCRIPTION
**Pull request by mnapoli**
Themes were broken because of new code now affected by this existing bug: leafo/lessphp#302. I bumped to v0.5.0 and checked the changelog, it was one of the 2 only significant change. The only other significant change is that syntax errors in Less now throw an exception (which allowed to fix a few existing bugs in our Less files). I think it's good to have (definitely help in when developing, I know I've raged a lot against mixins like `.box-shadow()` that weren't doing working without any explanation), however it might break plugins that have errors in their less files. Do we consider that a problem or a very small risk (for example we only had 2 Less bugs in our whole codebase)?

I added a UI test that checks that themes work so that we avoid any regression in the future.

Edit: FYI I removed the `.box-shadow` mixins for the following reasons:

> They are useless since box-shadow is supported in all browsers except IE 8 (in which using a prefix doesn't help anyway).

### CODE REVIEW

**Comment by diosmosis** [comment]
Are there any themes other than Morpheus that we maintain (I know there used to be PleineLune, but I think we stopped maintaining it)? If so, it would be good if we added UI tests for them (if we don't have them already).

**Comment by mattab** [comment]
> however it might break plugins that have errors in their less files. Do we consider that a problem or a very small risk (for example we only had 2 Less bugs in our whole codebase)?

+1 - I think it's not a problem as it is only small risk 

> I added a UI test that checks that themes work so that we avoid any regression in the future.

:+1: for the idea. The test enables theme `ExampleTheme` which looks the same as the default theme. Will this new test still help us detect a regression?

**Comment by mattab** [comment]
> Are there any themes other than Morpheus that we maintain (I know there used to be PleineLune, but I think we stopped maintaining it)?

PleineLune was deprecated, and there are no other theme that we need to maintain (at the moment) .

**Comment by mnapoli** [comment]
@mattab have a look at this: https://github.com/piwik/piwik/commit/7974635631db3adf2ee60351b2e19d01c68e26fc#commitcomment-11414730

**Comment by diosmosis** [comment]
What about taking a screenshot of the UI demo page? Will the theme be applied there?

Also, do you intend to customize the theme more (ie, use more variables) or is this it?

**Comment by mnapoli** [comment]
> What about taking a screenshot of the UI demo page? Will the theme be applied there?

Yes it should definitely apply there. I've added a test for that page.

> Also, do you intend to customize the theme more (ie, use more variables) or is this it?

No, we could decide to test every variable but right now I don't think it's very urgent/a priority. This test is mostly about checking that it works (e.g. on master themes don't work)

**Comment by diosmosis** [comment]
Screenshot tests are failing, I think phantomjs doesn't support `box-shadow`. Not sure how to fix this w/o putting the macro back.

**Comment by mnapoli** [comment]
Following discussion, TODO:

- remove the button shadows (this PR actually fixed the shadow which wasn't rendered before because the mixin was broken)
- button shadows will be added in #7896 anyway so there should be no UI change in this PR

**Comment by mnapoli** [comment]
Shadows and tests are fixed, this PR introduces no visual change: http://builds-artifacts.piwik.org/ui-tests.fixing-themes/12946.7/screenshot-diffs/diffviewer.html

Ready for review and merge.

**Pull request merged**
