### PR TITLE
[Vue] 4.6.0 fixes

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Found some issues after minimum supported browser testing:

- async/await is not supported in Vue code since it would add 6kb to each UMD file (details in original vue introduction PR)
- Feedback plugin can be disabled (due to WhiteLabel for example), so don't access it if it's not there
- fix typo in FeedbackQuestion.adapter.ts

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@diosmosis as we've already released an RC be great to target `next_release` branch instead of 4.x-dev so it makes it into the next 4.6 release (https://github.com/matomo-org/developer-documentation/pull/586/files)

**Comment by diosmosis** [comment]
@tsteur done

**Review by peterhashair — APPROVED** [review]
I think that's come from my PR. thanks for fixing it

**Comment by diosmosis** [comment]
@peterhashair there were two issues (and a typo), the other issue was mine :+1:

**Pull request merged**
