### PR TITLE
Pass in testomat integration key, when not running unit tests.

### PR DESCRIPTION
**Pull request by caddoo**
### Description:

Related to this PR: https://github.com/matomo-org/github-action-tests/pull/18

_[Here's the doc](https://docs.github.com/en/actions/learn-github-actions/expressions#example) for the confusing expression in the GH action_

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@caddoo I've updated the branch of the action here, so we can directly see if it works. It seems to upload the report, but I don't have access to the project, so I can't validate if the report data arrives in testomat or not.

**Comment by caddoo** [comment]
> @caddoo I've updated the branch of the action here, so we can directly see if it works. It seems to upload the report, but I don't have access to the project, so I can't validate if the report data arrives in testomat or not.

@sgiehl 
Sorry I should have mentioned, I tested the integration already. I'll see if I can get access for all.

You should have access to it now. You can review / merge once you are happy

**Comment by sgiehl** [comment]
@caddoo We need to find a way to pass env details to testomat. Currently you aren't able to see things like PHP version, database type and adapter there. That makes it kind of useless, as you wouldn't know if a test only fails on e.g. a specific php version or in general. Also it looks like that one CI run ends up in multiple reports on testomat

**Comment by caddoo** [comment]
> @caddoo We need to find a way to pass env details to testomat. Currently you aren't able to see things like PHP version, database type and adapter there. That makes it kind of useless, as you wouldn't know if a test only fails on e.g. a specific php version or in general. Also it looks like that one CI run ends up in multiple reports on testomat

I would say 'useless' is a strong word, without knowing the env details we can still see / highlight problematic tests. It's just a little bit more effort to manually identify which environment it fails for.

I'll spend some time seeing if we can make this better, but it shouldn't be a show stopper.

**Comment by sgiehl** [comment]
@caddoo it should be possible to pass the environment to testomat. At least it has a separate reporting around envs.
In addition we should maybe check if we only want to upload reports from `5.x-dev` and not every branch tests are running for. Otherwise we might end up having a lot failure reports for tests that failed for certain PRs while they were in development.

**Comment by caddoo** [comment]
> @caddoo it should be possible to pass the environment to testomat. At least it has a separate reporting around envs. In addition we should maybe check if we only want to upload reports from `5.x-dev` and not every branch tests are running for. Otherwise we might end up having a lot failure reports for tests that failed for certain PRs while they were in development.

@sgiehl 

I've added the env variables now, see screenshot:

image


I've also changed **when** we submit the reports to testomatio. I didn't do it by branch but I did it by event/trigger.

So now every `push` event which happens generally on merge for the `5.x-dev` and `next_release` branch which I think is sensible here, and we don't have to worry about updating the script to support `6.x-dev` later.

(You can see those previous triggers [here](https://github.com/matomo-org/matomo/actions?query=event%3Apush))

If you need to test this yourself you [can change the logic temporarily ](https://github.com/matomo-org/github-action-tests/pull/18/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R249) to always be true.

- I [have this run showing ](https://github.com/matomo-org/matomo/actions/runs/9509387376/job/26212257157)when its manual trigger (not sending to testomatio)
- I [have this run showing](https://github.com/matomo-org/matomo/actions/runs/9509653690) it running when the script thinks its a push (sending to testomatio)

**Review by michalkleiner — APPROVED** [review]

**Review by michalkleiner — APPROVED** [review]

**Pull request merged**
