### PR TITLE
Show warning when paq.push is not initialized correctly

### PR DESCRIPTION
**Pull request by tsteur**
refs https://github.com/piwik/piwik/issues/10878

This is PR for Piwik 3 for https://github.com/piwik/piwik/pull/10888

To test use eg 
```html
<html>
<head></head>
<body>
<script type="text/javascript" src="//apache.piwik/piwik.js"></script>
</body>
</html>
```

Then initialize tracker after document was loaded via `_paq.push`. You will see a console message and no created tracker. When using _paq.push for tracking, the Tracker needs to be configured upfront. Otherwise bugs may occur.

### CODE REVIEW

**Comment by tsteur** [comment]
Updated PR to still track but also log a message

**Comment by tsteur** [comment]
Updated PR again to not track when tracker is not initialized upfront

**Comment by mattab** [comment]
* Ideally when the user calls `setTrackerUrl` and `setSiteId` even after the tracker was initialised,  the tracker should initialise without error. Ie. the following code should not trigger an error but currently it does:

```
<!-- Piwik -->
<script type="text/javascript">
  var u="//localhost/piwik-master/";

  (function() {
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();

  var _paq = _paq || [];

setTimeout(function() {
  _paq.push(['setTrackerUrl', u+'piwik.php']);
  _paq.push(['setSiteId', '1']);
  _paq.push(["setCustomVariable", 1, "", "", "visit"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
}, 1000);
</script>
<!-- End Piwik Code -->
```

* If we don't init tracker when setSiteId/setTrackerUrl were called in the right order (even after tracker init), then we should track the data for sure, or alternatively not merge PR for now

* Suggested message: `Piwik Analytics error: _paq.push() was used before the Piwik tracker was correctly initialized. To initialise the tracker please make sure to first call the two methods 'setTrackerUrl' and 'setSiteId' via _paq.push(). Alternatively, you can create a tracker via Piwik.getTracker( trackerUrl, siteId ) and then call 'setTrackerUrl' and 'setSiteId' on the returned object. `
* you wrote in the message: `but it may fully work as tracker methods may not be executed in the correct order.` for the `Piwik.addTracker()` method -> do you maybe have an example?

**Comment by tsteur** [comment]
There are plenty of reasons why it won't fully work just search for issues in the issue tracker that are related to order. Eg we create cookies even though we shouldn't , or create cookies wrong domain etc. 

I can't do anything else here. Happy to close PR and it just won't keep working for users. Here was suggestion on top for https://github.com/piwik/piwik/issues/10797#issuecomment-263140282 but I likely won't find any time to work on it

**Comment by tsteur** [comment]
Also see comments where we discussed it. Eg custom tracker plugins won't be working with it etc

**Pull request merged**
