### PR TITLE
covert getPluginUmdChunks from private to protected

### LINKED ISSUE #19207: UI error when deploying matomo 4.9.1 on wordpress
## Expected Behavior
Be able to open matomo 4.9.1 on wordpress

## Current Behavior
Only a part of the interface is displayed. there is a js error 
Screenshot from 2022-04-20 11-14-49

## Possible Solution
removing the method getJsInclusionDirective in the plugins/WordPress/WpAssetManager.php file solves the issue.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #19207
covert getPluginUmdChunks from private to protected.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by justinvelluppillai** [comment]
Sorry @peterhashair I meant to do this on the `next_release` branch which means you have some `4.x-dev` changes here that shouldn't be. Can you maybe redo this on the `next_release` branch (maybe easier than fixing this one).

**Comment by peterhashair** [comment]
@justinvelluppillai sorry, my bad.

**Review by justinvelluppillai — APPROVED** [review]
Thanks @peterhashair the changes look good now. Can you please just confirm the failing tests are failing for unrelated reasons before merging?

**Comment by peterhashair** [comment]
@justinvelluppillai I look the failed tests, 4 are random, 1 is about SEO ranking. all unrelated.

**Pull request merged**
