### PR TITLE
Ensure empty tables also use max width

### LINKED ISSUE #19819: Ensure empty report tables also use max width
Not sure if that was on purpose or a regression. Previously, they were limited to a certain width but now in 4.12 they utilise the full screen width. 

For example it looked like this in 4.11

image

But now in 4.12 they use the full width.

I couldn't find anything in the changelog and assume this is a regression

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #19819

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
fyi not sure if related to this: It might make the evolution graph smaller yet not the sparklines. The evolution graph I believe should still have full width even when there's no data 
image

**Comment by sgiehl** [comment]
@tsteur I guess that was already the case before and should be unrelated to the fact if there is data or not. I've pushed a commit, so evolution charts aren't resized. Let's see if there are some screenshot changes due to that...

**Comment by tsteur** [comment]
@sgiehl just fyi I don't think this wasn't the case previously. I'm looking at some reports without this patch on production where it has zero data and the graph is shown full width.

**Comment by sgiehl** [comment]
@tsteur nvm. my last commit should have fixed that.

**Review by peterhashair — APPROVED** [review]
Looks good to me, @tsteur it's that ok to merge that update for empty table width?
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)

**Pull request merged**
