### PR TITLE
Show information in visitor profile if dataset was "truncated"

### PR DESCRIPTION
**Pull request by sgiehl**
Shown visits in visitor profile is currently limited by `live_visitor_profile_max_visits_to_aggregate` *(default 100)*. As some users might exceed this limit it would be helpful to show at least a message that the summary only represents the last X visits. 

based on #12375 

refs #12373

### CODE REVIEW

**Comment by diosmosis** [comment]
System test is failing (`makeVisitorTableFromArray()` call added in previous PR is missing the new `$rowCount` parameter). Otherwise looks good.

**Comment by diosmosis** [comment]
Not sure why, but `FOUND_ROWS()` isn't working on travis or for me locally. Still investigating...

**Comment by diosmosis** [comment]
found the issue, it's caused by the limit in the inner query: https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/Live/Model.php#L264-L268

FOUND_ROWS() will always be limited by that, I guess. @sgiehl is this something you noticed? or was it working for you?

**Comment by sgiehl** [comment]
Guess that worked in my tests, as the datasets were smaller than the `$limit*10`. But now only `$limit` is beeing used as iIrc a segment has been used before to load that data instead of directly using the `$visitorId` parameter. Need to have a closer look when I have some time if there is an easy solution for this...

**Pull request merged**
