### PR TITLE
Make resolution field bigger

### LINKED ISSUE #9913: DB field name Screen resolution is too small: width and height should not be limited to 9999 pixels
The current resolution field is set to VARCHAR(9). This means that the field may be truncated if we store a resolution width or height more than 9999 pixels. Then the resolution wouldn't fit in 9 characters (they are stored separated by a `x` in `log_visit.config_resolution`).

Goal of this issue is to change the DB field type to allow for more characters, so one could track very large resolutions. (note that the integration test in RequestTest.php (and `getResolution` in Tracker/Request) will need to be updated, see https://github.com/piwik/piwik/pull/9914/files#diff-35f2659319670251c767de1da7cb514aR358)

follows up https://github.com/piwik/piwik/issues/9911

### PR DESCRIPTION
**Pull request by tsteur**
fixes #9913

Allows us to eg persistent a resolution like `99999.12x99999.12`

### CODE REVIEW

**Comment by sgiehl** [comment]
LGTM. Btw as we now have Git LFS. We can directly update the screenshots in Pull Requests. Guess http://builds-artifacts.piwik.org/piwik/piwik/9913/19886/CoreUpdaterDb_main.png fails cause of this change.

**Comment by tsteur** [comment]
good point. I've just copied the file into expected-screenshots but git doesn't show me a changed file. Do I need to do anything special re git-lfs? I remember it did download all the files when I checked out 3.x-dev a while ago

**Comment by sgiehl** [comment]
I tried exactly that right now, and it shows me the changed file. Maybe the screenshots are not correctly checked out, try:
```
git lfs fetch
git lfs checkout
```

**Comment by tsteur** [comment]
Just tried it without

```bash
vagrant@piwik-trusty64:~/www/piwik$ git lfs fetch
Fetching 9913
(0 of 308 files) 0 B / 39.19 MB                                                                                                                                                     
vagrant@piwik-trusty64:~/www/piwik$ git lfs checkout
(333 of 333 files) 40.00 MB / 40.00 MB                
```

not sure if the 0 of 308 files is so good. I'll update my git. Still on `git version 1.9.1` :) maybe that helps

**Comment by sgiehl** [comment]
On my box (using git 2.7) it says:
```
Fetching 9913
Git LFS: (0 of 0 files, 308 skipped) 0 B / 0 B, 39.19 MB skipped
```

**Comment by tsteur** [comment]
Just updated to `git version 2.9.3` and same problem. Need to look into it tmrw I reckon

**Comment by tsteur** [comment]
I'm so stupid :) I copied the picture into another project that also had an `expected-screenshots` folder :)

**Pull request merged**
