### PR TITLE
New design for forms

### PR DESCRIPTION
**Pull request by mnapoli**
ref #7584, #7585, #7587

I have applied the new design for forms. This is more difficult than the other redesigns because the mockups do not cover even half of all the possible use cases (and sometimes they were not consistent). Additionally in order to get the desired layout I had to add `<div>` tags (formatting cannot be done entirely in CSS) unlike simpler elements like alerts, buttons or tables…

So I'm asking **please review the HTML layout** that one has to use to create forms. This layout will become API.

Currently, HTML forms are constructed using tables: these forms should not (will not) break as they might be used in plugins. However new forms should be created using the new way (i.e. not tables).

Here is a preview of new forms:

capture d ecran 2015-05-21 a 10 29 56

You can see some mockups here: #7587 (the new forms also appear in the installer, etc.)

And here is the HTML layout **that you should review**:

``` html
<form action="#">
    <div class="form-group">
        <label for="username">
            Username
        </label>
        <input type="text" id="username" placeholder="Some text here..."/>
    </div>

    <div class="form-group">
        <label for="email">
            Email
        </label>
        <div class="form-help">
            Here is more information.
        </div>
        <input type="email" id="email" placeholder="Some email here..."/>
    </div>

    <div class="form-group">
        <label>
            Report to load by default
        </label>
        <div class="form-help">
            This is a help text that can be used to describe the field.
            This help text may extend over several lines.
        </div>
        <label class="radio">
            <input type="radio" name="defaultReport" value="today">
            Today
        </label>
        <label class="radio">
            <input type="radio" name="defaultReport" value="yesterday">
            Yesterday
        </label>
        <label class="radio">
            <input type="radio" name="defaultReport" value="week">
            Previous 30 days (not including today)
        </label>
    </div>

    <div class="form-group">
        <label for="language">
            Language
        </label>
        <select id="language">
            <option>English</option>
        </select>
    </div>

    <div class="form-group">
        <label for="description">
            Description
        </label>
        <textarea id="description" rows="5"></textarea>
    </div>

    <input type="submit" value="Submit">
</form>
```

For some complex use cases I had to be a little creative, I used Bootstrap as an inspiration. Here is for example the before:

capture d ecran 2015-05-21 a 10 53 06

After ([input with addon](http://getbootstrap.com/components/#input-groups-basic)):

capture d ecran 2015-05-21 a 10 53 59

A little background:
- yes `<div class="form-group">` is a pain but doing without it was extremely complex and wouldn't even work with advanced use cases (like radio/checkbox lists, …)
- `form-group` is a class inspired by Bootstrap
- `<div class="form-help">` is `float: right` that's why it must be put _before_ the fields (side note: I think it's also good for screen readers/disabled users…)
- the `radio` and `checkbox` CSS classes are necessary to force display correctly (as block, etc.), applying directly to the input radio would mess up many things… This is also inspired by Bootstrap.

Some questions:
- do you think it would make more sense to replace `<div class="form-group">` by `<fieldset>`? I'm not 100% sure if it would make sense
- how about using the `<legend>` tags maybe? The reason I'm asking this is that we use `<label>` for titles of the form-groups as well as for radio/checkbox labels (sometimes 2 labels following each other as you can see in the example above). Using a different HTML tags might make things clearer?
- do you think it would be better to remove the custom class `<div class="form-help">` and replace it with alerts (since it's what is used behind the scenes): `<div class="alert alert-info">`
  - pro: that would allow to use other kind of alerts (warning, success…)
  - pro: simpler (less classes to know)
  - con: `form-help` is simpler than `alert alert-info`

Notes:
- I haven't changed all the forms yet, slowly converting them to the new style but I'd rather get your feedback before
- I haven't styled the `<select>` tags like in the mockups because on some browsers (e.g. Chrome) it's not possible: we would have to use hacks and recreate a select using HTML/CSS
- there is no longer a max-width for forms in the admin

### CODE REVIEW

**Comment by diosmosis** [comment]
> yes <div class="form-group"> is a pain but doing without it was extremely complex and wouldn't even work with advanced use cases (like radio/checkbox lists, …)

Personally I like this approach. It seems more semantically correct & clear, as opposed to mixing labels, inputs from different parts of the form.

And `<fieldset>` sounds like it's meant exactly for this use case. Same for using `<legend>`, according to mozilla docs it is meant to be used as the caption for `<fieldset>`s.

> <div class="form-help"> is float: right that's why it must be put before the fields (side note: I think it's also good for screen readers/disabled users…)

Do you think some developers might have issues w/ this? It seems easy to screw up. 

> do you think it would be better to remove the custom class <div class="form-help"> and replace it with alerts (since it's what is used behind the scenes): <div class="alert alert-info">

If `form-help` is just a shortcut for `alert alert-info` then I don't see an issue w/ keeping it. I think most forms won't necessarily need to display success/errors, and if the styling is the same as alerts (so no extra work needs to be done to display an alert in the same place/way), then it's easy/convenient for both use cases.

Regarding styling `<select>`, I believe Morpheus uses a library for styling checkboxes, perhaps something similar exists for `<select>`s? If it is to be done, probably better to do in another PR, though.

**Comment by tsteur** [comment]
looks otherwise good to me

**Comment by mattab** [comment]
Here is a quick feedback: looking the screenshot above (https://cloud.githubusercontent.com/assets/720328/7744667/99e2e468-ffa5-11e4-811f-c4962540a27e.png) from a usability point of view, there is not enough contrast for the inline help. Solution: either we make the Inline text Grey color darker (or alternatively: Make the background grey lighter). More contrast will make inline help easy to read.

**Comment by mnapoli** [comment]
@mattab I agree but this is the alert style, we can change it separately (because I think it would be good to apply that change for alerts too, not just form help)

@diosmosis I will try using fieldset and legend then!

Regarding "float: right" and "It seems easy to screw up" that's true, but we can immediately see that the help is positioned below the field in that case. I'll give another try at placing the help after the input in the HTML and see how that turns out.

> Regarding styling <select>, I believe Morpheus uses a library for styling checkboxes, perhaps something similar exists for <select>s? If it is to be done, probably better to do in another PR, though.

Agreed this PR will already be quite extensive.

**Comment by mnapoli** [comment]
I have tried using `fieldset` and `legend` tags and it was a complete fail from an accessibility point of view. See this answer: http://stackoverflow.com/a/7042529/245552

> Some screen readers assume that field sets will only be used that way and are optimized for that use case, causing the screen reader to announce the legend on every single input in the list

I haven't reproduced that particular behavior (I guess all screen readers are different) but I tried 2 screen readers and the fieldset behaves as a group, it becomes hard to tab or navigate inside them (i.e. it adds a lot of steps to be able to fill the form). Additionally replacing labels with legends makes them non-clickable because  not associated to the inputs anymore. Additionally with the screen reader legend≠label so inputs would have no description anymore…

All in all I think fieldsets are not a good option. Even for radios and checkboxes I found the user experience worse when using a screen reader (but maybe that's because I'm not used to it). I suggest to keep using `<div class="form-group">` and labels.

---

Regarding help blocks I tried to put it after the fields (inputs, radios, …) in the HTML layout but it requires some complicated Less/CSS and it messes up a lot of things (because we have to make the inputs float:left, which is a mess when there are several radios/checkboxes with labels). I don't think it's worth it, keeping it simple and logical is good (a float element should always be put before the item on which we want to align). And if by mistake we put the help *after* the input it's quite easy to understand what's wrong (visually it's explicit). Also the good thing with the current solution is that when using a screen reader the help is read before reaching the input, which is much better.

**Comment by diosmosis** [comment]
Ok, I withdraw my comments about `<fieldset>/<label>` and the `float:right`.

**Comment by diosmosis** [comment]
@mnapoli Is this ready to merge? If so, can you remove the WIP label? I can look again and merge if it looks good. I'll also create a follow up issue for the notification contrast.

**Comment by mnapoli** [comment]
Not 100% finished, I want to move all the forms to the new design. I also need to review all the UI tests to make sure there is no regression. I'll ping you when it's done ;)

**Comment by mattab** [comment]
Looking forward to the new forms applied consistently :+1: 

> I haven't styled the <select> tags like in the mockups because on some browsers (e.g. Chrome) it's not possible: we would have to use hacks and recreate a select using HTML/CSS

Is there another solution to style <select> tags in Chrome or do you think it looks acceptable not to style them?

**Comment by mnapoli** [comment]
Oh I think we should try as much as we can (because else it doesn't look good at all), even maybe use fake selects (if it doesn't mess up too much the tests). But I think it's even possible on Chrome with CSS only, it's just that it requires a more work because when you disable the default appearance you loose everything (e.g. the arrow) so you have to recreate the style from scratch. Anyway I need to research more into that, but in the meantime I think it shouldn't block that (which blocks the user/site manager).

**Comment by mnapoli** [comment]
I've given a try to styling selects and it worked (for Chrome, Safari and Firefox, need to test on IE):

capture d ecran 2015-05-31 a 21 59 32

The end result shouldn't be too complex CSS so I'll add it to this pull request.

**Comment by mnapoli** [comment]
For the record I've removed the background gradient as it was looking out of place (it was the only input element which didn't have a white background).

capture d ecran 2015-06-01 a 15 54 44

**Comment by mattab** [comment]
> For the record I've removed the background gradient as it was looking out of place (it was the only input element which didn't have a white background).

Absolutely agree :+1: 

noticed it's got grey background in segment editor: 
forms segment

Noticed the arrows & calendar seem a bit misplaced:

form calendar extra arrows

When date range is clicked, would be nice to see the date strings full (got: the last character or so is hidden:)
form date range

Besides this, looks good to merge!

**Comment by tsteur** [comment]
> When date range is clicked, would be nice to see the date strings full (got: the last character or so is hidden, expected: font size smaller for input field?)

Can we remove those date range strings? Doesn't belong in this PR but if it's easier to solve this way then it could be also done in this PR I reckon. We do not display them for any other period and it's just duplicated information in general and doesn't look good

**Comment by mattab** [comment]
> Can we remove those date range strings? 

The idea is to let user copy paste date ranges, or manually write the date rather than have to click multiple times in calendar.  We can maybe remove it but it would decrease usability for some (maybe very few) users?

**Comment by tsteur** [comment]
I think very few users do this as it is quite "technical". I did not even know it was possible to change the date there. If it is really good for usability, I'm wondering why it is only possible for ranges? Maybe it would be at least possible to make it look nice but that would be maybe another issue then.

**Comment by mnapoli** [comment]
@mattab thanks I have fixed those UI regressions (one was appearing only on Firefox). What's left is check every UI screenshot diff (lots of them because of small changes everywhere) + test using different browsers

**Comment by mattab** [comment]
Ok great :+1: merging (it will make it into the next beta)

**Comment by mnapoli** [comment]
I didn't check the screenshot diffs neither with different browsers did you? There were a lot of changed screenshots and I was stuck yesterday by the UI tests failing because of the segmentation faults

**Comment by mattab** [comment]
they were broken, I thought about it but then wanted us to move forward with design changes. Hopefully we can solve the UI tests issue. (not sure if it is #8034 or a new one)

**Comment by mnapoli** [comment]
yes they were broken, but this PR has been merged without being tested (at least by me) that's what I'm saying (was still WIP). I'm going to test on master then

**Pull request merged**
