### PR TITLE
Handle clicks on SVG elements. Fix #8346.

### LINKED ISSUE #8346: node.className.split is not a function on tracking click on/near SVG element
I've created a mirror of our signup page where we experience this error. Steps to reproduce:

1. Go to https://idorecall.com/static/bug-demos/piwi-classname.split/
2. Enter some email
3. In the signup success page, click on the "F"acebook link/icon.

After a few seconds, the Chrome console displays

    piwi.js:1390 Uncaught TypeError: node.className.split is not a function

The piwik.js is [from July 1st](https://github.com/piwik/piwik/blob/10124dd4b4cb4afe3df7850d53e5f9f39e680d15/js/piwik.js) and the line in question is [`var classes = node.className.split(' ');`](https://github.com/piwik/piwik/blob/10124dd4b4cb4afe3df7850d53e5f9f39e680d15/js/piwik.js#L1390)

The error occurs despite the checks for presence of `className` because the element in question is an SVG `<use>` and node.className is `SVGAnimatedString {}`. My markup is

```html
<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A//iDoRecall.com/?signupref">
  <svg>
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fa-facebook"></use>
  </svg>
</a>
```

http://stackoverflow.com/questions/12588913/svganimatedstring-missing-method-indexof suggests a possible solution.

A workaround is to add bogus classes to `<svg>` and `<use>` elements in the markup.

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by mattab** [comment]
Hi @dandv 

Thanks for Pull request. I noticed that the JavaScript tracking unit tests are failing, could you take a look and update tests accordingly, if the change is indeed correct? https://travis-ci.org/piwik/piwik/jobs/70837343

See readme about JS tests: https://github.com/piwik/piwik/tree/master/tests/javascript#javascript-tests

**Comment by dandv** [comment]
Unfortunately I'm on a very tight deadline and can't dedicate much time to this. Hopefully the reproduction steps have been useful and someone more familiar with the code can come up with a better fix?

**Comment by dandv** [comment]
I don't understand why that test fails, without looking at its code. Logically, all the patch does is pass-through the split className if className was a string, just as before. If it wasn't, it returns an empty array. What can className be in `hasNodeCssClass`? A JSDoc comment for that function would be great.

**Comment by tsteur** [comment]
I think `className in node` is the problem. `className` can be any class. Eg when HTML is `<div class="test test2">` and c `className="test2"` then it should return `true`. But `"test2" in node` won't be `true`

**Comment by dandv** [comment]
@tsteur: I think I got confused by `className` being both the name of the function argument that tells what class name to look for, and the [Element method `className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className). Any idea what causes the JSLint failure now?

**Comment by tsteur** [comment]
It's very tricky to find JSLint errors unfortunately, I debugged and found this:

```
a: "in"b: undefinedc: undefinedcharacter: 54d: undefinedevidence: "                if (node && className && 'className' in node && node.className) {"id: "(error)"line: 1389raw: "Unexpected 'in'. Compare with undefined, or use the hasOwnProperty method instead."reason: "Unexpected 'in'. Compare with undefined, or use the hasOwnProperty method instead."__proto__: Object
```

see eg http://stackoverflow.com/questions/6824895/jslint-error-unexpected-in-compare-with-undefined-or-use-the-hasownproperty and http://stackoverflow.com/questions/12179371/why-jslint-complains-about-this-code-and-how-should-i-fix-it

Just FYI: After merging we need to minify the piwik.js

**Comment by dandv** [comment]
> Just FYI: After merging we need to minify the piwik.js

We should also add a test for tracking clicks on SVG elements, but that's above my pay grade :) Happy my PR passed tests (I guess the screenshot differences are an expected failure).

I'll let someone more familiar with test writing take over.

**Pull request merged**
