### PR TITLE
Fix Clicking on the "Dashboard" top link hides all dashboard content

### LINKED ISSUE #11386: Clicking on the "Dashboard" top link hides all dashboard content
Reproduce:
* Open http://demo.piwik.org/
* The dashboard has loaded
* In the top bar click the "Dashboard" link
* Expected: the Dashboard reloads
* Got: dashboard disappears

empty

### PR DESCRIPTION
**Pull request by tsteur**
fixes #11386

### CODE REVIEW

**Comment by tsteur** [comment]
Also fixed the links in the admin menu that it wasn't possible to load the same page again. Eg go to General Settings => and then clicking on General Settings again will now reload the page.

**Comment by mattab** [comment]
It's working well - @tsteur do you maybe have some resource to explain why this fixes the problem? is it maybe related to our broadcast or angularjs routing?

**Comment by tsteur** [comment]
Search for _self: https://docs.angularjs.org/guide/$location

**Comment by sgiehl** [comment]
But is it really linking to dashboard now? The link is still to CoreHome/index, which might load the MultiSites Dashboard if the user configured that as default, or am I wrong?

**Pull request merged**
