### PR TITLE
Update MTM no data tab translation

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Making translation change requested by Product team and updating screenshot to match recent MTM changes to the no data page tab.

The following MTM PR will fix the broken UI test cases once this PR is merged: https://github.com/matomo-org/tag-manager/pull/818

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by caddoo** [comment]
Hi @snake14 

Sorry the PR description isn't clear (for me), can you update it so I understand what I'm reviewing, essentially what are the changes for.

Then I'll get onto it for you 👍

**Comment by snake14** [comment]
> Hi @snake14
> 
> Sorry the PR description isn't clear (for me), can you update it so I understand what I'm reviewing, essentially what are the changes for.
> 
> Then I'll get onto it for you 👍

@caddoo Apologies. I forgot to update the description after my initial testing. This PR was initially to update the screenshots to match the recent changes in MTM. Then, Product requested a change to a core translation, so I made that change as part of this PR as well.

**Review by caddoo — APPROVED** [review]

**Comment by snake14** [comment]
Thank you for approving the PR @caddoo . I don't have merge permission for this repo; could you please merge it?

**Comment by sgiehl** [comment]
@caddoo the UI tests or in that case the submodule would have needed to be updated here or after merge. now the tests are failing on 5.x-dev 🐼

**Comment by snake14** [comment]
@sgiehl As I mentioned in the description, I had an MTM PR ready to merge with the updated screenshots. Was I supposed to merge that first and have the MTM build failing until this PR was merged?

**Comment by sgiehl** [comment]
That's a bit of a problem, as one of both builds will fail after merge. That might be fine, but we at least need to ensure to merge a submodule update right after or restart the build of the plugin to fix it. Bit in any case it's important to ensure that any build isn't failing afterwards. As someone else might not directly know the reason

**Comment by snake14** [comment]
@sgiehl I created the [submodule PR](https://github.com/matomo-org/matomo/pull/22437) shortly after merging the MTM PR, but was unable to merge it. I guess I should have tagged a core reviewer on it.

**Comment by sgiehl** [comment]
@snake14 thanks for that, but I see it more in the responsibility of the merger to ensure that happens

**Comment by snake14** [comment]
Thanks @sgiehl . In the future, I can make sure and merge the MTM PR first. It sounds like it might be easier to have the plugin build fail for a little while. Hopefully the core PR won't take so long to merge.

**Comment by caddoo** [comment]
Is this all resolved now? Sorry for causing problems

**Pull request merged**
