### PR TITLE
Fixed in place sorting order bug for PHP version >= 8

### LINKED ISSUE #18130: Fixed in place sorting order bug for PHP8+
When trying to fetch API.getGlossaryMetrics the order of response changes if php version >= 8 , due to which testcases starts failing
Eg: https://3v4l.org/aK3vq

## Expected Behavior
The sort order should be consistent across php versions

## Current Behavior
Sort order differs for php versions
https://3v4l.org/aK3vq

## Possible Solution
A possible fix is to not return '0' if values are same.
Fixed Eg: https://3v4l.org/3cF8h

## Steps to Reproduce (for Bugs)
https://3v4l.org/aK3vq

## Context
Funnels Plugin test cases are breaking when running for php version >= 8

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Fixed in place sorting order bug for PHP version >= 8
Fixes : #18130 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by justinvelluppillai — COMMENTED** [review]
Is it maybe better for this to try sorting on something other than `'name'` if `$a['name'] === $b['name']` to ensure consistent results?

**Comment by AltamashShaikh** [comment]
> Is it maybe better for this to try sorting on something other than `'name'` if `$a['name'] === $b['name']` to ensure consistent results?

We have total 3 fields
1. name (Eg: Visits)
2. id (Eg: nb_visits)
3. documentation 

The next possible is id and that seems to work as expected.

Something like this
```
usort($metrics, function ($a, $b) {
            if ($a['name'] === $b['name']) {
                $value = strcmp($a['id'], $b['id']);
            } else {
                $value = strcmp($a['name'], $b['name']);
            }

            return $value;
        });
```

**Comment by tsteur** [comment]
@AltamashShaikh seems some test is failing now in https://app.travis-ci.com/github/matomo-org/matomo/jobs/542640794#L760 and needs to be fixed.

same is also visible in the two glossary screenshots which need to be updated: https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/49950/

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh seems some test is failing now in https://app.travis-ci.com/github/matomo-org/matomo/jobs/542640794#L760 and needs to be fixed.
> 
> same is also visible in the two glossary screenshots which need to be updated: https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/49950/

@tsteur Does it looks good to you now ?

**Pull request merged**
