### PR TITLE
GeoIP2

### PR DESCRIPTION
**Pull request by diabl0**
MaxMind GeoIP2 location provider for UserCountry plugin.

Requires geoip2/geoip2 package and provides support for GeoIP2 mmdb files.
Requires present one of files in misc directory: 
- GeoIP2-City.mmdb
- GeoLite2-City.mmdb
- GeoIP2-Country.mmdb
- GeoLite2-Country.mmdb

Also added ISO-3166-2 region codes to FIPS 10.2 conversion

Unfortunately i don't have access to other databases so no support for them.

### CODE REVIEW

**Comment by sgiehl** [comment]
Thanks for the PR. Haven't tested it, but wouldn't it be possible to move this integration into a new plugin? Maybe we need to make some tweeks in current code to handle that easier...
You might need to include the vendor requirements in your plugin directly then, but that shouldn't be a problem I guess.

**Comment by mattab** [comment]
Thank you @diabl0 for your contribution!

Stefan improved a bit the platform in #10523 so that you can now define Location providers in plugins. This lets you add your useful GeoIP2 support in a plugin which would be available on the marketplace. 

* You can create a plugin very easily, see: http://developer.piwik.org/guides/getting-started-part-1#create-a-plugin - your plugin should require Piwik `>=3.0.0-a1` as we only improved this in 3.x-dev branch
* Then put your GeoIp2.php  file into a folder `LocationProvider` in your plugin
* As soon as your plugin is enabled, the GeoIP2 location provider will be detected automatically and appear in the list.


> Unfortunately i don't have access to other databases so no support for them.

Could we maybe help you with this? For example, we can buy the database and send them to you... It is very awesome feature that many users will love and if we can help in this way it would be a pleasure! 

Let us know what you think. Thanks

**Comment by mattab** [comment]
You may need to use Piwik 3 from git `3.x-dev` branch until we release a first alpha/beta version (our goal is to release it by next week)

**Comment by diabl0** [comment]
It wasn't documented when i wrote it that's why I made this changes. I will try to look at this sometime next week and convert into plugin.

**Comment by mattab** [comment]
@diabl0 it wasn't actually implemented, and your pull request made us realise about it. So that's all good! Thanks for trying to convert to a plugin. Let us know if you have any trouble

**Comment by mattab** [comment]
Closing the pull request for now, as @diabl0 will try to create a plugin on the marketplace for this nice improvement.

**Pull request closed without merging**
