### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by Findus23**
A few fixes noticed on weblate.
I hope those whitespace are not required for properly spacing texts on the site. But if they are, things are already broken as they are missing in all translations.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by justinvelluppillai — APPROVED** [review]
Looks good to me. I think the failing UI tests are unrelated?

**Comment by sgiehl** [comment]
@Findus23 Thanks for doing that. We might maybe need to wait with merging that until we migrated to weblate. If we merge that now Transifex would remove all already done translations for that. Not sure if weblate has a better handling for whitespace changes.

**Comment by Findus23** [comment]
Indeed I would wait for a bit with merging this. I also kept it a draft so I can add more things I might notice during the weblate migration.

I don't know how weblate handles whitespace changes, but I have already seen that if a source string changes, the translators will see a diff of the string and can apply the changes to the translation.

**Comment by Findus23** [comment]
The trailing whitespace were fixed with the Weblate migration

**Pull request closed without merging**
