### PR TITLE
When trying to find a join for segmentation, also look for available ways to join in both directions

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Suppose we have two extra log tables in a plugin: `log_thing_event` and `log_thing`. `log_thing_event` joins `log_visit` on `idvisit`, while `log_thing` joins `log_thing_event` on `idlogthing`.

If we try to use `Segment` to generate SQL that queries `log_thing_event`, it will automatically join on `log_visit` to get segmentation to work. BUT if we try to use it to generate SQL that queries `log_thing`, it will not be able to make segmentation work, even though it can be joined to `log_visit` through `log_thing_event`.

This PR fixes this case. When looking for joins, the existing code tries to join a table to one of the previously seen tables in the `$from` array. It will look to see if it is directly joinable to log_visit, otherwise it will look in the `getWaysToJoinOtherTables()` of the table to join. This doesn't work in our case where `$from = ['log_thing', 'log_thing_event']`, because `'log_thing_event'` won't be in the `getWaysToJoinOtherTables()` of `'log_thing'`. Instead, `log_thing` will be in the `getWaysToJoinOtherTables()` of `log_thing_event`. So this adds the reverse of the existing check to make this type of query work.

The use case here is that `log_thing` will have far less rows than `log_thing_event` and querying over it first instead of `log_thing_event` can in some cases be far more efficient.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis is it possible to add some test for that? The ExampleLogTables plugin has some additional log tables, maybe those could be used for testing...

**Comment by diosmosis** [comment]
@sgiehl yes it's possible, I'll add them soon.

**Comment by tsteur** [comment]
@diosmosis could you maybe have a look at this one at some point? It be great to get this merged so we can deploy the new feature on demo or demo2 soon for a test on an actual site.

**Comment by diosmosis** [comment]
@tsteur @sgiehl added a test

**Review by sgiehl — APPROVED** [review]
LGTM

**Pull request merged**
