### PR TITLE
Skip password min length checks when disable_checks_usernames_attributes=1

### PR DESCRIPTION
**Pull request by lab-at-nohl**
see disable_checks_usernames_attributes in config/globals.ini.php

### CODE REVIEW

**Comment by tsteur** [comment]
Looks good. Thoughts @diosmosis or @sgiehl ?

**Comment by diosmosis** [comment]
Looks good. The minimum password check isn't all that useful anyway.

**Comment by lab-at-nohl** [comment]
@tsteur, @diosmosis, @sgiehl 

Any news on this? It just broke my update. 

Travis CI does not look comprehensible.

**Comment by tsteur** [comment]
👍

**Pull request merged**
