### PR TITLE
updated browser and os icons

### PR DESCRIPTION
**Pull request by Findus23**
Pull request as mentioned in #10587. (#9292)
from https://github.com/Findus23/device-icons

Example of changes: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/21561/UIIntegrationTest_visitors_software.png
### The following icons are missing:
- [x] 'AB' => 'ABrowse' X
- [ ] 'AF' => 'ANT Fresco'
- [x] 'BX' => 'BrowseX' X
- [ ] 'CS' => 'Cheshire'
- [ ] 'DB' => 'dbrowser' 
- [ ] 'DO' => 'Dorado'
- [ ] 'EB' => 'Element Browser'
- [x] 'ES' => 'Espial TV Browser' X
- [x] 'KP' => 'Kapiko' X
- [x] 'LS' => 'Lunascape' X
- [ ] 'LU' => 'LuaKit'
- [x] 'MU' => 'MIUI Browser' X
- [x] 'NF' => 'NetFront' X
- [x] 'NP' => 'NetPositive' X
- [ ] 'OD' => 'Odyssey Web Browser'
- [x] 'OR' => 'Oregano' X
- [x] 'PO' => 'Polaris' X
- [ ] 'SC' => 'SEMC-Browser'
- [ ] 'SN' => 'Snowshoe'
- [ ] 'SR' => 'Sunrise'
- [x] 'TZ' => 'Tizen Browser' X
- [ ] 'VB' => 'Vision Mobile Browser'
- [x] 'WO' => 'wOSBrowser' X
- [ ] 'WT' => 'WeTab Browser'
- [ ] 'XI' => 'Xiino'

### The following icons could be improved
- [ ] 'IB' => 'IBrowse' (text over image) X
- [ ] 'KI' => 'Kindle Browser' (official logo just text) X
- [ ] 'MX' => 'Maxthon' (maybe outdated) X
- [ ] 'NB' => 'Nokia Browser' (not sure if it is correct) X
- [ ] 'ON' => 'Opera Next' (Opera Next is now called Opera Beta) X

(X -> There is an icon in Piwik) 

## Update:
I also updated the os icons:
#### Missing:
- [ ] Brew
- [ ] MTK / Nucleus
- [ ] WebTV

#### Hard to recognize:
- [ ] HP-UX
- [ ] Solaris
- [ ] MeeGo
- [ ] PlayStation *
- [ ] Symbian *
- [ ] WebOS

I am unsure about MacOS and iOS. The [official iOS Logo](https://de.wikipedia.org/wiki/Datei:IOS_logo.svg) is hard to read, so I only used [the Text](https://github.com/Findus23/device-icons/blob/master/src/DevicesDetection/images/os/IOS.png).
Should I use the [latest MacOS logo](https://de.wikipedia.org/wiki/Datei:MacOS_wordmark.svg), the [old but distinctive logo](https://developer.apple.com/assets/elements/icons/mac-os/mac-os.svg) or just the apple logo?

### CODE REVIEW

**Comment by mattab** [comment]
The new icons look really great. Awesome!

As we wouldn't want to lose some icons, we should not remove any icon that was there before. Could you add back those low res icons as PNG? Then I think we can merge. Or did you want to do more work before we merge?

**Comment by Findus23** [comment]
I now have added the previous icons  (and changed the macOS-icon)

I'm currently working on newer Referrers-icons, but I'll probably create a new pull request.

What about the (obviously) failing tests?

**Comment by mattab** [comment]
> What about the (obviously) failing tests?

Don't worry about the tests we'll fix them at the end or after merging

**Comment by mattab** [comment]
@Findus23 sounds good to create separate PR for referrers icons, will make it slightly easier for us too


Do you know if we could maybe find a s sharper icon for Firefox icon? i'm not too sure but it looks like a bit blurry in http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/21604/processed/UIIntegrationTest_visitors_software.png

**Comment by Findus23** [comment]
> sharper icon for Firefox icon

I am using https://github.com/Findus23/device-icons/blob/master/src/DevicesDetection/images/browsers/FF.png which is a png of the latest svg from [Wikipedia Commons](https://commons.wikimedia.org/wiki/File:Mozilla_Firefox_logo_2013.svg).

I think the effect is because I am using the new logo which is "flatter" than the older ones:
test
(from https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/)

**Comment by mattab** [comment]
@Findus23 maybe the algorithm used in the image downsizing could participate in the blurriness as well. i've noticed in the past huge differences in quality depending on how the scaling down is done. Do you know if there are several algorithms available in your script (eg. bicubic / sinc / lanczos /etc.  I think would be interesting totry a few different ones and pick the one that generates clearer icons for 16px size?

**Comment by Findus23** [comment]
That's a good Idea.
As [I am using](https://github.com/Findus23/device-icons/blob/master/convert.sh#L36-L56) ImageMagick there are hundreds of ways to change the algorithm so I'll need to do some testing.

**Comment by mattab** [comment]
@Findus23 

Ok good to know. i'm sure with imagick we could get a great end result.

> pngquant -f --ext .png -s 1 --skip-if-larger --quality 70-95 "$distFile"

do you know why this line is in the script? probably would be good to use a lossless algorithm :+1:

**Comment by Findus23** [comment]
> probably would be good to use a lossless algorithm 

At first I was using `optipng -o 9 -q "$distFile"` (which is lossless) but with https://github.com/Findus23/device-icons/commit/c1e46fd9dc210ad3c6608d90aa9a4f9cd47825f0 and
https://github.com/piwik/piwik/pull/11063/commits/911f62397f36e7aba47f0ad5a7272d48a883aa14 I changed it to pngquant as it produces even smaller files and I wasn't able to see a difference. 

But I don't mind going back to optipng as a few KB more or less are not that important.

**Comment by mattab** [comment]
also can't see a difference on the first few icons that github shows the visual diff, likely the biggest factor is the imagick algorithm :+1:

**Comment by Findus23** [comment]
You were right. There is a way of avoiding blur when resizing: [Unsharped Resizing (USM)](https://www.imagemagick.org/Usage/resize/)
By adding the () parameter `-unsharp 0x1` the icons get much clearer.

| before        | after           
| ------------- |:-------------
|   aa  | aa
at | at
ch | ch
ff | ff
  | sf
kno | kno

**Comment by mattab** [comment]
Well done @Findus23 for finding this.... the difference looks amazing!

**Comment by Studio384** [comment]
Please use the official Windows logo in its official blue color, not this ugly mismatch.

**Comment by mattab** [comment]
@Studio384 feel free to submit the icon that should be used

**Comment by mattab** [comment]
@Findus23 do you think the PR is  ready to be merged? (any minor changes could be done afterwards but good to merge early and get this in beta)

**Comment by Findus23** [comment]
@Studio384, you are right. The windows logo I used isn't the "official" logo but a modification for Wikipedia (https://commons.m.wikimedia.org/wiki/File:Windows_logo_-_2012_derivative.svg). We should probably use the official one (even though it is harder to recognise in my opinion).
I'll change it tomorrow. 
About edge: I'm not sure what you mean. I think I am using the right icon for edge (https://github.com/Findus23/device-icons/blob/master/src/DevicesDetection/images/browsers/PS.png). Do you mean another icon?

If you have other ideas for improvements just mention it.

**Comment by Studio384** [comment]
@Findus23 I'm sorry, didn't see the Edge icon. Why is it called PS? I guess it's a left-over from Project Spartan?

Either way, I don't really see why the official Windows logo would be harder to recognize than an onofficial home-made version no-one will ever see. Either way, when you update it, make sure to use the 2015 version from Windows 10, with the Windows 10-blue color.

**Comment by Findus23** [comment]
@Studio384 , so you mean https://commons.m.wikimedia.org/wiki/File:Windows_logo_–_2012_(dark_blue).svg?

**Comment by Findus23** [comment]
@mattab there is just one thing I'd like to change before this (and the other pull requests) are ready for testing. 
Because of the resize we need to explicitly add the size of 16x16px to every `` in Piwik. 
I have changed most of them (the ui test will show if I missed some), except for:
- the HTML report (which seems to be easy) 
- the icons in datatables (so all tables in the software tab)
For this I need your help as I haven't found a solution for defining the sizes for them. (https://github.com/piwik/piwik/issues/10587#issuecomment-270101053 and following)

**Comment by Findus23** [comment]
@Studio384 I have now replaced the logo in https://github.com/Findus23/device-icons/commit/9ace925bc773bef8e8ccff9ed8e0bdf0b3009af5 and https://github.com/piwik/piwik/pull/11063/commits/34ee28de32ff61466d929cc638fc74ac0201f3c3.

**Comment by Studio384** [comment]
@Findus23 Yes, that's the version I ment.

**Comment by sgiehl** [comment]
I'm gonna merge that in a new branch now and fix the remaining tests before merging to `3.x-dev`
Thanks for this awesome PR.

**Comment by Findus23** [comment]
Could you also merge the other two pull requests in this branch as they would also need changes in the tests?

**Comment by sgiehl** [comment]
Good Point. I'll do that

**Pull request merged**
