### PR TITLE
Adds action for building tracker js files

### PR DESCRIPTION
**Pull request by sgiehl**
This action will make it possible to automatically update the minified tracker js files in a Pull Request.
It is triggered with a comment "build js" within a Pull Request.

It (currently) only works for Pull Requests that are based on a local branch.

### CODE REVIEW

**Comment by tsteur** [comment]
What will be the best way to test this?

**Comment by sgiehl** [comment]
Hm... I've developed & tested those actions on a fork. They need to be placed in the default branch (4.x-dev) to be executed

**Comment by tsteur** [comment]
OK feel free to merge tmrw and in worst case simply revert 👍

**Comment by tsteur** [comment]
OK feel free to merge tmrw and in worst case simply revert 👍

**Pull request merged**
