### PR TITLE
Fixed a typo in Extraction.php(FIrst pull request)

### PR DESCRIPTION
**Pull request by captainhaddock18**
fixed a typo and changed the spelling from "invald" to "invalid".

### CODE REVIEW

**Comment by sgiehl** [comment]
@captainhaddock18 Thanks for providing this fix. Looks like a couple of tests were actually comparing against exact that message. Would you mind updating those tests files as well?

**Comment by captainhaddock18** [comment]
> Would you mind updating those tests files as well?
Yes I update those files. Can you please tell me how to do it?

**Comment by captainhaddock18** [comment]
> @captainhaddock18 Thanks for providing this fix. Looks like a couple of tests were actually comparing against exact that message. Would you mind updating those tests files as well?

Yes I will update those files. Can you please tell me how to do it?

**Comment by sgiehl** [comment]
You may additional need to adjust this places:
* https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/Dimension/Extraction.php#L41
* https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/tests/Integration/Dimension/ExtractionTest.php#L214
* https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/tests/Unit/Dimension/ExtractionsTest.php#L61

**Comment by captainhaddock18** [comment]
> You may additional need to adjust this places:
> 
> * https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/Dimension/Extraction.php#L41
> * https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/tests/Integration/Dimension/ExtractionTest.php#L214
> * https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CustomDimensions/tests/Unit/Dimension/ExtractionsTest.php#L61

thank you for your help. I have updated In all the files

**Comment by sgiehl** [comment]
Can't see the changes here yet. Did you push them to the correct branch?

**Pull request closed without merging**
