### PR TITLE
Update icons

### LINKED ISSUE #7618: Update icons in Piwik
Currently icons in Piwik [are not consistent and are implemented as images](https://github.com/piwik/piwik/tree/master/plugins/Morpheus/images).

With the WIP of the redesign, we could take the opportunity to move towards font icons. Not doing this would mean either not using icons at all in redesigned parts, or using existing icons which don't fit well in it.

So we need a set of font icons.

The obvious solution IMO would be [Bootstrap](http://getbootstrap.com/components/#glyphicons) or even better, [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/) ~~but it requires Bootstrap…~~ (seem to be usable without Bootstrap, related to #7390)

Thoughts?

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7618

I have added the new font icons (TTF supported everywhere except IE8 + EOT for IE8 support). I have also replaced the usage of old icons. Sometimes instead of simply replacing the icons it made sense either to change the design a bit (e.g. all the user/site/goal/… "managers") or use standard UI elements (buttons, alerts, …). I haven't replaced _all_ the icons used in Piwik (mostly because some are much harder), this can be achieved later in other pull requests.

And by the way the new icons look much better on retina ;) (not pixellized)

For reviewing the PR please checkout the branch: some design changes are better to test in a browser rather than in a screenshot, especially the buttons in the "managers" (user, site, goals, etc.).

Here are the diff screenshots: http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/ You'll see that the square in the top-right has reappeared, and I don't remember what it is about and if it's a problem…

icons

### CODE REVIEW

**Comment by tsteur** [comment]
just FYI: The square is usually there when there is an update. Rebasing might hep

**Comment by tsteur** [comment]
just FYI: The square is usually there when there is an update. Rebasing might hep

**Comment by tsteur** [comment]
This here looks broken: http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/MeasurableManager_loaded . Same here http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/SitesManager_loaded , http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/MeasurableManager_add_measurable_view etc
 
Is the left margin supposed to be there? http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/RowEvolution_row_evolution


Is it normal that we use a red button for "adding entity" now (seen this in a few screenshot diffs)? http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/UIIntegrationTest_admin_manage_users

Edit / delete button look a bit weird similar to sitesManager: http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/UIIntegrationTest_admin_manage_users , http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/UIIntegrationTest_email_reports , http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/UIIntegrationTest_goals_manage

Is the icon here a bit smaller and further away from the text box? http://builds-artifacts.piwik.org/piwik/piwik/icons/14663/UIIntegrationTest_admin_settings_general

**Comment by mnapoli** [comment]
All those changes are deliberate :) Try it by pulling the branch locally, it's probably better to use it to see (hover, etc.).

To add more information on the red buttons, I've reused Piwik's default buttons (used everywhere else) for consistency (a consistent UI looks better and is easier to understand).

**Comment by mattab** [comment]
Nice progress on icons @mnapoli!

Re: red buttons for adding "entities". Since Edit+Delete are not red buttons, it is better to be consistent in this case, and use the `+` icon with black text for "Create new %s". In general, the UI looks better with + icon + black text for these actions.

can you add back the "Edit" and "Delete" texts next to the icons?

**Comment by mnapoli** [comment]
@mattab have you tried it locally? I spent a lot of time to try and improve all those tables, removing this kind of redundancy using the new icons was one of the main change of this PR:

capture d ecran 2015-08-13 a 18 32 07

To this:

capture d ecran 2015-08-13 a 18 33 05

Using it isn't confusing at all: the table headers + hovering makes it really clear what such buttons do. And we are talking about the 2 most common buttons ever in a web app.

What I've tried with this PR is continue on the consistency effort by introducing new standard UI elements (like the flat buttons, icon buttons, …) and replace custom design with the existing and new standard UI components.

**Comment by mattab** [comment]
good to hear it was all planned :-)

I checked the branch and it looks nice. I have couple feedback:
 * It's maybe not a problem to have the red buttons for adding entities... what do others think?
  * warning icon is misplaced in: warning icon
 * when the "info" alerts are displayed several time in page, eg. in Geo location settings, let's remove the bulb icons in these cases: many icons

What's left regarding adding icons, ie. which icons are left to be ported to the new ones? would be awesome to finish this in 2.15.0 :-)

**Comment by mnapoli** [comment]
> when the "info" alerts are displayed several time in page, eg. in Geo location settings, let's remove the bulb icons in these cases: […]

That's already the case, I tried to reproduce what you posted in your screenshot but I can't (Geolocation settings). It correctly displays without the bulb icon.

**Comment by mnapoli** [comment]
> warning icon is misplaced in: 

Fixed

> when the "info" alerts are displayed several time in page, eg. in Geo location settings, let's remove the bulb icons in these cases:

Fixed

**Comment by tsteur** [comment]
I'm not sure if this was mentioned already but think it might look better to vertically align the icons in notifications/warnings on top and not in the middle. 

I'd also prefer to not have the red buttons there. 

What is otherwise left here? The text in edit/delete?

**Comment by mnapoli** [comment]
> What is otherwise left here? The text in edit/delete?

What do you mean about edit/delete buttons?

> it might look better to vertically align the icons in notifications/warnings on top and not in the middle.

That how it was in the first version, it did not look good, see for example:



Or also http://builds-artifacts.piwik.org/piwik/piwik/master/14625/processed/CoreUpdaterDb_main.png

**Comment by tsteur** [comment]
> edit: They are vertically aligned. It only aligns to the top in IE8 and PhantomJS.

sweet! 

> What do you mean about edit/delete buttons?

Matt asked: "can you add back the "Edit" and "Delete" texts next to the icons?" so I got a bit confused what the current state on this is. From what I understood it is meant to be removed and we do not want to add them back but I'm not sure if I got it right :)

**Comment by diosmosis** [comment]
Looks good to merge after row evolution link / button thing is cleared up.

**Comment by mnapoli** [comment]
Restored the flat buttons for adding new entities, hopefully I didn't forget one.

**Comment by tsteur** [comment]
is it safe to merge? I could use the icons right now :)

**Comment by mnapoli** [comment]
It's ready to be merged if changes are OK.

**Comment by diosmosis** [comment]
Is the row evolution 'pick row to compare' link still supposed to be a button? @mattab Can you clarify?

**Comment by mnapoli** [comment]
@diosmosis I just made them flat, problem solved.

**Comment by diosmosis** [comment]
Follow up issue created here: https://github.com/piwik/piwik/issues/8632

**Pull request merged**
