### PR TITLE
vendor/twig/twig/lib/Twig/Extension/Core.php(1560): Warning - constant(): Couldn't find constant \Piwik::LABEL_ID_GOAL_IS_ECOMMERCE_ORDER

### PR DESCRIPTION
**Pull request by mattab**
Waiting for user feedback whether the notice is fixed

### CODE REVIEW

**Comment by robles-design** [comment]
I applied the fix, but it doesn’t work on my installation. Still the same warning:
WARNING: /piwik/vendor/twig/twig/lib/Twig/Extension/Core.php(1560): Warning - constant(): Couldn’t find constant Piwik::LABEL_ID_GOAL_IS_ECOMMERCE_ORDER - Piwik 3.1.1-b2

**Comment by mattab** [comment]
@robles-design What PHP version do you use?
Is there any chance you could send us (via https://piwik.org/contact/ ) a FTP or SSH access to your Piwik files, so we can try to find a solution for this?

**Comment by Findus23** [comment]
Another user for which it doesn’t work:

https://forum.piwik.org/t/visitors-in-real-time-not-working-after-upgrade-to-3-1/25524/17

**Comment by robles-design** [comment]
@mattab I've send you an email via https://piwik.org/contact/ 
PHP Version 7.1.6-nmm1
Hope this helps.

**Comment by teflontoni** [comment]
Hey @maatab I've sent you an email as well. (But not via the contact form, but from my business e-mail account). We already had an exchange of e-mails regarding this.
PHP 5.4.16

**Comment by robles-design** [comment]
@mattab Did you change something? Seems to work now. I'll test it more intensive tomorrow.

**Comment by mattab** [comment]
No I didn't change anything yet. Note that the issue only shows up if the Real Time Widgets shows a visit that has **converted a Goal**

**Comment by robles-design** [comment]
Ahh, ok. Thanks for the reply. At this time there aren't any goals, so I produced one and can confirm this.

**Comment by mattab** [comment]
Hi @robles-design @teflontoni 
I still haven't connected to your PIwik or changed anything there, but I think found the issue. Could you please apply this now updated patch? Would be great to hear your feedback!

**Comment by robles-design** [comment]
Hi @mattab 
I applied the updated patch and it seems to work. I couldn't reproduce the error. I'll give you more feedback after a working day with more traffic on the sites. Thanks for your help!

**Comment by mattab** [comment]
Great thanks for the quick feedback!

**Comment by robles-design** [comment]
Upgraded to 3.1.1 and it works. Thanks!

**Pull request merged**
