### PR TITLE
updated searchEngine and social icons

### PR DESCRIPTION
**Pull request by Findus23**
Follow-up to #11063: (related to #10587, #9292 and https://github.com/piwik/searchengine-and-social-list/issues/28)
I have crawled all URLs from the [searchengine-and-social-list](https://github.com/piwik/searchengine-and-social-list) and added
* the favicon defined via `<link rel="shortcut icon" href="/absolute/or/relative/link" />`
* or the first icon defined via `<link rel="icon" href="/absolute/or/relative/link" />`
* or the favicon served at `/favicon.ico`

If the .ico contains multiple sizes, the largest is extracted.
Finally, all images are converted to png.

To preserve historical data, I haven't deleted images of sites that aren't online any more.

Work in progress as I haven't checked all of them. (GitHub unfortunately shows only 25 visual diffs)

### CODE REVIEW

**Comment by sgiehl** [comment]
Note: We do not need images for all urls in the definition files. There is only one needed for each search engine / social network. The file name needs to have the url first listed in the search engine / social definition (regardless from which url you are able to pull it).

**Comment by Findus23** [comment]
I forgot to comment, but I have removed the unnecessary images and sharpened them as mentioned in https://github.com/piwik/piwik/pull/11063#issuecomment-269362531.

**Comment by Findus23** [comment]
The large icons in the tables should be resolved with this change in the first pull request:
https://github.com/piwik/piwik/pull/11063/commits/37b3ab001cc650126bfa8faeb19834905edd5a5a#diff-8b20fa1b843d28bf8988e7c3c93a54b2R483

**Comment by mattab** [comment]
Looks awesome @Findus23  - is the PR now ready to merge do you think?

**Comment by sgiehl** [comment]
This PR is ready? Just noticed the icons have different sizes. But guess that is the maximum size you could grab for each, correct?

**Comment by Findus23** [comment]
Exactly, most people use 16x16px as a favicon, but some had higher resolution icons, which I used.

**Pull request merged**
