### PR TITLE
delete old log_* table data also without idvisit

### LINKED ISSUE #16529: Old data in log tables without idvisit column are not purged (affects plugins)
According to customers in https://forum.matomo.org/t/form-analytics-doesnt-cleanup-its-old-form-field-form-page-log-data/38567

> I’m using Matomo (3.14.0) with Form Analytics (3.1.28). Both “delete old raw data” and “delete old aggregated report data” policies are in place (with core:archive cron job). Still, in practice, I see that Form Analytics purges records from the log_form db table only, leaving log_form_field and log_form_page tables filled with all the historical data from the beginning of time.
> I can confirm that old records are correctly purged from log_form but not from log_form_page/log_form_field tables, matching them by idvisit/idlogform. How can I clean that old data and prevent its accumulation in the future?

We would expect that log_form_page and log_form_field are purged indeed.

from @tsteur this is supposed to be done by core but it looks like it’s not fully implemented there for log tables without idvisit column.

### PR DESCRIPTION
**Pull request by geekdenz**
fixes #16529

### Description:

Reuse logic from DataSubject and refactor into core.

To test this manually, please see https://github.com/matomo-org/test-examples/blob/trackingformlogs/logdeleter/general/index.php . You can configure it with https://github.com/matomo-org/test-examples/blob/trackingformlogs/config/config.example.php .

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by geekdenz** [comment]
You'll need to apply this patch, otherwise it won't get into the code.

See https://github.com/matomo-org/test-examples/blob/trackingformlogs/logdeleter/general/index.php .

```patch
diff --git a/plugins/PrivacyManager/PrivacyManager.php b/plugins/PrivacyManager/PrivacyManager.php
index f11ff26b43..98055c9150 100644
--- a/plugins/PrivacyManager/PrivacyManager.php
+++ b/plugins/PrivacyManager/PrivacyManager.php
@@ -672,6 +672,7 @@ class PrivacyManager extends Plugin
         $deleteIntervalDays = $settings[$setting];
         $deleteIntervalSeconds = $this->getDeleteIntervalInSeconds($deleteIntervalDays);
 
+        return true;
         if ($lastDelete === false ||
             $lastDelete === '' ||
             ((int)$lastDelete + $deleteIntervalSeconds) <= time()

```

**Comment by sgiehl** [comment]
@geekdenz Wouldn't it make sense to add/change some tests in [LogDeleterTest](https://github.com/matomo-org/matomo/blob/4.x-dev/tests/PHPUnit/Integration/LogDeleterTest.php) to prove that the new logic works as expected. Ideally the new/changed tests would fail on 4.x-dev but work with the changes of this PR.

**Comment by tsteur** [comment]
@sgiehl it's not really needed since the logic we use itself is already tested.

**Review by sgiehl — DISMISSED** [review]
Just tested it locally, seems to work as expected 👍

**Review by tsteur — CHANGES_REQUESTED** [review]
@geekdenz it seems like maybe some other methods can now be removed as well like `Rawlogdao::deleteFromLogTable`?

The only other thought I have was that before we were doing `idvisit IN(1,2,3,4,4)` and now we use `idvisit=1 or idvisit = 2 or idvisit = 3`. I believe this is though the same for the query optimiser. Might be something to quickly double check / look into.

Also before we were doing `idvisit in (1,2,3,4)` and now we use placeholders using `?`. This is a regression and we should change the below query in `DataSubjects` to not use placeholders. When hundreds or thousands of placeholders are used then MySQL can get very very slow. We learned this over the years. We don't need to bind the parameters there if we cast the value to an integer.

**Comment by geekdenz** [comment]
> `idvisit IN(1,2,3,4,4)`

will be more efficient, though just by a constant factor (`strlen('idvisit = 1 OR ') - strlen('1,')`), even just because the text is shorter. The query optimiser might optimise this automatically though, but it adds another step for it. It'll add up with lots of IDs. I'll do it as it is not difficult.

**Comment by geekdenz** [comment]
OK. Double checked manually and got expected results:

```sql
mysql> SELECT distinct b.idvisit, c.visit_last_action_time, a.idlogform, a.idformview, a.field_name FROM matomo_log_form_field as a join matomo_log_form as b on a.idlogform=b.idlogform JOIN matomo_log_visit AS c ON c.idvisit=b.idvisit;
+---------+------------------------+-----------+------------+------------+
| idvisit | visit_last_action_time | idlogform | idformview | field_name |
+---------+------------------------+-----------+------------+------------+
|   10444 | 2020-08-01 00:00:00    |        24 | zaODNJ     | input1     |
|   10444 | 2020-08-01 00:00:00    |        24 | zaODNJ     | input2     |
|   10444 | 2020-08-01 00:00:00    |        24 | zaODNJ     | input3     |
|   10449 | 2020-08-01 00:00:00    |        28 | 9GlRNX     | input1     |
|   10449 | 2020-08-01 00:00:00    |        28 | 9GlRNX     | input2     |
|   10449 | 2020-08-01 00:00:00    |        28 | 9GlRNX     | input3     |
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input1     |
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input2     |
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input3     |
+---------+------------------------+-----------+------------+------------+
9 rows in set (0.01 sec)

mysql> SELECT distinct b.idvisit, c.visit_last_action_time, a.idlogform, a.idformview, a.field_name FROM matomo_log_form_field as a join matomo_log_form as b on a.idlogform=b.idlogform JOIN matomo_log_visit AS c ON c.idvisit=b.idvisit;
+---------+------------------------+-----------+------------+------------+
| idvisit | visit_last_action_time | idlogform | idformview | field_name |
+---------+------------------------+-----------+------------+------------+
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input1     |
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input2     |
|   10443 | 2021-09-07 03:05:54    |        23 | ZDa9lV     | input3     |
+---------+------------------------+-----------+------------+------------+
3 rows in set (0.01 sec)
```

**Comment by tsteur** [comment]
Fyi  tweaked the test cases to make sure it works fine when idvisit and idvisit+idsite is mixed and also to know it works when multiple deletions are requested. Was the easiest way for me to test the generated queries work.

Screenshot 2021-09-13 at 3 04 19 PM

Screenshot 2021-09-13 at 3 20 57 PM

**Comment by tsteur** [comment]
Generally tested for quite a while and looks all good to me. Waiting for automated tests to finish before merging 🎉

**Comment by geekdenz** [comment]
Thanks @tsteur for the added test and info!

**Pull request merged**
