### PR TITLE
update autocomplete on html to `on` and `off`

### LINKED ISSUE #19872: Update autocomplete values
In Matomo 4.12.0 it looks as though some fields are being auto filled by browser or browser extensions with the username. 
For example in the Measurables admin area browser autofill now enters the username in the search field:
image

I tested this in 4.11.0 and the behaviour was not the same, but after updating to 4.12.0 my browser password manager extension could auto fill the search bar with a username. I've tested a few different places where a search bar or input field is present and it seems to only affect the search input in the measurables.

This would mainly be an issue where people have browsers or extensions configured to autofill without interaction.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #19872 
update autocomplete on HTML from true and false to `on` and `off`

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
@peterhashair The change looks fine, but you don't need to request a review from me for every vue change now that the migration is nearing completion. Core reviewers can review them.

**Review by sgiehl — CHANGES_REQUESTED** [review]
This might not work as expected in some cases. E.g. when setting `autocomplete=off` directly, the change here would convert this to `autocomplete=on`.
Additionally this will add a `autocomplete=off` to all input fields that don't define a autocomplete. Not sure if that is expected.

Also we should consider to use the autocomplete attribute in a way, where we not only set it to `on` or `off`, but provide which data to autofill (or not).
For now I would say we should change all occurrences of `autocomplete=false` to `autocomplete=off`, so we later have the possibility to use something like `autocomplete="password"`

**Comment by peterhashair** [comment]
@sgiehl that makes more sense, I guess, we can change autocomplete from boolean to string, will update all the places that appear.

**Comment by peterhashair** [comment]
@sgiehl any suggestion on that PR, I update `autocomplete` to accept `string`

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
