### PR TITLE
New device icons

### LINKED ISSUE #11155: Improve icons and images in piwik
Follow-up to #10587 and similar to #9292

There are still many low resolution icons left in piwik:
- Flags:
     - Personally I don't like the "glossy" look of the current flags. (e.g fr)
     - There are many libraries providing official flags as svg (mostly from wikipedia | e.g [lipis/flag-icon-css](https://github.com/lipis/flag-icon-css))
     - After some tries I realized that converting the svg to 16px png images isn't enough.
While some simple flags look better (in my opinion, like at, fr or ch) ~others get ugly as too much detail is lost. (pk, us, sz, ba)~
     - ~I'm not sure what to do as it is pretty hard to show many details in 192 Pixel total (16x12)~
    This got better by increasing the icon size to 64x48px: ,,,
     - I would suggest keeping the height at 16px (48px) even if this means being a bit wider than the other icons, as they would fit better in line. 
     - [old](https://cloud.githubusercontent.com/assets/6266037/21582108/58952c50-d04b-11e6-8f24-495952351f06.png) vs. [new](https://cloud.githubusercontent.com/assets/6266037/21742341/dc4b105a-d4ec-11e6-9221-e9ba481fbffd.png)
- DevicesDetection/images/screens
    - In my opinion it's quite important to replace these (11) icons, as they are extremely pixelated next to the new icons 
6083834a-d13a-11e6-9ffb-38dd847ed4ad
     - Anybody got an idea what icons to use. I [haven't found](https://commons.wikimedia.org/wiki/Category:Computer_monitor_icons) pretty ones.

- DevicesDetection/images/brand
    - I'd suggest creating a list of most common brands and only replace the icons for them. (https://github.com/piwik/piwik/issues/10587#issuecomment-269909494)

But there are still many single icons left (either in Morpheus or in the `images` folders of the core plugins). Best would be to recreate them a vector image and maybe even embed them as svg.

### PR DESCRIPTION
**Pull request by Findus23**
fixes #11155

This replaces the old device icons with better ones from https://material.io/icons/

screenshot_20170408_094507

The icons aren't final so if anyone has better ideas, just mention them.

I hope the changes in  plugins/DevicesDetection/functions.php are okay.

There are still some tests failing.

(the failing UI tests are because of the new browser icons)

### CODE REVIEW

**Comment by sgiehl** [comment]
I like the look of the new icons!

**Comment by Findus23** [comment]
Is it possible something went wrong with the commits just now? [Travis restarted](]https://travis-ci.org/piwik/piwik/builds/220295534) and I got a conflict when pulling (`warning: Failed to merge submodule plugins/CustomDimensions (commits don't follow merge-base)`)

Did I do something wrong?

**Comment by sgiehl** [comment]
if you don't have any additional local changes or commits try:
`git reset --hard origin/new-device-icons`
otherwise you could also force push your branch

**Comment by Findus23** [comment]
Thanks, that fixed it. But what caused it?

**Comment by sgiehl** [comment]
Me :slightly_smiling_face: 
I had rebased your branch locally to view it with latest `3.x-dev` changes and accidentally pushed it - thought I already was on another branch...

**Comment by Findus23** [comment]
Ah, that explains it :smile:

**Comment by sgiehl** [comment]
@Findus23 Let's merge this for the upcoming 3.0.4. Is there any work left on your side?

**Comment by Findus23** [comment]
It's ready for me. There are just some tests that need to be fixed.

**Comment by sgiehl** [comment]
Ok. I'll rebase the branch and try to fix the remaining tests so we can merge it afterwards

**Comment by Findus23** [comment]
In addition we'll need to make this changes to the CustomDimensions Plugin
```diff
diff --git a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
index 9b55fd8..899c81f 100644
--- a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
+++ b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
@@ -65,7 +65,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -183,7 +183,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -299,7 +299,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -447,7 +447,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -563,7 +563,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
```

**Comment by sgiehl** [comment]
ok. Everything should be fixed/updated now. Thanks for the PR @Findus23

**Comment by mattab** [comment]
Well done, new icons look great!

**Pull request merged**
