### PR TITLE
Add option to disable ISP DB even if it exists in the filesystem

### PR DESCRIPTION
**Pull request by tsteur**
### Description:

refs CLOUD-710. @sgiehl do you reckon something like this could be an OK solution to disable the ISP/ASN DB even if it is present in the filesystem? I'm trying to add this for multi tenant install on Cloud where we will have the file present in the filesystem but only want it to be used by very few accounts. I tried playing around by pointing `path.geoip2` into a different directory depending on the tenant but this proved very difficult in a cloud setup and ensuring files are being kept up to date etc. This would make it a lot simpler.  
I haven't fully tested it but do you reckon that would work and be ok like this?

If that solution would be fine I could try and add some test for it.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
As this is no official config option and for now only being used for cloud, I guess we could go with that solution.
In general I think we should improve that geoip stuff overall. Imho the geoip provider should show all databases that were found for each type (location & isp), with the possibility to choose the ones to use. That way it would be possible to e.g. disable one of them or choose e.g. a country database even though a city database is available. 
In theory we could even do it in a way that allows to change the used database for each site separately.
But guess those changes are a bit out of scope for now.

**Comment by tsteur** [comment]
Awesome thanks. I've just done some manual testing and it worked. I couldn't really figure out a way to test it though. Do you have any idea? Or maybe it doesn't need one?

**Comment by sgiehl** [comment]
We could perform such tests with disabled isp and check that there aren't any results:
https://github.com/matomo-org/matomo/blob/d1e15c23dc07f87fb959a29013a519898302b182/plugins/GeoIp2/tests/Integration/LocationProviderTest.php#L94-L114

**Comment by tsteur** [comment]
Awesome, thanks for this @sgiehl . I've added some tests

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
