### PR TITLE
Remove gears detection

### PR DESCRIPTION
**Pull request by sgiehl**
cheers @pebosi for the initial work

replaces #15627

### CODE REVIEW

**Comment by sgiehl** [comment]
I've gone through the changes again and reviewed them. There were some tests failing and various changes missing in other repos (see linked PRs). Would be good if someone else could quickly look through the changes.

And just to point it out again. These changes will drop the column that was used to store the gears detection. But as it wasn't possible to segment for that and there shouldn't have many detections been positive in the past anymore, I think we can remove that. Already processed reports might still show gears, only new reports won't contain it anymore...

**Comment by tsteur** [comment]
@sgiehl not sure if this needs another review from someone else as you reviewed it initially?

**Comment by sgiehl** [comment]
@tsteur If removing the column is fine, guess it should be enough to have a look at the linked PRs and maybe the changes I've added to this PR

**Comment by tsteur** [comment]
Had a quick look and looks all good @sgiehl  👍

**Pull request merged**
