### PR TITLE
Update UI test around plugins order

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

After the recent change the order of plugins changed in the UI test screenshot. This change adds a default sort (that can be overridden via an existing mechanism, if needed), and updates the screenshot for consistency.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Added this to the 5.1.0 milestone as it's a fix that should be included in that version even though it's not part of the release package.

**Review by sgiehl — CHANGES_REQUESTED** [review]
This might look like a small change only, but it is actually a breaking one, that has the potential to break some configurations out there.
The order defines how the di config files are loaded. Plugins loaded later will have the possibility to overwrite configs of the previous ones.
Custom or additionally installed plugins are normally attached below, so they con overwrite core plugin configs. Sorting that list alphabetically breaks this behaviour.

**Comment by michalkleiner** [comment]
@sgiehl this was a fix of the UI test primarily, the test is broken even without the explicit `sort` added here. I believe the order got changed with the introduction of the feature flag mechanism where we needed to merge the always active plugins with the active plugins. So we probably need to reconsider that as well.

**Comment by michalkleiner** [comment]
I don't see the same failure this was addressing in the recent UI test runs so will close it for now. Can always revisit if needed.

**Pull request closed without merging**
