### PR TITLE
Open site in new tab/window if ctrl key is pressed

### LINKED ISSUE #13701: Website selector: Ctrl+Click should open the website in a new tab
Steps to reproduce:

* Click on website selector
* Do Ctrl+Click on a website name
* Got: the website clicked opens in the same window
* Expected instead: the website clicked opens in a new tab

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #13701

### CODE REVIEW

**Comment by diosmosis** [comment]
This doesn't work for me on OS X, I presume because the 'cmd' key needs to be pressed in order to launch in a new tab ('ctrl' opens a popup menu).

**Comment by sgiehl** [comment]
@diosmosis  could you check if `metaKey` instead of `ctrlKey` works on OS X? I don't have a Mac, so can't test it

**Comment by tsteur** [comment]
Can we change the HTML structure slightly to use an actual link for each site and the all websites plus `ng-href` or so which updates the link when things change? Then it would work properly on all OS etc

**Comment by sgiehl** [comment]
actually there are "real" links with hrefs for each site. But all clicks on those links are ignored because of `piwik-ignore-click`

**Comment by diosmosis** [comment]
@sgiehl w/ metaKey it works for me

**Review by Dzhuneyt — APPROVED** [review]

**Comment by sgiehl** [comment]
@diosmosis added a check to use `metaKey` for OS X and `ctrlKey` for other systems

**Review by Dzhuneyt — APPROVED** [review]

**Pull request merged**
