### PR TITLE
Typing Core/Access

### PR DESCRIPTION
**Pull request by tolbon**
Type Core/Access Folder
Add getHelpUrl URL for Write Role

### CODE REVIEW

**Comment by tolbon** [comment]
CI don't pass cause TagManagerPlugins I push a PR on this too

**Comment by tsteur** [comment]
@tolbon I have merged the tag manager PR. Could you pull the changes from tag manager `4.x-dev` branch and update the submodule for TagManager and push the change? Let me know if you need help with this.

**Comment by tolbon** [comment]
Yeah Can you explain please I'm not easy with that  !-_- sorry

**Comment by tsteur** [comment]
Are you using the command line for working with `git`?
You would do something like this:

```bash
cd plugins/TagManager
git checkout 4.x-dev
git pull origin 4.x-dev
cd ../..
git add plugins/TagManager
git commit -m 'Update tag manager submodule'
git push origin typing_core_access
```

If you use some UI for this I can't really help you that much. Basically you'd just need to make sure your Git UI pulls the latest changes for the Tag Manager repository in the `4.x-dev` standard branch and then you basically commit this update to your Matomo repository in this `typing_core_access` branch

**Comment by tolbon** [comment]
Thank you so much. I am not easy with git (submodules etc...)

**Comment by tsteur** [comment]
Thanks @tolbon updating the submodule worked 👍

**Pull request merged**
