### PR TITLE
File integrity checker now reports files found in the filesystem but not expected to be there

### LINKED ISSUE #11087: System check diagnostic issue a warning or even error if an unexpected file is found within Piwik filesystem (excluding marketplace plugins)
Add new System check diagnostic (or rather update the existing check `File integrity`) to issue a warning or even error if an unexpected file is found within Piwik filesystem (excluding marketplace plugins)

### PR DESCRIPTION
**Pull request by mattab**
fixes #11087

### CODE REVIEW

**Comment by mattab** [comment]
It looks like this when files are in the filesystem but not expected to be there:

integrity check

**Comment by mattab** [comment]
## As a result of this PR we may start to over-report problems, for example when you add some files in Piwik and they are expected to be there. Please report here if that's the case or create a new issue

**Comment by s1awa** [comment]
@mattab Please whitelist unifont.ttf from https://piwik.org/faq/how-to-install/faq_142/ in File integrity checker

pwk

**Comment by mattab** [comment]
Thanks for the note @s1awa  - created a separate issue

**Comment by mathomp4** [comment]
@mattab My only other suggestion for this would be, perhaps, breaking up the "run this command" command. A few times I've had a *lot* of files reported as unexpected. When I copy and paste the command, it's longer than some buffer on my box. It seems to be at 8189 characters, which must be a buffer in X? Gnome? Not sure who handles the middle button copy.

Would it be possible to limit the size of commands provided and give two or three commands to copy-and-paste?

**Comment by mattab** [comment]
Hi @mathomp4 Yes it's possible. But please create a new issue for this because this one is already closed

**Pull request merged**
