### PR TITLE
Allow use of GeoLite2-ASN database as ISP database

### LINKED ISSUE #12871: [3.5.0] Download of the geoip2 ISP/ASN database fails
The download self, will work, but the database will not detected:
Uses database: http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz
Error:

> No valid GeoIP database could be found in tar archive '/var/www/piwik/misc/GeoIP2-ISP.mmdb.tar.gz'!f

tar tzf GeoIP2-ISP.mmdb.tar.gz 
GeoLite2-ASN_20180508/
GeoLite2-ASN_20180508/COPYRIGHT.txt
GeoLite2-ASN_20180508/LICENSE.txt
GeoLite2-ASN_20180508/GeoLite2-ASN.mmdb

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12871

### CODE REVIEW

**Review by diosmosis — CHANGES_REQUESTED** [review]
Code looks good, some system tests appear to be failing now.

**Comment by diosmosis** [comment]
Unrelated to this PR, but noticed in https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/GeoIp2/GeoIp2.php#L26, we're checking if the current location provider is an instance of the `GeoIp2` plugin. I think the full namepsace needs to be there. Missed this in last PR review.

**Comment by diosmosis** [comment]
Tested locally, works, just need to fix the tests.

**Comment by sgiehl** [comment]
@diosmosis  fixed the check and updated the tests.

**Comment by mackuba** [comment]
Hey, this be available in the next release, right?

**Comment by diosmosis** [comment]
@mackuba this should be in 3.5.1, so should be in the latest release.

**Comment by mackuba** [comment]
@diosmosis ah, right, I've looked in the code on the server and the changes are there.

Is it necessary to enable the Provider plugin to see ISPs on the location reports page? I've dug into the code a little bit, and it looks like without the Provider plugin the `location_provider` column isn't even present in the database, but I've read somewhere that the Provider plugin is disabled by default, because it runs reverse DNS which is rather slow - but that shouldn't be needed at all if I get the provider info from the MaxMind database?... Does it make sense what I'm saying?

**Comment by diosmosis** [comment]
Looks like the plugin has to be installed for the column to be in the table and for the provider to be looked up: https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/UserCountry/Columns/Provider.php#L31. I think it also needs to be enabled in order to display the report. The reverse DNS logic shouldn't execute if the provider information is obtained via GeoIP2 (I believe).

I think otherwise you have to be using a Maxmind GeoIP implementation and the ASN database has to be named 'GeoLite2-ASN.mmdb' or 'GeoIP2-ISP.mmdb'.

**Comment by mackuba** [comment]
Great, thanks!

**Pull request merged**
