### PR TITLE
Responsive reports: 2 columns layouts now use Bootstrap CSS classes

### PR DESCRIPTION
**Pull request by mnapoli**
I have replaced the usage of CSS IDs `#leftcolumn` and `#rightcolumn` (used to create a 2 columns layout) with Bootstrap column classes.

Those 2 column layouts are now responsive and work on mobile (or any smaller screen).

To have an idea of the current problem, visit the current demo (e.g. http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#/module=VisitTime&action=index&idSite=1&period=day&date=yesterday) and try to resize the page: not responsive. With this PR the right column goes under the left column when the window width is too small.

### CODE REVIEW

**Comment by mnapoli** [comment]
The diff is pretty awful but the change is basically going from this:

```html
<div id="leftcolumn">
    ...
</div>
<div id="rightcolumn">		
    ...	
 </div>
```

(notice also that IDs were used which is not ideal because it's sometimes reused many times in the same page)

To this:

```html
<div class="row">
    <div class="col-md-6">
        ...
    </div>
    <div class="col-md-6">
        ...
    </div>
</div>
```

To learn more about Bootstrap classes read the documentation here: http://getbootstrap.com/css/#grid-example-basic

**Comment by mnapoli** [comment]
Here are some screenshots when the window is resized to something small.

### Before

capture d ecran 2015-03-23 a 14 18 07

### After

screencapture-piwik-dev-index-php

**Comment by mattab** [comment]
this has been an issue for a long time. Nice change! 
 * a report was created since the PR in https://github.com/piwik/piwik/blob/replace-columns-with-bootstrap/plugins/DevicesDetection/templates/software.twig#L6-6 and it's using leftcolumn

**Comment by mnapoli** [comment]
`software.twig` updated in the PR

**Comment by mattab** [comment]
nice, this is an improvement that will please many users

**Pull request merged**
