### PR TITLE
Ensure no tooltip is shown in opened limit selection

### LINKED ISSUE #12937: Tooltip for limit selector appears even when limit selector is open
image

I find it kind of distracting since it moves with the mouse and can block option text.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12937

### CODE REVIEW

**Comment by diosmosis** [comment]
Works the first time, but then the tooltip is removed from the selector. Guess it has to be re-added after the selector is closed?

**Comment by diosmosis** [comment]
Just did a quick test on demo.piwik.org, and if the `title=...` is on the `<input/>` in the limit selector and not the `.limitSelection` div, it seems to work well.

**Comment by sgiehl** [comment]
Updated it accordingly :+1:

**Comment by diosmosis** [comment]
Looks good 👍

**Pull request merged**
