### PR TITLE
Deprecated synchronous XHR requests rewritten to async

### LINKED ISSUE #8020: Rewrite all synchronous XHR as they are deprecated
Since Chrome 43 I am getting this warning in developer tools:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

I noticed especially in Dashboards plugin some sync requests but there might be even more. We need to rewrite those requests to be async.

I'm tagging it as performance/enhancement since it will also make the UI a bit faster. Feel free to change it.

### PR DESCRIPTION
**Pull request by barbushin**
I created this PR as duplicate of #8242, because #8242 source was `barbushin:8020_xhr_sync_fix2` and there was a problems with UI tests screenshots diff viewer(see https://github.com/piwik/piwik/pull/8242#issuecomment-120849678). 

Fixes #8020

### CODE REVIEW

**Comment by barbushin** [comment]
Can somebody please help me to understand what is wrong with UI tests in this PR?

I see diffs like this http://builds-artifacts.piwik.org/ui-tests.8020_xhr_sync_fix/14267.7/ActionsDataTable_initial and I can't find out why this happens, because PR code does not affects any HTML or CSS, only JS.

Thank you!

**Comment by mnapoli** [comment]
It looks like it's using a different font. But there seems to be the same issue on master (where tests are failing): http://builds-artifacts.piwik.org/ui-tests.master/14270.7/ActionsDataTable_initial So I think it's not an issue with your PR

**Comment by tsteur** [comment]
I will restart the tests, hope it helps

**Comment by tsteur** [comment]
There are some problems with change layout etc where we should look into http://builds-artifacts.piwik.org/ui-tests.master/14270.7/screenshot-diffs/diffviewer.html Only the tests starting with `Dashboard_` are caused by this PR

**Comment by tsteur** [comment]
I will close this issue as we converted lots of the UI to angular so we got rid of synchronous requests anyway. Cheers for the PR 👍

**Pull request closed without merging**
