### PR TITLE
update piwik-icons submodule

### PR DESCRIPTION
**Pull request by Findus23**
As I was in the middle of a restructure, the last Piwik release didn't include an update of the icons.
Because it's finished now Piwik 3.3 will have many icon changes (289 files in 37 commits):
https://github.com/piwik/piwik-icons/compare/ac9c01d795fc5608362db75609289b0543753aa5...48d5d33165746f4bb41a7b2b632f171325117fbf

Thanks again to @sogen for also contributing icons.

### CODE REVIEW

**Comment by Findus23** [comment]
This test seems broken:
https://builds-artifacts.piwik.org/piwik/piwik/update-piwik-icons-again/25435/Live_visitor_log.png

**Comment by sgiehl** [comment]
It's failing often in the last days... maybe we need to increase the wait times. will check that when I have some time

**Comment by Findus23** [comment]
Now all (working) tests should be fixed

**Comment by sgiehl** [comment]
Not sure why some of the tests nearly always fail for the build on branches, but work for PR builds against master... You can update the one remaining here: https://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/25440/Live_visitor_log.png

**Comment by Findus23** [comment]
Done in https://github.com/piwik/piwik/pull/12389/commits/a95699e562530ff6637165da0b5745c5d6f07bf4

**Comment by sgiehl** [comment]
Will have another look as soon as the builds finished. Guess we can merge it then :)

**Pull request merged**
