### PR TITLE
Fixed GitHub case

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by lipis** [comment]
screen shot 2016-10-07 at 13 16 22

I wanted to find/change that one.. but I'm guessing it's from another service :)

**Comment by lipis** [comment]
not sure why this is failing..

**Comment by tsteur** [comment]
Thanks for that 👍  Very appreciated

**Comment by lipis** [comment]
But where can I find the `Github` that is appearing on the chart?

**Comment by sgiehl** [comment]
This is in https://github.com/piwik/searchengine-and-social-list/blob/master/Socials.yml
But changing that wouldn't update already tracked data and so it would also effect statistics.
Evolution charts would show historical data for 'Github' but no ongoing data, where as 'GitHub' would start to be tracked - having no historical data

**Comment by tsteur** [comment]
That's here: https://github.com/piwik/searchengine-and-social-list 

https://github.com/piwik/searchengine-and-social-list/blob/07046e6c6472f3cf7751f45f7b1f1657dcf920e7/Socials.yml#L62

It is in a separate repository so other people can re-use it in other projects

**Comment by tsteur** [comment]
@sgiehl maybe we could use the `GroupBy` filter in the API there? Would be great to still have correct numbers independent of case

**Comment by lipis** [comment]
I agree with @tsteur  the grouping should not be depended on the case..

**Comment by sgiehl** [comment]
Guess that would be a possibility, but keep in mind, that the social definitions are update in all existing piwik using a task. So it would be broken there until Piwik was updated

**Comment by lipis** [comment]
I understand how programming works..

**Pull request merged**
