### PR TITLE
Omnifixture Update for automated UI screenshot tests

### PR DESCRIPTION
**Pull request by sgiehl**
Omnifixture wasn't update for a while now, so there are a lot of changes in UI tests that needs to be checked. Could anyone (@mattab, @tsteur, @diosmosis) please check the changed UI screenshots and mark the changes as correct or not.

### CODE REVIEW

**Comment by sgiehl** [comment]
Note: The rowevolution screenshots need #9241 to be merged in order to be processed correct. I'll do a rebase after that is done.

**Comment by diosmosis** [comment]
My approach to updating OmniFixture is to ignore changes that are just to data. It would be near impossible to isolate any data inaccuracies in the UI tests, IMO it's better to rely on system tests for that. If the new data triggers UI bugs (ie, css issues, double encoding, xss issues, etc.), then it should be fixed, but otherwise trying to check if the data is accurate would only be waste of time.

**Comment by mattab** [comment]
I clicked like crazy through all of them to check. In general there is less data in the new omnifixture, which seems maybe un-expected? 

examples:

 * http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_referrers_campaigns -> some campaign info are lost
 * http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_usersettings_index -> less visits
 * http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/MultiSitesTest_all_websites 
 * http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_goals_individual_goal -> much less goals
 * etc.

BUG:

 * Transitions not showing up http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/Transitions_transitions_popup_titles

 * no data in report: http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/GoalsTable_goals_table_abandoned_carts
  * also http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/GoalsTable_goals_table_ecommerce_view
  * also http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_ecommerce_products
  * this causes the UI test to fail http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/RowEvolution_row_evolution_ecommerce_item
 * no downloads data http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/Theme_home and http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_actions_downloads

 * no site search data http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/UIIntegrationTest_actions_site_search 
  * also here, causing this UI test to become useless http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/ViewDataTableTest_15_search

 * this looks like a real bug w/ Row evolution? : http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/RowEvolution_multirow_evolution_other_metric
 


UNRELATED:

 * http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/16875/ViewDataTableTest_8_tag_cloud -> this UI test is showing bar graph but according to its name, should show Tag Cloud

**Comment by mattab** [comment]
maybe you have some idea why the omnifixture now has less data @sgiehl @diosmosis ?

**Comment by sgiehl** [comment]
I've tested for a while where the data differences are coming from.
It seems that after building the OmniFixture the archives included do not contain all data, so I used console commands to invalidate all archives and rebuilt them using `core:archive`. The resulting sql dump seems to contain nearly the data as before. See http://builds-artifacts.piwik.org/piwik/piwik/omnifixtureupdate/17335/

Does anyone know if there were any changes in the past few months that could cause the OmniFixture not to contain full archives?

**Comment by diosmosis** [comment]
@sgiehl, @mattab asked me to work on this. Are you going to continue working on this? If so, please clarify with Matt.

**Comment by sgiehl** [comment]
Feel free to work on it.
You may have a look at the two fixes I had commited on this branch:
The first fixes builing the Omnifixture, which was broken for me again
after rebasing on master, the second fixes the Ui tests for switching the
display types...

**Comment by diosmosis** [comment]
I've rebased my local changes w/ your remote changes, so they're included for me locally.

**Comment by diosmosis** [comment]
@mattab Latest build may pass, you can see the screenshot changes here: https://github.com/piwik/piwik-ui-tests/pull/5/files

**Comment by mattab** [comment]
@diosmosis Awesome! :+1:  Could you please resolve conflict and merge both PR?

**Pull request merged**
