### PR TITLE
docs: add one-click deploy link to README

### PR DESCRIPTION
**Pull request by jbgh**
### Description:

Add [one-click deploy ](https://app.trydome.io/signup?package=matomo) to README

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [X] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [X] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Hi @jbgh, thank you for opening the PR.

At the moment, I don't think we are able to promote a specific hosting service like Dome in the main Matomo project's readme, sorry.

You are more than welcome to post to our [forums](https://forum.matomo.org/) or promote the service in other ways.

With that I'll close the PR. Thank you for understanding.

**Comment by jbgh** [comment]
Hi @michalkleiner thanks for the feedback! We are exploring ways to simplify the self-hosting process for matomo users, especially for those who may not have experience in setting up their own infrastructure.

This link allows users to who may not have the experience standing up their own infra to deploy it in one-click with having to mess with configuration. Might not be the necessary for your more technical audience, but could be more applicable for QA and PMs.

Feel free to test it. We're more than willing to maintain this if find it valuable for the matomo community.  In the meantime I'll look at engaging with the community on your forums.

**Comment by michalkleiner** [comment]
@Stan-vw perhaps still wort keeping on your radar.

**Comment by Stan-vw** [comment]
Thanks for tagging Michal.
@jbgh it sounds like I could be your "ideal user" as I'm a PM that would like to run various Matomo instances but the setup process isn't particularly intuitive for me. However, I'm not familiar with Dome, so I was surprised to see login/signup details on the linked page. Perhaps you can link the corresponding forum post, so that myself and potential future readers can ask our questions on how this works. As an example, if I'm going to sign up for a free trial of 7 days, why not just make a Matomo cloud account with a longer free trial 😄

**Pull request closed without merging**
