### PR TITLE
When creating HTML reports in tmp/assets/ include a random string in the filename

### LINKED ISSUE #13586: When creating HTML reports in tmp/assets/ include a random string in the filename
For users using Nginx or when .htaccess is disabled, it may be possible to guess the filenames and access HTML/PDF report data. 

To prevent this issue we could for example introduce a random string in the filename, which would be removed when the file is being downloaded via the API.

This should not impact most users as they would use apache with .htaccess support, which would prevent direct file access.

### PR DESCRIPTION
**Pull request by tsteur**
fix #13586

### CODE REVIEW

**Comment by diosmosis** [comment]
Should this also remove the suffix from the filename? Could be possible w/ a `Content-Disposition` header I think.

**Comment by tsteur** [comment]
Not sure what you mean?

**Comment by diosmosis** [comment]
The issues says "which would be removed when the file is being downloaded via the API". I assumed that there needed to be some code to remove the extra string, maybe that's not needed? I haven't tested locally, will do that.

**Comment by mattab** [comment]
I can't remember why we need to store reports on disk? but if we can get rid of that, it would be best :+1:

**Comment by diosmosis** [comment]
> The file wouldn't be downloaded, it would be persisted on the file system and a user can access the report through the returned output path at any time...

I see so there's no API method like `downloadReport()`.

**Comment by tsteur** [comment]
Done.

> I see so there's no API method like downloadReport().

Nope there isn't, there is only a direct download option for which the option "save on disk" is not needed.

**Comment by tsteur** [comment]
Fixed the test 👍

**Pull request merged**
