### PR TITLE
Updates expected screenshots

### PR DESCRIPTION
**Pull request by sgiehl**
I've updated the expected screenshots where I think the changes are valid.
[One is still failing](http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/20807/Overlay_page_new_links.png) due to some changes merged in https://github.com/piwik/piwik/pull/10580
Tried to figure out for a while why it is failing, but I didn't success. Reverting the changes from #10580 fixed the test again, so it needs to be one of the change there...

@mattab @tsteur could anyone have a small look at the changes and merge the PR if all are valid?

### CODE REVIEW

**Comment by tsteur** [comment]
Looks all good to me. The screenshot you mentioned not sure why it fails. It may be a random screenshot failure. Maybe we wait for a bit to see if it occurs all the time?

**Comment by sgiehl** [comment]
Tried that more than once. It's definitely not random. Fails always, but succeeds if changes of the mentioned PR are reverted.

**Comment by tsteur** [comment]
Maybe https://github.com/piwik/piwik/compare/3.x-dev...overlay_uitest_fix?quick_pull=1 helps. Otherwise we might need to improve the selector and then it may work

**Comment by sgiehl** [comment]
I'll merge this one now. We can try to fix the remaining test later

**Pull request merged**
