### PR TITLE
Add option to allow skipping logic that exits w/ an error code if warnings are detected in the output

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

This is for automation for the vue migration, specifically being able to run vue:build and tell if there is a legitimate error in the file.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — APPROVED** [review]

**Review by bx80 — CHANGES_REQUESTED** [review]
Just spotted an integration test exception on the travis build:

 ```
Uncaught exception: /home/travis/build/matomo-org/matomo/vendor/symfony/console/Symfony/Component/Console/Input/Input.php(180): The "ignore-warn" option does not exist. [Query: , CLI mode: 1]
[InvalidArgumentException]                
The "ignore-warn" option does not exist.  
```

**Comment by diosmosis** [comment]
@bx80 thanks for the catch!

ping @tsteur since this is an API change

**Comment by tsteur** [comment]
@diosmosis not sure I fully understand the regression. As long as `ignore-warn` is optional and we keep existing behaviour it should be fine?

**Comment by diosmosis** [comment]
@tsteur it's not a regression, I need the change for some automation, specifically to be able to run vue:build and check whether it actually built something rather than it failing because a WARNING was emitted (see https://github.com/matomo-org/matomo/pull/18392 for some details on the use case). I'm not sure how good the parameter name is.

**Comment by tsteur** [comment]
Name is fine by me. I can't think of a better name except some really long ones but they be too long.

I would however adjust the description to also include error logs `Return 0 exit code even if there are warnings or errors detected.` Although maybe that's misleading too as it then might sound like we would catch any kind of error and return 0 exit code?

**Comment by diosmosis** [comment]
@tsteur

> I would however adjust the description to also include error logs `Return 0 exit code even if there are warnings or errors detected`. Although maybe that's misleading too as it then might sound like we would catch any kind of error and return 0 exit code?

That sounds better. I can make it `Return 0 exit code even if there are warning logs or error logs detected in the command output.` to be more specific.

**Comment by tsteur** [comment]
Awesome, thanks 👍

**Pull request merged**
