### PR TITLE
README: adding badges 

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by tsteur** [comment]
Thanks for your PR. We have some badges at the end of the readme and some are duplicated now I think. Can you maybe move them to the end of the page?

**Comment by spekulatius** [comment]
Hello @tsteur 

thanks for your reply. I sorted this a bit more. Have a look and let me know what you think.

Spek

**Comment by tsteur** [comment]
I think they were supposed to be at the bottom but I'd personally prefer them at the top as well. As mainly developers look at this it is quite useful and I think it's very common to have the badges at the top.

Leaving this to @mattab

**Comment by mattab** [comment]
since all projects put buttons at the top, and users expect it, it's useful to be consistent :+1:  Thanks for the PR!

**Pull request merged**
