### PR TITLE
Fixes HTML_QuickForm2_ContainerIterator for PHP8.1

### LINKED ISSUE #18374: [PHP8.1] Deprecated return type of HTML_QuickForm2_ContainerIterator
Even after #18309 there are still two deprecation warnings in this script:
```
PHP Deprecated:  Return type of HTML_QuickForm2_ContainerIterator::hasChildren() should either be compatible with RecursiveArrayIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/matomo/libs/HTML/QuickForm2/Container.php on line 68
PHP Deprecated:  Return type of HTML_QuickForm2_ContainerIterator::getChildren() should either be compatible with RecursiveArrayIterator::getChildren(): ?RecursiveArrayIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/matomo/libs/HTML/QuickForm2/Container.php on line 74
```

## Expected Behavior

No deprecation warnings.

## Current Behavior

Deprecation warnings as shown above.

## Possible Solution

While this is not a good solution, I currently muted those via:
```php
    #[\ReturnTypeWillChange]
    public function hasChildren()
    {
        return $this->current() instanceof HTML_QuickForm2_Container;
    }

    #[\ReturnTypeWillChange]
    public function getChildren()
    {
        return new HTML_QuickForm2_ContainerIterator($this->current());
    }
```

## Steps to Reproduce (for Bugs)

1. Install `php8.1-fpm`
2. Access and browse Matomo web interface, through I couldn't identify the exact element/page which triggers this.

## Your Environment

* Matomo Version: v4.6.0-rc2
* PHP Version: 8.1.0RC6
* Server Operating System: Debian Bookworm
* Additionally installed plugins:
```
API, Actions, Annotations, BulkTracking, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, DBStats, DarkTheme 1.1.7, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Goals, IPReports 4.1.1, ImageGraph, Insights, Installation, Intl, LanguagesManager, Live, LogViewer 4.0.1, Login, Marketplace, Monolog, Morpheus, PagePerformance, PrivacyManager, Proxy, Referrers, Resolution, SEO, SegmentEditor, SitesManager, TrackingSpamPrevention 4.1.0, Transitions, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable
```

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

missed that in https://github.com/matomo-org/matomo/pull/18309

fixes #18374 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by MichaIng** [comment]
Are those probably required here as well? https://github.com/matomo-org/matomo/blob/c4431ba/libs/HTML/QuickForm2/Element/Select.php#L63-L69

**Comment by sgiehl** [comment]
@MichaIng thanks for spotting that. I've pushed a fix.

**Comment by justinvelluppillai** [comment]
@sgiehl were you able to reproduce this issue? I have been unsuccessful, even calling `$form->getElementsByName()` directly doesn't give any error for me in PHP8.1.

The changes look fine but it'd be good to see them fix an actual issue that I can repro 😝

**Comment by sgiehl** [comment]
Actually I couldn't. Those I could reproduce were already fixed in another PR.

**Review by justinvelluppillai — APPROVED** [review]
Seems like this will fix the reported issue the same as the other fixes you made.

**Comment by MichaIng** [comment]
I'm not sure how it could have happened, but Matomo v4.6.2 has now been released without this commit. Ah, I see now the v4.7.0 milestone, just wondering why since this is a trivial but effective fix without any backwards compatibility issues 🤔. However, I'll re-apply it again manually.

**Pull request merged**
