### PR TITLE
[Vue] Add support for scoped styles (though they will not be able to access theme variables).

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Noticed that my understanding of how Vue implements scoped styles was incorrect. I assumed it worked like Emotion, but for production Vue will generate a CSS file. So we can use scoped styles w/o increasing the JS bundle size.

Note, however, that theme variables defined in the normal Matomo asset pipeline are not available here, so it will be of limited use. For the migration I won't be moving them.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis Could you maybe add some scoped css to the example vue component? If we support it, would be good to have that there I guess.

**Comment by diosmosis** [comment]
@sgiehl good idea, added it :+1:

**Comment by peterhashair** [comment]
I think this is good to merge.

**Review by peterhashair — APPROVED** [review]
I guess that was me doing that way the other day.

**Pull request merged**
