### PR TITLE
Javascript to JavaScript

### PR DESCRIPTION
**Pull request by lipis**
As it happened here: https://github.com/piwik/developer-documentation/pull/148

### CODE REVIEW

**Comment by lipis** [comment]
There are plenty of cases that it's used as `javascript` in some comments as well.. but that's quite more challenging to detect without ruining everything :D

**Comment by lipis** [comment]
Not sure about the tests :/ Checked again if I touched anything else than all the `Javascript` entries.. but it seems nothing else was changed..

**Comment by sgiehl** [comment]
Thanks for your PR. Unfortunately we can't merge this PR for various reasons. 

- You've changed many translations files, but our translations are managed using transifex. So all changes would be overwritten with the next sync
- composer.lock shouldn't be changed manually
- Also you've changed some files of third party libs that are included in the tests. We should leave those files untouched

**Comment by lipis** [comment]
Just be more specific.. I don't need all the reasons.. [@mattab said exclude `libs/`](https://github.com/piwik/developer-documentation/pull/148#issuecomment-249392822) and that's what I did..

Should I ignore all the `lang` folder.. maybe leaving the `en.json`? Which one is your master file?

**Comment by sgiehl** [comment]
All `en.json` files are master files. Those can be changed the other ones shouldn't.

**Comment by lipis** [comment]
and which folders I should exclude from the `test` folder?

**Comment by sgiehl** [comment]
`tests/javascript/assets`
`tests/javascript/frameworks`
`tests/lib`

**Comment by mattab** [comment]
@lipis would be great if you could exclude ` tests/javascript/frameworks/` and `tests/libs` from the changes (as better not to update third party libs to not affect git history). 

The other changes in non-english translation files, I wouldn't mind merging anyway, as they will just get overwritten later and it does not matter. Maybe we could even separately do a mass replace of `javascript` [in Transifex](https://www.transifex.com/projects/p/piwik/) @sgiehl  ?

Thanks for the PR!

**Comment by sgiehl** [comment]
mass replacement isn't possible. If we change all occurrences of 'Javascript' in all `en.json`, all those strings will be invalidated on transifex and someone needs to retranslate them. If we don't want to loose those translations as it's a minor change, guess I would need to go through all those translations on transifex and retranslate them, which is quite time consuming (but wouldn't be the first time)

**Comment by mattab** [comment]
As there were only 2 strings in english changed, I would say it's fine to invalidate those two translations across all languages.

**Comment by lipis** [comment]
Or upload the sources as well after downloading them and maybe changing them again :)

**Comment by sgiehl** [comment]
That would be the same effort I guess and would have that risk that translations would be overwritten if someone is translating something between download and upload.

**Comment by lipis** [comment]
Updated!

**Comment by mattab** [comment]
If the tests will pass LGTM

**Pull request closed without merging**
