### PR TITLE
Propagate token auth in ajax requests for widgetized reports AND enable_framed_pages = 1.

### PR DESCRIPTION
**Pull request by diosmosis**

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis  could you describe (or link) the issue that should be fixed by your changes here?

**Comment by diosmosis** [comment]
@sgiehl There isn't one, it was from an innocraft support request. This makes embedding matomo in an iframe work w/ enable_framed_pages = 1 (so an iframe that links directly to `?module=CoreHome&action=index`,

**Comment by sgiehl** [comment]
embedding the whole sites works with this branch. But I actually didn't see any obvious problems when embedding `index.php` in an iframe on 3.x-dev branch. Is there anything specific that didn't work before? Don't wont to waste time by clicking though the whole functions

**Comment by diosmosis** [comment]
@sgiehl did you try logged out w/ a token_auth in the URL?

**Comment by sgiehl** [comment]
Ah, guess I was still logged in. Will test that again tomorrow.

**Review by sgiehl — APPROVED** [review]
tested again. works as expected :+1:

**Pull request merged**
