### PR TITLE
Game of Containers: Step 2 - Application encapsulation

### PR DESCRIPTION
**Pull request by diosmosis**
Work in progress, more to come later...

Winter is coming.

### CODE REVIEW

**Comment by mnapoli** [comment]
Can this PR be closed?

**Comment by diosmosis** [comment]
No, I've still got work to do on it, but I've moved it to the 3.0 milestone. If you think it's not needed, though, let me know.

**Comment by mnapoli** [comment]
Ah ok sorry I thought it was in review and I thought it was something already implemented in other PRs but I'm mistaken ;)

**Comment by tsteur** [comment]
closing this issue for now. We may continue on this change for Piwik 3 but we'll need to make the changes based on 3.x-dev branch when needed

**Pull request closed without merging**
