### PR TITLE
Fix system tests

### PR DESCRIPTION
**Pull request by tsteur**
I'm issuing a PR as I know that the date changes are on purpose because of eg #8640 but would be nice to have it confirmed that this format is correct. 

There are also some changes in Pivot tests which is I think related to having the second sort column now but not really sure if I understand the changes. Here I need to invest a bit of more time

### CODE REVIEW

**Comment by tsteur** [comment]
Actually, the pivot tests that change the sorting are correct and need to be merged. I compared them with the ones in master and after merging this one they will be the same as in master. Somehow the expected files that change the sorting are wrong in `3.0` branch and will be fixed again by this PR.

@sgiehl @mattab can you confirm the date changes are okay?

**Comment by tsteur** [comment]
I will merge to have green tests. We can still change it later... @sgiehl @mattab

**Comment by sgiehl** [comment]
I had already updated most of the test files to use the new date formats. It now looks like you have changed it to the old format again. If the tests are running now, maybe there is something wrong with the date formats. I can have a look later...

**Comment by tsteur** [comment]
Actually it looks like I have to change it back again: https://travis-ci.org/piwik/piwik/jobs/76452599#L705 so you're right and all is good. I'm not sure what is happening here. Maybe the command to sync processed tests is going wild or so

**Pull request merged**
