### PR TITLE
Add premium plugin menu items to professional services [4.x]

### PR DESCRIPTION
**Pull request by caddoo**
### Description:

This is an addition to the professional services plugin that will show premium plugins in the reporting menu with an empty widget if:

- That plugin is not activated
- Ads for professional services are available.

The content / title of the widgets is being worked on in a seperate PR.

In this PR I have force disabled showing the menu items intentionally so we can merge this without impact, there are unit test s for the logic around whether to show the item or not.

Once approved / merged, the follow up for the promotional page can be added.

Screenshot when the logic is used without being fixed as false.
image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@caddoo Please avoid creating PRs for 4.x-dev unless features are meant to go into a 4.x release ONLY. 
5.x-dev is the default branch on purpose. Any development should be done for that branch and if needed we can backport the changes to 4.x-dev afterwards.

**Comment by caddoo** [comment]
> @caddoo Please avoid creating PRs for 4.x-dev unless features are meant to go into a 4.x release ONLY.
> 5.x-dev is the default branch on purpose. Any development should be done for that branch and if needed we can backport the changes to 4.x-dev afterwards.

I went for 4.x-dev first, due to us wanting to push it to that version first. Is there a reason it should be the other way?

**Comment by bx80** [comment]
Always writing PRs for 5.x first ensures that nothing goes into 4.x that doesn't already exist in 5.x (so we don't unintentionally drop features) and that the technical design of the PR is build around 5.x capabilities first, rather than potentially writing for 4.x deprecated methods and then having a different solution for 5.x which increases review work and bug potential.

I've reviewed this change, it works well and I can't see any issues, if you want to provide a 5.x version then I can review that too and get them both merged.

**Comment by michalkleiner** [comment]
With my work being dependent on this, should I create a PR on top of this or wait until a 5.x version exists, have my part tested and reviewed for 5.x first, and then backport?

**Comment by bx80** [comment]
@michalkleiner If @caddoo can provide a 5.x version of this PR soon then it's probably easiest to create your 5.x version based on 5.x-dev after it's merged.

**Review by bx80 — APPROVED** [review]
This looks good to me, the relevant tests are all passing and the concept has already been reviewed approved in the 5.x PR :+1:

**Pull request merged**
