### PR TITLE
New design for the updater

### LINKED ISSUE #7450: New design for Updater screen
The goal of this issue is to refresh the design of the Piwik updater screens.

Here is an example of the new design for the "Piwik updated" screen:

piwik-update

We should also use this same design for the other Update screens to be consistent with this, ie.
 * Welcome: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterCode_newVersion.png
 * Auto update progress: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterCode_httpUpdateSuccess.png
 * HTTPs Upgrade failed: https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/CoreUpdaterCode_httpsUpdateFail.png
 * DB Upgrade required: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterDb_main.png
 * Piwik upgraded (screenshot above)

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7450 (redesign of the updater).

This PR is based on #7481 (Bootstrap grid system). Since the idea of including Bootstrap as a whole doesn't seem to go well (#7390) this redesign wasn't easy and doesn't look as good as it could (see screenshots below). To avoid struggling too much I have copy-pasted some standard Bootstrap classes (e.g. notifications, base button classes, etc..) as I needed. Still far from perfect as it doesn't work everywhere…

Below are screenshots of the current screens. I will keep them up to date if the pull request is updated.
### A new version is available

Current:

New:

capture d ecran 2015-03-30 a 16 57 08
### HTTPS download fail

Current:

New:

capture d ecran 2015-03-30 a 16 57 18
### HTTP download fail

capture d ecran 2015-03-30 a 16 57 29
### Update success

Current:

New:

capture d ecran 2015-03-30 a 16 57 48
### DB update

Current:

New:

screenshot1
### DB update error

capture d ecran 2015-04-02 a 15 53 47
### DB update success

Current:

New:

capture d ecran 2015-04-07 a 17 35 52
### Error page

Current:

New:

capture d ecran 2015-04-02 a 15 54 40

The stack trace is only displayed here because it's dev environment, don't pay attention to it.

### CODE REVIEW

**Comment by mnapoli** [comment]
I have pushed a new update regarding:

- **db updater**
- **exception pages**

Exception pages use the same "simple layout" so I applied the same redesign so that it's consistent. I have updated the screenshots in the issue description above, please have a look at them.

**Comment by mattab** [comment]
Feedback
 * DB update success: remove grey box around donation and make text look like other text in the Update screens
 * Otherwise looks good to me! :+1:

**Comment by mnapoli** [comment]
Thanks, I have tweaked the "DB update success" screen to remove the box display for the donation. Not perfect but better than before (the donation part is in a Twig template + its own CSS that is included in other parts of Piwik).

Screenshot updated.

**Comment by mnapoli** [comment]
By the way I forgot to remove the tags but this change is ready for review and merge.

**Comment by mnapoli** [comment]
Note: updated the PR to add support for custom logos (whitelabel) in the updater.

**Comment by mnapoli** [comment]
I've rebased on master now that the Bootstrap branch has been merged and that I updated the screenshots.

The UI tests now show the redesigned screens.

**Comment by mattab** [comment]
> The UI tests now show the redesigned screens.

it's very cool to be able to visualise the changes in this way... and it looks very good to me! :+1: 

(we didn't include icons from the mockup and we will decide how to handle icons in general in #7618)

**Pull request merged**
