### PR TITLE
Show missing datetimes in visitor profile (fixes #7522)

### LINKED ISSUE #7522: Visitor profile, visits loaded on click are missing the datetime
The goal of this issue is that in a Visitor Profile, when clicking on "Load more visits" the visits loaded should display the date time in the visit header bar.

(should be quick fix, so adding to 2.12.1)

[URL to reproduce](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=2015-03-22&period=week&idSite=7&segment=visitCount%3E%3D10#/module=Live&action=indexVisitorLog&date=2015-03-22&period=week&idSite=7&segment=visitCount%3E=10&popover=visitorProfile$3A60c547fab167a4de)

See missing visits:
visitor profile visits loaded on click are missing the datetime

### PR DESCRIPTION
**Pull request by sgiehl**
Simple fix for #7522

### CODE REVIEW

**Comment by mattab** [comment]
Thanks for PR @sgiehl - maybe a better fix would be to leave the private and enrich the visits in the API directly? this would improve the API itself for all users

**Comment by sgiehl** [comment]
Thougt about that, too. But the API and the visitor profile are currently using different date formats. Not sure why the profile has it own format defined.

**Comment by mattab** [comment]
:+1:

**Comment by fvdm** [comment]
Is this the change that's causing the long dates in the visitor log and mobile app recently?
If so, I kindly ask to revert this or find another solution. On desktop the dates don't display the time part and in the mobile app the date is using too much space causing the icons to drop to the second line.

schermafbeelding 2015-04-01 om 11 48 05

bestand 01-04-15 12 01 09

**Comment by sgiehl** [comment]
Yep it is. Reverting is imho not an option. It was not good to have a custom date format in visitor log only. We should maybe introduce a new date/time format or change the one used right now to maybe use a short dayname. But we would need to do that "piwik wide" and in all translations aswell, as the date formats are managed there....

**Pull request merged**
