### PR TITLE
updated css for no report

### PR DESCRIPTION
**Pull request by saleemkce**
Fix for issue : https://github.com/piwik/piwik/issues/7092

I create a new branch for this because the I got messy code merges from others' commits.

### CODE REVIEW

**Comment by tsteur** [comment]
Hey @saleemkce sorry to make it complicated but I think we still need this 

```
.widget .pk-emptyDataTable {
    padding-left: 15px;
}
```

To fix the left padding for the widgets in the dashboard. It'll be on the same line as the widget headline then. Once this is there I will merge! Sorry again

**Comment by saleemkce** [comment]
@tsteur Hi Thomas,

Is this okay that I replace the existing code block from,

```
.pk-emptyDataTable {
  padding-top: 20px;
  padding-bottom: 10px;
  padding-left: 11px;
}
```

to

```
.pk-emptyDataTable {
  padding-top: 20px;
  padding-bottom: 10px;
}

.widget .pk-emptyDataTable {
    padding-left: 15px;
}
```

**Comment by saleemkce** [comment]
@mattab @tsteur 

So, now I have a big problem. You could help me sort it out.

I just updated the new css I commented above and used "git status" command I see the following state

````
$ git status
On branch bugfix-css-alignment-report-updated
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    misc/log-analytics
        modified:   plugins/CoreHome/stylesheets/dataTable/_dataTable.less

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        misc/user/.htaccess

no changes added to commit (use "git add" and/or "git commit -a")
````

 Hence if I add **"plugins/CoreHome/stylesheets/dataTable/_dataTable.less"**, commit and push to remote repo, I see that I am updated with **others' commits and my old image graph commit** in the page. So, totally 6 changed files. So I have reverted back to https://github.com/saleemkce/piwik/commit/bee5df375d3cae0adb648b4b93002e3052e2cb45 which is my previous correct committed state.

Specifically, I assume 

```
On branch bugfix-css-alignment-report-updated
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
```
   this is where I am updated with others/my previous commits.

 What should I do now to commit only **"plugins/CoreHome/stylesheets/dataTable/_dataTable.less"** file into my bugfix branch. I am a bit new to git but a longtime SVN user. I have even tried some possible options (got ideas from StackOverfow which didn't help) but don't know how to proceed correctly. I strongly hope you could help me sort out this trivial issue.

**Comment by tsteur** [comment]
> No problem. Is this okay that I replace the existing code block from,

Yes, it is a problem. We still need the 11px for the normal empty data table. The 15px should be only applied if a widget is viewed within the dashboard. Should look like this:

```
.pk-emptyDataTable {
  padding-top: 20px;
  padding-bottom: 10px;
  padding-left: 11px;
}

.widget .pk-emptyDataTable {
  padding-left: 15px;
}
```

Re your other problem: Does it maybe help to do `git add plugins/CoreHome/stylesheets/dataTable/_dataTable.less` followed by `git commit` and `git push`? When doing the push you might want to specify the remote and branch like `git push origin bugfix-css-alignment-report-updated`. Maybe you also want to do a `git reset HEAD misc/log-analytics && git checkout misc/log-analytics` at some point. reset HEAD should not be needed though.

**Comment by saleemkce** [comment]
Okay, great I will update CSS as you mentioned.

Yes, before I did this **git add plugins/CoreHome/stylesheets/dataTable/_dataTable.less**,  I switched to master branch and did "git pull upstream master". Then I added and committed this ".less" file from my bugfix branch. Then, I did normal merge like "git merge master". Now, after all these steps, I do **"git push"** but I find others files to be present in my commit too. I couldn't understand where the problem rises. Moreover, I follow steps here http://developer.piwik.org/guides/contributing-to-piwik-core

Anything wrong here?

**Comment by tsteur** [comment]
You wrote you switched to master branch, probably you need to checkout your branch again `git checkout bugfix-css-alignment-report-updated`, make the changes and `git add && git commit...`, maybe followed by a `git rebase master` but probably not needed. 

BTW: You can as well just edit the file directly on Github:
https://github.com/saleemkce/piwik/blob/bugfix-css-alignment-report-updated/plugins/CoreHome/stylesheets/dataTable/_dataTable.less just press the edit button, make the changes, define a commit message and save.

**Comment by saleemkce** [comment]
okay thanks, I will try it out.

**Comment by tsteur** [comment]
Thx!

**Pull request merged**
