### PR TITLE
JavaScript SDK: add support to send tracking requests to multiple Piwik servers and/or store in one or  multiple websites ID

### PR DESCRIPTION
**Pull request by mattab**
Fixes https://github.com/piwik/piwik/issues/9525

### CODE REVIEW

**Comment by mattab** [comment]
@tsteur LGTM :+1: 

Todo: 

* [ ] Add tests 
* [ ] Replace [this documentation](http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers) with new, better way of using multiple trackers

**Comment by tsteur** [comment]
I have added tests and also added to `getAsyncTracker` a new method to get the actually created tracking instance that was created asynchronously. This could eg allow to create multiple tracker instances asynchronously, and once created, send different tracking requests to different Piwik instances to actually solve #9525 

If someone registers the same Piwik instance (same URL and same idSite) multiple times always the first tracker instance is returned so far. I don't think this is a big use case

**Comment by tsteur** [comment]
We should update documentation once new release is released and leave old documentation there for Piwik pre 2.16

**Comment by mattab** [comment]
> We should update documentation once new release is released and leave old documentation there for Piwik pre 2.16

Ok, created #10174

**Comment by tassoman** [comment]
Thank you so muchly :wink:

**Pull request merged**
