### PR TITLE
allow some tests that use exception backtraces to pass if line number changes

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

This change makes it possible for these tests to pass after related files have been prefixed.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by michalkleiner — DISMISSED** [review]
The change itself looks ok, however I was also expecting a test addition that would use the change e.g. test of the same output with different line numbers (if that's the main goal) at least for one of the test cases.

**Comment by diosmosis** [comment]
@michalkleiner I don't know what you're referring to, the point of this PR was to change the test to work even if the line numbers of the exceptions thrown by the tests change (because code or whitespace was added or removed from one of the files in the backtrace).

**Comment by michalkleiner** [comment]
> the point of this PR was to change the test to work even if the line numbers of the exceptions thrown by the tests change

Yes, we changed the evaluation, but we didn't add additional test inputs to validate it here.

**Comment by diosmosis** [comment]
@michalkleiner validate what?

**Comment by michalkleiner** [comment]
@diosmosis that the updated tests will work with inputs that have different line numbers to those we already have in the code base.

**Comment by michalkleiner** [comment]
Before this change, we had 'stacktrace1' input and a test testing for 'stacktrace1' exact match.
With this change we have a test testing for 'stacktrace%d', but we didn't add new passing 'stacktrace2' case and not passing 'stacktraceY' case.

**Comment by diosmosis** [comment]
@michalkleiner so you want me to test that phpunit's `assertStringMatchesFormat(%d, $number)` passes in the same way that `assertEquals($number, $number)`? I'm sorry, but I won't be doing that. And you're misunderstanding what those tests are actually there to test. The whole point of this PR is that the line number (provided by PHP **not** Matomo) is not worth including in the assertion. As in the whole point of this PR is to test that the line number in those messages is just a number and **not** a specific number.

**Comment by michalkleiner** [comment]
> The whole point of this PR is that the line number (provided by PHP not Matomo) is not worth including in the assertion. As in the whole point of this PR is to test that the line number in those messages is just a number and not a specific number.

I get that. What I was asking was to add a test that will confirm the new behaviour with two different inputs.

I removed my approval for now and will let someone else have a look, it seems we won't reach a shared view here.

**Comment by diosmosis** [comment]
> What I was asking was to add a test that will confirm the new behaviour with two different inputs.

You want me to test the new assertion behavior, which is just testing PHPUnit's assertion logic with a value that is not provided by the application. It is pointless work in every possible way.

**Review by sgiehl — APPROVED** [review]
I agree with @diosmosis here. The changes are making the test assertions a bit more "flexible". When testing exception traces there is not much sense in checking if the line number is the same. Doing that only requires to update the tests every time one of the files included in the trace is updated. We had to do that a couple of times in the past, which actually was annoying. So the changes here are an improvement.

**Pull request merged**
