### PR TITLE
Move old brand icons to piwik icons

### PR DESCRIPTION
**Pull request by Findus23**
First step towards #11626 

I'll look into the tests later.

### CODE REVIEW

**Comment by Findus23** [comment]
As ususal we need to change plugins/CustomDimensions.
```diff
diff --git a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
index 9b55fd8..899c81f 100644
--- a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
+++ b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
@@ -65,7 +65,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -183,7 +183,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -299,7 +299,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -447,7 +447,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
@@ -563,7 +563,7 @@
 		<languageCode>fr</languageCode>
 		<language>French</language>
 		<deviceType>Desktop</deviceType>
-		<deviceTypeIcon>plugins/DevicesDetection/images/screens/normal.png</deviceTypeIcon>
+		<deviceTypeIcon>plugins/Morpheus/icons/dist/devices/desktop.png</deviceTypeIcon>
 		<deviceBrand>Unknown</deviceBrand>
 		<deviceModel />
 		<operatingSystem>Windows XP</operatingSystem>
```

**Comment by sgiehl** [comment]
The mentioned diff should already be applied. But guess there might be changes in brand icons.

**Comment by Findus23** [comment]
You are right that was the previous change. Seems like there are no brand icons in the test files.
```bash
$ grep -r "brand"
tests/System/expected/test___API.getReportMetadata_day.xml:             <name>Device brand</name>
tests/System/expected/test___API.getReportMetadata_day.xml:             <dimension>Device brand</dimension>
tests/System/expected/test___API.getSegmentsMetadata.xml:               <name>Device brand</name>
```

**Comment by Findus23** [comment]
Yesterday I have replaced the most important brands with better icons: https://github.com/piwik/piwik-icons/commit/583c1adde78681a279f596ada621a8ec9e7d635f

It was easier than I thought because Wikimedia has many of them (even as svg).

**Comment by sgiehl** [comment]
@Findus23 guess that would be good to merge. Do you have time to rebase and update the expected screenshots and remaining system test files?

**Comment by Findus23** [comment]
@sgiehl I'll finish it as far as I'm able to.

Notes: 
- There seems to be a small font change: italic text is a bit more italic now (e.g. http://builds-artifacts.piwik.org/piwik/piwik/move-old-brand-icons-to-piwik-icons/23045/Dashboard_loaded_token_auth.png)
- MySQL version change in http://builds-artifacts.piwik.org/piwik/piwik/move-old-brand-icons-to-piwik-icons/23045/Theme_home.png

I hope I didn't destroy anything in git lfs with

**Comment by sgiehl** [comment]
Those changes are caused by the [precise image update of travis](https://blog.travis-ci.com/2017-05-04-precise-image-updates). Guess we simply need to update those screenshots as well

**Comment by Findus23** [comment]
Two more things: 
- This pull request also updates some other icons as I have improved the conversion from svg files in the meantime: https://github.com/piwik/piwik-icons/compare/3937b5daef048afb3446fbbeb6cdca5b9f6d6f5f...1b5597760791b2b305e6b9c26ca1a6b8b15ee0e5

- There are four failing system tests left.
> Failed asserting that 568941 matches expected 568880.

I've seen them before. Can I just update the number? I tried to download the system test artifacts but `wget http://builds-artifacts.piwik.org/piwik/piwik/system.23045.tar.bz2` just hangs.

**Comment by sgiehl** [comment]
> Two more things:
>
> This pull request also updates some other icons as I have improved the conversion from svg files in the meantime: piwik/piwik-icons@3937b5d...1b55977

No problem. Simply update those tests as well.

> There are four failing system tests left.
>
> Failed asserting that 568941 matches expected 568880.
> I've seen them before. Can I just update the number? I tried to download the system test artifacts but wget http://builds-artifacts.piwik.org/piwik/piwik/system.23045.tar.bz2 just hangs.

No, the files needs to be updates. That message occurs for non xml files like csv or pdf.
As comparing those files doesn't always work, we compare the size

**Comment by Findus23** [comment]
> No, the files needs to be updates. That message occurs for non xml files like csv or pdf.
As comparing those files doesn't always work, we compare the size

That makes sense. But I can't replace them as the download from builds-artifacts.piwik.org doesn't work and I the still haven't looked into running the tests locally.

Could you commit them? (The branch is called `move-old-brand-icons-to-piwik-icons`)

**Comment by sgiehl** [comment]
I'm able to download the file in the browser. I'll update those files

**Comment by sgiehl** [comment]
Ok. Now all tests seem to run again :+1:

**Comment by sgiehl** [comment]
had another rough look through all changes. Looks good. Will merge now :tada:

**Pull request merged**
