### PR TITLE
Add guide links on tracking code page and no data email

### LINKED ISSUE #15429: Mention guides for Wix, WordPress, SquareSpace, Sharepoint in the "No data" email and in the "Tracking code" page
Following up on #15360

we could also show the useful integration guides in 2 more places:

## Email about the website received no data

Screenshot from 2020-01-22 07-19-38

## Tracking code page in admin

Screenshot from 2020-01-22 07-21-33

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #15429 
Added setup guide links for Wordpress, Squarespace, Wix, SharePoint,  Joomla, Shopify and Google Tag Manager to the 'No data' email and to the tracking code page.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@tsteur @Findus23 Not sure on that one, but do we still need to add `rel="noreferrer noopener"` to new links, or is that meanwhile covered by meta tags or headers?

**Comment by tsteur** [comment]
`noreferrer` we wouldn't need anymore AFAIK. `noopener` is used by default in FF 79 https://bugzilla.mozilla.org/show_bug.cgi?id=1522083 , safari 68 https://webkit.org/blog/8475/release-notes-for-safari-technology-preview-68/  brave: https://github.com/brave/brave-browser/issues/1840  

Here's a detailed list of supported browsers: https://caniuse.com/mdn-html_elements_area_implicit_noopener

Seems maybe opera and android browser doesn't have this fixed yet and maybe still need it for a while? Also samsung browser only seems to have it since recently etc.

**Review by sgiehl — APPROVED** [review]
lgtm

**Comment by craigvc** [comment]
How does this get dealt with by white label plugin - i would like to reference my own guides.

**Comment by bx80** [comment]
Thanks for the question @craigvc, I haven't tested these links specifically with the white label plugin, but my understanding is that any links to matomo.org should be automatically removed. Unfortunately there isn't any capability to add your own links at the moment.

**Pull request merged**
