### PR TITLE
Query generated by Live plugin is too heavy

### LINKED ISSUE #9524: Query generated by Live plugin is too heavy.
The following API call generates a query which will always end up in a PHP timeout.

`index.php?module=API&method=Live.getMostRecentVisitorId&idSite=2&format=JSON&token_auth=TOKEN`

Generates the following query:

    Info: SELECT sub.* FROM (
				
			SELECT
				log_visit.*
			FROM
				piwik_log_visit AS log_visit
			WHERE
				log_visit.idsite in ('2') 
			ORDER BY
				idsite, visit_last_action_time DESC LIMIT 1
			) AS sub
			GROUP BY sub.idvisit
			ORDER BY sub.visit_last_action_time DESC

### PR DESCRIPTION
**Pull request by tsteur**
fixes #9524

Makes the query faster by first looking max 7 days back. If there was no visitor within 7 days (which should be rather rare), then we issue another query and look back all logs. 

Query basically now looks like 

``` sql
            SELECT sub.* FROM (
            SELECT
                log_visit.*
            FROM
                piwik_log_visit AS log_visit
            WHERE
                log_visit.idsite in (1) 
                AND log_visit.visit_last_action_time > '2016-01-10 21:21:32'
            ORDER BY
                idsite, visit_last_action_time DESC LIMIT 1
            ) AS sub
            GROUP BY sub.idvisit
            ORDER BY sub.visit_last_action_time DESC
```

@quba can you check if it is faster?

### CODE REVIEW

**Comment by sgiehl** [comment]
Code LGTM.

**Comment by quba** [comment]
Cool, it should work in most of the cases. I'm not sure about scanning all logs. Would be nice to fallback to some other predefined period, e.g. one year or 2 years, so that it still uses MySQL index. Imagine there are 2 sites - one with only a few visits monthly (idsite=2) and second one which is really big (300M actions/motnly). In this case, this query would be really heavy in case there have been no visits for idsite=2 since last week.

**Comment by tsteur** [comment]
I can issue another PR to fall back to one year, and then all visits.

**Comment by tsteur** [comment]
See https://github.com/piwik/piwik/pull/9547

**Comment by quba** [comment]
:+1:

**Pull request merged**
