### PR TITLE
Assume plugins that do not define a upper bound for Matomo version re…

### LINKED ISSUE #14342: Restrict open-ended require to the major Matomo version it defined
I just noticed that my Matomo instance had the `IPv6Usage` plugin running.

The plugin doesn't officially support Matomo 3, [hasn't been adopted by anyone](https://forum.matomo.org/t/adopt-a-plugin/26869) and [removed from plugins.matomo.org](https://plugins.matomo.org/IPv6Usage) 

```json
    "require": {
        "piwik": ">=2.12.0"
    }
}
```

But as the plugin has an open-ended `require` it hasn't been deactivated by Matomo.

I think Matomo should at least show a warning to superusers as subtle bugs may be caused by them and maybe this way more people would try to adopt popular plugins that aren't maintained anymore.

### PR DESCRIPTION
**Pull request by sgiehl**
…quirement as incompatible with Matomo 4

fixes #14342

### CODE REVIEW

**Comment by diosmosis** [comment]
Should we make a note in the CHANGELOG? And should we note this in the developer documentation?

I wonder if it would be helpful (and even possible) to have an error message displaying the reason for the automatic < 4.0.0-b1? I think some developers may get confused, but I'm not too sure (cc @tsteur).

**Comment by sgiehl** [comment]
Actually I guess we will need to update the marketplace and the developer docs. It seems we currently allow anything semver can parse. See https://developer.matomo.org/guides/distributing-your-plugin
ping @tsteur

**Comment by tsteur** [comment]
@sgiehl I've updated the marketplace for new plugin submissions or updates for existing plugins to require a lower and an upper limit. A developer will get an email with the error message and it will automatically suggest a good require string for that plugin when possible. Could you update the docs on developer site to have upper limits?

**Comment by sgiehl** [comment]
Updated the PR and adjusted the tests. Would be ready for another review

**Review by diosmosis — APPROVED** [review]
Guess the only thing left is the developer docs tweak?

**Comment by tsteur** [comment]
Merged the docs 👍

**Pull request merged**
