### PR TITLE
Fix siteSearchCategory segment

### LINKED ISSUE #16674: SearchCategory segment issue?
see https://github.com/matomo-org/matomo/blob/4.0.0-rc1/plugins/Actions/Columns/SearchCategory.php#L36-L41

it's calling a method that no longer exists. Not sure if this is an issue? 
image

I'm currently going through all changes in the changelog and checking if all code was adjusted to notice possible bugs and not sure if this one is an issue. I suppose it used to configure a segment maybe but is not anymore? Or maybe it is dead code?

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #16674

### Review

* [x] Functional review done
* [x] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] Security review done
* [x] Code review done
* [x] Tests were added if useful/possible
* [x] Reviewed for breaking changes
* [x] Developer changelog updated if needed
* [x] Documentation added if needed
* [x] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
failing UI tests are unrelated

**Comment by diosmosis** [comment]
Not sure if this is related to the original bug, but something I noticed:

the search category report doesn't have segmented visitor log icon:

image

**Comment by sgiehl** [comment]
Might be useful to add that as well... Will do that

**Comment by sgiehl** [comment]
@diosmosis updated the PR

**Pull request merged**
