### PR TITLE
Hide comparisons on no data page

### LINKED ISSUE #20957: No data page might show selected comparisons
## Context
When switching to a page that has no data, previously selected comparisons might still be applied. Those selection will still be shown.

## Expected Behavior
Previously selected comparisons should be hidden

## Current Behavior
image

## Possible Solution
Hide those not needed element

## Steps to Reproduce (for Bugs)
1. Go to a page that has data
2. Select some comparisons (segments and/or dates)
3. Switch to a site that doesn't have tracked data yet

## Your Environment
* Matomo Version: 5.0.0-b4
* PHP Version: 7.2
* Server Operating System: Linux

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #20957 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Is this really the best solution, @sgiehl? I don't have an alternative right at this moment, but it feels non-standard (best word I could come up with).

Would a full page template specifically just for the no-data screen/tabs that wouldn't have any of these components/widgets in it be a better approach, even if it is potentially more work?

**Comment by sgiehl** [comment]
@michalkleiner not sure if that wouldn't be a bit out of scope. In general I think it would make sense to have a simpler layout there. But currently that would mean copying a lot stuff from the dashboard layout to a new simpler layout. I guess to solve that better we would need to restructure the layout. But that could cause other problems if plugins rely on certain layout stuff.

What we could maybe have a some sort of new event that is triggered that can be used to hide the comparison stuff. similar to hiding the date selector. But not sure if that would be much of an improvement.

**Comment by michalkleiner** [comment]
All good, thanks for the explanation.
An event might be a bit better from the perspective that anything else needing hiding from the no-data screen could also use it, but it's not a dealbreaker for me.

**Comment by sgiehl** [comment]
@michalkleiner Had another thought on it and changed that a bit so it contains some more reusable parts...

**Comment by michalkleiner** [comment]
Touching parts I even didn't know existed (so I learned something) and I think the broadcast property could potentially be handy later on as well.

This looks better from my perspective than the previous show/hide approach 👍

**Review by michalkleiner — APPROVED** [review]

**Pull request merged**
