### PR TITLE
Fix different hints where to put tracking code on website

### LINKED ISSUE #11007: different hints where to put tracking code on website
different hints where to put tracking code on website:
in setup <->"no data yet" message

please see attachments

2016-12-14_15h41_42

2016-12-14_15h40_15

### PR DESCRIPTION
**Pull request by tsteur**
fixes #11007 

I'm not quite sure what was meant before with "footer" file. Renamed it to "head tag"

### CODE REVIEW

**Comment by tsteur** [comment]
What does "header file" mean?

**Comment by mattab** [comment]
it refers to most CMS / websites implementing the practise of having a header file and a footer file for easy modification across sites. I think the "footer file" is more famous/well-known but most people would understand header file as well, right?

**Comment by tsteur** [comment]
I don't think most people would understand what is meant by it. Maybe something would be better like "added to the &lgt;head&gt;" tag which is often defined in a "header.php", "header.tpl" or "header.twig" template file.

**Comment by mattab** [comment]
@tsteur Good point, done in https://github.com/piwik/piwik/commit/6442f147ad3b281d799448a063a5e388b758dbfa

**Pull request merged**
