### PR TITLE
add isFullRequest parameter to JS tracker queueRequest() …

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

This PR adds the ability to use `queueRequest()` with a full tracker request URL (ie, the result of `getRequest()`). The primary use case is when there is asynchronous code that is used to determine the contents of the request, and we want to make sure the correct parameters are used when the async code finishes. For example:

```
function myPluginTrackSomething(..., customizeParameter) {
    var tracker = getAsyncTracker(); // only one tracker just for the example
    var url = tracker.getRequest(...);
    customizeParameter(..., function (newParam) {
        tracker.queueRequest(url + '&param=' + encodeURIComponent(newParam), true);
    });
}
```

Prevents the following type of error:

1. user loads a SPA. myPluginTrackSomething() is called, which initiates the customizer callback
2. user changes the page, track pageview is called
3. customizer callback finishes and queueRequest is called. But since we use getRequest() beforehand, the URL uses the correct action name/URL, etc.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis would you solve the conflicts?

**Comment by diosmosis** [comment]
@sgiehl updated

**Comment by diosmosis** [comment]
added a test as well

**Review by sgiehl — CHANGES_REQUESTED** [review]
The javascript tests are failing and might need to be updated. Otherwise this imho looks good.
Might be possible though that our documentation needs an update.

**Review by peterhashair — APPROVED** [review]
JS tests passed, not too sure that Redis tests are related, seems random.

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)

**Pull request merged**
