### PR TITLE
Add reusable 'Click "something"' translatable text

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Repeats too many times on the no-data screens not to have it pulled out and reused.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sgiehl — APPROVED** [review]
Guess you will add some usages of that n another PR, so should be good to merge.
We might need to backport this to 4.x-dev with the other translations than aswell maybe.

**Comment by michalkleiner** [comment]
Yep, it will get used in the subsequent PR, but didn't want to clutter it too much and this felt like a good isolated piece.

The only question is whether CoreHome or General. I guess it can go into both and there are similar keys in both already 🤷.

**Comment by sgiehl** [comment]
> The only question is whether CoreHome or General. I guess it can go into both and there are similar keys in both already 🤷.

If that's something to be used across all code and maybe even in plugins it would logically make more sense to have it in `General`, but in the end it won't matter that much I guess.

**Comment by michalkleiner** [comment]
TagManager where I need it now already pulls strings from General and CoreHome which is what brought me to the question. Yeah, I'll move it to General. Very slight preference for that now when I look at it.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
