### PR TITLE
Show report generated time when date range includes today

### LINKED ISSUE #14977: Show more clearly the freshness of reports when looking at Today or This week
When viewing a report where the date includes Today, and when clicking on the help icon next to a report title, one can sometimes see the "Generated X hours Y min ago." information. This gives the freshness of the report:

Screenshot from 2019-10-07 23-19-33

It's a common frustration point to not know when were the reports processed, and not knowing whether the current report may be inaccurate because it was processed hours ago. "When was this data processed?" people ask themselves.

How could we make the situation more clear?
* could we also display the freshness info with a subtle time icon: "(icon) 5 hours ago" or "(icon) 34 min ago", on the top right (Selector bar), when date includes today?
* show this freshness info in the help infobox on all report titles. Currently the freshness is not visible under Evolution graphs and likely other reports too. We expect this info to show on all pre-processed reports (except a few specific which are not actual aggregated reports like all real-time reports).
* ...

### PR DESCRIPTION
**Pull request by flamisz**
### Description:

fixes #14977 

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by flamisz** [comment]
Note:
I wanted to show the generated time for the evolution graphs as well. I found one way, but then it modified the API results' JSON (added the generated time as metadata). I tried a couple of ways to solve it (see the commit history), but couldn't find any "clean" way I liked.
I recommend merge it as it is (of course if the PR is ok) and if we want, we can create a new issue for showing the generated time for evolution graphs. I spent too much time on this for now.

**Comment by flamisz** [comment]
Hi @mattab and @tsteur can you please check this and my previous ⬆️ comment? Should I spend more time on or we'd like to merge it as it is for now?

**Comment by mattab** [comment]
@flamisz 
> I recommend merge it as it is (of course if the PR is ok) and if we want, we can create a new issue for showing the generated time for evolution graphs.

Absolutely, sounds good this way :+1: 
 
Can you wait after we released 4.3.0 (so it can be tested in 4.4.0 beta)  to merge?

**Review by diosmosis — APPROVED** [review]
code looks good to me and change works locally

**Pull request merged**
