### PR TITLE
VisitorMap doesnt show anything when segment parameter is URL-encoded

### LINKED ISSUE #8813: VisitorMap doesn't show anything when segment parameter is URL-encoded
When using an encoded parameter for the segment, the VisitorMap widget does not show the visited countries. Anyway the number of total visits is still shown correctly.
Once the encoding is removed, the visited countries are marked correctly again.
piwik_visitormap_param_encoded_error
piwik_visitormap_param_not_encoded

Maybe the widget is not resolving the encoding and only matches the segment 1:1 with the database and cannot find a matchingsegment (browser triggered archiving is disabled in our case)

Segment definition in DB:
pageUrl=@web.mysite.com/en-us
Segment parameter encoded:
pageUrl%3D%40web.mysite.com%2Fen-us
Segment parameter not encoded:
pageUrl=@web.mysite.com/en-us

Using Piwik 2.14.3

### PR DESCRIPTION
**Pull request by tsteur**
fixes #8813 

took me a long time to reproduce. Used segment `&segment=pageTitle%3D%3DAbout%2520ExampleCode%3BcountryCode%3D%3Dde`

### CODE REVIEW

**Comment by mattab** [comment]
Good find!

**Comment by sgiehl** [comment]
That change causes some UI tests to fail:
http://builds-artifacts.piwik.org/piwik/piwik/master/17512/

The visitor maps are broken. On my local machine I got a js error.

`Uncaught TypeError: Cannot read property 'length' of undefined`

I'll try to investigate...

**Comment by sgiehl** [comment]
Guess I found the problem. If no segment is set, the segment for country map config is set to `false`. 

Before this change  `$params['segment']` was only set if there is a segment in the request. Now it is always set - and set to `false` if there is no segment in the request. Guess we need to check for a segment in the request before setting `$params['segment']`

**Comment by tsteur** [comment]
Thx for that, you're right. Fixed it in https://github.com/piwik/piwik/commit/e62c61cbea52320029052ca42b5ae0d96f9a0e36

**Pull request merged**
