### PR TITLE
Only track a ping if window actually has the focus

### PR DESCRIPTION
**Pull request by tsteur**
refs #9504 

I'm using `document.hasFocus()` to detect whether window is active to prevent sending any ping requests when it was opened via right click => open in new window and when the tab was actually never opened.

I did not use mouse events etc as suggested somewhere as there is not always a mouse present like on phones etc. It should be pretty much the best way to detect it and is supported by many browsers (including IE6 see https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus ).

Downside: It did not work so far for an iframe. I tested it within an iframe and the page within the iframe always reported `document.hasFocus() = false` (unless there was actually a click within the iframe, scrolling did not activate the iframe). Maybe someone else has an idea too?

### CODE REVIEW

**Comment by tsteur** [comment]
Update: I changed behaviour slightly. As we notice via an event whether the window gets or loses focus I only detect whether the window had the focus at least once to cover the case when a user opens it with a right click in a new window. This is easier and works better with iframes. 

If Piwik is used within an iframe we always presume it had focus at least once. This is the current behaviour as well see https://github.com/piwik/piwik/issues/9543 so we do not break anything until this problem is actually solved (which we maybe cannot solve).

**Comment by hpvd** [comment]
should't this be fixed without any additional effort with
> before each ping one can simply check if mouse position in browser window is still the same than before last ping - if so no new ping is send.
https://github.com/piwik/piwik/issues/9504#issuecomment-171883174
?

**Comment by tsteur** [comment]
There's not always a mouse, eg on phones. Not sure how to handle it there. There might be an equivalent but not really. Also if someone eg watches a video one might be still active but doesn't use the mouse.

**Comment by hpvd** [comment]
of course you are right regarding "no mice devices".
Maybe one need to detect any kind of "movement" generated by user:
mice and scrolling - and any kind of other action/event triggered on the page

for video watching it's more difficult...one need to think some times on it...

**Comment by mattab** [comment]
Very welcome improvement to the accuracy of measuring the Time on website using the heartbeat timer feature :+1:

**Comment by hpvd** [comment]
good to hear!
Please release a new beta and put it directly to demo where we had reproduced some unplausible values in visiting time.
=> so we can easily see within same environment if it helps and how many cases we catch with this

**Comment by mattab** [comment]
Done! thanks for your tests @hpvd

**Comment by hpvd** [comment]
thank you for new b4!
info in https://demo.piwik.org/ shows still b1
image

**Comment by hpvd** [comment]
since this is marked as "needs review" just a documentation of the actual status
2016-01-26_18h08_01

**Comment by tsteur** [comment]
thx for that!

**Comment by hpvd** [comment]
since there seem to be some changes since b6, it would be good to release b7 and directly install it in https://demo.piwik.org/ 
=> so we can easily see the impact of latest changes on average time on page...

**Comment by hpvd** [comment]
as also written on other places
https://github.com/piwik/piwik/issues/9504#issuecomment-174556731
the question is: which magnitude of value is plausible after enabling heartbeat?

maybe a bit longer because last page visited adds additional time?
or a little shorter beacuse now also onpage visits have a time on page?
or beacuase of both: nearly the same? e.g. +-20% ?

**Pull request merged**
