### PR TITLE
Improve translations

### PR DESCRIPTION
**Pull request by gboddin**
Previous error message seems to cause confusion amongst users when running in archiving mode.

Suggesting some clarification

### CODE REVIEW

**Comment by tsteur** [comment]
Ideally we would check whether we have actually processed it or whether is really no data which might be possible but it is complicated. See https://github.com/piwik/piwik/issues/404 . 

@mattab what do you think about this message meanwhile?

**Comment by tsteur** [comment]
Thx for the PR btw. I just realized it's only a translation string which has to be changed via https://www.transifex.com/piwik/piwik/ . We cannot change translations via PRs unfortunately. I'll close it for now but feel free to sign up on transifex via your github account and to suggest the change there

**Comment by sgiehl** [comment]
@tsteur Thats not correct. English translations needs to be updated in the code, as transifex pulls them from github. So this change might be valid.

**Comment by tsteur** [comment]
True, so it would invalidate all the others to make sure they get translated as well. Thx!

**Comment by mattab** [comment]
Hi @gboddin 
Transitions data is not processed or archived, but it is generated in real time. Therefore message should be correct.

**Comment by gboddin** [comment]
@mattlab

Not sure I get your point, but I'll explain the situtation that led to this PR : 

We're running a pretty medium instance of Piwik (~7M hits per months), and as you know an archiving can take some times.

When a (offline-archived) segment is edited, its data can be invalidated for some time (till the next archive process), which then display the mentionned message.

That's why we got one of our user asking if it could mention that data could actually come up ... soonish instead of saying there's no data at all.

**Pull request closed without merging**
