### PR TITLE
8075 labels in graph overlaps

### PR DESCRIPTION
**Pull request by sebastianpiskorski**
Added code for overlapping labels removal
Fixed UI test setViewportSize() function

Solution for Issue piwik/piwik#8075

### CODE REVIEW

**Comment by tsteur** [comment]
Can you append a screenshot how the added UI test `label_ticks_cutout ` looks after that change?

**Comment by tsteur** [comment]
I can't really say much do that as I'm not really into jqplot etc. From my side it would be ok to merge if it works and if it is well tested from your side. Have you also tested it in different browsers and resolutions?

**Comment by sebastianpiskorski** [comment]
@tsteur Here are screenshots. Before:
evolutiongraph_annotations_none

and after:
evolutiongraph_ticks_cutout

**Comment by tsteur** [comment]
How did it look before when the widget was that small?

**Comment by sebastianpiskorski** [comment]
@tsteur Here you have:

evolutiongraph_label_ticks_cutout

**Comment by tsteur** [comment]
Cool, that looks good :) Which browsers have you tested?

**Comment by sebastianpiskorski** [comment]
@tsteur 
Firefox 38.05
Chrome 43.0
Safari 8.0

**Comment by tsteur** [comment]
Do you mind testing in IE before merging if possible? IE 8 and IE10 or so would be great otherwise just IE9 or IE10 should do for now. Let me know if it is possible

**Comment by sebastianpiskorski** [comment]
@tsteur I work on mac and I don't have access to IE currently. Either in office nor in home. Maybe if I could install some VM, but I can't say when I will be able to do it.

**Comment by tsteur** [comment]
You might be interested in http://dev.modern.ie/tools/vms/ :)

**Comment by sebastianpiskorski** [comment]
@tsteur What do you think about this solution http://www.digitaltrends.com/computing/how-to-install-and-run-internet-explorer-on-mac-os-x-with-oracle-vm-virtualbox/ ?

**Comment by tsteur** [comment]
I use VirtualBox on MacOSX. Works fine :)

**Comment by sebastianpiskorski** [comment]
@tsteur Here are screenshots from IE 9,10,11on Win7, Oracle VirtualBox (ietestdrive)
screen shot 2015-06-18 at 7 03 28 pm
screen shot 2015-06-18 at 7 11 36 pm
screen shot 2015-06-18 at 7 26 27 pm

**Comment by tsteur** [comment]
Cheers!

**Pull request merged**
