### PR TITLE
Fixed #6398 - probably fixed/worked-around by sorting

### LINKED ISSUE #6398: Tracker: Serialization failure: 1213 Deadlock found when trying to get lock
so i use the tracking api. 

my code separates actions into groups of 500-800 (depending on session length)

each group is put into a queue, and threads send these groups to piwik to be tracked.

currently 15 threads send these groups simultaneously.

why i do this:
in my particular setup, i did some testing and around 500 was the sweet spot for piwik's ability to handle bulk tracks (less didn't decrease the time much, and more started increasing the time significantly)   

i also noticed that the times it takes to track these hits doesn't seem to increase much if you have multiple bulk requests at the same time.

the problem:
i recently upgraded from 2.2.2 to 2.7.0, and now when i run the same importer, i start getting error 500s from the tracker requests.

looking at the apache error logs, there seems to be deadlock issues:

[Tue Oct 07 13:00:01 2014] [error] [client 130.14.24.60] Error in Piwik (tracker): Error query: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction \t\t\t\t\t\t\t\tIn query: UPDATE piwikdev_log_visit                     SET idvisitor = ?, visit_total_time = ?, visit_last_action_time = ?, visit_exit_idaction_url = ?,  visit_total_actions = visit_total_actions + 1 , custom_var_k1 = ?, custom_var_v1 = ?                     WHERE idsite = ?                         AND idvisit = ? \t\t\t\t\t\t\t\tParameters: array

### PR DESCRIPTION
**Pull request by medic123de**
please review.
small-scale test has finished without error.

Deadlock occurs because 
Thread A holds lock on row 1,5,8,9 and wants 20.
Thread B holds lock on 2,3,15,20,25 and wants 9.

this happens because the Hit Objects in Recorders are not ordered. 
So Thread B can get a lock on row 20, and want to "warp back" to 9,
while Thread A holds row 9  and wants to advance to row 20.

Solution:
Ordering ensures Thread B waits for lock release on row 9, without having row 20 already locked.

### CODE REVIEW

**Comment by medic123de** [comment]
please add to FAQ:
"Never have 2 seperate processes or servers import logs for the same id_site at the same time. This will cause InnoDB Transaction Deadlocks"

**Comment by mattab** [comment]
Hi @medic123de I added the tag `Needs review` and hopefully we can review it for 2.12.0

**Comment by mattab** [comment]
Hi @medic123de do you maybe have an explanation for the System tests failures after your change? https://travis-ci.org/piwik/piwik/jobs/53025832

I'm moving to 2.13.0 milestone as we likely won't have time to merge for 2.12.0

**Comment by medic123de** [comment]
Hi Matt,
we managed to get errors again even with this approach.. it seems to improve the situation but not entirely fix it.

Situation is: the tests fail, because numbers are not as expected. If i get the code in Tracker/Visit.php right, isLastActionInTheSameVisit should be true for last $visit_standard_length 

So, there are only 3 criteria that are sufficient to match a visitor. The browser, the date and the IP.
I have to dig into the code wide deeper than expected to find why sorting does not entirely fix the situation, and why sorting leads to different results. 
That should not happen as I understand from Tracker/Visitor.php

I will close the pull request by the current situation ( as it does nox fix this issue ), and will go another way to 1st fix the potential harm ( by assuring no data is lost ), then investigate what really happens.

**Pull request closed without merging**
