### PR TITLE
Add password strength indicator to user mgmt forms

### LINKED ISSUE #13070: Better password handling during installation
I think it'd be helpful for the admin to have the following dynamic (JS-driven) indicators, just like WordPress:

- Indicator for weak passwords
- Indicator for when passwords don't match

### PR DESCRIPTION
**Pull request by katebutler**
Uses the [jquery.pwstrength]https://github.com/matoilic/jquery.pwstrength) library.

pw-very-weak

pw-very-strong

Fixes #13070

### CODE REVIEW

**Comment by diosmosis** [comment]
I haven't looked into how it would have to be used, but would https://github.com/dropbox/zxcvbn be usable here? Given it was created by dropbox, it might do a better job than the jquery lib.

**Comment by tsteur** [comment]
We had a look at that lib but I don't think an 800KB lib should be needed for a password check ;) We found the jquery lib is lightweight but does the most important job.

**Comment by sgiehl** [comment]
@tsteur just out of curiosity, what is the plan regarding JS Frameworks? Wasn't it getting rid of jQuery and switching to AngluarJS? If so, we might better look for a small AngularJS lib for password strength.

**Comment by Findus23** [comment]
I'm not sure we should add a dependency to 6 year old code just for 30 lines of JS.

I guess it should be possible to simply write the same feature in pure JS or Angular.

https://github.com/matoilic/jquery.pwstrength/blob/d6f07a13eba1479f481d0beceb612f439db406ae/jquery.pwstrength.js#L13-L44

But the main question is what excactly is a secure password (see https://xkcd.com/936/).
And when you take into account all possibilities (e.g. that `Password1!` is not a strong password), you either end up with a gigantic library [like the one by dropbxox](https://lowe.github.io/tryzxcvbn/) or start comparing it to [large databases of common existing passwords](https://plugins.matomo.org/PasswordVerifier) which also isn't perfect.

**Comment by fdellwing** [comment]
I'm not a fan of such password strength indicators as they mostly give a false sense of security for awful passwords. So either use `zxcvbn` (or similar) or nothing at all.

**Comment by diosmosis** [comment]
@tsteur looks like there's a php port (linked on the github repo desc). We could invoke it through ajax, what do you think?

**Comment by Findus23** [comment]
@diosmosis It wouldn't be realtime, but I think that's not that bad as the library can even return a list of suggestions on how to improve the password.

The question is if this should be part of Matomo or a plugin.

**Comment by diosmosis** [comment]
If it's meant to increase baseline security for users, I would think it should be part of Matomo, not an optional plugin. I was addressing the issue of it being an 800kb JS library. If the PHP port is used, then only minimal JS is added to the client.

**Comment by tsteur** [comment]
> @tsteur just out of curiosity, what is the plan regarding JS Frameworks? Wasn't it getting rid of jQuery and switching to AngluarJS? If so, we might better look for a small AngularJS lib for password strength.

There's not really a plan, although for sure be great. The main plan is to eventually get rid of twig templates and PHP controllers. But that might be many years away :) If there's a simple lib that works and does the job based on jQuery I would say why not. Probably before that, we need to at some point see how to upgrade from Angular 1.X to a newer angular version but this will be big project in itself.

> I guess it should be possible to simply write the same feature in pure JS or Angular.

@Findus23 Can you maybe explain what the point is to rewrite it in pure JS or Angular? When there's already something that works etc?

@Findus23 @fdellwing I had a quick look on http://matoilic.github.io/jquery.pwstrength/ before we chose the lib and it was giving OK suggestions. You could of course also slightly adjust the code. A 1KB be obviously not as as good as a `zxcvbn` 800KB lib but it does the job and gives a better indication than it was before (which was none).

@diosmosis @Findus23 we could port it to PHP. The lib is also > 2MB though and more work for a feature that is currently not so relevant for us in terms of priority. I would say we either go with the jQuery lib here or we close the PR and move the issue back to the backlog. We only decided to implement and work on the issue cause it's a quick solution with the jQuery version that doesn't add much overhead. Happy either way.

**Comment by diosmosis** [comment]
@tsteur it has already been ported to php: https://github.com/bjeavons/zxcvbn-php (the link is on the main zxcvbn github repo). Would just using this be an ok amount of work?

**Comment by tsteur** [comment]
@diosmosis I know that's why I meant it's > 2MB. I meant the work to do the ajax, change wording in the UI based on result, colours, etc. The issue has just no priority currently.

**Comment by diosmosis** [comment]
Ok, I'll leave it alone then.

**Comment by fdellwing** [comment]
> I had a quick look on http://matoilic.github.io/jquery.pwstrength/ before we chose the lib and it was giving OK suggestions.

@tsteur I do see that differently. The lib does not look at entropie at all, but simply checks for "complex" chars. Ignoring both length and possible common char replacement in the password. I would therefor say: The lib is worse than not having an indicator at all, because

> give a false sense of security for awful passwords.

**Comment by tsteur** [comment]
OK no worries. We can close the PR and move it out of the milestone for now.

**Pull request closed without merging**
