### PR TITLE
Add removeEcommerceItem() and clearEcommerceCart() methods to JS tracker.

### LINKED ISSUE #11766: trackEcommerceCartUpdate Doesnt Clear Cart Items
The docs say to use the addEcommerceItem for every item in the cart prior to calling the trackEcommerceCartUpdate method. However only the trackEcommerceOrder method clears the internal eCommerceItems variable. This causes problems when an item is completely removed from the cart - even when using addEcommerceItem with qty 0, the item still gets sent to the server and the server tracks the deleted item as still being in the cart with qty 1. 

A much cleaner mechanism would seem to be to just clear the internal eCommerceItems object after every CartUpdate in addition to track order. This of course necessitates using addEcommerceItem for every item in the cart on every change to it, but the docs already say to do that. Unless I'm missing a specific reason why CartUpdate doesnt clear eCommerceItems on purpose? I'm happy to submit a pull request for this one line change but wanted to see if there was a specific reason it was written this way.

### PR DESCRIPTION
**Pull request by diosmosis**
Fixes #11766

### CODE REVIEW

**Comment by sgiehl** [comment]
Code looks good so far. There is still one JS test failing and the minified versions needs to be updated.
Guess we also need to update the developer documentation afterwards so the new methods are mentioned there.

**Review by mattab — APPROVED** [review]
LGTM

Feedback

* could you open the PR with the new docs in the JS reference, and also for our guide in https://matomo.org/docs/ecommerce-analytics/  ?

**Comment by diosmosis** [comment]
Created dev docs PR here: https://github.com/matomo-org/developer-documentation/pull/258

**Comment by diosmosis** [comment]
For the addition to the docs, here is some text that can be added after the `To track Ecommerce orders, two Javascript functions are used: ...` section:

```
There are also two other JavaScript functions you may find useful:

removeEcommerceItem(productSKU) This removes a product from the order by SKU.
clearEcommerceCart() This clears the order completely.

Generally, you only need to call these method if you don't track the order all at once and it's possible for a user to edit their cart after addEcommerceItem() is called. Otherwise, if you track an order after or as it is placed, then you just need to add the items and track the order.
```

**Comment by diosmosis** [comment]
cc @mattab for last two comments

**Pull request merged**
