### PR TITLE
don't install unneeded polyfills with composer

### PR DESCRIPTION
**Pull request by Findus23**
see https://github.com/symfony/polyfill/blob/main/README.md#design

This removes `symfony/polyfill-php56` on the next `composer install`

### CODE REVIEW

**Comment by sgiehl** [comment]
That package actually was already automatically removed with a composer update. See #16649

**Comment by Findus23** [comment]
Ah, I didn't see that PR. 
We could still add those lines in case any other dependency adds polyfills.

**Comment by sgiehl** [comment]
Yes. Shouldn't hurt to prevent installing those polyfills nevertheless

**Review by sgiehl — APPROVED** [review]

**Comment by tsteur** [comment]
@Findus23 @sgiehl the tests are failing see https://travis-ci.com/github/matomo-org/matomo/jobs/424314293

**Comment by sgiehl** [comment]
guess merging in the latest changes should fix it...

**Comment by tsteur** [comment]
there's a test now failing. not sure if it is due to this? https://travis-ci.com/github/matomo-org/matomo/jobs/424766921#L925 @sgiehl @Findus23

**Comment by Findus23** [comment]
The same failure seems to be on 4.x-dev without this PR: https://travis-ci.com/github/matomo-org/matomo/jobs/424766869#L921

**Comment by sgiehl** [comment]
That was caused by the cookie PR. See https://github.com/matomo-org/matomo/pull/14444#pullrequestreview-521623030

**Pull request merged**
