### PR TITLE
Updates phpmailer/phpmailer to 6.4.1

### PR DESCRIPTION
**Pull request by sgiehl**
### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by flamisz** [comment]
Hi @sgiehl, how come the `composer.json` is not updated in this PR? Shouldn't we do that?

**Comment by sgiehl** [comment]
@flamisz That's only needed when the composer.json actually prevents an update due to the version restriction.

**Comment by diosmosis** [comment]
@sgiehl in the future, when we run composer update to update dependencies, will we lose this change?

**Comment by sgiehl** [comment]
no, why should we? I simply ran a `composer update phpmailer/phpmailer` and added the changes of `composer.lock` as usual.

**Review by flamisz — APPROVED** [review]

**Pull request merged**
