### PR TITLE
Include CustomDimensions plugin in core

### PR DESCRIPTION
**Pull request by sgiehl**
... and activate it automatically on update

refs #11524 

Note: After merging this, we should remove the `4.x-dev` branch of CustomDimensions plugin and migrate all issues.

### CODE REVIEW

**Review by diosmosis — APPROVED** [review]
LGTM. I guess we'll have to migrate the customdimensions issues into the core tracker, too eventually.

**Comment by tsteur** [comment]
LGTM  and could point re migrating the issues. Guess we'll then also need to disable the issues in that repo plus mention maybe in 3.X readme which appears on the marketplace that the plugin is included in core directly from Matomo 4.

**Comment by sgiehl** [comment]
@tsteur I've updated the PR so it contains the latest changes that were done on the plugin repo. Could you maybe merge the PR, migrate the issues and remove the 4.x-dev branch on the plugin repo maybe?
I've checked that there are no more open PRs or branches that may contain any changes that would need to be migrated...

**Comment by tsteur** [comment]
Merged and migrated the issues. Made the 3.x-dev the default branch and kept 4.x-dev branch for now but could also delete it.

**Pull request merged**
