### PR TITLE
For a Piwik PRO developer always specify a max version for a plugin by default

### PR DESCRIPTION
**Pull request by tsteur**
refs #8695

This is to be defined whether it's actually needed / wanted by Piwik PRO developers. 

Piwik PRO developers would enable Piwik PRO mode initially with 

`./console development:enable --piwikpro`

Following `development:enable` commands would not need this flag as we wouldn't change it afterwards anymore. It would be otherwise forgotton and annoying to always having to add this flag.

When this mode is enabled, and a plugin is generated, we automatically specify a maximum supported Piwik version in `plugin.json`. Instead of 

``` json
    "require": {
        "piwik": ">=2.15.0-rc1"
    },
```

we specify

``` json
    "require": {
        "piwik": ">=2.15.0-rc1,<=2.15.0-rc1"
    },
```

for Piwik PRO developers. From my understanding in #8695 this is what Piwik PRO developers want. So far it was specified in `.travis.yml`. Please note that when a max version is specified, it cannot be installed on a later Piwik version. This is something that needs to be configured.

Also see related PR https://github.com/piwik/travis-scripts/pull/21

### CODE REVIEW

**Comment by hpvd** [comment]
> Please note that when a max version is specified, it cannot be installed on a later Piwik version. This is something that needs to be configured.

don't know excactly if it's really the same technical background, but in FF you have in the past the problem that some addons doesn't work beacuse they were marked as "non compatible".Changing the supported version in the addon code solved this.This was pretty annoying.

hmm setting this: where from should one know that a plugin would work in special future version?
maybe it's a ready not working with the version before the set version...

**Comment by tsteur** [comment]
Yeah setting the max version is not really a good solution as it would kinda mean we fail as being a platform as we break API's randomly. However, from what I understood, this is the workflow for Piwik Pro developers. There are automated processes that run a plugin against a new Piwik version when it's about to be released and the max version gets automatically updated in case the tests are still green.

**Comment by tsteur** [comment]
FYI: This flag is only meant for Piwik PRO developers

**Comment by mattab** [comment]
as this is not be needed now, closing.

**Pull request closed without merging**
