### PR TITLE
fix for URL garbage issue

### PR DESCRIPTION
**Pull request by saleemkce**
updated fix.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @saleemkce 

Thanks for the pull request. I tested it using the script to reproduce the issue: https://github.com/piwik/piwik/issues/5014#issuecomment-48315208

but unfortunately the URL still appears with wrong characters: 


Note that Thomas even posted the solution earlier in: https://github.com/piwik/piwik/issues/5014#issuecomment-101824842

therefore i'm closing this PR and we will fix it soon

**Comment by mattab** [comment]
@saleemkce my attempt at fixing the issue: https://github.com/piwik/piwik/pull/7944/files

**Comment by saleemkce** [comment]
@mattab did you look at the conversation between me and Thomas https://github.com/piwik/piwik/pull/7866#issuecomment-101345460? There is an issue in **js/piwik.js line no.3314** in my changed files. Please go through this page and see some bug issues fixed here.

**Comment by mattab** [comment]
@saleemkce sorry I didn't look at the conversation, somehow I missed it. I just tested both cases:

```
 <a target="_blank" href="http://example.org/2013/06/test.php?param[]=1&test2=%D8%A5%D9%86%D8%B4%D8%A7%D8%A1-%D9%86%D8%B3%D8%AE%D8%A9-%D9%85%D8%AE%D8%B5%D8%B5%D8%A9-%D9%86%D8%B8%D8%A7%D9%85-%D8%AA%D8%B4%D8%BA%D9%8A%D9%84-%D8%A3%D9%8$

2nd link

 <a target="_blank" href="http://example.org/2013/06/إنشاء-نسخة-مخصصة-نظام-تشغيل-أوبنتو-ب">test with actualy Url utf8</a>

```

and both cases worked in the new PR #7944  so maybe that's a good solution?

**Comment by saleemkce** [comment]
@mattab oh that's great. Please commit your fix. I will later do so more testing in this and report you if anything goes wrong.

**Pull request closed without merging**
