### PR TITLE
Add query string to error logs

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

As title. Noticed a lot of these in the logs, but there's not enough information to see where they came from.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Did you suppose to changes this visible exception message: https://builds-artifacts.matomo.org/matomo-org/matomo/not-yet-installed-better-message/46346/Installation_access_no_config.png

**Comment by sgiehl** [comment]
@diosmosis there are still some failing tests

**Comment by diosmosis** [comment]
@sgiehl do you have any issue with merging this?

**Comment by sgiehl** [comment]
Seems tests are passing now. So feel free to merge

**Pull request merged**
