### PR TITLE
Fix triggers select in Add Goal form

### LINKED ISSUE #8244: Adding/Editing a new goal doesn't update its "state" and some UI issues
While testing #8242 I noticed some issues with "Adding new goals" and probably as well with "Editing goals". I'm using Chrome 43 on MacOS. To reproduce go to "Your Username in top right menu => Goals => Create new goal" 

* When selecting another value in the select field "Goal is triggered" the form is not immediately updated. I have to click on the select box again to see the UI change. This results in very weird states eg it says "manually" but it still shows all the radio boxes on the other side. Or it says "when visitors" but I'm not able to select any of the radio boxes.

* Missing space below "Goal is triggered" and checkbox "Case sensitive match" is positioned on the right instead of left. The labels also seem to look different etc but this should not be part of this issue as it might be quite a bit of work.

See screenshot: 

goals_management

* Wording is incorrect in "Manage Goals" overview. It says "Create a new goal" but then the opened form says "Add a new goal". In Websites Management / User Management we use the term "Add" and it should be used there as well

* When creating a goal triggered "Manually" and then editing a goal the radio boxes look disabled but still can be selected when choosing "Goal is triggered when visitors". They should not look disabled
 
goals_radio

### PR DESCRIPTION
**Pull request by barbushin**
Closes #8244

### CODE REVIEW

**Comment by tsteur** [comment]
I still have to click on the select for the changes to be applied, even after I changed the value.

Just had a quick look and it might be enough to listen to the `change` instead of `click` event here:

https://github.com/barbushin/piwik/blob/8244_goals_form_fix/plugins/Goals/javascripts/goalsForm.js#L108

That might be the only change needed but not sure re side effects. If that works, we could undo the other changes probably.

**Comment by barbushin** [comment]
Changed `.click` to `.change`, but for me it works the same. Like this http://i.imgur.com/gKzOzt0.gif

**Comment by tsteur** [comment]
Which browser are you using? It did not work for me on Chrome 43 with MacOSX.

@mattab the select box is now moved to the right see: http://i.imgur.com/gKzOzt0.gif What's your thought on that?

**Comment by barbushin** [comment]
I use Chrome 43, Firefox 34 and Opera 12 on Win8.1x64.

Regarding new select box position, I moved it to the right side because I thought it's HTML bug that it was located in left side. Also I think it will be better if we set `vertical-align: top` for blocks titles, like this http://i.imgur.com/yV4VIPb.png (current version: http://i.imgur.com/uoytH0r.png).

But anyway, it's up to you, guys, to chose the best solution. I'm not a designer :)

**Comment by mattab** [comment]
>  I'm not a designer :)

we're also not designers, but we do our best to build UI that look good and are usable. it's very important part of building a successful and amazing product.

@barbushin 
missing space

Could you add some space below this SELECT box as you can see it's too close to the radio boxes below

**Comment by barbushin** [comment]
@mattab What browser do you use? In Chrome 43 and Firefox 34 there is a space already 
image

**Comment by tsteur** [comment]
> Also I think it will be better if we set vertical-align: top for blocks titles

I like it much better, maybe you can issue another PR?

**Comment by barbushin** [comment]
@tsteur Sure! Just added that fix in https://github.com/piwik/piwik/pull/8279

**Comment by mattab** [comment]
> @mattab What browser do you use? In Chrome 43 and Firefox 34 there is a space already 

@barbushin I can see this behavior on both latest Chromium and Firefox on ubuntu

**Comment by barbushin** [comment]
@mattab  It's very strange because I can't reproduce it. There is `<p>` tag with `margin-top: 10px` for list of radio inputs 
image

**Pull request merged**
