### PR TITLE
Increase tested timeout for marketplace service test

### PR DESCRIPTION
**Pull request by bx80**
### Description:

The marketplace service system test randomly fails when the service request doesn't return in under two seconds. 

```
1) Piwik\Plugins\Marketplace\tests\System\Api\ServiceTest::
test_timeout_invalidService_ShouldFailIfNotReachable
Failed asserting that 4 is equal to 2 or is less than 2.

/home/runner/work/matomo/matomo/matomo/plugins/Marketplace/tests/System/Api/ServiceTest.php:154
```

As the default timeout is 60 seconds, increasing the test pass threshold to 4 seconds will still confirm that the timeout is being applied and will reduce random failures when the test server is running slowly.

This PR changes the 2 second check to 4 seconds.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
I wouldn't mind going to 5 or even 10 seconds so that we don't have to deal with the same thing in 6 months, if it's still within the timeout limit and we're not testing the speed but the success of the response.

**Comment by sgiehl** [comment]
Did you try checking why this test doesn't work on github? It's a bit weird that it takes longer than the defined timeout.
Maybe it's doesn't use curl for some reason?

**Comment by bx80** [comment]
@sgiehl 
> Did you try checking why this test doesn't work on github? It's a bit weird that it takes longer than the defined timeout.
Maybe it's doesn't use curl for some reason?

I didn't, it's randomly failing both locally and an github. Any suggestion for how to confirm that curl is being used when run on github?

**Comment by sgiehl** [comment]
@bx80 The tests also fails locally for you? I was never able to reproduce that locally...
You could maybe add some debug logs to the code that is executed by that test to see where the time limit is actually exceeded.
Might be good to understand why that limits is exceeded even though it is provided.

**Comment by bx80** [comment]
@sgiehl I've only seen it fail locally once when running tests at the same time as a network heavy db load test, I can't recreate it on demand.

In this particular test we're trying to connect to a non-existent domain, so the issue could be related to https://github.com/curl/curl/issues/2975 Based on that I'm not sure we should be expecting the curl timeout to fully cover DNS resolution delays in it's standard configuration. Perhaps we could look at adding support for [CURLOPT_QUICK_EXIT](https://curl.se/libcurl/c/CURLOPT_QUICK_EXIT.html) to the `sendHttpRequestBy` method or use a valid domain but invalid path for the test?

**Comment by michalkleiner** [comment]
I have an idea to try about how to test this reliably, will give it a quick go.

**Comment by michalkleiner** [comment]
Ok, I was able to replicate this locally in a reliable way.

It is indeed the DNS resolution that could take longer and can't be easily influenced.

Locally I use Laravel Valet which uses dnsmasq to help resolve test domains to local IPs.
I added a rule to proxy the `notexisting49.plugins.piwk.org` domain resolution to blackhole.webpagetest.org which is a blackhole server that drops all traffic (resulting in no rejection, no confirmation, just a timeout).

With that, the test fails reliably.

DNS timeout failure

**Comment by bx80** [comment]
Nice one @michalkleiner, since this establishes that the timeout used by the test doesn't apply to DNS resolution issues, it would seem that the idea of testing the timeout against a non-existent domain is invalid and we should either remove this test entirely or use a valid domain. Any thoughts @sgiehl @michalkleiner ?

**Comment by sgiehl** [comment]
We should remove checking for a certain timeout. The test could still be there to check if using an invalid domain in a request results in an exception and isn't silently ignored or similar.

**Comment by michalkleiner** [comment]
Yeah, probably remove the check for the expected response time and replace it with a request response check that can happen faster on some occasions than others, but should do the trick.

**Comment by sgiehl** [comment]
Looks like something went wrong when merging/rebasing

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
