### PR TITLE
Ensure git commands are run in the appropriate directory to prevent "fatal: Not a git repository (or any parent up to mount point /srv)"

### PR DESCRIPTION
**Pull request by bkbeckman**
Please issue pull request against the `3.x-dev` branch as the `master` branch currently represents our `2.X` version which is in LTS mode. 

Important fixes will be merged into `master` if needed after it was merged to `3.x-dev`.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @bkbeckman 

Are you using the AWS Toolkit to run Piwik tests?

**Comment by bkbeckman** [comment]
No.  I was just seeing the error message from #8771 when running console commands with an absolute path.

**Comment by mattab** [comment]
Ok, this console command is not related to the error messages there.

**Comment by bkbeckman** [comment]
From my investigations, it is.  The linked error message will be triggered any time the console command is executed with an absolute path inside of a directory that does not contain a .git folder.

Example,

```
$ ll -a
total 16
drwxr-x---  4 piwikadmin apache 4096 Sep 22 20:11 .
drwxr-xr-x  4 root       root   4096 Sep 22 20:10 ..
drwxrwxr-x 13 piwikadmin apache 4096 Sep 23 16:15 piwik
$ ./piwik/console examplecommand:helloworld
fatal: Not a git repository (or any parent up to mount point /media/ephemeral0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Note the error message.

Now let's see what happens when we run the command inside of the piwik directory.

```
$ ll -a
total 2720
drwxrwxr-x 13 piwikadmin apache    4096 Sep 23 16:15 .
drwxr-x---  4 piwikadmin apache    4096 Sep 22 20:11 ..
drwxrwxr-x  9 piwikadmin apache    4096 Sep 16 17:26 .git
-rw-rw-r--  1 piwikadmin apache     711 Sep  1 15:29 .gitattributes
-rw-rw-r--  1 piwikadmin apache    1319 Sep 16 17:12 .gitignore
-rw-rw-r--  1 piwikadmin apache    4774 Sep 23 18:22 .gitmodules
....more files...
```
Note the existence of .git.  Let's run the command again from this directory and see what we get...

```
$ ./console examplecommand:helloworld
HelloWorld:
```

No issues -- confirming this issue is the same one outlined in #8771.

Now, to see why this is happening, we open up Piwik\Plugins\TestRunner\Commands\TestRunOnAws.php and add a new line to the getCurrentGitHash() method.

```
    private function getCurrentGitHash()
    {
        // we should not use 'git' executable unless we are in a git clone
        if(!SettingsPiwik::isGitDeployment()) {
            return 'WARN: it does not look like a Piwik repository clone - you must setup Piwik from git to proceed';
        }
        debug_print_backtrace();
        return trim(`git rev-parse HEAD`);
    }
```
Note the debug statement.  Now when we run the console command again.

```
$ ./brian/console examplecommand:helloworld
#0  Piwik\Plugins\TestRunner\Commands\TestsRunOnAws->getCurrentGitHash() called at [/media/ephemeral0/piwikinstalls/brian/plugins/TestRunner/Commands/TestsRunOnAws.php:42]
#1  Piwik\Plugins\TestRunner\Commands\TestsRunOnAws->configure() called at [/media/ephemeral0/piwikinstalls/brian/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:65]
#2  Symfony\Component\Console\Command\Command->__construct() called at [/media/ephemeral0/piwikinstalls/brian/core/Console.php:91]
#3  Piwik\Console->addCommandIfExists(Piwik\Plugins\TestRunner\Commands\TestsRunOnAws) called at [/media/ephemeral0/piwikinstalls/brian/core/Console.php:74]
#4 [....SNIP....]
#5  Symfony\Component\Console\Application->run() called at [/media/ephemeral0/piwikinstalls/brian/console:27]
fatal: Not a git repository (or any parent up to mount point /media/ephemeral0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
HelloWorld:
```
We can see that `core/Console.php:91` is loading the `TestsRunOnAws `class and that `Piwik\Plugins\TestRunner\Commands\TestsRunOnAws:42` is calling the `getCurrentGitHash `method, which is execing a git command on a relative directory, which will throw an error message if the current working directory is not a working git directory.

Thus, I'm quite confident that #8771 is resolved by this pull request.

**Comment by mattab** [comment]
Thanks for additional information.

**Pull request merged**
