### PR TITLE
Update list of valid TLDs and IDNs

### PR DESCRIPTION
**Pull request by robocoder**
* Backport changes from:
  * Zend_Validate_Hostname from ZF 1.12.20
  * Zend\Validator\Hostname ZF2 (b3ebdf2, Feb 1, 2018)

### CODE REVIEW

**Comment by mattab** [comment]
Hi @robocoder 
Thanks for the PR :+1:  Noticed that the integration test which checks against many TLDs is now failing in: https://travis-ci.org/matomo-org/matomo/jobs/340708272

```
1) Piwik\Tests\Integration\EmailValidatorTest::test_allCurrentTlds
preg_match(): Compilation failed: regular expression is too large at offset 156184
/home/travis/build/matomo-org/matomo/libs/Zend/Validate/Hostname.php:2358
/home/travis/build/matomo-org/matomo/libs/Zend/Validate/EmailAddress.php:487
/home/travis/build/matomo-org/matomo/libs/Zend/Validate/EmailAddress.php:546
/home/travis/build/matomo-org/matomo/core/Piwik.php:575
/home/travis/build/matomo-org/matomo/tests/PHPUnit/Integration/EmailValidatorTest.php:21
/home/travis/build/matomo-org/matomo/tests/PHPUnit/Integration/EmailValidatorTest.php:66

```

Would you be able to update this integration test so it passes again?

**Comment by robocoder** [comment]
I'll look at it later this evening.

**Comment by robocoder** [comment]
The regex pattern buffer max length is determined by a compile-time setting when building php. Since this can vary between platforms, I arbitrarily used a cutoff of 256.

**Comment by robocoder** [comment]
Please remove the `Pull Request WIP` tag.

**Pull request closed without merging**
