### PR TITLE
Fix french language

### PR DESCRIPTION
**Pull request by WedgeSama**
Fix one little mistake on French language in installation plugin.

### CODE REVIEW

**Comment by sgiehl** [comment]
Thanks four your PR. Unfortunately we can't merge pull requests for translations, as our translations are managed at http://translations.piwik.org. We are automatically pulling translations updates from there and so everything changed here would be overwritten.
If you would like to further improve translations, please register at http://translations.piwik.org and do the changes there.

**Comment by WedgeSama** [comment]
Ok, I did not know. I will register on this.

**Comment by tsteur** [comment]
I wonder if we could add a comment to each lang json file linking to otrance and explaining that translations are made there?

**Comment by sgiehl** [comment]
Well, we have https://github.com/piwik/piwik/blob/master/lang/README.md

afaik json files cannot have comments.

**Comment by tsteur** [comment]
All good, wasn't sure whether they can have comments

**Pull request closed without merging**
