### PR TITLE
Next round: PSR-2 + php-cs-fixer

### PR DESCRIPTION
**Pull request by ThaDafinser**
Hello together,

i've done now really the smallest part to finally add php-cs-fixer to piwik.

How to install global: https://github.com/FriendsOfPHP/PHP-CS-Fixer#globally-composer

I extra left out following things:
# Include it for all php folders - Why not?

You guys should activate it, when you think its a good time that not all PRs need to go through a merge "hell". Just change the exclude/include part in .php-cs-fixer
# Do not add it to the build system and even not composer

As long as Piwik still support PHP 5.3.3 this is not possible. When Piwik at least requires PHP 5.3.6 we can add it then.

https://github.com/piwik/piwik/pull/7731
https://github.com/piwik/piwik/pull/8047
https://github.com/piwik/piwik/issues/7186
https://github.com/piwik/piwik/pull/7955

@mattab i think it would be a good idea to add this also to 2.15, since then merging/backporting from 3.x branch down would be easier?

My idea is to execute this by hand first from time to time and add more and more folder, until we have all. Then when also PHP 5.3.6 is required we add it to the build system

### CODE REVIEW

**Comment by mattab** [comment]
Hi @ThaDafinser I think (if i'm not mistaken) that if we want to fix the code (IMO it's nice to have!), we should do it rather quickly or we may risk a merge-hell with 3.0.0 and LTS branch. @tsteur any thought on this maybe?

**Comment by tsteur** [comment]
yes would be good to do after merging 3.0 to master! I already had yesterday some troubles re some line ending changes when I merged master => 3.0

**Comment by mattab** [comment]
Just to be sure, do you suggest we should do the PSR fix only after 3.0.0 has become `master` branch, ie. in 2016?

**Comment by ThaDafinser** [comment]
yes @mattab you are right: ASAP ...otherwise merging wont be fun, but with this change it will be much easier!

I just let it open for you guys, since you can choose a good moment - e.g. most (large) PRs are merged already....

**Comment by ThaDafinser** [comment]
Fixes executed #8884 #8885 #8888 #8889

**Pull request closed without merging**
