### PR TITLE
Deactivating a plugin: clear the caches before unloading the plugin

### LINKED ISSUE #8007: Deactivating a plugin works but display a warning message "The plugin XYZ has not been loaded."
Steps to reproduce:
 * On Piwik master, go to Administration > Plugins
 * Deactivate Provider plugin
 * Got: The Provider plugin is disabled as expected. But there is a full page with warning message `The plugin 'Provider' has not been loaded.`:
 * Expected: the Plugins page reloads the Plugins listing and this message is not displayed.

Notes:
 * this is a regression in 2.14.0 hence why I put `not-in-changelog` label
 * it may only bug for Third party plugins (and work fine for core plugins)

Stacktrace:
```
#0 /home/matt/dev/piwik-master/core/AssetManager.php(347): Piwik\Plugin\Manager->getLoadedPlugin('Bandwidth')
#1 /home/matt/dev/piwik-master/core/AssetManager.php(226): Piwik\AssetManager->pluginContainsJScriptAssets('Bandwidth')
#2 /home/matt/dev/piwik-master/core/Filesystem.php(28): Piwik\AssetManager->removeMergedAssets('Bandwidth')
#3 /home/matt/dev/piwik-master/core/Plugin/Manager.php(447): Piwik\Filesystem::deleteAllCacheOnUpdate('Bandwidth')
#4 /home/matt/dev/piwik-master/core/Plugin/Manager.php(349): Piwik\Plugin\Manager->clearCache('Bandwidth')
#5 /home/matt/dev/piwik-master/plugins/CorePluginsAdmin/Controller.php(453): Piwik\Plugin\Manager->deactivatePlugin('Bandwidth')
#6 [internal function]: Piwik\Plugins\CorePluginsAdmin\Controller->deactivate()
#7 /home/matt/dev/piwik-master/core/FrontController.php(497): call_user_func_array(Array, Array)
#8 /home/matt/dev/piwik-master/core/FrontController.php(97): Piwik\FrontController->doDispatch(NULL, NULL, NULL)
#9 /home/matt/dev/piwik-master/core/dispatch.php(34): Piwik\FrontController->dispatch()
#10 /home/matt/dev/piwik-master/index.php(27): require_once('/home/matt/dev/...')
#11 {main}
```

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #8007

The plugin instance is used for clearing the caches, so it needs to be unloaded _after_ the caches are cleared. I'm opening for review because I am not certain what I'm doing isn't affecting other parts :/ (and maybe there's a better solution)

For the record it started to show the warning after a20e71c61aa9ae74dac9e1b899772357d4d3a64c fixed a bug (unloading plugins wasn't really unloading before) which made this bug more visible (so it may have been partially broken for some time before).

### CODE REVIEW

**Comment by diosmosis** [comment]
Can you trigger the bug in a test?

**Comment by diosmosis** [comment]
I think these two things would help in checking that there are no side effects:

1. Check whether `Manager::removePluginFromConfig()`, `Manager::unloadPluginFromMemory()`, `Manager::executePluginDeactivate()` inadvertently accesses one of the caches that are cleared. If so, maybe the cache will be recreated before the plugin is removed from the Plugin\Manager list?

2. Access the caches in a plugin's `Plugin::deactivate()` and make sure the recreated cache doesn't cause problems.

This is just from looking at the existing code, though. I haven't worked w/ this code in a while, so I don't know of any specific issues.

**Comment by tsteur** [comment]
LGTM. Not merging directly since there were some other comments

**Comment by mnapoli** [comment]
I've added a test covering that and had a look at the code, couldn't find usage of the cache.

**Pull request merged**
