### PR TITLE
Change on svgBasePath to work with reverse proxy

### PR DESCRIPTION
**Pull request by tinwinaung**
Will be better if we change $view->piwikUrl with specific domain

### CODE REVIEW

**Comment by sgiehl** [comment]
@tinwinaung would you mind trying to explain what problem this change will solve? Is the hostname included not the correct one?

**Comment by tsteur** [comment]
I can see how this might be a problem if `getPiwikUrl` is not correct and stored eg as 127.0.0.1 or something. Haven't tested though if it works.

**Comment by tinwinaung** [comment]
@tsteur : May I know where this getPiwikUrl value come from? Currently, I have problem with realtime map for matomo hosted behind proxy server.

@sgiehl : svgBasePath is not correct for realtime map because my getPiwikUrl return specific url path. I just try to make it absolute path.

**Comment by mattab** [comment]
If Matomo is behind a reverse proxy and installed in a sub-path, please follow instructions in https://matomo.org/faq/how-to-install/faq_98/

IMO this change shouldn't be needed if you follow the instructions? please re-open if it's not working and explain the steps you took.

**Pull request closed without merging**
