### PR TITLE
update pchart library from 2.1.3 to 2.1.4 and moved them to a new folder

### PR DESCRIPTION
**Pull request by tsteur**
While having a look at this PR https://github.com/piwik/piwik/pull/7660/files I noticed there is an update available for pchart (since Jan 2014). It fixes eg a labelling bug on the pie charts and adds a feature re opacity.

I also moved the files to another folder as it included the version number before. This _should_ not have an impact re breaking things but I could re-add the old files again into the libs folder till Piwik 3.0.0

There is a package for pchart on packagist/composer but those are all forks and initially we said we will only use composer for repositories that are maintained by the author of the lib.

I did a diff between 2.1.3 and 2.1.4 to see if we applied any patches in the past and to do a quality/security review of the patches and to see what was changed. I re-applied our patches again (re Japanese characters etc)

### CODE REVIEW

**Comment by diosmosis** [comment]
@tsteur is it important that this is merged soon? I'd like to write some UI tests for the ImageGraph plugin first. At least smoke tests, in case it's not possible to get travis + local to render the same images.

**Comment by tsteur** [comment]
Nope, not needed soon

**Comment by diosmosis** [comment]
@tsteur can you rebase?

**Comment by tsteur** [comment]
done

**Pull request merged**
