### PR TITLE
[4.x] Add German, Spanish, French, Italian and Dutch translation for no-data GTM page

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Add translations for GTM tab of the no-data screen.
Companion PR to #20637 for 4.x branch

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Please don't merge until the 5.x PR is approved by the product team and merged.

**Comment by Findus23** [comment]
Just in case you don't know it: You can use the Weblate glossary (https://hosted.weblate.org/projects/matomo/glossary/) to make sure "special Matomo phrases" like "Custom Dimensions" are translated the same here as everywhere else in Matomo (If you manage the translations via the Weblate UI, it also automatically suggests the glossary phrases)

**Comment by michalkleiner** [comment]
Failing tests are pre-existing/failing on the base `4.x-dev` branch as well.

**Comment by michalkleiner** [comment]
5.x PR #20637 already merged

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
