### PR TITLE
Show description bubbles below column if they would be out of viewport if shown above

### LINKED ISSUE #9838: Embed Piwik Report - columnDescription-bubbles are out of view
When embedding a piwik report the column description bubbles can are not fully visible.

Please see the demo for reference:
http://demo.piwik.org/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=7&period=day&date=yesterday&disableLink=1&widget=1

Hover over the column headlines (i.e. page views).

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #9838

### CODE REVIEW

**Comment by adaqus** [comment]
The code looks ok. I wonder whether it is possible to avoid situations like this:

column-doc

Because document body ends where table's 'frame' ends, bubbles with longer text cannot be entirely displayed.

**Comment by sgiehl** [comment]
might be possible. can check that later

**Comment by sgiehl** [comment]
Had another look. Is not easily possible. Widgets cut off overlapping content, to avoid overlapping in dashboard, so there is no smooth way to let it overlap

**Comment by adaqus** [comment]
Ok, so let's not bother. I can also see that tooltip changed its position a little bit in UI test ('UIIntegrationTest - 'should display metric tooltip correctly') - visitble in UIIntegrationTest_metric_tooltip.png screenshot. So expected image should be corrected.

**Comment by sgiehl** [comment]
Sure. Needs to be done after merging, as it is in another repo...

**Comment by adaqus** [comment]
@sgiehl Ok, so PR looks OK :+1:

**Comment by mattab** [comment]
LGTM @sgiehl

**Pull request merged**
