### PR TITLE
Make sure overlay API requests send force_api_session as POST param

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

In the JS tracker we try to detect whether we are in an Overlay iframe by checking the HTTP referrer. If the referrer is from a specific Overlay controller action, then we know we're in Overlay.

The regex for parsing the segment parameter in this detection logic is incorrect. In it, we end up matching the segment parameter, plus everything after it. For example, in `&segment=&token_auth=...&force_api_session=1` we match `&token_auth=...&force_api_session=1`, and assume this is the segment.

This is passed on to the Overlay/client.js code which appends it to every API request it makes, assuming that it's the segment. These parameters passed in the URL breaks the force_api_session code, since in the browser we make POST requests (so the token_auth is not saved in the browser cache), and server side we do not allow force_api_session to be used in $_GET if using a POST request.

Fixing this in two ways:

1. fixing the regex to not be greedy
2. making sure token_auth/force_api_session are not appended to the URL even if present in the API request

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
build js

**Comment by diosmosis** [comment]
build js

**Review by sgiehl — COMMENTED** [review]
The code changes look good. But didn't do any local testing yet

**Comment by diosmosis** [comment]
The customer has replied it works, @sgiehl ok to merge this?

**Comment by sgiehl** [comment]
Sure

**Pull request merged**
