### PR TITLE
Adding PHP7 build on travis

### PR DESCRIPTION
**Pull request by ThaDafinser**

### CODE REVIEW

**Comment by tsteur** [comment]
Nice, I was thinking about that recently as well. We should start working on making Piwik PHP 7 compatible if not done yet. @diosmosis I reckon we also need to update travis-yml instead right? https://github.com/piwik/travis-scripts/blob/master/generator/templates/travis.yml.twig

It will be also useful to add it now so plugin developers might get some time to make sure it's working correctly with PHP 7

**Comment by tsteur** [comment]
I presume until we have full support for PHP 7 we should run one job `AllTests with PHP 7` and one job for all `UiTests with PHP 7`. Once PHP 7 is stable we could change to replace some jobs that currently use `5.6` with `7.0`

**Comment by tsteur** [comment]
@ThaDafinser they seem to fail because of 

```
The command "phpenv config-rm xdebug.ini;" failed and exited with 1 during .
```

https://travis-ci.org/piwik/piwik/jobs/77465717#L541

**Comment by ThaDafinser** [comment]
@tsteur already saw that and stopped there. I know that xdebug still lacks a bit of PHP7 support at least, but that is not the problem.

> Generating autoload files
> Piwik\Composer\ScriptHandler::buildXhprof
Building xhprof...
Fatal error: could not build extension (make failed)! View tmp/xhprof-logs/make.log for more info.
0.03s$ phpenv config-rm xdebug.ini;
File xdebug.ini does no exist.
The command "phpenv config-rm xdebug.ini;" failed and exited with 1 during .
Your build has been stopped.

**Comment by tsteur** [comment]
OK, so we should not build xhprof for PHP 7?

**Comment by ThaDafinser** [comment]
@tsteur i disabled now xhprof and the xdebug file and the build "works now" at least for PHP7: https://travis-ci.org/piwik/piwik/builds/78231802

**Comment by tsteur** [comment]
Nice, Unit tests execute 5 times faster with PHP 7 (8 seconds vs 40 seconds) if I'm seeing this right :)

@mattab when do you think will we roughly work on PHP 7 support? We should fix most important errors first as integration and system tests do not run at all currently. Won't need to merge it before having basic support for it

**Comment by mattab** [comment]
It would be very nice to have if LTS version was fully compatible with PHP7  - will minimise LTS related support issues in the future. Maybe we can try to get php7 support in 2.15.0?

**Comment by tsteur** [comment]
FYI: I started working on some more PHP 7 support in #8706

**Comment by mattab** [comment]
Let's close this PR in favor of https://github.com/piwik/piwik/pull/8706/files

Cheers @ThaDafinser for starting it

**Pull request closed without merging**
