### PR TITLE
Include lox/xhprof in the Matomo build release

### LINKED ISSUE #17939: Include lox/xhprof in the Matomo build release so Profiling works
Only works when installed from git but no longer works when installed from regular release zip.

That's likely because `lox/xhprof` is marked as development dependency in composer.json.

### PR DESCRIPTION
**Pull request by tsteur**
### Description:

fix https://github.com/matomo-org/matomo/issues/17939

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Wondering if we also need to update https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/core/Composer/ScriptHandler.php#L21 and the referenced shell script, as it still uses `facebook/`, while the package now uses `lox/`

**Comment by tsteur** [comment]
@sgiehl changed those. Not really sure though it's generally still needed.

**Comment by sgiehl** [comment]
If it's not needed, guess we should simply remove it. There also seems to be a `build-xhprof.sh`, not sure what it was good for and why it is not called in `ScriptHandler::buildXhprof` 🤷 
Btw. Guess it might be needed to run a composer update after this was merged, otherwise it might remain in the dev packages in composer.lock.

**Comment by tsteur** [comment]
I removed these scripts for now. We can always add back if needed for some reason.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
