### PR TITLE
Remove "refer us" feature

### LINKED ISSUE #18232: Remove "refer us" feature
In https://github.com/matomo-org/matomo/pull/17234 we added the "refer us" feature which shows a popup asking to share on twitter, facebook, linkedin.

We couldn't see too many shares so far now we would like to remove this feature again to have less popups.

### PR DESCRIPTION
**Pull request by andyjdavis**
### Description:

This is a possible solution for https://github.com/matomo-org/matomo/issues/18232

I have taken "remove this feature" to mean remove the code involved and not simply turn it off.

Rather than trying to revert the commits in the original PR I opted to go through the changes and remove what didn't appear to be required/useful.

Firstly, I did it this way as there are changes made after the initial PR was merged like translations of the "refer us" popup's strings and possibly other changes.

Secondly, some of the changes from the original PR may still be useful. For example in plugins/Feedback/Feedback.php renderViewsAndAddToPage() can still support multiple popups if it needs to do that again.

I am unsure if there is another process for the removal of unused strings from language files.

Let me know if anything about this is incorrect and I will be happy to fix it :)

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by Findus23** [comment]
> I am unsure if there is another process for the removal of unused strings from language files.

Just FYI, if you remove them from en.json, weblate should automatically remove them from all other languages in its next PR

**Comment by sgiehl** [comment]
Actually it would be better to only adjust them in `en.json`, as otherwise Weblate might get merge conflicts if there were changes in that file in any language.

**Comment by peterhashair** [comment]
@andyjdavis Thanks for the PR. I merged your changes to my PR if that's ok. Otherwise, there will be conflicts.

**Comment by andyjdavis** [comment]
@peterhashair no problem. Shall I just close this PR?

>Actually it would be better to only adjust them in en.json, as otherwise Weblate might get merge conflicts if there were changes in that file in any language.

@sgiehl is it still worth doing this? I assume that would now need to happen in @peterhashair's PR.

**Comment by peterhashair** [comment]
@andyjdavis sure you can close that PR if that ok, also can I put your name for that issue on the next release :).

**Comment by andyjdavis** [comment]
Closing this PR. I hope it was useful :)

**Comment by peterhashair** [comment]
@andyjdavis it's really helpful, 99.99% using your code, just some tiny updates :), you are on the next release list :)

**Pull request closed without merging**
