### PR TITLE
Prevent possible notice when using tracker config

### PR DESCRIPTION
**Pull request by peterhashair**
### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@peterhashair Could you please explain when exactly this is an issue? (The issue number L3-264 seems invalid, so can't look up anything)

**Comment by peterhashair** [comment]
@sgiehl This happens when you tracking a site has login function, before login and after login are record as 2 different visits under `visits log`, and have those config set up in the tracking code. Then I revert this PR [`e0417845f8fd7031e00e97c3576415c998abb2ce`](https://github.com/matomo-org/matomo/pull/17636) it start to work. 
```javascript    
 _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          _paq.push(['setSecureCookie', true]);
          _paq.push(['setUserId',null]);
          _paq.push(["setCookieDomain", "*.test"]);
          _paq.push(["setDomains", "*.test"]);
          _paq.push(["requireCookieConsent"]);
          ```

**Comment by sgiehl** [comment]
@peterhashair What exactly happens in that case? You now described a certain tracking use case and which problem your changes might aim to fix, but not which problem in the PHP code it tries to solve.

Based on the changes in the PR, there must have been some sort of warning / error / notice in PHP (like an undefined index).
In order to say if your fix actually solves any issue it would be good to know the exact PHP error and the stack trace, so it's possible to check if maybe reading the config in the first place might be done incorrectly.

**Comment by sgiehl** [comment]
@peterhashair could you answer my questions from the previous comment?

**Comment by peterhashair** [comment]
@sgiehl sorry, I believe this PR is not valid anymore, but the problem was I can remember the code below keeps returning true. 
```php
        if (TrackerConfig::getConfigValue('enable_userid_overwrites_visitorid', $this->getIdSiteIfExists())) {
```

**Comment by sgiehl** [comment]
> @sgiehl sorry, I believe this PR is not valid anymore, but the problem was I can remember the code below keeps returning true.
> 
> ```
>         if (TrackerConfig::getConfigValue('enable_userid_overwrites_visitorid', $this->getIdSiteIfExists())) {
> ```

The default value is `true`, so this is expected, unless someone changes the value in his config. 🤷

**Comment by sgiehl** [comment]
I'll merge this one now. Even though it does not have anything to do with the referenced issue, it could under certain circumstances avoid possible notices. e.g. when accessing a tracker config value that doesn't exist.

**Pull request merged**
