### PR TITLE
Use explicit timeout when rendering evolution graphs

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Refs DEV-17230.

This should be seen as a temporary workaround before a proper fix is implemented. Local testing showed that 100ms may not be enough and the graph still doesn't render, 250ms worked reliably in cases where the markup for the card was returned instantly (via temporary hardcoding in index.php).

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — DISMISSED** [review]
This works in testing for me :+1:

Any ideas what a non-temporary fix would look like?

**Comment by michalkleiner** [comment]
@bx80 I guess the proper way how this is meant to work is to render the graph as soon as the card is visible, so using an intersection observer based event as the trigger for jqplot to render the graph.

**Comment by sgiehl** [comment]
Maybe that javascript method call shouldn't be part of the rendered datatable response, but more part of the javascript that tries to load and render a certain datatable. Or maybe we would need to have some vue-entry instead and a component to call that method. This might then maybe be already be picked up automatically.

**Comment by michalkleiner** [comment]
Yeah, there could be any number of ways this can be improved, at the moment this is just a stop-gap solution for the immediate issue at hand. We can create a follow up enhancement ticket when/before this is merged.

**Comment by sgiehl** [comment]
The "problem" with this solution is, that you need to go through all UI tests that are displaying a datatable and add a manual waiting time of 250ms to ensure they run correctly again. This will increase the time the tests run...
Currently there are a lot of them failing, so we can't merge this anyway. Looking for a proper solution might in the end maybe even take less time than fixing the tests.
To be honest @michalkleiner you shouldn't put a PR with that many failing UI tests into review. And @bx80 you shouldn't approve something like that.

**Comment by michalkleiner** [comment]
You're right @sgiehl. I must admit I didn't look at the UI tests before I added the Needs review label and to be frank I also don't trust the UI tests anymore, they are failing in one way or another most of the times so I assumed it was the same scenario.

**Comment by tsteur** [comment]
FYI in case it helps, this is on sandbox staging. The issue still happens for me like 50% of the time or so.

FYI The Media Analytics plugin defines what we call "Middleware parameters" to decide on demand if the report should be shown or not.

This is done in `plugins/MediaAnalytics/Reports/Get.php`
image

I would assume there's an issue around this with below code and the race condition.
image

It would then also mean the issue is only for reports with middleware parameters which means the issue wouldn't be for all evolution graphs which is good.

**Pull request closed without merging**
