### PR TITLE
Support configuration of a reader database

### LINKED ISSUE #7554: Add auxiliary database support for big instances
Goal of this ticket is to discuss and hopefully implement solution allowing single Piwik instance to query two replicant databases.

Outline of issue:
- big Piwik instances often have master-slave db replication,
- currently only use (in our case) of slave servers is to perform db backups, and in emergency cases to switch into master to provide HA

However slave servers could be put to much better use if we can redirect archiving queries onto slave db.
Long running and heavy queries could be triggered against slave, then results processed in PHP and write archives to master server.
This would significantly relieve tracker, take away some other problems with db performance when traffic peak meets long running archiving.

For initial scope, maybe only select queries triggered by LogAggregator could be launched against auxiliary db server, and in future we add option for developers to decide which db to use.
Even putting basic LogAggregator queries into slave would give significant boost to performance.

What do you think?

### PR DESCRIPTION
**Pull request by tsteur**
If configured, most archiving, live, and archive reading queries (when browser archiving is disabled) will be read from a reader instead of the master. This means mainly the tracker will hit the master database and when writing archives.

FYI added a system check that connection works if a reader is configured.

fix https://github.com/matomo-org/matomo/issues/7554

### CODE REVIEW

**Comment by tsteur** [comment]
@mattab @sgiehl @diosmosis could you have a quick look at this? Any thoughts? 

Tested it locally and worked quite well. Also adjusted all our premium features to use `LogAggregator::getDb()` and `VisitorDetailsAbstract::getDb() // in a BC way`  so in the future the core can easily decide/control whether to use slave or master etc. 

Once I get the OK will give it a test on a different Matomo.

**Comment by mattab** [comment]
Didn't look at the code in details but the idea sounds great! Many users will have slave databases running doing nothing and this is a great way to leverage this valuable CPU. 

 Just wondering, what happens if the reader goes down, would it maybe help to full back to master automatically or is it better to fail explicitly?

**Comment by tsteur** [comment]
For now it would just fail. Would otherwise need a lot of extra code etc. It's just to get a quick win. Later you can at some point do a lot more with it.

**Comment by tsteur** [comment]
Maybe we could merge this feature already? Considering it will use regular DB if no reader is defined it shouldn't change anything. Can also patch this later though.

**Comment by diosmosis** [comment]
Code looks good to me, seems ok to merge to me

**Pull request merged**
