### PR TITLE
[WIP] New flag icons

### PR DESCRIPTION
**Pull request by Findus23**
#11155

I have probably missed some places, where the icons are used:
#### checked:
- Visitors -> Locations
- Real Time Map popup
- Visitor Log
- Visitors in Real-time
- PDF Report
- HTML Report
- Visitor Log in Piwik App
  - unfortunately the app is caching the images, even if the account is deleted and readded.
  - but on my phone some of the new flags were loaded and displayed correctly

#### TODO
Goal Overview: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22170/UIIntegrationTest_goals_individual_goal_updated.png

How can I modify the metadata?
https://github.com/piwik/piwik/blob/3.x-dev/plugins/Goals/templates/_listTopDimension.twig#L10

#### New Unknown Flag:

xx 1

#### TI
```
1) Piwik\Plugins\UserCountry\tests\Unit\UserCountryTest::testFlagsAndContinents
Failed asserting that an array contains 'ti.png'.
```
There is no country with the languagecode ti in https://dev.maxmind.com/geoip/legacy/codes/iso3166/
It seems to be the **NATO** code for Tajikistan, but the ISO Code is TJ (https://en.wikipedia.org/wiki/ISO_3166-2:TJ), where the icon can be found.

### CODE REVIEW

**Comment by sgiehl** [comment]
@Findus23  `TI` is used for Tibet. See https://github.com/piwik/piwik/blob/3.x-dev/core/Intl/Data/Resources/countries.php#L240

**Comment by Findus23** [comment]
@sgiehl That makes sense. As I assume flag-icon-css won't add them (see their issue 215), I've added it similar to the unknown flag.

**Comment by mattab** [comment]
One challenge of the new flags is that the white is not visible on a white background. For example French/Russia/Poland flags have some white which looks like the flag is out of shape when displayed on white background. See for example in: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22326/processed/UIIntegrationTest_ecommerce_log.png

compared to previous flags which had some shadow set (in http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22326/UIIntegrationTest_ecommerce_log.png )


Maybe we could find a solution to this visual challenge?

**Comment by Findus23** [comment]
Maybe a thin border (similar to http://flag-icon-css.lip.is/game/capital/) helps?
screenshot_20170220_103939
I'm not completely sure if looks good.

**Comment by mattab** [comment]
It's already better IMHO - but maybe someone has an even better idea :sunglasses:

**Comment by mattab** [comment]
Feedback

* there is a unit test failing `1) Piwik\Plugins\UserCountry\tests\Unit\UserCountryTest::testFlagsAndContinents Failed asserting that an array contains 'ac.png'.` -> might be good to not delete any flags, as I think they could all be used somehow... good we have this test to check this :) 
* re: failing system tests. What was the reason of removing the flags logoHeight/logoWidth in metadata? would be good to leave them there as it helps API consumer displaye flags with the right sizes. If the new way is to only set the logoHeight to 16px then we could only set the logoHeight metadata and only remove the logoWidth. If possible to also set logoWidth, would be nice to have but not needed.
 * I think when restoring this metadata it should also fix the issue in the Goals > Overview report currently showing large flags
* in `plugins/Live/templates/getVisitorProfilePopup.twig` one of the changes is a regression (aka 'merge fail'). it is the part with `<div class="visitor-profile-lifetimevalue">` should still be there. it was introduced in #11294 
* in the visitor log seems the flags are bottom aligned currently, would be nice to vertical-align the flags. visible in the USA flags at the bottom of http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22369/UIIntegrationTest_widgetize_ecommercelog.png
* similarly would be nice if possible to middle align the flags in the visitor profile as can be seen here they are bottom aligned http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22369/UIIntegrationTest_visitor_profile_popup.png
*  :+1: to  add a grey border for now, or some other kind of nice looking shadow
* for the unknown flag, maybe we could have a simpler looking unknown flag. ie. a question mark only without grey bars would look better / simpler. Grey bars are a bit unappealing and attract attention

Very much looking forward to this!

**Comment by Findus23** [comment]
>there is a unit test failing 1) Piwik\Plugins\UserCountry\tests\Unit\UserCountryTest::testFlagsAndContinents Failed asserting that an array contains 'ac.png'. -> might be good to not delete any flags, as I think they could all be used somehow... good we have this test to check this :)

I'm not sure. e.g. *ac* doesn't exist as a country code in [maxminds list](https://dev.maxmind.com/geoip/legacy/codes/iso3166/), [Wikipedia](https://en.wikipedia.org/wiki/Ascension_Island) (it would be [SH-AC](https://en.wikipedia.org/wiki/ISO_3166-2:SH)) nor in the [piwik API](https://github.com/piwik/piwik/pull/11376/files#diff-0ef453532895d8511dc00a731aa4f9b3).
And the [currrent icon](https://github.com/piwik/piwik/blob/3.x-dev/plugins/UserCountry/images/flags/ac.png) just shows the british flag, not the [Flag of Ascension Island](https://en.wikipedia.org/wiki/Flag_of_Ascension_Island).

In my opinion we shouldn't include them. (In the worst case they would fallback to the unknown flag)

> re: failing system tests. What was the reason of removing the flags logoHeight/logoWidth in metadata? would be good to leave them there as it helps API consumer displaye flags with the right sizes. If the new way is to only set the logoHeight to 16px then we could only set the logoHeight metadata and only remove the logoWidth. If possible to also set logoWidth, would be nice to have but not needed.

The reason is that the icons are (displayed) 16px high but 21.333333px wide.
If it works to only remove the logoWidth, I'll do it.

> I think when restoring this metadata it should also fix the issue in the Goals > Overview report currently showing large flags

I'll test it.

> in plugins/Live/templates/getVisitorProfilePopup.twig one of the changes is a regression (aka 'merge fail'). it is the part with <div class="visitor-profile-lifetimevalue"> should still be there. it was introduced in #11294

Looks like I quite messed up that merge, but it seems like  https://github.com/piwik/piwik/pull/11272/commits/1cf3d5b10e6b68f2acb00d5e591a15da2d346605 fixes it.

to be continued... (I'll write the rest later)

**Comment by Findus23** [comment]
> in the visitor log seems the flags are bottom aligned currently, would be nice to vertical-align the flags. visible in the USA flags at the bottom of http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22369/UIIntegrationTest_widgetize_ecommercelog.png
similarly would be nice if possible to middle align the flags in the visitor profile as can be seen here they are bottom aligned http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22369/UIIntegrationTest_visitor_profile_popup.png

I seem to fail to center them as the `.visitorLogIconWithDetails` span doesn't seem to have the same size as the icon.
screenshot_20170221_133225

**Comment by mattab** [comment]
the `ac` etc. comes from this file: https://github.com/piwik/piwik/blob/e8602f5d81a2f402c80b11ffcfa391cdff238e08/core/Intl/Data/Resources/countries-extra.php#L9-9

Not really sure if we really need a flag for those. But we need to get the test to pass which currently requires a .png icon for each of those... maybe easier for now to put the "unknown" flag for each of those?

>  I seem to fail to center them as the .visitorLogIconWithDetails span doesn't seem to have the same size as the icon.

It looks more centered now in your screenshot, maybe sufficient?

**Comment by Findus23** [comment]
I have now added all missing flags: https://github.com/piwik/piwik-icons/commit/5167dc5724535a3cbaa08389825e421f1b7e256b

BTW: Maybe we should wait for #11383 before merging and then modify this pull request to also use the submodule.

**Comment by mattab** [comment]
@Findus23 well done, this is a wonderful improvement.


Only remaining feedback:

* Could you fix the system tests so they all pass? (except CustomDimensions or other marketplace plugins ones, i'll fix them after merge as it's a bit annoying with the submodules)
* For the failing integration test, either 1) put the correct flag in Piwik  or 2) add an exception for ac.png in this test -> so the test passes

We will fix the UI tests after merge. Can't wait to merge this :+1:

**Comment by Findus23** [comment]
I have already fixed the missing flags in https://github.com/piwik/piwik-icons/commit/5167dc5724535a3cbaa08389825e421f1b7e256b

When  #11383 is merged, I'll need to completely rework this to use the new path (and remove the icons from the pull request).

**Comment by mattab** [comment]
As the submodule to https://github.com/piwik/piwik-icons has been added into Piwik we can now proceed with the beautiful flag icons :+1:

**Comment by Findus23** [comment]
Closing in favor of #11553

**Pull request closed without merging**
