### PR TITLE
Add "Skip to content" feature when user presses tab key (accessibility)

### PR DESCRIPTION
**Pull request by flodrwho**
- item 1 #7004
  this adds a link in the head which only appears when tabed over, this sends the user down the page to the main content where another corresponding link is. then is changed the css so it would be off screen when not focused on. and it will be the first thing focused on when the tab key is pressed.

### CODE REVIEW

**Comment by mattab** [comment]
Also:
* Blue color was set darker for more contrast
* Alt text was added to graph to explain they are graph

**Comment by mattab** [comment]
Great changes, thanks @flodrwho ! :+1:

**Comment by jdeyla** [comment]
Hi,
I'm testing on demo site: https://demo.piwik.org

SKIP CONTENT link is quite good buta has some rproblems, when using just the keyboard (text appears but under the menù)
I suggest to use the same approach of http://webaim.org/ (just TAB on keyboard)

I also suggest to use their script in order to highlight text or link or buttons, which is another problem Piwik has.

**Comment by mnapoli** [comment]
@jdeyla I don't understand what the problem is? To me it works perfectly fine on the demo, just like the site you linked.

**Comment by mattab** [comment]
> I also suggest to use their script in order to highlight text or link or buttons, which is another problem Piwik has.

Hi there, could you create an issue for this problem and maybe show a screenshot showing the problem?

**Comment by jdeyla** [comment]
Hi I didn't create an issue beacuse this issue was the right one in my opinion. I attach a screenshot taken with Firefox 36.0.1 Win XP, tabbing on skip content link
piwik1

**Comment by mattab** [comment]
Hi @jdeyla thanks for report. tracked in #7451

**Pull request merged**
