### PR TITLE
Log segments that are being archived

### LINKED ISSUE #7536: Log which segments are currently being archived
The goal of this issue is to do a small improvement the core:archive log, 

Currently the core:archive output looks like: `Will pre-process for website id = 2, range period, the following 10 segments: { pageUrl!=xx, segment2here, segment3here, segment4here, .... } `

the log line can get very long.... 
The idea would be to have an output like this:

```
Will pre-process for website id = 2, range period, 10 segments
Starting processing for website id = 2, range period, of these 3 Segments { pageUrl!=xx, segment2here, segment3here  } [1 / 4]
Starting processing for website id = 2, range period, of these 3 Segments { segment4here, ..., ...  } [2 / 4]
Starting processing for website id = 2, range period, of these 1 Segments { segment10here  } [4 / 4]
[...]
```

Note: by default 3 segments will be triggered at once (`--concurrent-requests-per-website=3`). if a website has eg. 100 segments, it would issue 34 requests or so. This simple log statement change will really improve the experience to Piwik administrators!

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7536

Example:

```
INFO CoreConsole[2015-04-16 23:22:25] Starting Piwik reports archiving...
INFO CoreConsole[2015-04-16 23:22:25] Will pre-process for website id = 1, day period, 2 segments
INFO CoreConsole[2015-04-16 23:22:25] - pre-processing all visits
INFO CoreConsole[2015-04-16 23:22:25] - pre-processing segment entryPageTitle=@Web%20Analytics
INFO CoreConsole[2015-04-16 23:22:26] - pre-processing segment pageTitle=@Piwik
INFO CoreConsole[2015-04-16 23:22:26] Archived website id = 1, period = day, 6 visits in last last2 days, 0 visits today, Time elapsed: 1.380s
INFO CoreConsole[2015-04-16 23:22:26] Will pre-process for website id = 1, week period, 2 segments
INFO CoreConsole[2015-04-16 23:22:26] - pre-processing all visits
INFO CoreConsole[2015-04-16 23:22:26] - pre-processing segment entryPageTitle=@Web%20Analytics
INFO CoreConsole[2015-04-16 23:22:26] - pre-processing segment pageTitle=@Piwik
INFO CoreConsole[2015-04-16 23:22:36] Archived website id = 1, period = week, 459 visits in last last3 weeks, 301 visits this week, Time elapsed: 9.440s
```

### CODE REVIEW

**Comment by diosmosis** [comment]
Can you add a unit/integration test? Maybe to CliMultiTest.

**Comment by diosmosis** [comment]
Also could add an assertion for the output in ArchiveCronTest, not sure how important that is.

**Comment by mattab** [comment]
a subtle but big improvement to humans consuming the log!

Here is suggestion to improve output when there are 200 segments: 

 * display the progress of segments eg. from:

`INFO CoreConsole[2015-04-16 23:22:26] - pre-processing segment pageTitle=@Piwik` 

to 

`INFO CoreConsole[2015-04-16 23:22:26] - pre-processing segment pageTitle=@Piwik [2/200 segments done]` (if there was 200 segments)

**Comment by mattab** [comment]
> Also could add an assertion for the output in ArchiveCronTest, not sure how important that is.

+1 testing for the `core:archive` output has a lot of value, regression these nice logging messages could have large impact on piwik admins

**Comment by mnapoli** [comment]
I rebased on master and pushed tests for CliMulti + the cron archive output. FYI the cron archive output test takes ~ a minute (I created 1 website + 1 segment, I didn't add any visits).

**Comment by mattab** [comment]
+1 - it's a real good feeling to see new tests for `core:archive` output :)

**Comment by diosmosis** [comment]
Looks good to me, I think the tests can be sped up later so if the build passes, I will merge.

**Comment by mattab** [comment]
Btw the test could be made faster by appending to the command `--force-periods=day` which will cause archiving to only process the day (should make it maybe 3-4 times faster) - feel free to make the change after the merge if you want...

**Pull request merged**
