### PR TITLE
Fixes Segmented Visitor Log with segments containing spaces

### LINKED ISSUE #13113: Segmented Visitor Log does not have data with Page Title containing whitespace (URL contains +)
hello,
We are using Matomo since a few weeks and we are facing this : 
- Go to Behaviour | Pages
- Then we have the list of the visited pages
- When we want to open the segmented Visitor Log then we have no data in the log if the page title contains whitespace (or the URL contains + character)
For instance : 
* with this url we don't have data in Visit Log : https://erswiki.analytics.moodys.net/display/DRI1UG/.About+This+Document+v1.0
* with this url we DO have Visit Log : 
https://erswiki.analytics.moodys.net/pages/viewpage.action?pageId=215918735

URL are managed by Atlassian Confluence and we have maybe 90% of URL based on + character. So we have this issue for a huge amount of pages. Did we miss something in the Matomo configuration ?
image

Thanks
Emmanuel

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #13113

### CODE REVIEW

**Comment by diosmosis** [comment]
Shouldn't the parameter be encoded automatically in ajax requests? Seems like this would double encode it (which should work because matomo handles it specifically, but it seems like a fix that could cause problems later). Maybe we should be urlencoding the values that can have spaces when adding the segment label?

**Comment by fdellwing** [comment]
Left a comment at #13113

**Comment by mattab** [comment]
@sgiehl do you maybe have an idea about how to fix https://github.com/matomo-org/matomo/issues/11806 which is similar?

**Comment by mattab** [comment]
> Shouldn't the parameter be encoded automatically in ajax requests? 

Yes, but then i see this code:

```

        // we took care of encoding &segment properly already, so we don't use $.param for it ($.param URL encodes the values)
        if(parameters['segment']) {
            url += 'segment=' + parameters['segment'] + '&';
            delete parameters['segment'];
        }
```
so the segment parameter is a special case/hack and not URL encoded as it's assumed by our Ajax helper that the value is already properly URL encoded. so URL encoding it manually as done in this PR is needed it seems...

**Comment by eetasse** [comment]
hi guys, I have updated to 3.6 version a few weeks ago and I still experience this issue with URLs containing whitespaces. This is not clear if this PR is in 3.6 ? If does it supposed to fix the issue ?
The Confluence URLs sent to Matomo contains initialy + (PLUS) chars. These chars are substituted with whitespaces later in Matomo. I did a very dirty workaround on the tracking client side javascript in replacing the PLUS chars with UNDERSCORE : then I am able to see the Visit Log but Confluence does not follow obviously the altered URLs. Any idea to workaround else ? Very thanks

**Comment by mattab** [comment]
It's supposed to work, please can you create new a issue? @eetasse

**Comment by fdellwing** [comment]
See:  #13460

**Pull request merged**
