### PR TITLE
Add system check for the hash() function

### LINKED ISSUE #11449: Add system check for the hash() php function
Error reported by email:

> Fatal error: Call to undefined function hash() in ....../vendor/twig/twig/lib/Twig/Environment.php on line 331

To prevent this error let's add a system check for the hash() function.

`hash()` is enabled by default in PHP but it can be disabled when php is compiled with `--disable-hash`.

### PR DESCRIPTION
**Pull request by dbrock98**
Check during install if the hash() function exists in PHP. While enabled by default, it is possible to exclude this function at compile time by passing --disable-hash to configure. Fixes #11449.

### CODE REVIEW

**Comment by okay19** [comment]
Looks like the CI failed because of the screenshot test. Should I change anything in the PR to fix/reflect that?

**Comment by sgiehl** [comment]
You can update the expected UI test files by using the processed one from travis: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22539/processed/Installation_system_check.png
That should fix the tests.

**Comment by sgiehl** [comment]
@okay19 seems the screenshot is now no longer stored on GitLFS. Are you able to change that? If not maybe remove the commit again and I will update that afterwards

**Comment by okay19** [comment]
@sgiehl Done. I haven't used Git LFS before, so I had to do a little research.

**Comment by sgiehl** [comment]
awesome. Thanks for the update. Now all tests are passing :+1:

**Comment by mattab** [comment]
Thanks @okay19 for your contributions recently! Would be awesome if you want to contribute more :+1:

**Pull request merged**
