### PR TITLE
add file:// protocal exclude option in tracker

### LINKED ISSUE #17017: JS tracker should not track anything when the protocol is file:// to avoid tracking personal data by accident
Use case:

Someone downloads a page from your website and stores it locally. Then the user opens it and the user will be tracked and the URL might look like

```
file:///C:/Users/myname/AppData/Local/...
```

This way we actually track personal data potentially by accident without knowing.

* We would always exclude page urls with this protocol by default
* There should be a method to opt out of this feature so you can track these requests if needed. 
* We create an FAQ to document this behaviour / feature.

As this could be seen as a BC break we need to maybe wait for Matomo 5 for this and/or clearly announce this and warn users of this change.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #17017 
add file:// protocol exclude option in the tracker

add `_paq.push(['enableFileTracking']);` will start track protocal `file:`

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
Not too sure if we can write a test for that feature, to change window.location.protocal maybe a problem.

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
@sgiehl just checking, if that is the right solution.

**Comment by peterhashair** [comment]
build js

**Comment by sgiehl** [comment]
@peterhashair what should your PR provide? Currently it adds a config option, that can be changed. But the option is not having any effect, so it's kind of useless 🤔

**Comment by peterhashair** [comment]
@sgiehl I thought this would escape the tracking. 

```javascript

                if (!configFileTracking && windowAlias.location.protocol === 'file:') {
                    configDoNotTrack = true;
                }
```

**Comment by sgiehl** [comment]
> @sgiehl I thought this would escape the tracking. 
> 
> ```javascript
> 
>                 if (!configFileTracking && windowAlias.location.protocol === 'file:') {
>                     configDoNotTrack = true;
>                 }
> ```

Isn't that variable responsible for something completely different? Didn't have look right now, but iirc that should be the config flag responsible for checking "do-not-track" headers in the browser.

**Comment by peterhashair** [comment]
build js

**Review by Findus23 — CHANGES_REQUESTED** [review]
Just so we don't forget: Once this feature is finished, we need to mention it as a breaking change in the CHANGELOG.md.
As this would at least stop the tracking of one of my sites by default. (correction: I just remembered that it doesn't use file:// URLs anymore)

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
build js

**Review by bx80 — APPROVED** [review]
Tested with locally saved html file that loads the Matomo tracking code via https, by default no tracking requests are sent. With the new `enableFileTracking` config setting enabled the tracking requests are sent :+1:

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] n/a [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] None [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] n/a [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] n/a [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] n/a Existing documentation updated if needed

**Comment by justinvelluppillai** [comment]
@peterhashair did you see/action @Findus23 comment re updating the changelog with this?

**Comment by peterhashair** [comment]
@justinvelluppillai will update changelog shortly

**Pull request merged**
