### PR TITLE
GPLv3: Replace line end characters from CRLF to LF

### PR DESCRIPTION
**Pull request by stweil**
Ending lines with CRLF is only useful for pure Windows files.

Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by mattab** [comment]
@stweil could you maybe apply this to all other files that don't have proper line endings?

**Comment by stweil** [comment]
The remaining ones with CRLF belong to pChart. If you want, I can sent a pull request for those files as well (also against branch [3.x-dev](https://github.com/piwik/piwik/tree/3.x-dev)?).

**Comment by mattab** [comment]
Yes would be great thanks. We also need to add a test to releasechecklist
test file to prevent committing files with cord in the future. If you want
to do this as well, would be great

Matthieu

**Comment by stweil** [comment]
The pChart files are fixed by PR #10591. I'll have a look at the test needed for continuous integration later (probably not this week).

**Pull request merged**
