### PR TITLE
Fix failing UI tests

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Due to various code changes (like #17937, #17879) UI tests are currently failing. This PR aims to fix them again.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Note: I've introduced a new method `page.waitForLazyImages()`, which removes the loading attribute from all images and then waits for all images to load. Otherwise we can't ensure in some UI tests which images would be loaded or not.

**Review by tsteur — COMMENTED** [review]
Does it make sense to call this automatically as part of

* `this.waitForNetworkIdle() `
* `this.webpage.on('load', () => {`  (I know those ones are only loaded later but if it might still be good just in case we use it more in the future)
* maybe also in `this.webpage.on('requestfinished'`

Then developers maybe won't need to think about this as it can be tricky to find out etc

**Review by justinvelluppillai — APPROVED** [review]
Nice one.

**Comment by justinvelluppillai** [comment]
@sgiehl sorry maybe jumped the gun merging there didn't notice @tsteur 's suggestion. Can create a new PR if we want to implement those suggestions also.

**Comment by sgiehl** [comment]
@tsteur will check if that works and create a new PR if so

**Pull request merged**
