### PR TITLE
Add tracking spam prevention plugin as a submodule

### PR DESCRIPTION
**Pull request by tsteur**
### Description:

See https://github.com/matomo-org/plugin-TrackingSpamPrevention for the features that were added.

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@diosmosis @sgiehl I suppose it is normal that we run all the UI tests of a plugin with a submodule again? Like in https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/44659/ 
image

**Comment by diosmosis** [comment]
@tsteur I think it's because we consider the plugins bundled w/ core to be tested this often (testing compatibility on every matomo change). Otherwise the tests would only run when the plugin changes, even though a change in core could cause problems.

**Comment by sgiehl** [comment]
Remaining test failures seem unrelated. Btw @tsteur did we decide if this plugin will be shipped with Matomo or if it will be available through Marketplace? We might need to adjust the build script maybe 🤔

**Comment by tsteur** [comment]
@sgiehl it should be not included in core but instead it is already on the marketplace. Do we need to adjust anything?

**Pull request merged**
