### PR TITLE
Faster unit testing

### PR DESCRIPTION
**Pull request by szepeviktor**
The purpose of this Pr is to measure long-running unit tests.

phpunit-speedtrap needs phpunit 7

### CODE REVIEW

**Comment by szepeviktor** [comment]
Ancient PHP version prevent using modern tools 😢

**Comment by Findus23** [comment]
@szepeviktor Indeed, but as 5.6 is still supported by PHP  and a lot of people are still using it, it probably won't change soon.

https://demo-anonymous.matomo.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?idSite=1&period=year&date=today&category=General_Visitors&subcategory=CustomVariables_CustomVariables

**Comment by Findus23** [comment]
@szepeviktor 
BTW, the file you are editing gets automatically generated by this software project, so you might want to propose your changes there:

https://github.com/matomo-org/travis-scripts

**Comment by szepeviktor** [comment]
> Class 'PHPUnit_Framework_TestCase' not found
There must have been an APi change in phpunit.

I am not god at projects for the masses on shared hosting.
Sorry.

**Comment by sgiehl** [comment]
> Class 'PHPUnit_Framework_TestCase' not found

phpunit uses namespacse instead of those class names in newer versions

**Comment by szepeviktor** [comment]
Trying out an ancient version

**Pull request closed without merging**
