### PR TITLE
Website responsive fixes #7031

### LINKED ISSUE #7031: Slow report website and dashboard in Piwik 2.10.0
Hi,

I'm using Piwik 2.10.0 and experiencing slow website response of about 1+ minute for 6+ million records in monthly archive table. I trace it down to the daily archive blob being update/invalidate every time the UI try to read from archive. 

Background
==========
- My Piwik instance track 8 Sites with about ~100K visits per day across all sites.
- My original setup was 2ecu + 2gb VPS, but it was unbearably slow.  I have since throw a ton of hardware at it and done a lot of optimization.  The current setup is:
- pi.mysite.com: 8cpu + 8gb of ram to handle tracking from client
- report.mysite.com: 10cpu + 10gb of ram + 100GB RAID10 for MySQL and cron archiving

Most of the time, CPU on report.mysite.com is only at 10% and memory at 60%.   High memory usage is the result of TokuDB engine my MySQL setup.

With such beefy setup, I still get timeouts with cron archive and website even though my CPU and Memory usage stay the same.  I'm almost at the point of giving up, but then I notice a pattern.  It usually happen toward the end of the month and at the end of the day.

Debug
======
As it is reproducible, I did some SQL troubleshooting and identify that the issue has to do with the SQL executed from this module:
https://github.com/noogen/piwik/blob/master/core/DataAccess/Model.php - line 75: updateArchiveAsInvalidated

Issue was identified that the website always call the "get" method of report archiving causing slow UI response.  Somehow, this SQL cause a full table read resulting in 1 second for every 1 million record in the monthly archive table.  I move this invalidation in "Archive.php" from "get" method to "prepareArchive" method.  This allow the cron job to continue to work while reducing the issue in the UI.

I have also prepared a pull request.  The change is simple but please review because I do not know the inner working of Piwik as I am not a regular Piwik Developer.

### PR DESCRIPTION
**Pull request by noogen**

### CODE REVIEW

**Comment by mattab** [comment]
maybe something for @tsteur ?
refs #7031

**Comment by tsteur** [comment]
Not so much into that anymore. If all tests still work than it should be okay probably

**Comment by tsteur** [comment]
Had a look at the code for a while and it might actually work. There seems to be definitely an issue as it should invalidate archives when it is not allowed to archive... so either this fix seems or alternatively replace the current line in `get` with

```
if (!Rules::isArchivingDisabledFor($this->params->getIdSites(), $this->params->getSegment(), $this->getPeriodLabel())) {
    $this->invalidatedReportsIfNeeded();
}
```

**Comment by tsteur** [comment]
I tested the code change for quite a while and it seemed to work but tests were failing in an edge case. Therefore calling this method a bit earlier: https://github.com/piwik/piwik/commit/4df10df9be84928daee184f7768bf1902298896b 

The edge case is if there are recorded actions/visits before the website creation date. We would not correctly invalidate such archives as we get the website creation date here: https://github.com/piwik/piwik/blob/2.11.0-b3/core/Archive.php#L667-L672 but the archives are invalidated here: https://github.com/piwik/piwik/blob/2.11.0-b3/core/Archive.php#L685 . The invalidate archive causes the site creation to change under circumstances but the creation date was accessed earlier in the previous link.

If reports are still slow with the committed change we need to ignore this edge case maybe.

**Pull request closed without merging**
