### PR TITLE
Add support for hash URLs in campaign param removal, update list of params to strip

### PR DESCRIPTION
**Pull request by caddoo**
### Description:

Previously the `disableCampaignParameters` feature didn't take into account # campaign parameters in the URL, now it does.

Also the list of campaign parameters to strip wasn't extensive, now it strips a larger predefined list as well as any custom ones set by the client.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
I had some more thoughts around that topic. With the current implementation I think it does not have any sense to have the `enableCampaignParameters` method at all. It might actually only cause unexpected behavior, as enabling them after a first requests was already sent, might cause ongoing requests to create a new visit if the campaign parameters are still present.

If we want to provide the possibility to update the referrer once consent for it was provided, we might need a more complex solution to send and correctly update that in the backend.

**Comment by caddoo** [comment]
> I had some more thoughts around that topic. With the current implementation I think it does not have any sense to have the `enableCampaignParameters` method at all. It might actually only cause unexpected behavior, as enabling them after a first requests was already sent, might cause ongoing requests to create a new visit if the campaign parameters are still present.
> 
> If we want to provide the possibility to update the referrer once consent for it was provided, we might need a more complex solution to send and correctly update that in the backend.

Yeah I think you're right, I don't see the use-case being there right now either, I've removed it along with the tests.

**Comment by michalkleiner** [comment]
Code changes look good, there's one too many JS assertion somewhere (the JS tests failure seems related).

**Review by sgiehl — APPROVED** [review]
I've fixed the JS tests and updated UI test screenshots. For me everything looks good to merge now.

**Review by michalkleiner — APPROVED** [review]

**Pull request merged**
