### PR TITLE
Adding some metrics requested by customers

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Customers have been requesting some metrics be made available in CustomReports, so this PR is trying to add some of those.

Metrics being added:
- Average product quantity 
- Average product price
- Product Revenue (Total & avg)
- Total click outlinks 
- Product Category (Dimension) 
- Total content interactions (Entries with Content Interaction)
- Content interaction rate

Internal ticket: PG-3658

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by snake14** [comment]
Converting to draft because it looks like my latest commit broke some tests.

**Comment by sgiehl** [comment]
@snake14 In general it would be good to split up the PR into one PR per metric you want to add and where possible add a test for it. That makes it easier to review and merge it step by step.

Note: Time on page won't work that way, as that metric isn't tacked as a normal dimension. Instead it also stores the id of the previous action the stored time is actually valid for. This can't be achieved with a SQL query.

**Comment by snake14** [comment]
> @snake14 In general it would be good to split up the PR into one PR per metric you want to add and where possible add a test for it. That makes it easier to review and merge it step by step.
> 
> Note: Time on page won't work that way, as that metric isn't tacked as a normal dimension. Instead it also stores the id of the previous action the stored time is actually valid for. This can't be achieved with a SQL query.

Thank you @sgiehl . I'll remove the time on page metrics. I've been using my CustomReports PR to test most of the metrics.

**Comment by snake14** [comment]
@sgiehl I'm not finding any good examples of testing new metrics in this repo. Could you please point me in the right direction? Do I mock a new report or something?

**Comment by snake14** [comment]
Closing in favour of https://github.com/innocraft/plugin-CustomReports/pull/240

**Pull request closed without merging**
