### PR TITLE
Handle failed promise by silently ignoring it

### LINKED ISSUE #17454: JS Tracking code may generate "The operation is insecure" warnings with specific Firefox settings
This bug is just a follow up to a already known bug, but i decided to start a new issue here as the others are marked as resolved or have been merged.

References: 
* https://forum.matomo.org/t/firefox-84-promiseerror-securityerror-the-operation-is-insecure/40299/8
* https://github.com/matomo-org/matomo/pull/17139
* https://github.com/matomo-org/matomo/issues/17136

Ok, i can now reproduce this bug with `4.2.1` in Firefox `87.0` on windows. It is still present and still causes errors in our JS error logs. It depends on some specific firefox strict security settings.

Following example:
* Open any site you want with Firefox
* Open F12 console
* Enter and execute this: `console.log(navigator.serviceWorker && navigator.serviceWorker.ready)`
* Error occurs

The console command is basically the same as used in matomo here
https://github.com/matomo-org/matomo/blob/4.x-dev/js/piwik.js#L6989

Demo:
firefox-bug

Settings:
image

### PR DESCRIPTION
**Pull request by justinvelluppillai**
### Description:

fixes #17454 

The setting in firefox to delete cookies when firefox closes causes navigator.serviceWorker.ready to fail and firefox gives the operation is insecure error. This change silences the error by handling the rejected promise with the second argument to the .then() function.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
minify js

**Comment by tsteur** [comment]
build js

**Comment by justinvelluppillai** [comment]
build js

**Comment by justinvelluppillai** [comment]
To test this open a page with matomo tracking js on it, go offline then back online again (eg turn wifi off/on) and without this change you will see a console error, with this change you shouldn't.

**Comment by diosmosis** [comment]
Looks good :+1:

**Pull request merged**
