### PR TITLE
Migrate user-permissions-edit component to vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off of #18566.**

Changes:
* Migrate user permissions edit component.
* Allow returning jquery request handle from AjaxHelper.

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — COMMENTED** [review]
overall looks good to me, just one thing, not sure we need to fix it, when saving details after the password confirm modal appears, the autofill password plugin will change the email field in the background to an auto-filled username, which will lead to an error. 

Maybe the confirm popup appears in background fields should be read-only to prevent auto-fill.

**Comment by diosmosis** [comment]
@peterhashair by "autofill password plugin" do you mean a matomo plugin or a browser extension? Can you provide a link to it?

**Comment by peterhashair** [comment]
@diosmosis browser extension. Like bitwarden or chrome password autofill. I think it trying to fill 2 fields, username, password. The popup only has the password field, so it changed the field behind the popup confirm.

**Comment by diosmosis** [comment]
@peterhashair that's interesting, thanks, I'll disable the inputs as you suggest.

**Comment by diosmosis** [comment]
@peterhashair fixed in https://github.com/matomo-org/matomo/pull/18576 where the relevant angularjs code is migrated

**Review by sgiehl — APPROVED** [review]
lgtm

**Pull request merged**
