### PR TITLE
Add possibility to specify a limit for visits in Live.getVisitorProfile

### LINKED ISSUE #9046: Let Live.getVisitorProfile http API return more than 10 visits (new parameter &limitVisits=X)
index.php?module=API&method=Live.getVisitorProfile&idSite=8&visitorId=XXXXXX&format=xml&token_auth=XXXXXX

if you add &format_limit=50 you still only get the last 10 visits. Unable to return more. We need to be able to get more data from that query.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #9046 

I tried to write some tests for it but failed. Problem: I couldn't really find a fixture where we have many different visits of the same visitor. Tried to write one for a visitor having only a few visits but couldn't figure out the `visitorId`. I could probably get it by logging it in tracking when tests execute them but not trivial when there are also tracking requests for other users etc. It would be doable though. Does anyone maybe know a fixture defining many visits for one visitor? Then I'd add a test for it.

Also: I have not named it `filter_limit` or `filter_offset` since this would be not really correct. As mentioned here https://github.com/piwik/piwik/issues/9046#issuecomment-149121896 these parameters are reserved for the root element. However, `lastVisits` is not a root element. Applying `filter_limit/filter_offset` for `lastVisits` property would be confusing since someone else might expect it to apply for `countries` or another property. Therefore I added a new parameter `limitVisits`. Let me know if there are any other thoughts on this.

### CODE REVIEW

**Comment by mattab** [comment]
@tsteur  This fixture looks like it's got several visits by the same visitor: TwoSitesManyVisitsOverSeveralDaysWithSearchEngineReferrers 

Otherwise looks good to me!

**Comment by tsteur** [comment]
That one is meant for referrers. I'll create a new fixture instead...

**Comment by tsteur** [comment]
Also it was generating many different visitors which was the problem with other fixtures as well

**Comment by tsteur** [comment]
Added a test

**Comment by mattab** [comment]
fyi @tsteur tests fail with `PHP Fatal error:  Cannot redeclare class Piwik\Plugins\Live\tests\System\ApiCounterTest in /home/travis/build/piwik/piwik/plugins/Live/tests/System/ApiCounterTest.php on line 186`

**Comment by tsteur** [comment]
Can you try again? I think it had some problems re renaming the file from `APICounterTest` to `ApiCounterTest` or so

**Pull request merged**
