### PR TITLE
php-cs-fixer (folder: plugins)

### PR DESCRIPTION
**Pull request by ThaDafinser**
`php-cs-fixer fix plugins --level=psr2`

it's time to get all files to psr2.

there will be a seperate PR per folder (just in case there are issues with merging or something else)

### CODE REVIEW

**Comment by ThaDafinser** [comment]
The build is fine, just a github issue: https://travis-ci.org/piwik/piwik/jobs/83102616

**Comment by tsteur** [comment]
@mattab I think we should not merge before we have merged 3.0 branch into master.

**Comment by ThaDafinser** [comment]
@tsteur like already discussed in #8704 if we do this, it should be for the `2.x` branch and `3.x` branch, to prevent future backport issues from `3.x` to LTS version.

If you merge `3.x` to master, this wont affect `2.x` if i'm right?

What is then the "way to go"? Wait for `3.x` to get `master` and do it after that for the `2.x` branch, since from that point only real issues get backported?

**Comment by tsteur** [comment]
I guess it depends on when we will merge `3.0` into `master`. They are already quite different and `3.0` is quite a bit behind because of the many changes. Need to update it again. I think we can merge `3.0` into `master` after the `2.15` release and then merge this one directly afterwards. We can possibly also do it in both branches and not have to wait till we merge `3.0` into `master`?

**Comment by mattab** [comment]
> We can possibly also do it in both branches and not have to wait till we merge 3.0 into master?

@tsteur @ThaDafinser indeed maybe it would be the easier to create one Pull request on each branch (`master` and `3.0`), to limit the "merge hell" ?

**Comment by ThaDafinser** [comment]
@mattab +1 from me

**Comment by mattab** [comment]
See also our follow up issue `Automatically convert our code base to use a consistent code style` #9545

**Pull request closed without merging**
