### PR TITLE
Updates composer dependencies

### PR DESCRIPTION
**Pull request by sgiehl**
- Removing symfony/polyfill-util (v1.17.0)
  - Removing symfony/polyfill-php56 (v1.17.0)
  - Removing nikic/php-parser (v4.4.0)
  - Removing jeremeamia/superclosure (2.4.0)
  - Updating composer/ca-bundle (1.2.7 => 1.2.8)
  - Updating maxmind/web-service-common (v0.7.0 => v0.8.0)
     * PHP 7.2 or greater is now required.
     * Added additional type hints.
  - Updating maxmind-db/reader (v1.7.0 => v1.8.0)
     * Fixes for PHP 8.0
  - Updating geoip2/geoip2 (v2.10.0 => v2.11.0)
     * IMPORTANT: PHP 7.2 or greater is now required.
     * Added the `isResidentialProxy` property to `GeoIp2\Model\AnonymousIP` and `GeoIp2\Record\Traits`.
     * Additional type hints have been added.
  - Updating phpmailer/phpmailer (v6.1.7 => v6.1.8)
     * Mark ext-hash as required in composer.json. This has long been required, but now it will cause an error at install time rather than runtime, making it easier to diagnose
     * Make file upload examples safer
     * Update links to SMTP testing servers
     * Avoid errors when set_time_limit is disabled (you need better hosting!)
     * Allow overriding auth settings for local tests; makes it easy to run tests using HELO
     * Recover gracefully from errors during keepalive sessions
     * Add AVIF MIME type mapping
     * Prevent duplicate To headers in BCC-only messages when using mail()
     * Avoid file function problems when attaching files from Windows UNC paths
     * Improve German, Bahasa Indonesian, Filipino translations
     * Add Javascript-based example
     * Increased test coverage
  - Updating symfony/polyfill-ctype (v1.18.1 => v1.20.0)
  - Updating symfony/polyfill-mbstring (v1.18.1 => v1.20.0)
  - Updating twig/twig (v3.0.5 => v3.1.1)
      * Fix "include(template_from_string())"
      * Fix sandbox support when using "include(template_from_string())"
      * Make round brackets optional for one argument tests like "same as" or "divisible by"
      * Add support for ES2015 style object initialisation shortcut { a } is the same as { 'a': a }
  - Updating pear/archive_tar (1.4.9 => 1.4.10)
  - Updating opis/closure (3.5.6 => 3.6.0)
  - Updating php-di/phpdoc-reader (2.1.1 => 2.2.1)
  - Updating phpdocumentor/type-resolver (1.3.0 => 1.4.0)
  - Updating phpdocumentor/reflection-docblock (5.2.1 => 5.2.2)
  - Updating phpspec/prophecy (1.11.1 => 1.12.1)

refs #14601

### CODE REVIEW

**Comment by Findus23** [comment]
> Mark ext-hash as required in composer.json. This has long been required, but now it will cause an error at install time rather than runtime, making it easier to diagnose

Should we maybe add this here:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/Diagnostics/Diagnostic/PhpExtensionsCheck.php#L58

**Comment by sgiehl** [comment]
@Findus23 let's do that in a new PR. Guess we could also remove `Reflection` and `SPL`,  from that list, as they are actually built in.

**Comment by sgiehl** [comment]
@Findus23 just checked that. The availability of the hash function is checked here: https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Diagnostics/Diagnostic/PhpFunctionsCheck.php#L61

**Comment by Findus23** [comment]
Thanks for checking. I was confused as they called it `ext-hash`.

**Comment by tsteur** [comment]
@sgiehl @Findus23 can we merge it? tests seem to pass?

**Comment by sgiehl** [comment]
@Findus23 Maybe the check would be better placed in the extension check. But at least it is checked in any way...

@tsteur Guess it can be merged then

**Pull request merged**
