### PR TITLE
fix insights widget "Others" percentage

### LINKED ISSUE #17615: Insights widget shows only "Others" page titles
Since Matomo v4.3.0 I think, the dashboard widgets "Insights Overview" and "Moves and Shakers" of the Insights plugin show only "Others +100%" and "Others -100%" where most changed page title views should be listed. It looks like page titles with less views/changes are accumulated as "Others", but all of them together change most, which doesn't seem like intended, at least makes it useless.

## Expected Behavior

Two distinct most changed page titles should be shown in the widgets.

## Current Behavior

PAGE TITLES | UNIQUE PAGEVIEWS | EVOLUTION
-- | -- | --
Others | +5259 | +100%
Others | -5691 | -100%

## Possible Solution

No idea. Probably an underlying API has changed, when obtaining a list of page titles, where less important page titles are merged?

## Steps to Reproduce (for Bugs)

1. Enable Insights plugin
2. Add both Insights widgets "Insights Overview" and "Moves and Shakers" to dashboard

## Your Environment

* Matomo Version: 4.3.1-rc1 (issue was present with 4.3.0 already)
* PHP Version: 8.0.5
* Server Operating System: Debian Bullseye
* Additionally installed plugins:
```
API, Actions, Annotations, BotTracker 2.02, BulkTracking, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, DBStats, DarkTheme 1.1.6, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Goals, ImageGraph, Insights, Installation, Intl, LanguagesManager, Live, LogViewer 4.0.1, Login, Marketplace, Monolog, Morpheus, PagePerformance, PrivacyManager, Proxy, Referrers, Resolution, SEO, SegmentEditor, SitesManager, Transitions, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable
```
* Browser: Opera 78
* Operating System: Windows 10 21H1

### PR DESCRIPTION
**Pull request by flamisz**
### Description:

fixes #17615 

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
code looks good :+1:

**Comment by MichaIng** [comment]
Many thanks. I applied the new code, but I think I have to wait for the next report generation to see the results.

Where is the new function `getPastRowFromCurrent` actually used?
**EDIT: Ah sorry, I see now it is an override.**

**Comment by MichaIng** [comment]
Okay, it does not fix the issue in our case. I added the code, verified it, cleared all caches, but it still shows:
```
Others +100%
Others -100%
```
on all page title lists.

Are there other companion changes required, committed outside of this PR?

**Comment by diosmosis** [comment]
@MichaIng This by itself seemed to fix it for me locally (and the test works on this branch but fails on 4.x-dev). I'll reopen the original issue.

**Comment by diosmosis** [comment]
@MichaIng could you post the following screenshots to help us debug?

- a screenshot of the insights overview page w/ the issue visible (and the period / date visible)
- a screenshot of the page titles report for the same period/date, sorted in descending order so the Others row is shown first
- a screenshot of the page titles report (as before) but for the previous period/date (again sorted so we see the Others row)

**Comment by MichaIng** [comment]
insights

The page titles report does not show "Others" at all, neither for the current period (this is one week), nor for any previous period, long or short.

**Comment by diosmosis** [comment]
@MichaIng I'll try to reproduce this again. Would you be willing to provide view access to your Matomo in the event I can't?

**Comment by MichaIng** [comment]
Yes, I can do that.

**Comment by diosmosis** [comment]
@MichaIng can you email dizzy@innocraft.com with access details? I'll take a closer look today.

**Comment by MichaIng** [comment]
Okay that is strange, the issue seems to fade currently, while all I just did is updating another app. Is the "Others" entry preserved in reports and because of this still shown even that the code has been fixed? The very same time range the screenshot above is from now does not shot "Others" anymore, the "PAGE TITLES" section in the "Insights Overview" widget is gone completely instead. I still see "Others" when switching to "day" or "week" view (above is "date range", covering last seven days).

But I'll send you access details regardless.

**Comment by diosmosis** [comment]
@MichaIng 

> Is the "Others" entry preserved in reports and because of this still shown even that the code has been fixed?

It is preserved in reports, but the Insights report is not stored in the database. It's built dynamically using stored reports for the current period and previous period, for example, the page titles reports. So if the data in the periods for other reports (like the page titles reports) change, then the Insights reports should display different data immediately. I'm not sure why it would show nothing now... I'll take a look later and see what I can find.

**Comment by diosmosis** [comment]
Resolved via email, the PR does work.

**Comment by MichaIng** [comment]
Yes, many thanks. The entries from the old records basically needed to fade out.

**Comment by sgiehl** [comment]
@diosmosis so we can close #17615 again?

**Comment by diosmosis** [comment]
@sgiehl yes :+1:. Closed it.

**Pull request merged**
