### PR TITLE
New flag icons

### PR DESCRIPTION
**Pull request by Findus23**
Replacement for #11272

I hope I haven't forgot something. Let's see what the tests are saying.

## Tests:

https://travis-ci.org/piwik/piwik/jobs/216225571#L703:

I don't know what's wrong. We have a `gb-eng`-flag: https://github.com/piwik/piwik-icons/blob/master/dist/flags/gb-eng.png

## TODO:

Fix `plugins/CustomDimensions`
```diff
diff --git a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
index 9b55fd8..65bb6be 100644
--- a/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
+++ b/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
@@ -85,7 +85,7 @@
                <continentCode>eur</continentCode>
                <country>France</country>
                <countryCode>fr</countryCode>
-               <countryFlag>plugins/UserCountry/images/flags/fr.png</countryFlag>
+               <countryFlag>plugins/Morpheus/icons/dist/flags/fr.png</countryFlag>
                <region />
                <regionCode />
                <city />
@@ -203,7 +203,7 @@
                <continentCode>eur</continentCode>
                <country>France</country>
                <countryCode>fr</countryCode>
-               <countryFlag>plugins/UserCountry/images/flags/fr.png</countryFlag>
+               <countryFlag>plugins/Morpheus/icons/dist/flags/fr.png</countryFlag>
                <region />
                <regionCode />
                <city />
@@ -319,7 +319,7 @@
                <continentCode>eur</continentCode>
                <country>France</country>
                <countryCode>fr</countryCode>
-               <countryFlag>plugins/UserCountry/images/flags/fr.png</countryFlag>
+               <countryFlag>plugins/Morpheus/icons/dist/flags/fr.png</countryFlag>
                <region />
                <regionCode />
                <city />
@@ -467,7 +467,7 @@
                <continentCode>eur</continentCode>
                <country>France</country>
                <countryCode>fr</countryCode>
-               <countryFlag>plugins/UserCountry/images/flags/fr.png</countryFlag>
+               <countryFlag>plugins/Morpheus/icons/dist/flags/fr.png</countryFlag>
                <region />
                <regionCode />
                <city />
@@ -583,7 +583,7 @@
                <continentCode>eur</continentCode>
                <country>France</country>
                <countryCode>fr</countryCode>
-               <countryFlag>plugins/UserCountry/images/flags/fr.png</countryFlag>
+               <countryFlag>plugins/Morpheus/icons/dist/flags/fr.png</countryFlag>
                <region />
                <regionCode />
                <city />
```

### CODE REVIEW

**Comment by mattab** [comment]
## Remaining feedback

* can we add a grey border around flags in Visitor Log and Profile? 
 * http://builds-artifacts.piwik.org/piwik/piwik/new-flag-icons/22719/processed/UIIntegrationTest_ecommerce_log.png
 * also in the Goals overview http://builds-artifacts.piwik.org/piwik/piwik/new-flag-icons/22719/UIIntegrationTest_goals_individual_goal_updated.png
 * and in reports http://builds-artifacts.piwik.org/piwik/piwik/new-flag-icons/22719/UIIntegrationTest_visitors_locations_provider.png
 * and possibly any other place the flags are displayed

**Comment by Findus23** [comment]
- Goals overview and Visitor Log: 0a5b2a5cdb
- Visitors in Real-Time: not necessary:
screenshot_20170329_173311
- Real-time-map-popup: black background
- E-Commerce log: can't test, but looks similar to Visitor Log.
- Reports: I have no idea how to apply css only to the flags report

**Comment by mattab** [comment]
Status: grey border needed in:

* Country + Region + City reports
* [Visitor profile](http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22746/processed/UIIntegrationTest_visitor_profile_popup.png)
* Ideally in email reports too

I'll try take a quick look at the Country + Region + City reports first

**Comment by Findus23** [comment]
Visitor profile should be easy. I'll look into it

**Comment by mattab** [comment]
Info:
* Not going to set a border in the PDF Reports

**Pull request merged**
