### PR TITLE
DNT ignore for Epiphany

### PR DESCRIPTION
**Pull request by ThaDafinser**
https://github.com/piwik/piwik/issues/8682

### CODE REVIEW

**Comment by ThaDafinser** [comment]
I dont like the current check, since it's directly in the code and it's not version specific.

Would this be maybe a good idea to move this job to the device-detector library? https://github.com/piwik/device-detector

ping @sgiehl

**Comment by sgiehl** [comment]
Not sure if moving it to device detector makes it much better... Regardless where it's done we need to maintain a list with the browsers that should be handled special...

**Comment by tsteur** [comment]
Can we merge this one and create a new issue for how to maintain that list? @sgiehl

**Comment by sgiehl** [comment]
Sure, why not.

**Comment by tsteur** [comment]
@ThaDafinser  feel free to create issues for your suggestion. We can possibly move the definition to a DI config outside the code so plugins could extend it as well.

Defining a min version for browsers would be nice too and fair for the users to respect their privacy.

**Comment by tsteur** [comment]
Thx for the PR :)

**Pull request merged**
