### PR TITLE
backport confirm password fix for loginldap on 3.x

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Use activated login plugin method in confirm password workflow, not Login since it will be deactivated when another login plugin exists.

### Todo

* [ ] after merge and release, release new LoginLdap 3.x series

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis did you update the TagManager submodule on purpose?

**Comment by diosmosis** [comment]
@sgiehl no, not on purpose, will remove

**Comment by tsteur** [comment]
seems it doesn't break any test so we can merge this @diosmosis @sgiehl ?

**Comment by diosmosis** [comment]
will merge, if there's an issue let me know and i'll fix in another pr

**Pull request merged**
