### PR TITLE
Replace jQuery.dotdotdot with pure CSS

### LINKED ISSUE #20941: Dependency jquery.dotdotdot has a non-commercial license
Matomo is licensed under the GPL-3.0+, but our library-scanner detected a non-commercial license in the dependency jquery.dotdotdot (published under CC-BY-NC-4.0). 

## Context
The license CC-BY-NC-4.0 is a non-commercial-usage license as of https://creativecommons.org/licenses/by-nc/4.0/
This is not expected, since https://matomo.org/licences/ states a free use of matomo under GPL-3, which is contrary to the usage of a dependency with a non-commercial license.

## Expected Behavior
Usage of matomo without conflicting licenses in dependencies.

## Current Behavior
jquery.dotdotdot has a non-commercial license

## Possible Solution
As far as i understood, jquery.dotdotdot is only used for module-documentation for the matomo developers and is never be used in any context to end-users. Could it be simply removed in the release-process?

## Your Environment
* Matomo Version: 4.14.2-b146
* PHP Version:  8.0.28
* Server Operating System: SLES15 SP4

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #20941

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
@sgiehl do we have this covered by a UI test (and it still passes) or there's no UI test for this?

**Comment by sgiehl** [comment]
There is no UI test covering this, as the `marketplace updates` stream is mocked to an empty set.
It basically only affects this widget on the admin home screen: 
image

**Comment by michalkleiner** [comment]
~Can you please help me where do I find those Marketplace updates? Can't seem to see it anywhere.~ Found it right after I posted the question. All good.

**Review by michalkleiner — APPROVED** [review]

**Comment by michalkleiner** [comment]
I think we should hold off merging until we create `5.1.x-dev` branch or we add it to 5.1.0-b2 as we are not in feature freeze yet.

**Comment by sgiehl** [comment]
Let's include it in 5.1.0-b2

**Pull request merged**
