### PR TITLE
Display "Professional Services" link in the "An error occured" error screen

### PR DESCRIPTION
**Pull request by mattab**
I can't display the link conditionally  as the testMinimumVersion.php file must be PHP4 compatible.

### CODE REVIEW

**Comment by tsteur** [comment]
Can we somehow respect the users settings to disable these ads there? There's a config setting for it but the config might not exist at the time of calling this method. If the class Config is loadable and a config exists it would be nice to respect it as users might see otherwise ads for a competitor of their hoster / agency.

**Comment by mattab** [comment]
@tsteur I can't display the link conditionally as the testMinimumVersion.php file must be PHP4 compatible, so we can't use Config or read config file...

**Comment by tsteur** [comment]
It should work with a `class_exists('Piwik\Config', false)` I think but would need to be tested

**Comment by mattab** [comment]
@tsteur because of namespaces it doens't work, I tried:
```
--- core/testMinimumPhpVersion.php	(revision 888ade738e5e1367406cf7865c5feb5da94ab0fd)
+++ core/testMinimumPhpVersion.php	(revision )
@@ -143,10 +143,15 @@
                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org">Piwik.org homepage</a></li>
                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/faq/">Piwik Frequently Asked Questions</a></li>
                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/docs/">Piwik Documentation</a></li>
-                            <li><a rel="noreferrer" target="_blank" href="http://forum.piwik.org/">Piwik Forums</a></li>
-                            <li><a rel="noreferrer" target="_blank" href="https://piwik.pro/contact/?pk_campaign=App_AnErrorOccured&pk_source=Piwik_App&pk_medium=ProfessionalServicesLink#contact-form">Professional help (Piwik PRO)</a></li>
-                            </ul>';
+                            <li><a rel="noreferrer" target="_blank" href="http://forum.piwik.org/">Piwik Forums</a></li>';
+
+            if (class_exists('Piwik\Config', false)
+                && Piwik\Config::getInstance()->General['piwik_pro_ads_enabled'] == 1) {
+                $optionalLinks .= '<li><a rel="noreferrer" target="_blank" href="https://piwik.pro/contact/?pk_campaign=App_AnErrorOccured&pk_source=Piwik_App&pk_medium=ProfessionalServicesLink#contact-form">Professional help (Piwik PRO)</a></li>';
-        }
+            }
+            $optionalLinks .= '</ul>';
+        }
+
         if ($optionalLinkBack) {
             $optionalLinkBack = '<a href="javascript:window.history.back();">Go Back</a>';
         }
```


but this gives on PHP4
```
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>[...][...]</b> on line <b>148</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>[...][...]</b> on line <b>148</b><br />

```


it can be executed on PHP4 here: http://sandbox.onlinephpfunctions.com/code/1d7b8fa8593da5bcf529ad3282b4acc86122ae9e

so maybe it's not possible because of namespace?

**Comment by tsteur** [comment]
I guess we could do a PHP version check or something but not sure. I guess the way to do it would be to put it in `ExceptionHandler`. I think it's ok to show Piwik PRO when someone tries to install Piwik on PHP 4.X or something and sees the ad. If it comes from the exception handler we do have the config and it would be nice to respect the setting

**Pull request merged**
