### PR TITLE
Fix processed metrics are not shown in visitor map when viewing cities

### PR DESCRIPTION
**Pull request by tsteur**
Eg nb_actions_per_visit
bounce_rate
avg time per visit

Bounce rate seems to always show 100% now but not sure why

### CODE REVIEW

**Comment by tsteur** [comment]
It looks like the bounce rate is actually 100% in my test data.

**Comment by sgiehl** [comment]
If I have seen that correctly, we are currently not using number formatting for the visitor map. So the numbers won't be localized. Correct? We have a JavaScript Numberformatter (https://github.com/piwik/piwik/blob/master/plugins/CoreHome/javascripts/numberFormatter.js) we should use.

**Comment by tsteur** [comment]
It's using the number formatter for the tooltips (at least in City view) but not for the value in the circle. Here it has kind of slightly different format I would say and shortens values eg 10000 bekomes 10k to fit in the circle

**Comment by sgiehl** [comment]
LGTM

**Pull request merged**
