### PR TITLE
Improved old icons

### PR DESCRIPTION
**Pull request by Findus23**
While looking through the UI icons I found the following improvements: (#11177)
- plugins/DevicesDetection/images/brand/*.ico are PNG files with a wrong file extentions
- converted all icons to png (no more jpg or gif (except for loading icons/animated gifs))
- deleted plugins/Live/images/visitor_profile_background.jpg ([this .less file](https://github.com/piwik/piwik/blob/3.x-dev/plugins/Live/stylesheets/visitor_profile.less#L6) doesn't seem to be used any more)
- What about plugins/CoreHome/images/bg_header.png? I guess it can also be deleted.
- plugins/CoreHome/images/favicon.ico was a PNG. I replaced it with a real multisize ico file.
- I found [this comment](https://github.com/piwik/piwik/blob/9243b9a7b6fae8237596f76cda1fe8b6816463af/plugins/ImageGraph/API.php#L347). Is it still relevant?

### CODE REVIEW

**Comment by mattab** [comment]
Thanks for the PR!

Feedback:

* an integration test fails with `png format failed for following icons /home/travis/build/piwik/piwik/plugins/CoreHome/images/favicon.ico`. Would it be possible to make the favicon PNG format?

> I found this comment. Is it still relevant?

I'd say it's still relevant, but maybe the code below won't be useful / executed anymore as you seem to have converted all icons away from gif? If that's the case you could maybe try remove the code (or we can leave it as a fail safe in case icons in gif are later added)

**Comment by Findus23** [comment]
>an integration test fails with png format failed for following icons /home/travis/build/piwik/piwik/plugins/CoreHome/images/favicon.ico. Would it be possible to make the favicon PNG format?

What is the reason behind having a wrong file extension for png files and as a result sending the wrong mime type to the browser.
If you want to have a png favicon, we could add two icons (16px and 32px) and reference them as png. (As [realfavicongenerator.net](https://realfavicongenerator.net) does it)
```html
<link rel="icon" type="image/png" href="/plugins/CoreHome/images/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/plugins/CoreHome/images/favicon-16x16.png" sizes="16x16">
```

>I'd say it's still relevant, but maybe the code below won't be useful / executed anymore as you seem to have converted all icons away from gif? If that's the case you could maybe try remove the code (or we can leave it as a fail safe in case icons in gif are later added)

I'd just keep it there.

**Comment by mattab** [comment]
> If you want to have a png favicon, we could add two icons (16px and 32px) and reference them as png. (As realfavicongenerator.net does it)

Would be great to do remove our favicon.ico completely and do it properly with png files as you suggest :+1:

**Comment by sgiehl** [comment]
Keep in mind, we are allowing to change the favicon by uploading one. If we
now use two with different sizes, maybe that logic needs to to be adjusted,
as well.

**Comment by Findus23** [comment]
@sgiehl you are right, I forgot about this possibility. 
It gets even more complicated because chrome (also opera and chrome mobile) prefer ico favicons over png, if it has a higher resolution (mine includes 16,32,48,64px)
Safari (desktop always preferes the ico, even if it is smaller. 
And the "old" Android Browser always picks the last defined icon. 
http://caniuse.com/#feat=link-icon-png


I assume there is no way to generate multisize ico files in Piwik, so maybe it's really best to drop the .ico so it can't interfere with the custom favicon. (Which would have to be rewritten to generate the correct png files).

**Comment by RMastop** [comment]
Could the project from @chrisbliss18 be of help here?
https://github.com/chrisbliss18/php-ico

**Comment by mattab** [comment]
I'll update the integration test so it does not check the format of favicon.ico. Merging now, Thanks  @Findus23 for the PR!

**Pull request merged**
