### PR TITLE
Add Movers And Shakers widget to default dashboard

### LINKED ISSUE #13153: Add "Movers and shakers" widget to the default dashboard
I think it would be quite valuable to have. I don't know what it shows when there is no data... maybe could explain what the plugin does... because after installation there will be no data and this way users can understand what the widget is for... 

maybe we can also add a few more reports to this report? not sure.

### PR DESCRIPTION
**Pull request by tsteur**
Could also move it to top left even before the "Visitors in real time widget"? @mattab any preference? As it may be quite useful to see it first, but not needed.

fixes #13153

### CODE REVIEW

**Comment by mattab** [comment]
it's a good idea but the problem is that Movers & Shakers does not yet work for custom date ranges. Most users will have a date range selected as their default period, and the widgets shows only a message ` It is not possible to generate insights for this date and period combination. `

-> Would it be possible to add support for custom date range in Movers & Shakers first?

**Comment by tsteur** [comment]
Probably not, lets move it out of the milestone then. 
BTW: Most users will have today or yesterday as their default period quite likely ;) I doubt too many people even change it or know they can change it ;)

**Comment by diosmosis** [comment]
Adding WIP tag since this can't be merged yet

**Comment by tsteur** [comment]
I'll move it to 3.10 then. Although I highly doubt most users change their default date and even set it to a date range :)

**Comment by mattab** [comment]
how much work would it be to make movers & shakers work for custom date ranges? covered in https://github.com/matomo-org/matomo/issues/5815

Will close it for now but be great to merge this once https://github.com/matomo-org/matomo/issues/5815 is fixed

**Pull request closed without merging**
