### PR TITLE
Hide duplicate actions in visitor log by default

### LINKED ISSUE #9586: visitor log: grouping hides information
In visitor log visits of the same page are grouped.
This behaviour curently hides information: one could not see (on hover) time on page for each visite.

With this one has no change to unterstand/speculate why this page is requested/visited by the visitor more than one time.

This becomes even more important when optimized implemantation of heartbeat could show more "breaks" within a visit (because page was in background in between)

2016-01-20_21h46_10

2016-01-20_21h53_06

### PR DESCRIPTION
**Pull request by sgiehl**
...and extend them on click

fixes #9586

### CODE REVIEW

**Comment by sgiehl** [comment]
UI test failures are unrelated to this PR

**Comment by mattab** [comment]
Could you add a UI test that clicks on the "Expand group" and check the actions expand as expected? Ideally the UI test would take a screenshot of only the visit including the expanded actions so it's clear what the UI test does.

**Comment by mattab** [comment]
* @sgiehl let's also make this behavior consistent in the Visitor Profile

**Comment by sgiehl** [comment]
I've update the PR to have consistent behavior on profile and log

**Comment by mattab** [comment]
@sgiehl  Looks good :+1: 
Could you resolve the conflict, and merge this?

**Comment by sgiehl** [comment]
conflict resolved. all related tests are passing again...

**Pull request merged**
