### PR TITLE
[Vue] migrate transitions plugin to Vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:
* Migrate transition-exporter to Vue.
* Migrate transition-switcher to Vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
It seems like when you refresh the page, it loads a warning, but 4.x-dev doesn't have that warning.

https://user-images.githubusercontent.com/3783072/161456442-537f8a28-106a-436a-ba4c-ad058f2de24b.mp4

**Comment by diosmosis** [comment]
@peterhashair should be fixed w/ last commit

**Review by peterhashair — APPROVED** [review]
Looks good to me

**Comment by sgiehl** [comment]
@peterhashair @diosmosis it would be good to always merge in the latest changes from 4.x-dev and check if all tests are passing before merging a PR. That way you would have noticed this failure:
```
1) Piwik\Tests\Integration\ReleaseCheckListTest::test_noVueHtmlWithoutSanitize
Found uses of v-html without $sanitize:
- /home/travis/build/matomo-org/matomo/plugins/Transitions/vue/src/TransitionSwitcher/TransitionSwitcher.vue
Failed asserting that a string is empty.
/home/travis/build/matomo-org/matomo/tests/PHPUnit/Integration/ReleaseCheckListTest.php:721
```

**Pull request merged**
