### PR TITLE
[Vue] migrate geoip2 updater to Vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:
* Migrate geoip2 updater directive to Vue.
* Allow inline help in Field/FormField components to be specified via named slot instead of angularjs method of specifying jquery selector, and instead of vue method of using dynamic component (though that is still supported).

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — APPROVED** [review]
Tested UI working as expected.

**Comment by sgiehl** [comment]
@diosmosis One thing doesn't seem to work correctly anymore.
If no geoip database is installed and you choose to configure manually and provide a URL for both databases and click the save button, the updater downloads the first database directly and the progress bar is displayed below. It takes a while for this to finish and then nothing happens. The last download request actually contains the next database that should be downloaded, but seems that isn't used. Once all downloads are finished I guess a notification should be shown or the page should be reloaded. This doesn't work with only one database either.

**Comment by diosmosis** [comment]
@sgiehl should be fixed

**Comment by sgiehl** [comment]
@diosmosis doing the manual setup now works without problems. But using the one click setup to automatically download the database now only shows the progress bar, the file name below isn't shown any longer.

**Comment by diosmosis** [comment]
@sgiehl should also be fixed

**Comment by peterhashair** [comment]
@diosmosis the VUE build failed, probably needs a re run

**Comment by diosmosis** [comment]
@peterhashair I rebuild the files locally before committing.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
