### PR TITLE
Add php cs fixer

### LINKED ISSUE #7186: Fix warnings + coding standards with PHP-CS-Fixer
Hello together,

there i a small little helper with a huge benefit i use currently for all my projects:
https://github.com/FriendsOfPHP/PHP-CS-Fixer

This little does not only checking for coding standards, it can be actually used to apply them.
There are e.g. tons of unused use statements in Piwik, which would be automatically removed by that tool

Also that tool can be executed as "dry-run" to only report problems, so it can be included in the travis build process.

piwik

### PR DESCRIPTION
**Pull request by fabiocarneiro**
Fixes #7186

I saw that there is already a PR for that, but was created 1 month ago. Its taking **~117 seconds** to run, and it is reporting **326 failures**.

I had to update the dependencies to include php-cs-fixer. Here is a list of what was modified.

```
  - Removing myclabs/php-enum (1.3.2)
  - Removing twig/twig (v1.18.0)
  - Installing twig/twig (v1.18.1)
    Downloading: 100%         

  - Removing monolog/monolog (1.12.0)
  - Installing monolog/monolog (1.13.1)
    Downloading: 100%         

  - Removing symfony/monolog-bridge (v2.6.3)
  - Installing symfony/monolog-bridge (v2.6.7)
    Downloading: 100%         

  - Removing sebastian/version (1.0.4)
  - Installing sebastian/version (1.0.5)
    Loading from cache

  - Removing sebastian/environment (1.2.1)
  - Installing sebastian/environment (1.2.2)
    Loading from cache

  - Removing sebastian/diff (1.2.0)
  - Installing sebastian/diff (1.3.0)
    Loading from cache

  - Removing symfony/yaml (v2.6.3)
  - Installing symfony/yaml (v2.6.7)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.4.1)
    Downloading: 100%         

  - Removing phpunit/phpunit-mock-objects (2.3.0)
  - Installing phpunit/phpunit-mock-objects (2.3.1)
    Loading from cache

  - Removing phpunit/php-token-stream (1.4.0)
  - Installing phpunit/php-token-stream (1.4.1)
    Loading from cache

  - Removing phpunit/php-file-iterator (1.3.4)
  - Installing phpunit/php-file-iterator (1.4.0)
    Loading from cache

  - Removing phpunit/php-code-coverage (2.0.15)
  - Installing phpunit/php-code-coverage (2.0.16)
    Loading from cache

  - Removing phpunit/phpunit (4.4.5)
  - Installing phpunit/phpunit (4.6.6)
    Downloading: 100%         

  - Removing phpseclib/phpseclib (0.3.9)
  - Installing phpseclib/phpseclib (0.3.10)
    Downloading: 100%         

  - Removing symfony/var-dumper (v2.6.3)
  - Installing symfony/var-dumper (v2.6.7)
    Downloading: 100%         

  - Removing doctrine/annotations (v1.2.3)
  - Installing doctrine/annotations (v1.2.4)

  - Removing doctrine/cache (v1.4.0)
  - Installing doctrine/cache (v1.4.1)
    Loading from cache

  - Removing pear/archive_tar (1.3.15)
  - Installing pear/archive_tar (1.3.16)
    Downloading: 100%         

  - Removing symfony/event-dispatcher (v2.6.3)
  - Installing symfony/event-dispatcher (v2.6.7)
    Downloading: 100%         

  - Removing guzzle/guzzle (v3.9.2)
  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing php-di/invoker (1.0.0)
    Downloading: 100%         

  - Installing symfony/stopwatch (v2.6.7)
    Downloading: 100%         

  - Installing symfony/process (v2.6.7)
    Downloading: 100%         

  - Installing symfony/finder (v2.6.7)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.6.7)
    Downloading: 100%         

  - Removing symfony/console (v2.6.3)
  - Installing symfony/console (v2.6.7)
    Loading from cache

  - Installing fabpot/php-cs-fixer (v1.8)
    Downloading: 100%         

  - Installing doctrine/annotations (v1.2.4)
    Downloading: 100%         

  - Updating mnapoli/php-di 5.0.x-dev (b555566 => 7afd257)
    Checking out 7afd2574c3f4c23814a43dbca23d7cd1741aa489
```

### CODE REVIEW

**Comment by mattab** [comment]
Hi @fabiocarneiro 

Thanks for PR. as you write there is already a PR for this, is there particular reason you create another one? #7731

**Comment by fabiocarneiro** [comment]
@mattab The other one seems not to be running on travis.

**Comment by tsteur** [comment]
Is it possible to execute it only with one job instead of each time again? Maybe we could run it with the Unit Tests on PHP 5.6 or so?

**Comment by mattab** [comment]
Hi there, feel free to continue discussion in this other pull request: #8704

**Pull request closed without merging**
