### PR TITLE
Adding helper function for UI tests

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Created a new helper function for hiding the side navigation while taking screenshots. This is based on the [function recently used in CustomAlerts](https://github.com/matomo-org/plugin-CustomAlerts/pull/153/files#diff-fd8e5f49c335ad8bcc2733456df917d7bd7140cc34b67c66efe68e84621b9b73R16). Since we have quite a few plugins with failing UI builds due to recent nav bar changes, I figured that it would be good to add a reusable function instead of duplicating code.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]
System and UI test failures look unrelated to this change.

**Review by bx80 — APPROVED** [review]
Looks okay to me and the adjusted tests are passing :+1:

**Comment by sgiehl** [comment]
Note: The menu styling of the left menu is currently inconsistent between reporting and admin UI. I've created https://github.com/matomo-org/matomo/issues/21641 for that.
If we decide to also remove the box shadow in the admin UI, this would solve any problems around the shadow being displayed in screenshots.
If we add it to the reporting menu, we might need to look for a proper CSS solution anyway, as otherwise the shadow might also appear on all reporting screenshots.

**Comment by michalkleiner** [comment]
Thanks for the PR @snake14. We had a chat within the internal core team and we think the approach should be focused more on resolving the shadow issue through a different way (TBD) so I'll close this PR for now. For plugins that may have the same issue it's ok to duplicate the few lines of code for now in their UI tests.

**Comment by snake14** [comment]
@michalkleiner Thank you for letting me know. I kind of hate to go through around 10 plugins adding the same function just to have it no longer necessary once core decides the overall fix. Any estimate on a timeframe? I'm torn between the desire to keep the code clean and the desire to keep the builds green.

**Comment by michalkleiner** [comment]
Appreciate that, thank you for the comment. We have https://github.com/matomo-org/matomo/issues/21641 to properly address the shadow issue in core, so hopefully not that far away.

**Pull request closed without merging**
