### PR TITLE
If no pivotBy column is specified, make sure when getting first column in table

### PR DESCRIPTION
**Pull request by diosmosis**
… in table to find associated metric index value.

### CODE REVIEW

**Comment by mattab** [comment]
@diosmosis looks good. Feedback: tests are failiing, can you update the expected files?

**Comment by mattab** [comment]
actually test results look different... see eg. (is this expected or a regression?)

Screenshot from 2019-05-28 13-03-32

**Comment by diosmosis** [comment]
Was a copy-paste failure, should be fixed.

**Comment by diosmosis** [comment]
@mattab fyi, merged this

**Pull request merged**
