### PR TITLE
test for trim action name

### PR DESCRIPTION
**Pull request by flamisz**
### Description:

ref #15501 

Turned out it's not fixing the original issue. For more details see the comments on that issue.

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sgiehl — CHANGES_REQUESTED** [review]
@flamisz  Looks fine. Maybe you could add a new test for that case where the delimiter is set empty and an actions (url) with pre- or appending spaces is tracked. Guess this could be added here: https://github.com/matomo-org/matomo/blob/4.x-dev/tests/PHPUnit/Integration/Tracker/ActionTest.php

**Comment by flamisz** [comment]
@tsteur and @sgiehl I found something interesting with this `action_name` while I was writing a test. 
I modified back my changes to see the test a made is failing, but it's not. So I checked and we already trim the action name, but not there where I modified the code. 

https://github.com/matomo-org/matomo/blob/b17616097d6b353dc65b0d77773d0c78977646e8/core/Tracker/ActionPageview.php#L28-L29

and then:

https://github.com/matomo-org/matomo/blob/b17616097d6b353dc65b0d77773d0c78977646e8/core/Tracker/Action.php#L212-L215

So this couldn't be the original issue. I can add the tests and not modifying the code, so we will see actually it is trimmed. 
But then what was the issue for the user?

**Comment by sgiehl** [comment]
@flamisz Had a closer look at the code myself now and it seems the action name is trimmed in all cases already. I guess there are actually no changes needed. Will comment the original issue as well.

**Comment by sgiehl** [comment]
Merging this one as an additional test can't hurt ;-)

**Pull request merged**
