### PR TITLE
Fix for opt-out toggling on page load and incorrect default state

### LINKED ISSUE #19879: Fix for opt-out toggling on page load and incorrect default state
## Expected Behavior
The opt-out checkbox should only change when clicked. The checkbox and text should display the actual current state of the users choosen settings.

- If the cookie `mtm_consent_removed` is set, the opt-out text should state, the user has opted-out. The checkbox should **not** be checked and say: "You are currently opted out. Check this box to opt-in."
- If there is **no** `mtm_consent_removed` cookie set, the checkbox should be checked and the text should say: "You are not opted out. Uncheck this box to opt-out."

## Current Behavior
Everytime the page with the opt-out is loaded, the state of the opt-out is toggled. So if there is no `mtm_consent_removed` cookie set, it will be set. Meanwhile the checkbox and text displays the opposite of the cookie state. It seems like the JS is just toggling the state everytime.

## Steps to Reproduce (for Bugs)
1. Create a page that only inlcudes the tracking snippet and the opt-out snippet
2. Simply reload the page multiple times

## Context
We are trying to implement the cookieless, opt-in method. Therefore the tracking code has set the following options:
```js
    _paq.push(["setDoNotTrack", true]);
    _paq.push(["disableCookies"]);
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
```
No other cookies are set for the domain. There are results beeing tracked by this example page.

(The different single and double quote styles are actually generated by Matomo UI).

## Your Environment
* Matomo Version: 4.12.1 (previously also occured on 4.12.0)
* PHP Version: 7.4.3
* Server Operating System: Linux
* Additionally installed plugins: CustomVariables
* Browser: Chrome, Firefox
* Operating System: macOS

### LINKED ISSUE #19888: New Opt-out solution: checkbox is OFF per default even though I'm being tracked
We are using Matomo 4.12.1 .

We integrated the new script to Opt-out without the previous iframe (#17452).
Since we track without cookies and do not use a consent tool, the behavior is incorrect.
In the default case, the checkbox is off and it means that I would not be tracked.

## Steps to Reproduce 

1. Integrate Tracking-script without consent tool
2. integrate Opt-out script with DIV-Container
3. The Opt-out dialog shows that I would not be tracked. But that is wrong. I'm being tracked.

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #19888 
Fixed #19879 

The JavaScript tracker opt-out was setting the current opt-out state on page load which was incorrectly causing the state to toggle, this bit of code has now been removed.

The standalone opt-out was interpreting no 'consent cookie' or 'remove consent cookie' to mean the user was opted out, which is incorrect. An extra check has been added so that if neither the 'consent cookie' or the 'remove consent' cookie are set the the user is considered to be currently opted-in.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — COMMENTED** [review]
The function test on that one works as expected, but there are lots of UI tests failing that seem unrelated.

**Review by peterhashair — APPROVED** [review]
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)

**Comment by MatomoForumNotifications** [comment]
This pull request has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834/6

**Comment by KarthikRaja1388** [comment]
Customer's request:

Good morning, I am a Matomo Cloud customer.  I would like to report a bug about the code you provided with the opt-out js (from the Matomo backend). When I visit the page where the form is present and then I refresh, the  data is changed automatically (example: once it is checked, the next  time it is not and so on).  Link where the form is present and the bug can be reproduced: https://drapersitaly.it/it-it/cookie-policy/

**Comment by peterhashair** [comment]
@KarthikRaja1388 can I convert the comment to an issue ticket?

**Comment by KarthikRaja1388** [comment]
@peterhashair sure

**Comment by bx80** [comment]
> When I visit the page where the form is present and then I refresh, the data is changed automatically (example: once it is checked, the next time it is not and so on)

This PR should fix that problem once it's released, not sure we need a new issue for it?

**Pull request merged**
