### PR TITLE
[Vue] migrate PiwikMarketplaceController, piwik-marketplace directive and piwik-plugin-name directive

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off of #18955.**

Changes:
* Migrate PiwikMarketplaceController & piwik-marketplace directive to vue component.
* Migrate piwik-plugin-name directive to 
* Handle vue-directive HTML attribute to apply vue directive to vanilla HTML (ie, twig template output). Shouldn't be used in new code, mostly to use in twig code that may not get converted to Vue.
* Remove use of $location in broadcast.updatePopoverParamValue.
* Add types for dotdotdot library.

UI test failure appears to be unrelated.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developedirectoryr.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — COMMENTED** [review]
When I sorted the plugin by popular under `MarketPlace`->`Browse`->`Sort` give this error

```
materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6 Uncaught TypeError: Cannot set properties of null (setting 'tabIndex')
    at n.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:40751)
    at new n (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:35734)
    at Function.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:11708)
    at Function.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:44091)
    at n.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:173497)
    at new n (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:169473)
    at Function.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:11812)
    at Function.value (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:175649)
    at n.fn.init.jQuery.fn.<computed> (materialize.min.js?cb=db9b12e02c7b2b7ca078e7b1509b8c32:6:13212)
    at Ge (FieldSelect.vue?de7a:34:11)

```

**Comment by diosmosis** [comment]
@peterhashair I think this is a random race condition that happens in Materialize. It came up before but I couldn't find a fix for it. Can you check if it happens every time? Its all working for me locally.

**Comment by peterhashair** [comment]
@diosmosis it happens on mine every time, but people claim there is a bug on materialize and VUE. here is the solution for that, hopefully, that helps https://stackoverflow.com/questions/33704122/vuejs-materializecss-select-field/43728599#43728599

**Comment by diosmosis** [comment]
@peterhashair that link doesn't mention the tabIndex error, which has been present since before the vue migration. Can you tell me what browser you were using and any other information to help reproduce?

**Comment by peterhashair** [comment]
@diosmosis  I am using chrome. Nothing special, just pull the code. Click on the video steps. Maybe this will help 

https://localcoder.org/materialize-cannot-set-property-tabindex-of-null-at-dropdown-makedropdownfoc
```
[Development]
enabled = 0
```

https://user-images.githubusercontent.com/3783072/159612904-d58d7d40-eb64-493e-a52d-eaab9a16be3c.mp4

**Comment by diosmosis** [comment]
@sgiehl would you have time to try and reproduce the error @peterhashair is seeing? I'm still not able to reproduce it.

EDIT: ignore this was able to reproduce.

**Comment by diosmosis** [comment]
@peterhashair can you try doing a `./console cache:clear` and hard reload? That looked like it sent you to the main dashboard, instead of back to the marketplace.

EDIT: Wait, maybe that's the cause, I was trying from the admin page. Yes, I can reproduce it now. Thanks for uploading a video :+1:

**Comment by peterhashair** [comment]
@diosmosis this line causes the problem `this.dropdownEL` is null. Haven't look too deep. 
](https://github.com/matomo-org/matomo/blob/1a3d0de2d7a7b287de0acc04df7c586fe9f6a53d/node_modules/materialize-css/dist/js/materialize.js#L2571)

**Comment by diosmosis** [comment]
@peterhashair should be fixed in latest commit

**Comment by diosmosis** [comment]
@peterhashair can you take another look?

**Comment by peterhashair** [comment]
@diosmosis when you do performance search a plugin, it redirects to the dashboard page. See screen record


https://user-images.githubusercontent.com/3783072/159815616-23de5809-1ebe-4b59-9447-00b717da0d1f.mp4

**Comment by diosmosis** [comment]
@peterhashair pushed a fix, hopefully the last one. Had to modify the Marketplace controller action to allow 'query' to be obtained from $_GET as well as $_POST, so the reporting page marketplace won't redirect to the admin page (cc @sgiehl).

**Comment by peterhashair** [comment]
@diosmosis there is another one sorry. When you click `More` button. It doesn't do the popup. see screenshot

https://user-images.githubusercontent.com/3783072/159834837-e6d3bfb6-7617-4b3e-be62-710f76ae2353.mp4

**Comment by diosmosis** [comment]
@peterhashair should be fixed in the latest push. Thanks for the thorough testing! :+1:

**Review by peterhashair — APPROVED** [review]
looks good to me

**Pull request merged**
