### PR TITLE
Show search engine names in Transitions instead of keywords

### LINKED ISSUE #21143: Transitions shows search engines providers as 'Unknown'
When looking at the Transitions report in Behaviour -> Pages, the search engine providers are listed as 'Unknown'...
image

I can reproduce this in Cloud and on-premise.

The actual search engine referrer appear in the segmented visitor's log in the Pages report for the same URL.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

The transitions overlay is currently showing how many visitors came from search engines. Below that category it shows the keywords that had been used. While this was very useful years ago, it meanwhile has almost no value anymore.
All major search engines are meanwhile hiding there keywords, resulting in the list to mainly list `Unknown`

image

To deliver some value in showing that list it's more of use to show the names of search engines that were used:

image

fixes #21143

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
It seems we currently don't have this covered by a UI test. Would it be possible to add one?

**Comment by sgiehl** [comment]
I've added a UI test.

**Review by michalkleiner — APPROVED** [review]
Tested locally and displays names of search engines in the transition view as newly expected.

**Comment by michalkleiner** [comment]
Test failures unrelated.

**Comment by agency-w52** [comment]
merging this would be greatly appreciated 🙏

**Pull request merged**
