### PR TITLE
Fix dashboard interaction with menu

### LINKED ISSUE #9750: Create/Remove a new dashboard is not working as expected
### Issue 1: Create new dashboard does not work well

Reproduce:
 * Click Dashboard > Create new dashboard
 * Give a name `empty` and select Empty dashoard, click 
  * Got: New dashboard is not added to left menu
  * Expected: new dashboard "empty" added to left menu, and menu entry selected

 * Then click on "Add a widget"
  * Got: nothing happens
  * Expected: dashboard control toggles and lets user add widget

### Issue 2: Remove dashboard does not work well

 * Create a new dashboard
 * Click "Remove dashboard"
 * Got: 
  * left menu dashboard entry is not removed from left menu
  * the default dashboard layout is then loaded (maybe because the `idDashboard` in URL points to the removed dashboard)
 * Expected instead:
  * left menu dashboard entry is removed, 
  * the first custom dashboard is loaded.
 
### Issue 3: Rename is slightly buggy
 * Rename a custom dashboard
 * Got: left menu still shows old name
 * expected: left menu dashboard name updates with the new name

### Steps

 * Add UI tests for each use case
 * Check dashboard controls work as expected

Notes:
 * Possibly this is already fixed in Piwik 3.0 - the new UI tests will let us know :+1:

### PR DESCRIPTION
**Pull request by sgiehl**
fixes the problems described in #9750 

to ensure those features still work in the future, I've added some UI tests

fixes #9750

### CODE REVIEW

**Comment by tsteur** [comment]
LGTM but http://builds-artifacts.piwik.org/piwik/piwik/fixdashboardmenu/18149/Dashboard_create_new seems to fail?

**Comment by tsteur** [comment]
It works otherwise :+1:

**Comment by sgiehl** [comment]
Don't think it fails. The test was skipped before, and I guess the screenshot was maybe outdated. See https://github.com/piwik/piwik/pull/9845/files#diff-bb8133931a30cab56862c5d8dceda8eaL209

**Comment by tsteur** [comment]
Oki. Wasn't sure if it was outdated or not. LGTM in this case :+1:

**Pull request merged**
