### PR TITLE
Fix SystemTests

### PR DESCRIPTION
**Pull request by szepeviktor**
Found one `piwik`

### CODE REVIEW

**Comment by Findus23** [comment]
Hi, if I checked correctly this, the test you edited checks the author of the SecurityInfo plugin.

So to don't make the test fail, you'd need to also edit the authro of the plugin.

https://github.com/matomo-org/plugin-SecurityInfo/blob/4d72dc5be011872d6f72ffd2ce3265cf8b4052ba/plugin.json#L17-L23

**Comment by szepeviktor** [comment]
@Findus23 I've made this change based on https://travis-ci.org/matomo-org/matomo/jobs/365433166#L872-L878

**Comment by Findus23** [comment]
Then I guess I didn't check properly.

**Comment by szepeviktor** [comment]
Test fixed https://travis-ci.org/matomo-org/matomo/builds/366807249?utm_source=github_status&utm_medium=notification

Please merge.

**Comment by szepeviktor** [comment]
@mattab Could it be that PR-s are being merged for a long time with failing tests?

**Comment by tsteur** [comment]
Cheers 👍

**Comment by mattab** [comment]
@szepeviktor yes, this is the case. If you want to help make the builds green more often, we welcome your help!

**Comment by szepeviktor** [comment]
@mattab Could you copy it to the dev branch too?

**Comment by szepeviktor** [comment]
Sorry
https://github.com/matomo-org/matomo/commit/ae7e3f2a98b8eff65d4b1fb3cb250d2d47b7951f

**Pull request merged**
