### PR TITLE
Archiver: do not create done flags like "done."

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Noticed calling `getDoneStringFlagFor` w/ `$plugin = false` when `pluginOnly=1` can result in done flags like `done.`.

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@diosmosis would this be causing reading archives that were created with this flag? or would that basically not have worked already anyway?

**Comment by diosmosis** [comment]
@tsteur if there were already archives made w/ `done.`, it might be an issue... we could have an update to change those I guess (an update `where name = 'done.'`?

**Comment by tsteur** [comment]
@diosmosis could be done. Just trying to understand: Would it be otherwise an issue to having flags with `done.`? But all good to add such an update script and fixing it

**Comment by diosmosis** [comment]
> Would it be otherwise an issue to having flags with done.? 

For leaving them, I think the only issue is if they're no longer queried and `done` archives aren't present. Now it might be an issue in that we might not be querying them properly? It's hard to tell w/ this issue exactly where it causes problems.

**Comment by diosmosis** [comment]
Note: I did see them created in prod when making plugin specific archives, maybe nowhere else.

**Comment by tsteur** [comment]
Also quickly another question: Would it cause issues if there are afterwards maybe two archives with a `done` flag? And they might contain different reports? I know it's a bit hard to say what would happen. I could imagine that some archive may be deleted or reports would be only read from one archive?

**Comment by diosmosis** [comment]
> Would it cause issues if there are afterwards maybe two archives with a done flag?

I'm not sure what you mean? After the update, having two archives w/ `done` should be fine since that's what we want (all archives would have the `done` flag or done w/ plugin/segment.

**Comment by tsteur** [comment]
All good then 👍

**Comment by diosmosis** [comment]
merging this, fyi @tsteur

**Pull request merged**
