### PR TITLE
Fixed view type for visitor log

### LINKED ISSUE #6928: Visitor log may be displayed with many columns
It was reported [in the forums](http://forum.piwik.org/read.php?2,123190) (and several more posts) that the Visitor Log can appear broken with many columns displayed instead of only 3 columns.

To reproduce the issue you can edit the table preference setting with:
```
UPDATE `piwik`.`piwik_option` SET `option_value` = '{"isFooterExpandedInDashboard":true,"filter_limit":100,"viewDataTable":"table"}' WHERE `piwik_option`.`option_name` = 'viewDataTableParameters_root_Live.getLastVisitsDetails';
```

where `root` is your username. Setting `"viewDataTable":"table"` creates the bug. 

Maybe this is caused because the Visitor Log uses a custom table visualisation with an ID of `'Piwik\Plugins\Live\VisitorLog'` and it expected this `viewDataTable` value?

### PR DESCRIPTION
**Pull request by sgiehl**
This PR aims to fix #6928 by allowing to set a fixed view type for reports.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @sgiehl - thanks for the PR!
looks good to me. @tsteur maybe you have some opinion as well?

**Comment by tsteur** [comment]
I'm not sure re the name `isDefaultTypeFixed`. In the context of `Report` I would not think of a fixed ViewDataTable/Visualization. 

Would maybe also rather check for `isFixed...` in https://github.com/piwik/piwik/blob/2.10.0/core/ViewDataTable/Factory.php#L92 instead of in report class then it works everywhere as `ViewDataTabe::build` is also called in other places. We are getting the report eg here: https://github.com/piwik/piwik/blob/2.10.0/core/ViewDataTable/Factory.php#L161

**Comment by sgiehl** [comment]
@tsteur better that way?

**Comment by tsteur** [comment]
Sorry can you maybe rename `isDefaultTypeFixed` to something like `alwaysUseDefaultViewDataTable` or `isViewDataTableFixed` or maybe you have a better idea? I know it is not much better but a bit more consistent with `getDefaultTypeViewDataTable` for plugin developers. Not sure why I named it `getDefaultTypeViewDataTable` initially, not such a great name... 

Side note: Would be nice to use for Piwik 3.0 the wording `Visualization` instead of `ViewDataTable` even if it is technically wrong (as the base class is currently called `ViewDataTable` which we would have to rename) but much more clearer for everyone what is meant.

**Comment by sgiehl** [comment]
@tsteur changed method name to ```alwaysUseDefaultViewDataTable ```. If everything is fine now, feel free to merge.

**Pull request merged**
