### PR TITLE
allow to disable tracking failure notifications

### LINKED ISSUE #14447: Feature request: option to disable tracking failure notifications
Hello,

as asked in the forum [1]: please add an option to disable the automatic notifications about tracking failures.

Cheers,
Timo

[1] https://forum.matomo.org/t/how-to-disable-e-mails-about-tracking-failures/32854

### PR DESCRIPTION
**Pull request by fdellwing**
Fixes  #14447 in a very basic way.

### CODE REVIEW

**Review by diosmosis — APPROVED** [review]
Code looks good. @mattab what do you think about the new INI option?

**Comment by tsteur** [comment]
@fdellwing @diosmosis usually these settings start with `enable_`

**Comment by diosmosis** [comment]
👍 to prefix w/ `enable_` for consistency

**Comment by fdellwing** [comment]
Updated the PR :)

**Pull request merged**
