### PR TITLE
Minor changes to create super user step in installation

### LINKED ISSUE #9321: Minor changes to Installation > Create Super User step for German users
When installing Piwik, at the Super User installation step ([screenshot](https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_superuser.png)), 
when we detect that the browser language is German, then:

- we write `Piwik PRO Gmbh` instead of `Piwik PRO`
- link to https://piwikpro.de/ instead of piwik.pro
- and we un-check the second checkbox for `Piwik PRO Gmbh` newsletter

These minor changes are legally required to collect data for German users.

Fyi: we will also need to enable a double opt-in mechanism in this mailing newsletter

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #9321

### CODE REVIEW

**Comment by tsteur** [comment]
I wonder if we can write a test for this form? 

@mattab can you have a look whether it works as you wanted?

**Comment by sgiehl** [comment]
I thought about writing a test for it. But as the changes are only for German language, tests might fail when translations are updated. That would make updating translations more time consuming...

**Comment by tsteur** [comment]
>  But as the changes are only for German language

That's why it might be could to have some. I guess not many of us use German language (I don't) so we would maybe not notice when anything breaks there and it seems to be important for legal maybe. I reckon it would be good here when the test fails when this key is updated but I'm not really aware when it might fail. Maybe it would be possible to write a test in a way that is not so much dependent on that key?

**Comment by mattab** [comment]
> That would make updating translations more time consuming...

in that case it would be ok as it is quite rare that a German string used on the installation screen will change. Btw to show the page in given language it simply works to add `&language=de` to url.

**Comment by sgiehl** [comment]
I've added a simple UI test:

**Comment by tsteur** [comment]
LGTM

**Pull request merged**
