### PR TITLE
Use variadics/splat instead of call_user_func_array()/func_get_args()

### PR DESCRIPTION
**Pull request by staabm**
### Description:

the more explicit form is easier to read and static analysis tooling friendly

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by staabm** [comment]
wow, its suprising how super slow this CI pipeline is. are there any efforts planned or known issues I could work on to improve it?

**Review by michalkleiner — APPROVED** [review]
Nice, this looks good to me and I also like the code being more explicit and easier to read, so it's 👍 from me. Tests are passing as well.

What do you think @sgiehl/@bx80?

**Comment by michalkleiner** [comment]
Hi @staabm, thank you for the contribution.

Yes, we are aware of the speed of the pipeline and long-term are looking into speeding things up by optimising the tests, dropping older PHP version support (over time), rearranging the UI tests into different groups and other kinds of optimisations. We have an ongoing issue from way-back-when that we can repurpose for this as some of the info there is outdated (https://github.com/matomo-org/matomo/issues/6312).

Before starting working on any changes we can have a somewhat async chat there on the options etc so no one wastes their time and effort.

**Comment by sgiehl** [comment]
Actually I wasn't aware that the splat operator was introduced in PHP that "early". For some reason I had in mind, that would have been as of PHP 7.4, and therefor didn't use it here yet...

**Pull request merged**
