### PR TITLE
[Hotfix] remove &nbsp; in template

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

remove nbsp

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Just out of curiosity, does that mean we shouldn't used &nbsp; in Vue files at all? If so maybe we should document that somewhere

**Comment by diosmosis** [comment]
@sgiehl Seems like it, unless its ok to remove/not apply the specific test in ReleaseCheckListTest. Unfortunately I have no idea why its there.

I have it on my list to document it in developer-documentation. It's still possible to use it, but you'd have to use a computed property.

**Comment by sgiehl** [comment]
Guess it would otherwise be fine to ignore the compiled Vue files in that check. Iirc the check was there to prevent accidentally inserted invisible/special characters

**Comment by diosmosis** [comment]
I see, that's what I thought at first, but I guess I overthought.

**Pull request merged**
