### PR TITLE
Fix overflow handling of datatables

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

With introducing the datatable scroller in #14594, there actually shouldn't be any further need of checking if the table has enough space, as it always fits. Guess adding a overflow-y was needed to ensure the overlays were at least visible with scrolling. 
The current handling actually always displays a vertical scroll bar as soon as the table would be too wide (without the datatable scroller), causing all overlays to be displayed in the report instead of overlaying it:

Chrome:
image

Firefox & IE:
image

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@sgiehl I'm not sure what this fixes? Is there an issue for it?

**Comment by sgiehl** [comment]
There is no issue yet afaik. Came across that issue when testing the page performance stuff. You can easily reproduce it with any dashboard widget that would be wider than the available space. You can use the page url widget for example in a small dashboard column. It will always show the vertical scrollbar, even though that isn't actually needed. When you click one of the footer icons, the overlays aren't showing correctly because of that.

**Comment by diosmosis** [comment]
Can't reproduce the issue, but I didn't notice any problem w/ the change so I guess it's good to at least remove unneeded code. It's possible I didn't test the exact place where this happens though...

**Comment by sgiehl** [comment]
@diosmosis Steps to reproduce:
Go to the dashboard. Add the pages widget. The widget should always show an vertical scrollbar. Click the limit selection in the footer, this should kind of break the layout (which should not happen with this changes)

**Comment by diosmosis** [comment]
@sgiehl was able to reproduce, he fix works 👍

**Review by diosmosis — APPROVED** [review]

**Pull request merged**
