### PR TITLE
Ensure to send performance timings as integer values

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

refs #17371

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
build js

**Comment by diosmosis** [comment]
Should we maybe do this server side as well to be safe in case people use the tracker API directly or use log importing?

**Review by diosmosis — CHANGES_REQUESTED** [review]
If adding server side changes, can we also change a test so it uses a float value in tracking?

**Comment by sgiehl** [comment]
@diosmosis looking at the code it seems the values should actually already be casted to integer server side. At least they are defined as those here:
https://github.com/matomo-org/matomo/blob/23d551750442d12975ee9c2af6f73ac9bbf75c1a/core/Tracker/Request.php#L415-L420

So the changes here actually won't have a big effect. But it's still useless to send floats if we use them as integers...

**Comment by diosmosis** [comment]
makes sense :+1:

**Pull request merged**
