### PR TITLE
[Vue] in site selector execute search on searchTerm change rather than keydown

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

…so special keys dont have an effect

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis this seems to work as expected. While testing I found some other issues / improvements for the site selector.

- Each time a search request is sent from the site selector, it also sends a request to `SitesManager.getNumWebsitesToDisplayPerPage`. Guess it should be enough to only do that once on init?

- When the search term is changed, it seems that previous requests might still be executed and result in weird behavior. You can reproduce that by pasting/typing a search term and directly clicking in the search box again (which cleans the term). The results for the search will be displayed nevertheless and the input box is hidden

**Comment by diosmosis** [comment]
@sgiehl fixed those and one other issue I found

**Comment by peterhashair** [comment]
@diosmosis not sure that's on my local, but when I try to run vue:build CoreHome it shows the error below.
image

**Comment by diosmosis** [comment]
@peterhashair can't reproduce. Are the files there? If you clear the webpack cache is the error still there?

**Comment by peterhashair** [comment]
@diosmosis sorry that my bad, my git was on the case insensitive. didn't pick up the `Menudropdown` to `MenuDropdown` change. but I test this . work as expected

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
