### PR TITLE
SystemTestsCore: fix ImportLogsTest race condition on visits with identical date/time

### PR DESCRIPTION
**Pull request by rr-it**
### Description:

Make `Piwik\Tests\System\ImportLogsTest::testApi` always complete successfully.

Sometimes this test failed and sometimes it succeded.

```
2024-01-30T14:59:34.8855103Z 1) Piwik\Tests\System\ImportLogsTest::testApi with data set #5 (array('Live.getLastVisitsDetails', 'VisitsSummary.get'), array(1, '2012-08-09', 'month', 'pageUrl=@/docs/,pageUrl=@/blo...manage', array(5), '_complexActionSegment'))
2024-01-30T14:59:34.8857423Z Piwik\Tests\System\ImportLogsTest: Differences with expected in '/home/runner/work/matomo/matomo/matomo/tests/PHPUnit/Framework/TestCase/../../System/processed/test_ImportLogs_complexActionSegment__Live.getLastVisitsDetails_month.xml'
2024-01-30T14:59:34.8858959Z Failed asserting that two DOM documents are equal.
```

This was caused by two fake log entries with an identical date/time …

https://github.com/matomo-org/matomo/blob/6c9413be6fbb432ad621f55a11debf4090581a67/tests/resources/access-logs/fake_logs_enable_all.log#L14-L16

… in combination with an insufficient sort order for this case - `ORDER BY log_visit.visit_last_action_time` only:

https://github.com/matomo-org/matomo/blob/6c9413be6fbb432ad621f55a11debf4090581a67/plugins/Live/Model.php#L560-L565

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Nice find @rr-it!

Just being curious and perhaps a question for @sgiehl or @tsteur — could it have been on purpose that we had identical log entries just differing in the IP address (IPv4 vs IPv6) in the dummy logs? Does some webserver log in this way if there are multiple IPs configured for an interface? I suspect not, but worth double checking.

If the above is not a concern, the rest looks good!

**Comment by tsteur** [comment]
> Just being curious and perhaps a question for @sgiehl or @tsteur — could it have been on purpose that we had identical log entries just differing in the IP address (IPv4 vs IPv6) in the dummy logs? Does some webserver log in this way if there are multiple IPs configured for an interface? I suspect not, but worth double checking.

My initial assumption would be, because no other test is failing, that it's not on purpose and the change be okay?

Looking at the commit that added it in https://github.com/matomo-org/matomo/blob/771ae1342fef9454025d1aaa19569d8094bc34a8/tests/resources/access-logs/fake_logs_enable_all.log#L16 it's also likely not on purpose that it has same time?

If needed, you could otherwise check though which tests are using the fixture

**Comment by michalkleiner** [comment]
Ok, the team thinks this is ok then so do I :)

@rr-it could you please rebase your fix on `5.0.x-dev` branch so we can include the fix in the next patch version?

**Comment by rr-it** [comment]
@michalkleiner Done. This fix is rebased on 5.0.x-dev branch.

**Comment by michalkleiner** [comment]
@sgiehl I think the phpcs failure is because it runs the merge check against the 5.x-dev branch, the 5.0.x-dev doesn't have the lines in the file it's complaining about. What do you reckon to do here?

**Comment by michalkleiner** [comment]
I guess we can ignore it in this instance?

**Comment by sgiehl** [comment]
The CS failure is the result of not having all changes from 5.0.x on 5.x. I've no merged over all changes and fixed CS on 5.x-dev. Guess that should fix CS on this PR

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
