### PR TITLE
Wait for end event before exiting UI Tests

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

replaces #21473

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by achakko** [comment]
@sgiehl Yes this seems to work. An end state was recorded in testomat for this run, see screenshot attached, and the test reporting in actions seem fine as well. I'd love for this to be merged to avoid any further api blocks for test reporting. 
image

**Review by achakko — APPROVED** [review]
Approved based on https://github.com/matomo-org/matomo/pull/21760#issuecomment-1877415430 if it helps 👍

**Review by bx80 — APPROVED** [review]
This change looks good to me :+1:

Should we be able to see the list of failed tests in the testomat run report when selecting the 'failed' tab?

image

**Review by michalkleiner — APPROVED** [review]

**Comment by achakko** [comment]
> This change looks good to me 👍
> 
> Should we be able to see the list of failed tests in the testomat run report when selecting the 'failed' tab?
> 
> image

Thanks @bx80 Yes, it should show the failed tests if you click on Failed like below. The error you see can also happen if some tests from repo were not updated in testomat which I can update 
image

**Pull request merged**
