### PR TITLE
Add instruction tab for React.js to no data screen & improve JS code instruction tab

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Merged React no data screen and JS code cleanup.
Fixes: #PG-2779, #PG-2799

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by bx80** [comment]
@AltamashShaikh I think the TagManager submodule reference might need updating in this PR? 

I got this error when loading the no-data react tab:
```
Too few arguments to function Piwik\Plugins\TagManager\TagManager::embedReactTagManagerTrackingCode(), 
1 passed and exactly 3 expected
in /var/www/matomo/plugins/TagManager/TagManager.php line 271
```
The same error is shown on the UI tests. Running `git submodule update` after checking out this branch results in a detached head for the TagManager submodule. Checking out the TagManager 4.x-dev branch fixed the issue for me locally.

You probably need to do something like:
```
cd [matomo folder]
git checkout cherrypick-react-and-js-cleanup
cd plugins/TagManager
git checkout 4.x-dev
cd ../..
git add plugins/TagManager
git commit -m "Update submodule"
git push
```
Which should update this PR to reference the 4.x-dev branch for TagManager and fix the UI test.

**Comment by AltamashShaikh** [comment]
@bx80 updated submodule as suggested

**Comment by AltamashShaikh** [comment]
@sgiehl @bx80 are we good to merge this ?

**Review by sgiehl — APPROVED** [review]
Only had a rough look through the code and did some quick testing in the UI, as those changes should already have been reviewed in detail for 5.x-dev. Looks good for me though.

**Pull request merged**
