### PR TITLE
Add Tibet back to China map

### PR DESCRIPTION
**Pull request by huangzhong**
Remove commit 4e47c8 (Remove Tibet from the map) #6006

### CODE REVIEW

**Comment by khlipeng** [comment]
Tibei and Taiwan should be a part of China

**Comment by xiasun** [comment]
I wonder when it comes to different points of view, based on which knowledge are you going to decide whether accept it or not?

For example, you accepted Tibet here as an independent country, why won't you accept California as an independent country? I want to learn about your common rule for this kind of issue.

Seriously this is important for an open source software developer.

**Comment by justjavac** [comment]
Tibei and Taiwan should be a part of China

**Comment by huruji** [comment]
Tibei and Taiwan should be a part of China

**Comment by jamesjieye** [comment]
@mattab This is not cool!!! You are not acting based on common knowledge.

**Pull request closed without merging**
