### PR TITLE
Added code to include schedule command for plugins while generating github action

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added code to include schedule command for plugins while generating github action.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
Looks good :+1: 
I tested running the command to generate a config for a plugin and it added the schedule as expected.

**Comment by sgiehl** [comment]
@AltamashShaikh this looks fine. Just a general thought around that. Might it make sense to provide the cron value as parameter? That would allow us to differ it from plugin to plugin a bit. Otherwise all plugin actions would be triggered at the exact same time, causing a long action queue to block any further requests for some time.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh this looks fine. Just a general thought around that. Might it make sense to provide the cron value as parameter? That would allow us to differ it from plugin to plugin a bit. Otherwise all plugin actions would be triggered at the exact same time, causing a long action queue to block any further requests for some time.

@sgiehl Makes sense, will update the PR :+1:

**Comment by AltamashShaikh** [comment]
@sgiehl Added `--schedule-cron="0 2 * * 6"` option which can be used by anyone in generic

**Review by bx80 — APPROVED** [review]
Works well for me using the new parameter. With `--schedule-cron="0 3 * * 7"` a cronjob is added to the test action, without the parameter no cronjob is added :+1:

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] n/a [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] None [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] n/a [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] Not needed [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] Not needed Existing documentation updated if needed

**Pull request merged**
