### PR TITLE
Update workflow with actions/checkout@v3 to actions/checkout@v4

### PR DESCRIPTION
**Pull request by mikkeschiren**
### Description:

actions/checkout@v3 is deprecated, and shouldn't be used any more. 
Also some minor fixes on removal of whitespaces.

A warning can be seen e.g. in the PHPCS action:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Review

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Hi @mikkeschiren and thank you for your contribution and opening the PR.
Would you happen to have a link to some information about the v3 action being deprecated?

**Comment by mikkeschiren** [comment]
> Hi @mikkeschiren and thank you for your contribution and opening the PR. Would you happen to have a link to some information about the v3 action being deprecated?

Hi, sorry for not including that, you can see it in the output here as an example: https://github.com/matomo-org/matomo/actions/runs/7758937941

More information here: https://github.com/actions/checkout/pull/1436

**Comment by michalkleiner** [comment]
Since all the checkout actions seem to work correctly with v4 and the failures are only the flaky tests we already know about, I'm happy with this.

I'm of two minds as to which branch it should target. For me it's a maintenance PR and could/should target 5.0.x-dev and then merged up to 5.x-dev, do you agree @sgiehl?

**Review by michalkleiner — APPROVED** [review]

**Comment by sgiehl** [comment]
No big preference where to merge that to. As v3 will still work for a long time, there is no real need to have it in 5.0.x-dev, but wouldn't hurt either. As changing the base branch and rebasing the origin would be additional work I would also be fine with simply merging it as is.

**Pull request merged**
