### PR TITLE
No longer require idsite in addtracker

### LINKED ISSUE #14781: JavaScript tracker: change `Piwik.addTracker()` to allow not setting an idSite
Could we change `Piwik.addTracker()` to allow not setting an idSite there, and only have the first parameter URL instead?

This  is needed to fix a big regression in Tag Manager.

## Why needed now?

This  started being an issue a few weeks since we changed: https://github.com/matomo-org/tag-manager/commit/f0e368d4e58ba9af86551fad4b7b578a5bb9761c as we are no longer setting the idsite.

## Reproduce

Steps sent by a customer (haven't reproduced it myself, but can see the error live on their site):

* Use tag manager and Matomo separately for example:
```
 <!-- Matomo -->
    <script type="text/javascript">
        var _paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="https://URL_HERE/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src='URL_HERE/matomo.js'; s.parentNode.insertBefore(g,s);
        })();
    <!-- End Matomo Code -->

​    <!-- Matomo Tag Manager -->
        window._mtm = window._mtm || [];
        window._mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src='https://URL_HERE/js/container_uAZDfecL.js'; s.parentNode.insertBefore(g,s);
    </script>
    <!-- End Matomo Tag Manager -->

```
* Create a container
* Create custom html Tag with the following code:
```
        try {
            window._mtm = window._mtm || [];
            window._mtm.push(data);
            console.log('mtm', data);
        }
        catch (e) {
            console.log('matomo error', e);
        }

```

(`data` could be eg. `{ category: "clic-réseaux-sociaux", event: "clic-réseaux-sociaux", label: "nom-réseaux-facebook" } `

## JS Error when using tag manager:

```
matomo error Error: A siteId must be given to add a new tracker
at Q.addTracker (matomo.js:63)
at Object.addTracker (matomo.js:74)
at container_uAZDfecL.js:357
at Object.push (container_uAZDfecL.js:43)
at Object.fire (container_uAZDfecL.js:356)
at g._doFire (container_uAZDfecL.js:36)
at g.fire (container_uAZDfecL.js:36)
at container_uAZDfecL.js:33
at Array.<anonymous> (container_uAZDfecL.js:384)
at t.push (container_uAZDfecL.js:21)
```

### PR DESCRIPTION
**Pull request by tsteur**
fix https://github.com/matomo-org/matomo/issues/14781

### CODE REVIEW

**Review by sgiehl — APPROVED** [review]
Guess the failing JS tests need to be fixed in TagManager: https://travis-ci.org/matomo-org/matomo/jobs/573555566#L750
Otherwise looks good to merge.

**Comment by Asjenw** [comment]
@sgiehl @tsteur When is this planned to be released? We constantly get errors at our website, probably because of this issue. I saw the release date being changed from 4-9 into 15-10, is that the definitive date or is it likely to change again?

**Comment by tsteur** [comment]
It will be included in the next release. The current beta already includes this change I think

**Comment by Asjenw** [comment]
Hi Thomas,

Ok. How can I switch to the current beta? My Matomo Cloud version is 3.11.0
it says, but I cannot see where to change it into a beta version.

Regards,

Asjen

Op di 17 sep. 2019 om 22:36 schreef Thomas Steur <notifications@github.com>:

**Comment by tsteur** [comment]
https://matomo.org/faq/how-to-update/faq_159/

**Comment by Asjenw** [comment]
Hi Thomas,

Thanks, but I cannot find that setting under General Settings. I'm not
hosting Matomo myself but using Matomo Cloud (
https://hypotheekwacht.matomo.cloud/). Is it also possible to update to a
beta release when you don't host Matomo on-premise?

Regards,
Asjen

Op wo 18 sep. 2019 om 22:32 schreef Thomas Steur <notifications@github.com>:

**Comment by tsteur** [comment]
@Asjenw we will update it there for you likely in the next 24-48 hours. When you have such issues on cloud simply get in touch with our support by mail: support at matomo.cloud

**Comment by Asjenw** [comment]
Thanks! I'll wait a few days, see if it works indeed and otherwise email
support.

Regards,
Asjen

**Pull request merged**
