### PR TITLE
Allow emails to be themed.

### LINKED ISSUE #12919: Email header bar: let developers customise the background color and font color
In our [scheduled emails](https://matomo.org/docs/email-reports/) and in custom alerts emails we send, we now display our Header bar with logo and link to the dashboard:

scheduled report
custom alert

-> The goal of this issue is to make the header bar font color, and header bar background color, ideally re-use the existing colors from the App header bar. 

cc @tsteur

### PR DESCRIPTION
**Pull request by diosmosis**
Changes:
- Add new event `Emails.setThemeVariables` that modifies the variables used to set the fonts/colors in emails. Currently internal. Used by ExampleTheme.
- Change twig templates to use hex colors where it was using rgb colors before (apparently hex colors are better supported in email clients).

An email w/ ExampleTheme settings & a serif font:

image

Fixes #12919

### CODE REVIEW

**Comment by mattab** [comment]
Noticed the color of Table of content regressed in the branch (it used to be darker grey):

screenshot from 2018-08-02 01-48-21

**Comment by mattab** [comment]
The main use case for this issue/PR is to be compatible with White Label. Just tested to configure WhiteLabel like this:

screenshot from 2018-08-02 01-55-00

and the HTML email report is un-changed.

-> was it supposed to work maybe?

**Comment by diosmosis** [comment]
Created a WhiteLabel PR, here is a pic:

image

BTW, original issue should mention WhiteLabel if that is the main reason for it.

**Comment by mattab** [comment]
> BTW, original issue should mention WhiteLabel if that is the main reason for it.

oops, sorry forgot to mention this!

LGTM, just the tests needs fixing (minor changes in the html/pdf reports)

**Review by mattab — APPROVED** [review]

**Comment by tsteur** [comment]
As mentioned in other PR eventually be good to 

1) Use an object instead of an array for `getDefaultEmailStyles` so auto completion and refactoring etc works . Like `class EmailStyles { public $brandNameLong = ''; }`

2) Eventually we should define theme colors only in one place. Now a theme designer needs to set it in php plus less. Ideally we would only do this in PHP. There could be one Theme object to configure theme colors like `class ThemeConfiguration { public $colorText = ''; public $colorLink = ''; }` and then the class `EmailStyles` would remove quite a few properties and use where possible those colors. There wouldn't need to be any `theme.less` anymore as all colors would be possible to configure through PHP in one place. PHP would then add the less theme variables through `AssetManager.addStylesheets` event.

I think this should be done for consistency maybe at the latest in Matomo 4 or 5, or now if not too much work. Could be quick. FYI @mattab @diosmosis

**Comment by diosmosis** [comment]
will do

**Comment by diosmosis** [comment]
Created a PR and this issue: https://github.com/matomo-org/matomo/issues/13251

**Pull request merged**
