### PR TITLE
#8734 Bad filesystem detection (NFS)

### PR DESCRIPTION
**Pull request by nuxwin**

### CODE REVIEW

**Comment by nuxwin** [comment]
@mattab 

The following check which was previously added in master:

```
$commandFailed = (false !== strpos($output, "no file systems processed"));
```

was not sufficient. Thing about LANG environment variable which can be different.

**Comment by tsteur** [comment]
Did only adding the `trim()` fix the issue?

**Comment by nuxwin** [comment]
@tsteur 

Yes ;)

**Comment by tsteur** [comment]
Nice, thx

**Pull request merged**
