### PR TITLE
Fix exporting main metrics with a period of weeks and export format CSV

### LINKED ISSUE #17441: Exporting main metrics with a period of "week" as CSV produces broken exports
When exporting the main metrics with a period of _week_ as CSV the resulting export is broken, because the date span contains a comma, which is also the column separator used in CSVs.

## Expected Behavior

Exporting main metrics with a period of _week_ as CSV results in usable data.
Example: 
```csv
Date,Unique visitors,Visits,Users,Actions,Maximum actions in one visit,Bounces,Total time spent by visitors (in seconds),New Visits,Actions by New Visits,Unique new visitors,New Users,max_actions_new,Bounce Rate for New Visits,Avg. Actions per New Visit,Avg. Duration of a New Visit (in sec),Visitors from Search Engines,Visitors from Social Networks,Visitors from Direct Entry,Visitors from Websites,Visitors from Campaigns,Percent of Visitors from Direct Entry,Percent of Visitors from Search Engines,Percent of Visitors from Campaigns,Percent of Visitors from Social Networks,Percent of Visitors from Websites,PagePerformance_network_time,PagePerformance_network_hits,PagePerformance_servery_time,PagePerformance_server_hits,PagePerformance_transfer_time,PagePerformance_transfer_hits,PagePerformance_domprocessing_time,PagePerformance_domprocessing_hits,PagePerformance_domcompletion_time,PagePerformance_domcompletion_hits,PagePerformance_onload_time,PagePerformance_onload_hits,PagePerformance_pageload_time,PagePerformance_pageload_hits,Avg. network time,Avg. server time,Avg. transfer time,Avg. DOM processing time,Avg. DOM completion time,Avg. on load time,Avg. page load time,Conversions,Visits with Conversions,Revenue,Conversion Rate,nb_conversions_new_visit,nb_visits_converted_new_visit,revenue_new_visit,conversion_rate_new_visit,Pageviews,Unique Pageviews,Downloads,Unique Downloads,Outlinks,Unique Outlinks,Searches,Unique Keywords,Bounce Rate,Actions per Visit,Avg. Visit Duration (in seconds),Avg. Duration of a Returning Visit (in sec),Avg. Actions per Returning Visit,Bounce Rate for Returning Visits,Returning Visits,Actions by Returning Visits,Unique returning visitors,Returning Users,Maximum actions in one returning visit,Distinct search engines,Distinct social networks,Distinct keywords,Distinct websites,Referrers_distinctWebsitesUrls,Distinct campaigns,nb_conversions_returning_visit,nb_visits_converted_returning_visit,revenue_returning_visit,conversion_rate_returning_visit
"2021-02-22,2021-02-28",1,1,0,1,1,1,0,1,1,1,0,1,100%,1,0s,0,0,1,0,0,0%,0%,0%,0%,0%,0.15,1,0.549,1,0.073,1,0.466,1,0.562,1,0.066,1,1.866,1,0.15s,0.55s,0.07s,0.47s,0.56s,0.07s,1.87s,0,0,0,0%,0,0,0,0%,1,1,0,0,0,0,0,0,100%,1,0s,0s,0,0%
"2021-03-15,2021-03-21",448,1228,36,2317,23,805,136761,530,1012,422,36,23,67%,1.9,2 min 26s,319,110,171,521,107,1%,2%,1%,1%,3%,136.293,1234,602.219,1234,206.332,1234,1393.43,1234,864.863,1234,234.408,1234,3437.545,1234,0.11s,0.49s,0.17s,1.13s,0.7s,0.19s,2.79s,204,184,35268.78,14.98%,66,32,16804.19,6.04%,1831,1553,110,110,80,80,37,29,66%,1.9,1 min 51s,1 min 25s,1.9,65%,698,1305,299,31,23,9,3,131,153,239,12,0,0,0,0%

```

## Current Behavior

Exporting main metrics with a period of _week_ as CSV results in broken data.
Example: 
```csv
Date,Unique visitors,Visits,Users,Actions,Maximum actions in one visit,Bounces,Total time spent by visitors (in seconds),New Visits,Actions by New Visits,Unique new visitors,New Users,max_actions_new,Bounce Rate for New Visits,Avg. Actions per New Visit,Avg. Duration of a New Visit (in sec),Visitors from Search Engines,Visitors from Social Networks,Visitors from Direct Entry,Visitors from Websites,Visitors from Campaigns,Percent of Visitors from Direct Entry,Percent of Visitors from Search Engines,Percent of Visitors from Campaigns,Percent of Visitors from Social Networks,Percent of Visitors from Websites,PagePerformance_network_time,PagePerformance_network_hits,PagePerformance_servery_time,PagePerformance_server_hits,PagePerformance_transfer_time,PagePerformance_transfer_hits,PagePerformance_domprocessing_time,PagePerformance_domprocessing_hits,PagePerformance_domcompletion_time,PagePerformance_domcompletion_hits,PagePerformance_onload_time,PagePerformance_onload_hits,PagePerformance_pageload_time,PagePerformance_pageload_hits,Avg. network time,Avg. server time,Avg. transfer time,Avg. DOM processing time,Avg. DOM completion time,Avg. on load time,Avg. page load time,Conversions,Visits with Conversions,Revenue,Conversion Rate,nb_conversions_new_visit,nb_visits_converted_new_visit,revenue_new_visit,conversion_rate_new_visit,Pageviews,Unique Pageviews,Downloads,Unique Downloads,Outlinks,Unique Outlinks,Searches,Unique Keywords,Bounce Rate,Actions per Visit,Avg. Visit Duration (in seconds),Avg. Duration of a Returning Visit (in sec),Avg. Actions per Returning Visit,Bounce Rate for Returning Visits,Returning Visits,Actions by Returning Visits,Unique returning visitors,Returning Users,Maximum actions in one returning visit,Distinct search engines,Distinct social networks,Distinct keywords,Distinct websites,Referrers_distinctWebsitesUrls,Distinct campaigns,nb_conversions_returning_visit,nb_visits_converted_returning_visit,revenue_returning_visit,conversion_rate_returning_visit
2021-02-22,2021-02-28,1,1,0,1,1,1,0,1,1,1,0,1,100%,1,0s,0,0,1,0,0,0%,0%,0%,0%,0%,0.15,1,0.549,1,0.073,1,0.466,1,0.562,1,0.066,1,1.866,1,0.15s,0.55s,0.07s,0.47s,0.56s,0.07s,1.87s,0,0,0,0%,0,0,0,0%,1,1,0,0,0,0,0,0,100%,1,0s,0s,0,0%
2021-03-15,2021-03-21,448,1228,36,2317,23,805,136761,530,1012,422,36,23,67%,1.9,2 min 26s,319,110,171,521,107,1%,2%,1%,1%,3%,136.293,1234,602.219,1234,206.332,1234,1393.43,1234,864.863,1234,234.408,1234,3437.545,1234,0.11s,0.49s,0.17s,1.13s,0.7s,0.19s,2.79s,204,184,35268.78,14.98%,66,32,16804.19,6.04%,1831,1553,110,110,80,80,37,29,66%,1.9,1 min 51s,1 min 25s,1.9,65%,698,1305,299,31,23,9,3,131,153,239,12,0,0,0,0%

```

## Possible Solution

Escape the date span for exports with a period of week using double quotes. Or use a different character between the two dates in the date span. 

## Steps to Reproduce (for Bugs)

1. Go to "Visitors" > "Overview"
2. At the "Visits Over Time" graph change the period to "week"
3. Export the dataset with export format "CSV".
4. The CSV is broken.

This is reproducible on https://demo.matomo.cloud

## Context

 --

## Your Environment

* Matomo Version: 4.2.1
* PHP Version: 8.0.3
* Server Operating System: CentOS 8.3
* Additionally installed plugins: 

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by ziegenberg**
### Description:

FIXES  #17441.

Escape the first column in CSV exports because it might contain a date span, and the date span will contain a comma.

_If a test to prevent regressions is desired, I would need help with implementing that._

_Note:_ As soon PHP 8 is the required minimum escaping could be limited with `str_contains()`.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review was done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by ziegenberg** [comment]
Ready for review.

**Comment by ziegenberg** [comment]
I did not run the tests locally and they might need to be updated.

**Comment by sgiehl** [comment]
Wondering if it might make sense to use a method like this to build a correctly escaped CSV string

```php
function convertArrayToCSV($data) {
    $fh = fopen('php://temp', 'rw');
    fputcsv($fh, array_keys(current($data)));

    foreach ($data as $row) {
        fputcsv($fh, $row);
    }
    rewind($fh);
    $csv = stream_get_contents($fh);
    fclose($fh);

    return $csv;
}
```
Haven't tested it though, but could maybe prevent other issues with CSV.

**Comment by ziegenberg** [comment]
@sgiehl There is also `buildCsvString()` which is only called from `renderDataTable()`. So creating an extra csv-rendering function for `renderDataTableMap()` seems a bit redundant.

May it be feasible to combine both?

**Comment by sgiehl** [comment]
Sorry. Seems I didn't have a closer look before 🙈 
I guess it might simply be enough to use the `formatValue` method, which should automatically escape the string if needed.

**Comment by ziegenberg** [comment]
I rebased onto current _4.x-dev_ and modified it to use `formatValue()`. It does seem to do the trick! :D

**Review by sgiehl — APPROVED** [review]

**Comment by sgiehl** [comment]
Thanks for updating the PR. Looks good now. Will wait until the tests finished and if all relevant tests are passing will merge it.

**Comment by ziegenberg** [comment]
should we add some unit tests for regression testing?

**Comment by sgiehl** [comment]
> should we add some unit tests for regression testing?

That would be nice. Maybe we could add one here: https://github.com/matomo-org/matomo/blob/4.x-dev/tests/PHPUnit/System/CsvExportTest.php#L35-L39

**Comment by ziegenberg** [comment]
I guess `CsvExportTest::$fixture = new TwoVisitsWithContents();` [here](https://github.com/matomo-org/matomo/blob/78387db99ce0e0fe6d7226fd8cb40a5458c4353a/tests/PHPUnit/System/CsvExportTest.php#L81) would need to be extended as `$dateTime = self::$fixture->dateTime;` is currently set to a single date and not a time span?

**Comment by sgiehl** [comment]
In the test array linked above you can simply add something like this:
```php
            array($apiToCall, array('idSite'                 => $idSite,
                                    'date'                   => Date::factory($dateTime)->toString() .','. Date::factory($dateTime)->addDay(21)->toString(),
                                    'period'                 => 'week',
                                    'format'                 => 'csv',
                                    'testSuffix'             => '_multi')),
```

Running the tests should then produce 2 new result files in processed folder, that can simply be moved to expected files.

**Comment by ziegenberg** [comment]
I guess, this is as good as it gets for the moment. Tests are added. I'm waiting for Travis opinion on my work. Locally the tests run through.

-> ready for review

**Comment by sgiehl** [comment]
@ziegenberg Thanks for that. With those tests we actually have all we need. Tests also seem to pass 👍

**Pull request merged**
