### PR TITLE
Append a suffix to temporary downloaded geoip files

### PR DESCRIPTION
**Pull request by sgiehl**
### Review

* [x] Functional review done
* [x] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] Code review done
* [x] Tests were added if useful/possible
* [x] Reviewed for breaking changes
* [x] Developer changelog updated if needed
* [x] Documentation added if needed
* [x] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
Seems like it might be a bit of work, but is it possible to build this into the Http class so anyone that downloads to a file will have the suffix?

**Comment by sgiehl** [comment]
@diosmosis does it make sense to do that always? It would actually be a breaking change as downloaded files would suddenly have another name as expected - unless we make that optional, but then it would be kind of useless as the default would need to be to not append anything to have bc.

**Comment by diosmosis** [comment]
@sgiehl good point, can't think of a way for it to just automatically work for existing uses.

**Review by diosmosis — APPROVED** [review]
tested locally + code looks good

**Pull request merged**
