### PR TITLE
Fixing geoloc title for visitors submenu

### PR DESCRIPTION
**Pull request by gboddin**
Somehow piwik was displaying Provider_SubmenuLocationsProvider instead of the actual menu title.

Fixed for english language.

### CODE REVIEW

**Comment by sgiehl** [comment]
That one was removed in 2d3c709c. Do you have any custom plugins installed?

**Comment by gboddin** [comment]
Nop but I did the following upgrade path :
2.10 -> 2.11.2

I actually have https://github.com/gboddin/MysqlPostConnectCommands but it shouldn't matter

**Comment by gboddin** [comment]
FYI the piwik distribution for our cluster is built with :

```
#!/bin/bash
echo Reseting
[ -d piwik ]&&rm piwik -Rf
echo Extracting piwik ... 
wget -O - "https://builds.piwik.org/piwik-latest.tar.gz"|tar -xz
[ -f "How to install Piwik.html" ]&&rm "How to install Piwik.html"
cd piwik
curl -sS https://getcomposer.org/installer | php
php composer.phar install -o --no-dev
rm composer.*
rm *json
git clone https://github.com/gboddin/MysqlPostConnectCommands.git plugins/MysqlPostConnectCommands
find -type d -name .git|xargs rm -Rf
find -type f -name .git|xargs rm -f
find -type f -name .gitignore|xargs rm -f
find -type f -name .gitattributes|xargs rm -f
find -type f -name .gitmodules|xargs rm -f
find -type f -name .gitkeep|xargs rm -f
cd ..
tar cz piwik > piwik-distrib.tar.gz
```

**Comment by splinter89** [comment]
Hi!
I also have "Visitors" - "Provider_SubmenuLocationsProvider" link leading to "Visitor Map" page, and looks like the problem is in updating process.
When updating Piwik (2.8.3 -> 2.13.1), I unzipped the latest version and overwrote existing files, so I've got all **added** and **changed** files.
But **removed** files (like `plugins/Provider/Menu.php`) was left in their places and now they are somehow autoloaded.
However, if I simply remove it, I get `No entry or class found for 'Piwik\Plugins\Provider\Menu'` error.

**Comment by mattab** [comment]
FYI: we will try to fix this bug "correctly" in this issue: #7986

**Pull request closed without merging**
