### PR TITLE
Handle write permission correctly when checking for users with access to same site

### LINKED ISSUE #18692: Fixes problem where dashboards can't be copied to users in certain circumstances
Refs DEV-2411
Not sure exactly under what circumstances this bug occurs, but in some cases its not possible to copy a dashboard to a different user. 

For example we had a case where an `Admin` user was not able to copy a dashboard to a specific `View` user. They were able to copy to **some** View users and other Admin users, but several View users were not showing on the list when trying to copy.
Other Admin users were also not able to copy to that specific View users until that View user was made an Admin user.

Thomas mentioned that this might be something that only happens under certain circumstances depending on what users exist:
image

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #18692

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by justinvelluppillai — COMMENTED** [review]
While these changes seem sensible I can't reproduce the original issue so it's not possible to confirm this actually fixes the issue. @sgiehl did you manage to reproduce the issue? The original comment says the user was Admin and couldn't copy the dashboard to a View user, so I'm not sure if this solves that.

**Comment by sgiehl** [comment]
@justinvelluppillai I wasn't able to reproduce with view permission. But guess the users that weren't visible had `write` and not `view` permission, which would easily explain the problem.

**Comment by sgiehl** [comment]
@justinvelluppillai did you do a code review on this one? If so, guess we can merge it, as it should at least fix an issue for users with write permission.

**Review by justinvelluppillai — APPROVED** [review]
I will approve this on the basis it fixes a potential bug. I've pinged @Starker3 internally to see if it fixes the issue he originally reported also.

**Comment by sgiehl** [comment]
It definitely fixes a bug. I could reproduce the problem with write permission. Will merge it.

**Pull request merged**
