### PR TITLE
use ProcessedMetric instances in Referrers.get instead of using a filter

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

This way, they will be unformatted when format_metrics=0 is supplied in the API request.

Changes:
* Add `VisitorsFromReferrerPercent` processed metric class.
* Use `VisitorsFromReferrerPercent` in Referrers.get via extra processed metrics metadata.
* Add tests to ensure the metrics are formatted correctly.
* In API.get, merge extra processed metrics metadata when merging tables from different Plugin.get methods.
* Make sure when format_metrics=bc that the Referrers percent metrics are formatted so the API output doesn't change by default.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
@matomo-org/core-reviewers can someone take a look at this PR also for the 4.X release? I need it for the Looker Studio related work I'm doing.

**Review by bx80 — APPROVED** [review]
This looks good to me, I ran some reports and did some breakpoint testing to confirm the values were calculating correctly. Seems like everything is matching the old filter values :+1: 
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] n/a [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] Tests updated [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] None [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] n/a [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] n/a [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] n/a Existing documentation updated if needed

**Comment by sgiehl** [comment]
This one needs to be re-created for 5.x-dev as well. As we don't merge changes from 4.x-dev over to 5.x-dev anymore it would otherwise be not included in Matomo 5.
In general it might be better to create PRs against 5.x-dev and afterwards backport them to 4.x-dev if needed.

**Comment by diosmosis** [comment]
thanks for the review @bx80 

@sgiehl created a 5.x-dev PR here: https://github.com/matomo-org/matomo/pull/20601

**Comment by sgiehl** [comment]
GitHub somehow failed to update the status of this one properly. It was actually merged twice to 4.x-dev. But the PR status wasn't updated to merged 🤷

**Pull request closed without merging**
