### PR TITLE
Improves "No data has been recorded yet" page

### LINKED ISSUE #11277: On "No data has been recorded yet" show links to guides, faq and features
Good to onboard especially new users there. Piwik has so many features and possibilities it will be good to use that moment to make a user aware of it. We could show a link to our User Guides and FAQs and / or to the list of features https://piwik.org/features/

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #11277 and #11436

### CODE REVIEW

**Comment by mattab** [comment]
Nicely done. I've already submitted feedback before - @tsteur what do you think? Feel free to merge if you don't have more improvements :+1:

**Comment by tsteur** [comment]
I would probably only change a bit the wording.
From first sentence "Please set up the JavaScript tracking code on your website if you haven't done already."
to something like "Please set up the tracking code below into your website or mobile app if you haven't done already." . 

Then in title "Tracking code for Site XXX" it should be "site" instead of "Site.

Without referencing the below tracking code it is otherwise a bit confusing. I will create an issue to add a feature "email developer". 

The headlines `h3` are barely possible to distinguish from the text but that's just our design and not related to this PR. Bit hard to scan it.

Maybe in "you can track a mobile app or any other type..." we could mention "you can track a mobile app (eg Android or iOS) or any other type..." but not really needed to mention Android and iOS. May be just a bit more clear or eye catching.

**Comment by sgiehl** [comment]
> Then in title "Tracking code for Site XXX" it should be "site" instead of "Site.

Guess you had a look at the changed screenshots. Maybe bit confusing test data in this case. The text is `Tracking code for sitename`, in the tests that is `Site XXX`

> Maybe in "you can track a mobile app or any other type..." we could mention "you can track a mobile app (eg Android or iOS) or any other type..." but not really needed to mention Android and iOS. May be just a bit more clear or eye catching.

Wouldn't mention iOS or Android as it should also be possible to track any other type of mobile app (like Windows, Blackberry,... even if we currently might not have an SDK)

**Comment by sgiehl** [comment]
> From first sentence "Please set up the JavaScript tracking code on your website if you haven't done already."
to something like "Please set up the tracking code below into your website or mobile app if you haven't done already." .

Changed that. Should anything else be changed? otherwise good to merge I guess.

**Comment by tsteur** [comment]
> Guess you had a look at the changed screenshots. 

Indeed 👍  sounds good to merge

**Pull request merged**
