### PR TITLE
Bump php-di to 5.0.0.

### PR DESCRIPTION
**Pull request by limonte**
php-di

### CODE REVIEW

**Comment by limonte** [comment]
Can't figure out why build is failing. Need help here, thanks!

**Comment by mattab** [comment]
where do you get this output from?

we can't use PHP-DI 5.0.0  as it requires PHP 5.4 and Piwik requires PHP 5.3 so we can't use PHP-DI 5 yet (but that beta version works on PHP 5.3)

**Comment by limonte** [comment]
@mattab I'm trying to upgrade piwik to 2.14:

a

**Comment by limonte** [comment]
@mattab I think it's better to bump requered PHP version than use beta (not even RC) package as dependency.

**Comment by mattab** [comment]
See #7323

**Pull request closed without merging**
