### PR TITLE
use speak: never

### LINKED ISSUE #17565: CSS: "speak" property: "none" changed to "never"
grafik
link: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Dashboard_Dashboard&subcategory=1

## Expected Behavior
`speak: never`

## Current Behavior
`speak: none`

## Possible Solution
`speak: never`
see https://www.w3.org/TR/css-speech-1/
grafik

## Steps to Reproduce (for Bugs)
see above

## Your Environment
* Matomo Version: 4.2.1 (demo.matomo.cloud)
* Browser: Firefox
* Operating System: windows 10

### PR DESCRIPTION
**Pull request by Findus23**
fixes #17565

seems like this was changed some time ago (`https://github.com/w3c/csswg-drafts/issues/510`)

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
Is this something other browsers might still implement as `none`? I'm wondering if we should have both just in case.

**Comment by Findus23** [comment]
@diosmosis I was wondering the same thing, but I can't find any information about this. But it seems like `none` was never in a finished standard, so no browser should have implemented it (at least in theory): `https://github.com/w3c/css-validator/issues/231`

**Comment by sgiehl** [comment]
When I add `speak: never` to an element my Chrome reports it as invalid. The computed styles then show `speak: normal`.
`speak: none` would be valid in Chrome.
Firefox actually does not know the property `speak` and reports all values as invalid.

**Comment by Findus23** [comment]
@sgiehl Indeed it seems to be the same for me. I'm not even sure if this is even implemented in a browser and does anything. Using `aria-hidden` on icons seems to be the better solution for accesibility anyway.

**Comment by sgiehl** [comment]
So shall we simply close this one? Or should we add both (`none` and `never`), so the browser can decide which one to pick?

**Comment by Findus23** [comment]
As `none` is the value chromium suggests and I think everyone else not supporting this at all, the best thing is probably to just close this.

**Pull request closed without merging**
