### PR TITLE
Avoid segment encoding issues

### LINKED ISSUE #11321: segment not valid-errors when filtering for operating system
When I try to create a segment with a filter for a specific operating system piwik throws a bunch of errors. This happens when creating a segment that is only filtering for a operating system as well as combining other filters with the operating system. Other filters like provider or site url work fine, also in AND/OR-combinations.

`ERROR: Failed to get data from API: The segment 'deviceType%3D%3DDesktop%3BoperatingSystemCode%3D%3DWIN%2CoperatingSystemCode%3D%3DMAC' is not valid. #0 /piwik/core/Segment.php(155): Piwik\Segment\SegmentExpression-&gt;parseSubExpressions() #1 /piwik/core/Segment.php(106): Piwik\Segment-&gt;initializeSegment('deviceType%253D...', Array) #2 /piwik/core/Archive.php(225): Piwik\Segment-&gt;__construct('deviceType%253D...', Array) #3 /piwik/plugins/VisitsSummary/API.php(29): Piwik\Archive::build('1', 'day', '2017-01-07,2017...', 'deviceType%253D...') #4 [internal function]: Piwik\Plugins\VisitsSummary\API-&gt;get('1', 'day', '2017-01-07,2017...', 'deviceType%253D...', 'nb_uniq_visitor...') #5 /piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array) #6 /piwik/plugins/API/API.php(388): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #7 [internal function]: Piwik\Plugins\API\API-&gt;get('1', 'day', '2017-01-07,2017...', 'deviceType%253D...', Array) #8 /piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array) #9 /piwik/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #10 /piwik/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI() #11 /piwik/core/Plugin/Controller.php(249): Piwik\Plugin\Visualization-&gt;render() #12 /piwik/plugins/VisitsSummary/Controller.php(121): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution)) #13 [internal function]: Piwik\Plugins\VisitsSummary\Controller-&gt;getEvolutionGraph() #14 /piwik/core/FrontController.php(542): call_user_func_array(Array, Array) #15 /piwik/core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch('VisitsSummary', 'getEvolutionGra...', Array) #16 /piwik/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #17 /piwik/index.php(27): require_once('/www/htdocs/w01...') #18 {main}`

### PR DESCRIPTION
**Pull request by sgiehl**
I've removed all encodeURI/decodeURI stuff from the segments. Angular already encodes it in the URL automatically, so it was encoded twice in some cases.
I've currently tested the changes successfully on:

* Internet Explorer 11
* Chrome 56
* Firefox 47
* Vivaldi 1.7

Hope I haven't missed any test case...

Maybe anyone could test it on some other browsers @mattab @tsteur 

_side note: as the double encoded segments worked in many cases before, it might eventually be possible that this changes breaks some bookmarks having double encoded segments in it. But I haven't found any so far_

fixes #11321
maybe refs #10973

### CODE REVIEW

**Comment by mattab** [comment]
Seems to work well :+1: well done. I would suggest to release this in a beta ASAP and ask wider feedback

**Comment by sgiehl** [comment]
Ok. Sounds good. Let's wait for the tests to pass and then we can merge and release a beta

**Comment by sgiehl** [comment]
Build fixed. Merging now :)

**Comment by tsteur** [comment]
What I would recommend to test is the segment selector in exported widgets (if not done yet). Also to eg load it with a segment in the URL and hash, with a segment in the URL but different segment in hash, only a segment in hash. Each of them then afterwards also change it a few times etc. Also each case would be ideally tested with lots of multiple different conditions and with &"'#... in the values to be sure to not introduce a regression again. I remember there were some problems that time that needed some extra encoding - I think.

**Comment by sgiehl** [comment]
Tested the segment selector in widgetized dashboad and also in various combinations in url, hash, or directly selecting or adding one. But I'm not sure if I missed one.
Maybe it would be good to create a follow up issue to create UI tests for every test case that comes up to our mind. So we can prove everything works and will work in the future.

**Comment by tsteur** [comment]
👍 on all the tests. It is not trivial...

One thing I noticed that doesn't work is when editing a segment like this and then "saving". It shows "custom segment" afterwards and I'm not sure if it's actually applied. But since @mattab changed the "save" logic to Piwik 2 logic a while ago it's likely not be a regression.

screenshot at feb 21 10-46-54

**Pull request merged**
