### PR TITLE
adding method of unifying current url and alias

### PR DESCRIPTION
**Pull request by wronan**
adding method of unifying current url and alias so both start (or don't start) with '/'

Original ticket: https://github.com/piwik/piwik/issues/9872

### CODE REVIEW

**Comment by tsteur** [comment]
Can you build a simple html page with a link and the tracking code to reproduce this issue?

Otherwise we can't test it and check for regressions. Also let us know about operating system and exact browser version. We did some tests with IE11 recently and it worked fine but it's possible that it only occurs in a certain case.

**Comment by wronan** [comment]
Hi @tsteur 
@mgonera wrote that problem occurs on IE11, then he changed his mind (or Internet Explorer changed his mind - IE has a mind of it's own :D ) because problem is with IE10 (but the title stayed as was).

I'm cooperating with @mgonera, we have a test site (but it's simple - very simple or even Very simple one may say). Don't want to post the links here, because he was the one to setup it, it's on his server. He will probably share it without a problems but I don't want to do this for him. @mgonera, would you be so kind?

**Comment by mgonera** [comment]
@wronan share whatever is needed, I think they already are here somewhere. Just pass the credentials privately and please indicate the directories on the server (as you may remember I gave you access one level higher than I was supposed to). thanks.

**Comment by tsteur** [comment]
A simple HTML page could be enough eg with a "paste" service. We don't need a URL

**Comment by mgonera** [comment]
@tsteur I provided this to your e-mail directly

**Comment by mgonera** [comment]
@tsteur can you review it?

**Comment by tsteur** [comment]
My time is a bit limited these days but I can already tell that tests are missing. From the looks it seems like a valid patch but it'll take some time to test it etc. When there are tests then it'll be easier to later to review

**Comment by mattab** [comment]
Review

* please add an automated tests in `tests/javascripts/index.php`

**Comment by mattab** [comment]
Thanks for the PR @wronan! I created this new PR with the tests: https://github.com/piwik/piwik/pull/10302 and changed the code slightly. we'll merge it in 2.16.2 :+1:

**Comment by wronan** [comment]
Thx man. Sorry for the delay with tests. I'm overwhelmed with work... Till the next PR then :)

**Pull request closed without merging**
