### PR TITLE
Fix checkboxes in Manage Websites form

### LINKED ISSUE #8247: Sites Manager doesn't save or show some saved global settings
Noticed this while testing #8242 . I'm using Chrome 43 on MacOS. Under "Admin => Sites Management" when selecting the checkbox "Enable website specific user agent exclusion." and "Keep Page URL fragments when tracking Page URLs" and then press "Save" the page will reload but those checkboxes are not checked. I'm not sure if the value is actually stored or whether they are just not displayed correctly.

### PR DESCRIPTION
**Pull request by barbushin**
There is a popular conflict between Angular and iCheck. I tried different solutions, like using custom derective for iCheck https://github.com/fronteed/iCheck/issues/62, but it does not helps. 

I think for now we can just disable iCheck for that Angular form.

Closes #8247

### CODE REVIEW

**Comment by tsteur** [comment]
Nice! Hopefully we can get rid of iCheck at some point. It always causes problems...

**Comment by tsteur** [comment]
Just FYI: Google released a lite version of material design which could be used as an alternative for iCheck see eg http://www.getmdl.io/components/index.html#toggles-section . It also provides nice switches etc

**Comment by mattab** [comment]
> Nice! Hopefully we can get rid of iCheck at some point. It always causes problems...

definitely, we had so many bugs because of iCheck!

> Just FYI: Google released a lite version of material design which could be used as an alternative for iCheck

This looks great, shall we migrate to it?

**Comment by barbushin** [comment]
I'm a big fan of Material Design, and https://github.com/google/material-design-lite is  really great. But there is a huge work to migrate, I think. May be we should ask some professional front end developer to estimate this kind of migration? 

Regarding building complex interactive Web applications, I think that there should be professional front-end programmer with relative experience.

**Comment by tsteur** [comment]
This would be only about checkboxes, radio, and switches. Not a whole redesign. We're doing the whole redesign more or less step by step

**Pull request merged**
