### PR TITLE
Removes AWS test runner

### LINKED ISSUE #15961: Guzzle 3 is deprecated (composer dependency warnings)
I've cloned this repository but I got two deprecation warnings:

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
> guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

Then I got another deprecation warning:

> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

### PR DESCRIPTION
**Pull request by sgiehl**

### CODE REVIEW

**Comment by tsteur** [comment]
Not sure we need to update other places eg on developer website or in the code maybe search quick for aws? Noticed it is mentioned here but not important: https://matomo.org/blog/2014/11/how-to-write-unit-tests-for-your-plugin-introducing-the-piwik-platform/

**Comment by tsteur** [comment]
otherwise feel free to merge

**Comment by tsteur** [comment]
fyi @sgiehl removed the aws settings from global config. Might need a screenshot update before merging

**Comment by sgiehl** [comment]
roughly searched through our other repos and didn't find anything.

**Pull request merged**
