### PR TITLE
Rename composer package to matomo/matomo

### PR DESCRIPTION
**Pull request by sgiehl**
All packages should still be available as piwik/piwik, as this repo should still be used for updating that package.
After this PR was merged, we need to submit the package with the new name on packagist, so it will be available.

refs #12519

### CODE REVIEW

**Comment by tsteur** [comment]
Looks good @sgiehl will you submit this afterwards?

**Comment by sgiehl** [comment]
@tsteur can submit it. Wondering if we maybe should wait for a first 4.0 beta to publish the new package

**Comment by tsteur** [comment]
👍 moved it to RC

**Comment by tsteur** [comment]
@sgiehl can you merge this PR on Monday or so and then publish the package on packagist?

**Comment by sgiehl** [comment]
@tsteur done. Shall we mark piwik/piwik as abandoned and suggest the new name for usage? The old name would still work and provide all releases, but composer would suggest to switch to the new name...

**Comment by tsteur** [comment]
sounds great @sgiehl

**Pull request merged**
