### PR TITLE
only show_limit_control on Acquisition/Overview

### PR DESCRIPTION
**Pull request by geekdenz**
### Description:

Not super beautiful fix, but it works.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@geekdenz did you have a look at @sgiehl comment in https://github.com/matomo-org/matomo/pull/17987#issuecomment-920095127 ? Did changing this one to `true` maybe not fix the problem?

**Comment by geekdenz** [comment]
@tsteur I already checked his comment and fixed it here:
https://github.com/matomo-org/matomo/commit/24a4cfe9c1b506aa7bcf8ac3bc61366e8bfac24c
Did you see that or is there something wrong with the fix?

**Comment by geekdenz** [comment]
build js

**Comment by geekdenz** [comment]
@sgiehl I believe this means it is fixed:

https://builds-artifacts.matomo.org/matomo-org/matomo/m-17965/49074/Comparison_row_evolution.png

**Review by sgiehl — CHANGES_REQUESTED** [review]
@geekdenz please don't build JS files in pull request that actually didn't change anything in the piwik.js. This was actually forgotten when merging another PR and should either be directly fixed on 4.x-dev or with a separate PR. Here it will lead to merge conflicts.

The solution you proposed might fix the problem described in the issue, but actually might not be the simplest / best way.
The default value of `show_limit_control` is true. So it is enabled by default. See 
https://github.com/matomo-org/matomo/blob/be724571d2f477b4f553411d41df3fb22408c0a6/core/ViewDataTable/Config.php#L329-L335
or specifically for the evolution charts here:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution/Config.php#L41-L45
So the reason why the limit control is not shown for the referrer evolution chart is, that it's disabled in the according report class:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/Referrers/Reports/GetReferrerType.php#L105
Simply removing this one line should fix the issue. Overwriting that again doesn't make sense at all.

**Comment by geekdenz** [comment]
Sorry, @sgiehl and thanks for the suggestion.

**Comment by tsteur** [comment]
I'll close https://github.com/matomo-org/matomo/issues/17965

fyi @geekdenz if you put `fix #17965` in the PR description then it will close the related issue automatically when merging.

**Pull request merged**
