### PR TITLE
[Vue] introduce frontend unit testing for vue & migrate periods.spec.js

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off #18091. That must be merged first.** Or just merge this one and close the other I guess.

* Introducing jest + jsdom to replace anguarjs unit tests. There was a mocha/karma integration for Vue, but it doesn't work with Vue 3 and no one seems to be working on that. Currently I'm not using chai, though it could be if desired.
* Run vue tests in travis-ci AngularJS job.
* Migrate the periods angular service tests to TypeScript + Jest.

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
fyi @diosmosis there's a merge conflict and the tests fail in https://app.travis-ci.com/github/matomo-org/matomo/jobs/540966028#L1375-L1381 The tests itself succeed but some package file seems to not exist?

**Comment by diosmosis** [comment]
@tsteur / @sgiehl the typescript compiler wasn't behaving the same on travis-ci vs. locally. I found a configuration that works, so it's passing now, but I'm not sure why it behaves differently locally.

**Comment by diosmosis** [comment]
@tsteur seeing there is now a ReleaseCheckListTest failure due to matomo.zip size. The package-lock.json file is the biggest now, but I think we don't need to include this in the release. What do you think?

**Comment by tsteur** [comment]
@diosmosis indeed we can ignore that one and not include it in the release. Are the tests otherwise passing?

**Comment by diosmosis** [comment]
@tsteur there are some ui test failures, but they seem unrelated. They're not failing on 4.x-dev though, so re-running the build to see if they're random. Is it ok to merge if they pass?

**Comment by diosmosis** [comment]
@tsteur looks like some were random. The bulk of the other failures have this error:

```
         <div class='alert alert-danger'><strong>Error:</strong> curl_exec: SSL certificate problem: certificate has expired. Hostname requested was: plugins.piwik.org</div>
```

I'll see if I can fix the build in this PR.

**Comment by Findus23** [comment]
@diosmosis I assume that's still because of the UI tests using Xenial

**Comment by diosmosis** [comment]
@tsteur build is passing. I've also created a matomo-package pr.

**Comment by tsteur** [comment]
@diosmosis looks good for me to merge. I tested and seemed to work and also had a look through the code. It says though that https://github.com/matomo-org/matomo/pull/18091 needs to be merged first? Is this still the case or we simply merge this PR and close #18091?

**Comment by diosmosis** [comment]
@tsteur this pr is built on that one, so this can be merged and the other ignored if desired. I only split them apart so they'd be easier to review (if needed).

**Comment by diosmosis** [comment]
@tsteur can you take a look at ^?

**Comment by tsteur** [comment]
That looks all good to me @diosmosis 👍

**Comment by diosmosis** [comment]
@tsteur ok, will merge soon

**Pull request merged**
