### PR TITLE
[Vue] Fixes #18663, make sure $location is initialized early.

### LINKED ISSUE #18663: Top navigation in General Settings no longer working
This seems to be broken for me on demo2 https://demo2.matomo.org/index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=day&date=yesterday and locally  but it works on demo.matomo.org 

Looks like a regression in a recent change maybe?

When I click on one of these links then it doesn't jump to the correct settings 
image

### PR DESCRIPTION
**Pull request by diosmosis**
### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — APPROVED** [review]
looks good to me

**Comment by sgiehl** [comment]
I guess this one should have gone to `next_release` as well, as it fixes a regression in 4.7

**Comment by tsteur** [comment]
@peterhashair could you recreate this PR for `next_release` branch as well?

**Comment by peterhashair** [comment]
@tsteur sure

**Pull request merged**
