### PR TITLE
Add possibility to select a specific frame within a page

### PR DESCRIPTION
**Pull request by tsteur**
eg `page.selectFrame('myFrameName');` and at the end of the test `page.selectMainFrame();`

What doesn't seem to work yet correctly is typing within the frame. I presume the position where the click should happen is not calculated correctly (it clicks before sending keys).

### CODE REVIEW

**Comment by tsteur** [comment]
Now also supports `page.click(selector)`

**Comment by tsteur** [comment]
Still a little issue is when selecting a frame within a frame, but planning on fixing this right now unless needed.

**Comment by tsteur** [comment]
Merging now as needed in 3.x-dev branch. Tests still succeed and do not affect any of our existing tests.

**Comment by mattab** [comment]
If possible would be nice to document this new feature in https://developer.piwik.org/guides/tests-ui#capturing-only-a-part-of-the-page even very quick :+1:

**Pull request merged**
