### PR TITLE
Disables some more feature if internet features are disabled

### PR DESCRIPTION
**Pull request by sgiehl**
We already added check at various places. This aims to complete it:

* Disallow usage of Marketplace
* Disables GeoIP Autoupdate tasks
* Disables GeoLocation Auto Updater UI

Is anything still missing?

refs #6324

### CODE REVIEW

**Comment by diosmosis** [comment]
Did a find usages of Http class and found some other possible candidates for this check:

CoreAdminHome\Tasks::updateSpammerBlacklist()
Referrers\Tasks::updateSocials()
Referrers\SearchEngines::updateSearchEngines()
maybe the MobileMessaging plugin?

**Review by diosmosis — COMMENTED** [review]
Tested locally works, even when a geoip autoupdate task was previously scheduled.

**Comment by diosmosis** [comment]
Noticed that the 'Marketplace' link is displayed even if internet access is disabled:

image

Think we should remove it since it will never work?

**Comment by sgiehl** [comment]
> CoreAdminHome\Tasks::updateSpammerBlacklist()
> Referrers\Tasks::updateSocials()
> Referrers\SearchEngines::updateSearchEngines()

Those tasks should already only be added when internet is enabled

**Comment by sgiehl** [comment]
regarding MobileMessaging and Marketplace: Wondering if we maybe should simply "deactivate" those plugins if internetfeatures are disabled.

**Comment by diosmosis** [comment]
If they're deactivated, will they be activated when the setting is enabled? I guess we could just unload it at the start of a request, might have the same effect...

**Comment by sgiehl** [comment]
Marketplace and MobileMessaging plugins will now be dynamically removed from the list of activated plugins in each request if internet connection is disabled in config.

**Comment by diosmosis** [comment]
@sgiehl thought of one more thing, would it be a good idea to mention if a plugin requires internet in the manage plugin page?

Btw @mattab some API/product changes were added here (new API to `Plugin` class and product change in that plugins requiring an internet connection are unloaded), can you provide your opinion?

**Comment by sgiehl** [comment]
> @sgiehl thought of one more thing, would it be a good idea to mention if a plugin requires internet in the manage plugin page?

we could do so. But not sure about it, as other plugins require a working internet connection for some specific features as well. And that wouldn't be displayed then

**Comment by diosmosis** [comment]
Ah ok, that's what I was thinking about, then 👍 will approve

**Review by diosmosis — APPROVED** [review]

**Comment by sgiehl** [comment]
@mattab / @tsteur could someone else give a comment on:

> _diosmosis commented 12 days ago_
> Btw @mattab some API/product changes were added here (new API to Plugin class and product change in that plugins requiring an internet connection are unloaded), can you provide your opinion?

**Comment by mattab** [comment]
The new API & marking internet-requiring plugins in the Plugins overview look good to me :+1:

**Pull request merged**
