### PR TITLE
Update SEO Metrics: make all metrics work and remove pagerank which was deprecated

### PR DESCRIPTION
**Pull request by pebosi**
The only working metric was Alexa, so i updated the others to work again.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @pebosi 
thank you for the Pull request and fixing these issues!

Why did you remove the pagerank metric?

**Comment by pebosi** [comment]
Google has shutdown the public Pagerank. it's always 0 for all sites. 
More info: http://searchengineland.com/google-has-confirmed-they-are-removing-toolbar-pagerank-244230

**Comment by mattab** [comment]
> Google has shutdown the public Pagerank. it's always 0 for all sites. 

so it makes sense to remove it for sure!


we should check that the PR does not introduce regression: some of the other metrics you fixed (Bing, domain age) seem to work currently for "piwik.org" domain ie. 
untitled 

What domain names were these metrics not working for you?

**Comment by pebosi** [comment]
Not working for pebosi.net, google.de, many others.
The reason for this is the User-Agent which is transferred to the Metric Urls, which contains my locale "de-DE". So my changes are just to make sure the queries use correct lang paramerters or to handle both dots and comma.

Only DMOZ was not working at all.
Am 16. August 2016 um 06:47:17 +02:00, hat Matthieu Aubry <notifications@github.com> geschrieben:

**Comment by tsteur** [comment]
@pebosi I'd be happy to merge this but the change would be needed for Piwik 3. Do you mind creating this PR for the "3.x-dev" branch? I don't think anything has changed in SEO in Piwik 3 so it should be straight forward hopefully. Let me know if there's any trouble

**Comment by mattab** [comment]
Since Github lets use change the base branch, i've changed it to 3.x-dev and we'll review this for 3.0.0

**Comment by pebosi** [comment]
Is there something to do?

**Comment by tsteur** [comment]
Thanks for this :+1: Tested it and worked for me.

**Pull request merged**
