### PR TITLE
[DEV-16595] Add missing no-data screen translations

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

A few translations here and there were missing for some of the 5 top languages.
Contains a link to TagManager PR that will be removed once merged there and updated via the submodules action.

Please review from the technical perspective and we'll merge once the copy has been checked by the stakeholders.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@michalkleiner from a technical point of view it might be easier to directly change those translations in weblate. Weblate directly performs a couple of sanity checks and you could directly have marked them as reviewed there.
Merging them here is a bit more complex. I will now force weblate to update it's PRs, then we need to merge the translation PR from weblate and see if this PR might afterwards have conflicts that need to be resolved.

**Comment by michalkleiner** [comment]
That makes sense, I can do that (with a little help on how to do it and access to marking them reviewed) and then close the PR.

**Comment by michalkleiner** [comment]
Removing the Stale tag but this PR will be eventually closed anyway in favour of Weblate translation updates.

**Comment by michalkleiner** [comment]
Superseded/replaced by https://github.com/matomo-org/matomo/pull/21157 where the translations were entered via Weblate.

**Pull request closed without merging**
