### PR TITLE
Bump lodash from 4.17.11 to 4.17.14 in /tests/lib/screenshot-testing

### PR DESCRIPTION
**Pull request by PatOnTheBack**
Automated fix by dependabot.

### CODE REVIEW

**Comment by Findus23** [comment]
This isn't that important as this directory isn't included in the released Matomo build, but just used for tests.
Instead all those dependencies should be updated sometime at once: #14549

**Comment by PatOnTheBack** [comment]
@Findus23 Would it make sense to just merge this PR now and gradually update dependencies?

**Comment by PatOnTheBack** [comment]
The CI test failed for PHP 5, not PHP 7.

**Comment by sgiehl** [comment]
The library you updated is only used for screenshot testing, which is the build running on PHP 5 only. But that shouldn't be caused by this update. So guess it wouldn't harm to merge that :man_shrugging:

**Pull request merged**
