### PR TITLE
Fix segment for referrer websites subtables

### LINKED ISSUE #14918: Segmented Visitor log on Acquisition > Websites sub-table does not open the right visits
I think this is a regression but not sure exactly when it was introduced.

## Reproduce

* in acquisition > websites > click on a website Domain, it opens the sub-tables with list of pages for that website
* Open `Segmented Visitor Log`
* [Reproduce URL](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62&updated=1#?idSite=62&period=month&date=2019-09-30&category=Referrers_Referrers&subcategory=Referrers_SubmenuWebsitesOnly&popover=RowAction$3ASegmentVisitorLog$3AReferrers.getUrlsFromWebsiteId$3AreferrerUrl$253D$253Deurope$25252Fdestinations$3A$257B$2522date$2522$253A$25222019-09-30$2522$252C$2522period$2522$253A$2522month$2522$252C$2522idSubtable$2522$253A$25221$2522$257D)

Got:
Screenshot from 2019-09-30 11-59-02

The segment is incorrect, it says `referrerUrl==here_is_path_of_the_page` but we expected instead the segment to include the full Referrer URL, not only the path.

Expected the Segmented Visitor Log to use the right "segment" to fliter only people who came from this page.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #14918

### CODE REVIEW

**Comment by tsteur** [comment]
@sgiehl LGTM. Could you fix the tests though before merging?

**Comment by sgiehl** [comment]
@tsteur actually it seems that none of the failing tests is related to this changes...

**Comment by tsteur** [comment]
What about eg https://travis-ci.org/matomo-org/matomo/jobs/592247565#L821 ?

**Comment by sgiehl** [comment]
Interesting. Those tests didn't fail for the `push` build, but in `pr` build :man_shrugging: 
Will update it

**Comment by tsteur** [comment]
@sgiehl there still seem to be some failing tests see https://travis-ci.org/matomo-org/matomo/jobs/592791003#L821

**Pull request merged**
