### PR TITLE
Allow removing download extensions (fixes #7444)

### LINKED ISSUE #7444: Exclude extensions as downloads
We have a webservice that uses .exe in the URL. These calls is always tracked as a download.
Would love to see a per site setting to exclude / include extensions as a download.

### PR DESCRIPTION
**Pull request by sgiehl**
This PR aims to fix #7444 and adds the possibility to exclude an extension from the list of "download extensions".

It also converts the list of already excluded extensions into an array and resolves the regexes to single values, so it is possible to remove only some of them.

Methods for setting, adding and removing extensions now accept single values as well as multiple values (as array or separated by "|")

### CODE REVIEW

**Comment by mattab** [comment]
Feedback
 * Looks good!
 * could you add some unit tests in `tests/javascript/index.php`?
 * after merge, we will need to update the [Javascript client doc](http://developer.piwik.org/api-reference/tracking-javascript)

**Comment by sgiehl** [comment]
I've added some tests.

**Comment by mattab** [comment]
looks good to me, merging :+1:

**Comment by mattab** [comment]
Hi @sgiehl, just remembered we didn't update the developer documentation at: https://github.com/piwik/developer-documentation/blob/master/docs/tracking-javascript.md - would you mind documenting the new method there?

**Comment by sgiehl** [comment]
Sorry. I somehow thought the documentation is some kind of autogenerated. I've updated the doc in https://github.com/piwik/developer-documentation/commit/1794b90a2f8b95b2aef0812bfeaf66811a64edac

**Pull request merged**
