### PR TITLE
Add tests for piwik/searchengine-and-social-list#14 for Japanese search engines and keywords

### PR DESCRIPTION
**Pull request by piwikjapan**
Add tests for piwik/searchengine-and-social-list#14
Use kanji strings instead of just 'Piwik'.

### CODE REVIEW

**Comment by tsteur** [comment]
Thank you @piwikjapan . It looks like some tests are failing now see https://travis-ci.org/piwik/piwik/jobs/154982100 . Can you have a look? Is it maybe a bug in Piwik?

You can try to run the tests locally by executing `./console tests:run unit` within Piwik directory

**Comment by piwikjapan** [comment]
@mattab said on #10394:
> try running composer `update piwik/piwik/searchengine-and-social-list` in your branch and push the updated composer.lock to the pull request, this may fix your issue?
so I tried.

Locally by excusing below:
`./console tests:run ./plugins/Referrers/tests/Unit/SearchEngineTest.php`:
```
[yamachan@piwik piwik]$ ./console tests:run ./plugins/Referrers/tests/Unit/SearchEngineTest.php
Executing command: cd /home/yamachan/piwik/tests/PHPUnit && /home/yamachan/piwik/vendor/bin/phpunit   ../.././plugins/Referrers/tests/Unit/SearchEngineTest.php
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

Runtime:        PHP 5.4.16
Configuration:  /home/yamachan/piwik/tests/PHPUnit/phpunit.xml.dist

.............................................................   61 / 1290 (  4%)
.............................................................  122 / 1290 (  9%)
.............................................................  183 / 1290 ( 14%)
.............................................................  244 / 1290 ( 18%)
.............................................................  305 / 1290 ( 23%)
.............................................................  366 / 1290 ( 28%)
.............................................................  427 / 1290 ( 33%)
.............................................................  488 / 1290 ( 37%)
.............................................................  549 / 1290 ( 42%)
.............................................................  610 / 1290 ( 47%)
.............................................................  671 / 1290 ( 52%)
.....................................F....................F..  732 / 1290 ( 56%)
.............................................................  793 / 1290 ( 61%)
.............................................................  854 / 1290 ( 66%)
.............................................................  915 / 1290 ( 70%)
.............................................................  976 / 1290 ( 75%)
............................................................. 1037 / 1290 ( 80%)
..F.......................................................... 1098 / 1290 ( 85%)
.................................F........................... 1159 / 1290 ( 89%)
............................................................. 1220 / 1290 ( 94%)
............................................................. 1281 / 1290 ( 99%)
.........

Time: 1.93 seconds, Memory: 14.50MB

There were 4 failures:

1) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #1 ('www.118700.se', array(array('q'), 'sok.aspx?q={k}', '118 700'))
www.118700.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

2) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #22 ('www.allaverksamheter.se', array(array('What'), 'SearchResult.aspx?What={k}', 'Allaverksamheter'))
www.allaverksamheter.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

3) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #332 ('www.isodelen.se', array(array('Keywords'), 'sokresultat?Keywords={k}', 'Isodelen'))
www.isodelen.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

4) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #424 ('www.riksdelen.se', array(array('What'), 'SearchResult.aspx?What={k}', 'Riksdelen'))
www.riksdelen.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

FAILURES!
Tests: 1290, Assertions: 2049, Failures: 4.
```

**Comment by sgiehl** [comment]
try running `composer update piwik/searchengine-and-social-list` on console. that should update the definition package.

**Comment by piwikjapan** [comment]
Again, excuted locally:

```
[yamachan@piwik piwik]$ composer update piwik/searchengine-and-social-list
> Piwik\Composer\ScriptHandler::cleanXhprof
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package mnapoli/phpdocreader is abandoned, you should avoid using it. Use php-di/phpdoc-reader instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
> Piwik\Composer\ScriptHandler::buildXhprof
[yamachan@piwik piwik]$ ./console tests:run ./plugins/Referrers/tests/Unit/SearchEngineTest.php
```

I had the same result - snip.

**Comment by sgiehl** [comment]
is your composer.lock modified?

**Comment by piwikjapan** [comment]
I did not touch.
But I am not really sure about git merge:

```
[yamachan@piwik piwik]$ git remote -v
origin  git@github.com:piwikjapan/piwik.git (fetch)
origin  git@github.com:piwikjapan/piwik.git (push)
upstream        git@github.com:piwik/piwik.git (fetch)
upstream        git@github.com:piwik/piwik.git (push)
[yamachan@piwik piwik]$ git fetch upstream
[yamachan@piwik piwik]$ git merge upstream/master
Already up-to-date.
[yamachan@piwik piwik]$ composer update piwik/searchengine-and-social-list
> Piwik\Composer\ScriptHandler::cleanXhprof
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package mnapoli/phpdocreader is abandoned, you should avoid using it. Use php-di/phpdoc-reader instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating autoload files
> Piwik\Composer\ScriptHandler::buildXhprof
```

**Comment by sgiehl** [comment]
@piwikjapan I updated the dependencies. Seems the tests are running correctly now

**Pull request merged**
