### PR TITLE
use RecordBuilders in Actions plugin

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR depends on: https://github.com/matomo-org/matomo/pull/20394 which should be reviewed and merged first**

Changes:
* Create ActionReports RecordBuilder for the bulk of Actions archiving code.
* Create SearchCategories RecordBuilder for the site search categories report.

Note: Actions archiving runs many queries on log tables, updating records it holds in memory, so with the current logic, these reports cannot be aggregated separately. However, it's probably do-able to separate them if the record format is changed. Instead of one record per type of Action, which is then minimally processed in API methods, the result of each log aggregation query (eg, page URLs, page Titles, then entry/exit metrics for actions, goals metrics for actions, etc.) can stored directly as a record, and merged together in the API. I am told this is not a priority, however, so I'll create an issue for this if/when this PR is merged.

**Note: actually I will not be creating a PR for ^, because I misunderstood my own code and separating those would only really be of benefit if partial record processing was applied to day periods.**

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
I noticed that RecordBuilder could be unit tested w/ some effort so I added some tests for it, and fixed some issues to get it to pass.

**Comment by sgiehl** [comment]
@diosmosis I can't explain why, but something in this PR seems to cause some other Unit tests to fail. As they are passing on 5.x-dev, we need to fix them here before merging...

**Comment by diosmosis** [comment]
Needed to clear the site cache in tearDown(). Should be passing now.

**Review by bx80 — APPROVED** [review]
This looks good to me, the related automated tests are passing and I did some additional manual tests which worked well.

**Pull request merged**
