### PR TITLE
[Vue] add report generated styling and element to vue component

### LINKED ISSUE #18476: Report generated info missing since Matomo 4.6.x
The "report generated" info is not visible anymore after Matomo 4.6.x

I can see that the info is still in the code like this:
`<h2 class="card-title ng-isolate-scope" report-generated="Report generated 12&nbsp;min&nbsp;5s ago" piwik-enriched-headline="" data-v-app="">`

But I am not able to display it somehow.

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Fixes #18476

Not sure how, but the report generated styling and element was not added to the Vue component. Adding it back.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis the submodule changes should be reverted I guess

**Comment by diosmosis** [comment]
@sgiehl done

**Review by peterhashair — APPROVED** [review]
I think this is good to go, but the actually report-generated I thought is removed before. I mean this part here. 
https://github.com/matomo-org/matomo/pull/18035/files
```javascript
    <div v-show="showReportGenerated" class="icon-clock report-generated"></div>
```

**Comment by justinvelluppillai** [comment]
@peterhashair is right, this was removed in #18035 on purpose, and is displayed differently now. I have closed the issue and will close this PR also.

**Pull request closed without merging**
