### PR TITLE
Deprecated some tracker events

### LINKED ISSUE #7837: Deprecate no longer needed / wanted events
Piwik 3.0.0 will be happening soon. Therefore we should mark some events as deprecated soon. This will allow us to remove them in Piwik 3.0.0. We also need to make sure to remove those events in a follow up issue in Piwik 3.0.0. Why is this important? Imagine you update from 2.X to 3.0.0. Your Piwik works fine. If we actually remove those events in 3.1.0 and someone else updates to 3.1.0 it can break his Piwik although such an update should not break as it is not a major version update.

In the past I noticed some events that are no longer really needed/wanted, should be renamed or cause performance problems (like `Site.getSite` did).  We should go over the list of events (http://developer.piwik.org/api-reference/events) and see if this is the case for some of them. Please comment if you know any event.

Part of this issue is also to make sure that all deprecated events are documented in our developer changelog. Eg we already deprecated many events like `Menu.Reporting.addItems`, `API.getReportMetadata`, `WidgetsList.addWidgets`.

### PR DESCRIPTION
**Pull request by tsteur**
refs #7837 

A pull request for the documentation is here: https://github.com/piwik/developer-documentation/pull/100

Ideally we would merge documentation before this as I added some links to those docs. We can close #7837 once both are merged

### CODE REVIEW

**Comment by mnapoli** [comment]
Deprecated tags can take the reason inline, this is useful so that tools can show the reason why something is deprecated. E.g. in PhpStorm you get a warning when using something deprecated, and at the same time you see the message. Additionally, it's simpler and less confusing (an empty `@deprecated` can be very confusing because it doesn't tell you what to do next).

Example, from this:

```php
/**
 * This event is deprecated, use [Dimensions](http://developer.piwik.org/guides/dimensions) instead.
 *
 * @deprecated
 */
```

to this:

```php
/**
 * @deprecated Use [Dimensions](http://developer.piwik.org/guides/dimensions) instead.
 */
```

**Comment by tsteur** [comment]
I didn't wanna do this as we do not show this message behind `@deprecated` in the docs on developer.piwik.org. In this case I only want to have the docs for this deprecated message on developer.piwik.org. There is no auto completion for events anyway in PHPStorm etc

**Comment by diosmosis** [comment]
@tsteur Can you rebase? Will merge both branches when done.

**Comment by tsteur** [comment]
Rebased it and will merge now

**Pull request merged**
