### PR TITLE
Add more tests for format=original.

### PR DESCRIPTION
**Pull request by diosmosis**

### CODE REVIEW

**Review by sgiehl — COMMENTED** [review]
@diosmosis any reason for adding those tests? Imho it's very hard to validate if the content of each test file is correct. If it's only for proving the format `original` works, maybe there's a better way to check without comparing any file contents?

**Comment by diosmosis** [comment]
The original format is going to be used for another plugin that will unserialize after getting serialized data back over a network. Which means it can be easy to add new data to the result of an API method that cannot be unserialized.

I suppose an alternative here is to just serialize & then unserialize it. Will look into that.

**Comment by diosmosis** [comment]
Updated to just unserialize the response and check it unserialized.

**Review by sgiehl — APPROVED** [review]
Looks much better now :ok_hand:

**Pull request merged**
