### PR TITLE
Show row actions no matter how many results in the data table are shown

### PR DESCRIPTION
**Pull request by tsteur**
refs https://github.com/matomo-org/matomo/issues/14418

### CODE REVIEW

**Comment by diosmosis** [comment]
This solves the performance issue by using a single event instead of one on each row, correct?

**Comment by tsteur** [comment]
@diosmosis before it was iterating over all rows whenever the table was loaded and was doing work for each row and setting up event listener for each row which is now indeed only a single event.

**Comment by diosmosis** [comment]
👍

**Comment by mattab** [comment]
Very awesome to have this bug fixed :tada:

**Pull request merged**
