### PR TITLE
update vue cli build

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

@diosmosis  try this works for me. `./console vue:build` on local. But somehow the github action VUE build doesn't run correctly

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
@peterhashair you'd have to change a vue file to trigger the github action. You can either make a pointless change to a vue/ts file or just run it locally and push the changes. If the tests pass, it would be worth trying. Since the problem is random it would be hard to test for anyway.

**Comment by peterhashair** [comment]
@diosmosis I don't think that works, it still failed if I try a second time.

**Comment by diosmosis** [comment]
> @diosmosis I don't think that works, it still failed if I try a second time.

You mean the github action? You will have to change a vue file, commit and push it, otherwise the action will think nothing has changed and not rebuild. If you mean something else, let me know.

**Comment by peterhashair** [comment]
@diosmosis sorry I mean, `vue:build`
image

**Comment by diosmosis** [comment]
@peterhashair so the random errors are still there? If yes, it might be because the change is to eslintrc.js but the errors come from the typescript compiler `tsc`.

**Pull request closed without merging**
