### PR TITLE
Avoid menu shadow to be displayed in notifications UI test

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

refs https://github.com/matomo-org/matomo/issues/21458

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by caddoo — APPROVED** [review]
Approved, but just checking are these notifications tested in other UI tests?

Wondering if we need this test at all.

**Comment by sgiehl** [comment]
I guess other UI tests cover certain notifications as well, but that one has all at once, so might be good to keep it.

**Comment by caddoo** [comment]
> I guess other UI tests cover certain notifications as well, but that one has all at once, so might be good to keep it.

I think all at once isn't a realistic scenario we should be testing.

**Comment by sgiehl** [comment]
Theoretically all at once could be displayed though even if unlikely. Also overall I think it's more useful to have one UI test that checks that all type of notifications look correct (with static notification messages) and avoid testing notifications in other tests and only check that they are present without taking a screenshot of them there.

**Comment by michalkleiner** [comment]
I'd say keeping a screenshot of one notification in place would still be beneficial to cover any alignment/spacing/layout issues. But agree that we don't need to test all types there.

**Pull request merged**
