### PR TITLE
removed files related to unsupported databases

### LINKED ISSUE #18039: Remove not used DB adapters
Meaning https://github.com/matomo-org/matomo/blob/4.5.0-b2/core/Db/Adapter/Pdo/Mssql.php and https://github.com/matomo-org/matomo/blob/4.5.0-b2/core/Db/Adapter/Pdo/Pgsql.php

Since these are not supported can we remove them? It requires us on occasion to add core to these classes when we add methods to the other adapters and it confuses new developers thinking we might support them and that they need to be tested.

@mattab @sgiehl or do you know any reason why they still exist in the code?

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Removed Mssql and pgsql driver, which are not in used.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@peterhashair can you also remove a few other references related to these?

For example 
image

eg there is a setting `minimum_pgsql_version` which was used by the pgsql adapter which is no longer needed.

We can also remove the comment in `Adapter.php` that says "other adapters supported by Zend_Db (can remove all the commented adapters)

image

There is also a file `core/Tracker/Db/Pdo/Pgsql.php` which we can remove.

**Comment by peterhashair** [comment]
@tsteur sorry about that should be removed now.

**Comment by tsteur** [comment]
@peterhashair There is also a file `core/Tracker/Db/Pdo/Pgsql.php` which we can remove. Otherwise looks so far good to merge.

**Comment by peterhashair** [comment]
@tsteur sorry about that I saw that one, I was thought we just not using the customer driver but zend driver, read the support docs again, we don't support Postgresql at all. Should I remove `libs/Zend/Db/Adapter/Pdo/Pgsql.php ` as well?

**Comment by tsteur** [comment]
We can keep the other zend file as it's part of the zend library 👍

**Pull request merged**
