### PR TITLE
Link to edit a goal

### LINKED ISSUE #7345: Make it easier to see how to edit a Goal
The goal of this issue is to make it easier for users to see how they can edit the Goal in Piwik. 

Here is a simple usability improvement idea:

 * in the Report for a particular goal ([eg. on demo](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=Goals&action=goalReport&idSite=7&period=day&date=yesterday&idGoal=2)) on hover on the top title (the Goal name) we could show, next to the two icons, a link `Edit goal`. 
  * this link would be the same effect as clicking on the title itself: load the `Manage Goals` screen.

Maybe you also have a suggestion?

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7345

capture d ecran 2015-04-06 a 13 12 55

### CODE REVIEW

**Comment by mattab** [comment]
Feedback
 * did you try to write `(edit goal)` instead of the icon? otherwise it may feel like "icons overload" (it was discussed [in issue](https://github.com/piwik/piwik/issues/7345#issuecomment-77041357))

**Comment by mnapoli** [comment]
Yes I tried and it looked weird and overloaded. In the issue there are no reasons given why not to use icons.

**Comment by mattab** [comment]
it doesnt look awesome, but it's a small part of the app, and it's a useful shortcut to let users edit goals, so +1 

maybe others have suggestions?

**Comment by diosmosis** [comment]
I think some text would be useful, otherwise I wouldn't assume the icon is for editing goal, so much as editing for the header text.

**Comment by mnapoli** [comment]
I'll work on a solution with a text link + a screenshot

**Comment by diosmosis** [comment]
Nice goal, btw :)

**Comment by mnapoli** [comment]
Comparing the 2 options:

capture d ecran 2015-04-10 a 17 21 41

**Comment by diosmosis** [comment]
Not sure how it would look, but maybe a right aligned link that says `(edit goal)` or `(edit goal details)`?

**Comment by mnapoli** [comment]
Aligned to the right of the screen? Here the screenshot is truncated but on a large screen it would be really far from the title (all alone on the right).

**Comment by diosmosis** [comment]
That's what I was thinking of (far to the right). This may not apply to others, but associating an edit link with the title for goal reports, rather than something directly related to the goal seems odd to me. I'm not a UX expert though.

Maybe <small>ed and surrounded with () and left aligned. Just spitballing here.

**Comment by tsteur** [comment]
What about the suggestion of @Bugsbane in https://github.com/piwik/piwik/issues/7345#issuecomment-90761253 . He suggested to add a menu link "Manage Goals" before "Add a new Goal". Reckon this would be most clear and visible.

**Comment by mattab** [comment]
> add a menu link "Manage Goals" before "Add a new Goal". Reckon this would be most clear and visible.

+1 - not sure why we didn't do it in the first place

**Comment by mnapoli** [comment]
OK closing this then

**Pull request closed without merging**
