### PR TITLE
Resolve problems with VisitorMap

### PR DESCRIPTION
**Pull request by andrzejewsky**
Resulve issues: 
https://github.com/piwik/piwik/issues/8081 - now, if we have unknow regions, the legend will not appear
https://github.com/piwik/piwik/issues/8060 - changed z-index

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, thank you for the patch. I'm testing it locally and I get errors:

> Uncaught TypeError: Cannot read property 'push' of undefined

It seems to happen around [here](https://github.com/piwik/piwik/blob/a26872e960d99caf4ae8862904a6dd986e7bc493/plugins/UserCountryMap/javascripts/visitor-map.js#L237-237), I'm having a deeper look to try and fix it but if you have a fix feel free to push it.

**Comment by mnapoli** [comment]
I think this change is better to fix #8081:

```diff
if (stats.min == stats.max) {
    colscale = function () { return chroma.hex(oneCountryColor); };
    if (choropleth) {
        $('.UserCountryMap-legend .content').html('').show();
+        if (values.length > 0) {
            addLegendItem(stats.min, true);
+        }
    }
    return colscale;
}
```

**Comment by andrzejewsky** [comment]
@mnapoli the error with ```push``` is occurring, because to the ```chroma.limits``` we put a empty array (```values```). This commit https://github.com/piwik/piwik/commit/dfcfb3d8e5c56124c67790518293242191911d60 will fix it

**Comment by mnapoli** [comment]
Sounds nice now, I will test again

**Comment by mnapoli** [comment]
I can confirm it fixes #8081.

And it fixes the z-index problem of #8060 but not the other problems mentioned in that issue. We'll need to fix those separately.

Thanks for the fix, I'll merge it.

**Pull request merged**
