### PR TITLE
CronArchive: Catch UnexpectedWebsiteFoundException

### LINKED ISSUE #14393: Add option to core:archive that allows you to continue even if the site is not in matomo anymore
Hi, could a option be added that allows you to continue even if you get a error like:

  [Piwik\Exception\UnexpectedWebsiteFoundException]                               
  An unexpected website was found in the request: website id was set to '2897' .  

please?

This would be super useful.

Or is there a way to clear the deleted websites so they are not run?

### PR DESCRIPTION
**Pull request by paladox**
This is to allow the archive to continue if the site was deleted from matomo.

Fixes #14393

### CODE REVIEW

**Comment by paladox** [comment]
ci failure seems unrelated.

Submodule path 'tests/travis': checked out 'f93beed1fcbc90be0e961e2883124651f463efae'
Failed to recurse into submodule path 'plugins/Morpheus/icons'
The command "eval git submodule update --init --recursive " failed. Retrying, 2 of 3.

**Comment by paladox** [comment]
I've tested this locally and seems to work (i correctly get a "Skipped website id 2946, got: UnexpectedWebsiteFoundException") where needed.

**Comment by tsteur** [comment]
@paladox the PR needs to be made against 3.x-dev, not master

**Comment by paladox** [comment]
done in https://github.com/matomo-org/matomo/pull/14403

**Pull request closed without merging**
