### PR TITLE
Post JavaScript events when performing an action

### PR DESCRIPTION
**Pull request by tsteur**
So plugins can listen to it. They don't need documentation since they won't be official API

### CODE REVIEW

**Comment by tsteur** [comment]
FYI we will also need to merge https://github.com/piwik/plugin-CustomDimensions/pull/58

**Comment by sgiehl** [comment]
LGTM, the one in the plugin as well. Shall we add that in CustomAlerts, as well? Just to be consistent...

**Comment by tsteur** [comment]
Good point, will add it there

**Comment by tsteur** [comment]
FYI: Tried to add it to custom alerts but wasn't as trivial because it is a plain link there and not angularjs. Will add it when we need it

**Pull request merged**
