### PR TITLE
Search for visitor IDs over whole table not just last 30 mins

### PR DESCRIPTION
**Pull request by diosmosis**
In the tracker when searching by visitor ID, search through entire log_visit table instead of just in the last 30 mins.

Should be fast thanks to already existing index (h/t @tsteur)

CC @mattab can you take a look at this re any possible privacy implications?

### CODE REVIEW

**Comment by mattab** [comment]
Should work and in theory not introduce a performance regression :+1:

**Comment by sgiehl** [comment]
> Should work and in theory not introduce a performance regression

@tsteur @mattab should we maybe test that on some bigger cloud instances before merging? Otherwise tests may need some updates, but would be good to merge then.

**Comment by diosmosis** [comment]
FYI, I've been fixing tests for this in https://github.com/matomo-org/matomo/pull/13935 which contains this change + some fixes, this PR probably shouldn't be merged. I think it's good to have it open for any discussion though. I'll close it when I merge the other one.

**Comment by diosmosis** [comment]
Included in #13935

**Pull request closed without merging**
