### PR TITLE
Remove LocalTracker class from use in tests.

### PR DESCRIPTION
**Pull request by diosmosis**
This pull request removes the old LocalTracker class. The class was introduced before bulk tracking was available in order to speed up build time. It should no longer be necessary.

Furthermore, it complicates efforts to store the database connection in the DI container. The tracker uses a different DB connection than the rest of Piwik, so if the DB connection is stored in the container we have to somehow switch to tracker DB, then back when using LocalTracker. It's easier just to not use LocalTracker.

Notes:
- Includes change to the mock LocationProvider so it can be used in the normal tracker. Requires storing state in the option table since it has to be remembered between tracker requests. The class is deprecated in this pull request, since it is also as outdated as the LocalTracker.
- Adds an initializePlatform hook to Fixture classes. Similar to `Fixture::provideContainerConfig()`, it is executed in TestingEnvironment so Fixtures can do whatever setup they need for every Piwik PHP process. Used here to setup the mock LocationProvider for distributed use and to use specific GeoIP databases.

@mattab Please review and/or merge.

After merging, one thing to do:
- [ ]  Modify Bandwidth plugin which uses the local tracker in a test.

### CODE REVIEW

**Comment by mattab** [comment]
* since you removed the class from codebase, can we also remove all `$useLocal` including method parameter list? it's OK in this case to break BC in case someone else was using LocalTracker
 * add a quick note about this change to the Changelog.md
 * do you know why the order of fields changed in Live API output? im afraid this will fail a lot of opensource + pro plugin tests that have system tests with Live API...

**Comment by tsteur** [comment]
Actually, I found the LocalTracker very useful to write Integration tests instead of system tests. That's also why it is used in Bandwidth see https://github.com/piwik/plugin-Bandwidth/blob/master/tests/Integration/BandwidthTest.php#L112. It would be very nice to still be able to write Integration tests.

**Comment by diosmosis** [comment]
> since you removed the class from codebase, can we also remove all $useLocal including method parameter list? it's OK in this case to break BC in case someone else was using LocalTracker

I removed it from all callers (except Bandwidth since it's in a different repo). I kept the parameter so we can throw and have clear error messages for people that still used it.

> do you know why the order of fields changed in Live API output? im afraid this will fail a lot of opensource + pro plugin tests that have system tests with Live API...

It has to do w/ plugin loading order I think. Should only affect uses of local tracking since when the local tracker is used, plugins are already loaded. Now since they go through separate processes, the loaded plugins is in a different order.

**Comment by diosmosis** [comment]
> Actually, I found the LocalTracker very useful to write Integration tests instead of system tests.

The local tracker shouldn't be used in any test; it uses the same environment as the tests instead of the proper tracking environment which at best causes issues when running different tests together (ie, as on travis) and at worst makes the test inaccurate.

Properly executing the tracker from within the same process as tests is simply not possible at the moment because the tracker + its environment are not encapsulated in any way. To accomplish this, we would need better DI support. Which is what this pull request will indirectly help w/.

I suggest creating an issue if it's important that integration tests do not invoke the tracker through the web server. It will be possible within two pull requests after https://github.com/piwik/piwik/pull/7312 is merged.

**Comment by tsteur** [comment]
> I suggest creating an issue if it's important that integration tests do not invoke the tracker through the web server. It will be possible within two pull requests after #7312 is merged.

It is no longer an integration tests if it does invoke the tracker through the web server. It would be a system test. Is it possible to let the LocalTracker there and fix the LocalTracker once we have better DI support so that it does use the actual DB etc?

**Comment by diosmosis** [comment]
> It is no longer an integration tests if it does invoke the tracker through the web server. It would be a system test.

Honestly, are semantics that important to you? If this gets merged, I can fix those integration tests so they use the tracker w/o going through a server request in two pull requests. If you don't want to create the issue I can create it myself and assign it to myself.

> Is it possible to let the LocalTracker there and fix the LocalTracker once we have better DI support so that it does use the actual DB etc?

The specific issue this is for is putting the DB connection into DI. Since the tracker uses a separate class, using the LocalTracker will result in an error if the DB connection is in a single container (unless we use separate keys which defeats the purpose of using DI).

However, the two pull requests mentioned above don't require this change, I am only trying to work concurrently since it takes so long for pull requests to be merged.

**Comment by tsteur** [comment]
> Honestly, are semantics that important to you?

Yes, it is. It is important that we can run the Tracker locally and test various things that way and also for faster performance etc. I'm ok with it as long as we actually get a replacement for this as a follow up. I created an issue for that #7597 Thx!

**Comment by diosmosis** [comment]
No longer focusing on DI. @mnapoli might be working on better DI support, he took up one of the efforts I was working on before.

**Comment by tsteur** [comment]
This change would be nice to have eventually as it makes writing tests less complicated (one less parameter when creating tracker). However, in the near future we won't have resources to finish this for now. We certainly will use the changes made here later when removing the local tracker 👍

**Pull request closed without merging**
