### PR TITLE
Allow up to 63 characters TLD in email address

### LINKED ISSUE #9485: Zend Hostname validator is outdated for current TLD names.
Currently Piwik is using Hostname validator from 2011, which won't pass modern TLDs. Zend hostname validator requires TLD to have no more than 10 characters. Both versions 2.15 and 3.0 are affected.:
https://github.com/piwik/piwik/blob/3.0/libs/Zend/Validate/Hostname.php#L560
https://github.com/piwik/piwik/blob/2.15.0/libs/Zend/Validate/Hostname.php#L560

Currently IANA allow such TLDs as: 
 - TRAVELERSINSURANCE
 - BARCLAYCARD

which have respectively 18 and 11 characters and are valid TLD names.
source: http://data.iana.org/TLD/tlds-alpha-by-domain.txt

Newest version of hostname validator isn't a solution either, because its hardcoded domain list doesn't contain all possible domain names.
https://github.com/zendframework/zend-validator/blob/master/src/Hostname.php#L76

### PR DESCRIPTION
**Pull request by sebastianpiskorski**
We should allow for 63 characters TLDs, according to RFC 1035, instead of arbitrary 10.

https://en.wikipedia.org/wiki/Domain_Name_System#cite_ref-rfc1034_1-2

As far as minimum length of 2 is acceptable, becuse IANA says that it isn't likely to introduce 1 character TLD, maximium length is too short.
Also updated valid TLDs list to current state: http://data.iana.org/TLD/tlds-alpha-by-domain.txt

This partially resolves #9485

### CODE REVIEW

**Comment by sebastianpiskorski** [comment]
Cloud someone from Pwik team kick this job? https://travis-ci.org/piwik/piwik/jobs/101118866 for me?

It have errored on something random `The command "./tests/travis/setup_webserver.sh" failed and exited with 127 during .`

**Comment by tsteur** [comment]
Is there maybe a way we do not have to update Zend? Maybe we can configure a hostname class?

**Comment by sebastianpiskorski** [comment]
@tsteur This PR resolves problem temporarily.

**Comment by tsteur** [comment]
OK Cheers, looks good to merge. Should we create a new issue to solve it permanently?

**Comment by tsteur** [comment]
Created https://github.com/piwik/piwik/issues/9509

**Pull request merged**
