### PR TITLE
Fix GitHub links for 'About matomo'-Page (Footer)

### PR DESCRIPTION
**Pull request by obendev**
There are still old GitHub links in the footer of the 'About matomo'-Page
I changed them to the new ones, so that there is no unnecessary redirect
Old pull request #14528

### CODE REVIEW

**Review by diosmosis — APPROVED** [review]
LGTM

**Comment by obendev** [comment]
Path for icons changed, this is why there is a conflict.
Should I do a new pull request or can someone resolve this by hand?

**Comment by obendev** [comment]
Fixed a conflict because the file names of the icons were changed in 3.10 d6fa5948c93266af3934d40e2fe6d044a11f9f10

**Comment by tsteur** [comment]
Cheers @obendev

**Pull request merged**
