### PR TITLE
Use https protocol in tracking code if force_ssl is enabled

### LINKED ISSUE #7366: Incomplete tracking code: http/https missing in front of URL string
Dear all, 

I just noted that the auto-generate javascript / image tracking code seems to be incomplete for the server URL. The following code is generated and misses the protocol information (e.g., "https:" or http:"
in front of the URL string (e..g, during the definition of "u").

Is there a reason for this?

````
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//<url>";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//<url>?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
````

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #7366

### CODE REVIEW

**Comment by Findus23** [comment]
Many thanks! :tada: 

I'd go even a step further and document somewhere that the non-https tracking codes should be replaced.
Thankfully a lot of people are using https for Matomo (or the InnoCraft cloud), but have to track non-https sites. 
So for most people all data is sent unencrypted and twice unnecessarily.

**Comment by diosmosis** [comment]
Actually, one thing, can we add a test to `TrackerCodeGeneratorTest` for this case?

**Comment by Findus23** [comment]
@diosmosis In addition the same issue is with people using `//matomo.example/` URLs.

Do you have any idea on how to detect this (as depending on webserver config the HTTP request never reaches Matomo)?

**Comment by diosmosis** [comment]
I was imagining a diagnostic that would request the site's page server side and look for the tracking code (as I believe GA does).

**Comment by Findus23** [comment]
@diosmosis That sounds like a good idea (even though it may not work in some situations).

Maybe a server-based debugging tool is more successful than my browser-extension-based one.

**Comment by sgiehl** [comment]
+1 for adding some type of diagnostic for that. But maybe we should handle that in another issue/pr as I'm not sure if we can handle that before the release of 3.5.0

**Comment by diosmosis** [comment]
I'll create an issue later today.

**Comment by tsteur** [comment]
💯

**Comment by diosmosis** [comment]
Created new issue here: https://github.com/matomo-org/matomo/issues/12801

**Review by diosmosis — APPROVED** [review]

**Pull request merged**
