### PR TITLE
Disable Access to Matomo Updater via Webinterface

### PR DESCRIPTION
**Pull request by daylicron**
Useful if your're running Matomo in a multi server environment. Disabled by setting:
enable_auto_updates = 0

### CODE REVIEW

**Comment by tsteur** [comment]
Just checking: Are the links to those URLs already removed when the auto update is disabled? 

If yes, be good to merge.

**Comment by daylicron** [comment]
Unfortunately not. That's why we had to implement this. With the given options for config.ini.php there is no way to disable Matomo updates via the webinterface.

**Comment by mattab** [comment]
Thanks for the PR @daylicron :+1: Feedback:

* Instead of duplicating the code could you create a method in the class like `checkAutoUpdateIsPossible` 
* which, if not, throws an exception explaining that auto update is disabled? This way users know the problem which would be better than being redirected silently.

**Comment by sgiehl** [comment]
@daylicron are you able to update the PR according to @mattab's suggestions?

**Comment by mattab** [comment]
Thank you for this proposed pull request.

Because it was last updated more than one month ago, it is our policy to close pull requests opened for a long time without updates. If you would like to continue work on the pull request, please simply ping us to have it re-opened (after you have pushed a new commit).

We hope you understand this and we look forward to seeing an update from you on this pull request or another one!

Thanks.

**Pull request closed without merging**
