### PR TITLE
[WIP] Update config for PerformanceInfo pluging

### PR DESCRIPTION
**Pull request by ThaDafinser**
https://github.com/ThaDafinser/Piwik-PerformanceInfo

Need another public method for the global.ini path.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @ThaDafinser can you explain what you are trying to achieve? 

I think currently you can already load the local values by doing `Config::getInstance()->Section` so I'm not sure if this PR is needed?

**Comment by mnapoli** [comment]
That might conflict with the refactoring in #7312, @diosmosis might have some more info/alternative solution?

The method is not tagged `@api`, which means we can refactor it later and break your plugin. If you add `@api` that means we have to stay backward compatible on this, so I think there should be a compelling reason to do so.

**Comment by diosmosis** [comment]
To get from local config, you should just access the section directly. Sections in the local config completely override default settings in global/common/etc., so the method isn't needed.

**Comment by ThaDafinser** [comment]
@diosmosis i would like to show the user where the value come from, see here:
https://github.com/ThaDafinser/Piwik-PerformanceInfo/issues/2

If i just use the `last value` it might be set in the local config or not. (e.g. Global and local could be the same)

**Comment by ThaDafinser** [comment]
This is how i do it now in my plugin
https://github.com/ThaDafinser/Piwik-PerformanceInfo/blob/master/Controller.php#L44-L46
https://github.com/ThaDafinser/Piwik-PerformanceInfo/blob/master/Controller.php#L217

Is there any other way to get that?

**Comment by diosmosis** [comment]
Ah, ok, I see what your use case is now. The method in the pull request is probably the best solution to this, and it can be easily supported/maintained by the changes in #7312. @mattab Feel free to merge.

**Comment by mattab** [comment]
before merging we would  need to
 *  add a test for it,
 *  tag method with `@api` (and possibly others that you need in your plugin) so we don't break them in the future

**Comment by tsteur** [comment]
I recently needed this method nearly as well. Would be nice to merge this after adding an `@api` as Matt suggested. Maybe you can also add a basic test to https://github.com/piwik/piwik/blob/2.13.0-b1/tests/PHPUnit/Unit/ConfigTest.php#L45

BTW: I noticed this is in the Unit test group when it is actually an integration test as it access the file system etc but we can leave it there for now.

**Comment by ThaDafinser** [comment]
see the new PR

**Pull request closed without merging**
