### PR TITLE
Added website id to multisite overview

### PR DESCRIPTION
**Pull request by DevDaveo**
Here's my PR for #11734.

### CODE REVIEW

**Comment by sgiehl** [comment]
Did you maybe forget to push everything? I can't see where the id should be added to the overview. You've simply added a new data attribute that is not used anywhere.

**Comment by DevDaveo** [comment]
Actually that's everything. Just wanted to add the website ID to hide it with an userscript from the overview. Maybe we could add a setting to hide in the Piwik settings -> Website -> Manage?

**Comment by mattab** [comment]
@DevDaveo Could you also display this ID in the tooltip on the Sparkline at the end of each row? Currently reads "Go to dashboard of SITE_NAME" ---> "Go to dashboard of SITE_NAME (Website id XYZ)"

**Comment by mattab** [comment]
Hi @DevDaveo 

please check my previous comment. For now i'll close the PR but we are happy to merge if you can apply the feedback. Thanks!

**Pull request closed without merging**
