### PR TITLE
Minor npm updates & ui test fixes

### PR DESCRIPTION
**Pull request by sgiehl**
refs #16030

### CODE REVIEW

**Comment by Findus23** [comment]
Updating chroma.js should also be possible as even though it is a major change it is only used for the color bars in maps.

**Comment by sgiehl** [comment]
@Findus23  was wondering if that would have any benefit. The library seems to have a lot more features now, which increased the size quite a bit. See https://bundlephobia.com/result?p=chroma-js@0.6.3

**Comment by sgiehl** [comment]
also we are actually planning to replace the maps with something new, so guess that lib might get removed anyways...

**Comment by Findus23** [comment]
@sgiehl As the library is just a collection of equations it should be fine from a security point of view to stay with the old library.

**Pull request merged**
