### PR TITLE
No-data GTM screen translations

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Add translations for GTM tab of the no-data screen.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
The translations are pending product team review, so please don't merge until they are confirmed to be correct.

**Comment by michalkleiner** [comment]
Failing tests are already failing on `5.x-dev` and are unrelated to this PR so it's not for this PR to address that.
Let's get this reviewed and merged since it's causing a lot of troubles rebasing and reviewing locally every time a new addition is added to the no-data screen.

**Comment by michalkleiner** [comment]
Internal ref. for context: DEV-16595

**Review by sgiehl — APPROVED** [review]
Looked through all the languages and the GTM part is translated as expected. Will merge this PR and mark the translations as reviewed on weblate

**Comment by michalkleiner** [comment]
Thanks @sgiehl. I will update the PR for `4.x-dev` branch as well.

**Pull request merged**
