### PR TITLE
Moved i18n data to core/Intl

### PR DESCRIPTION
**Pull request by sgiehl**
Instead of moving the i18n-data to a separate repository, they are now located in `core/Intl`.

I've generated those files out of the old Piwik data and used data from [unicode-cldr/cldr-localenames-full](https://github.com/unicode-cldr/cldr-localenames-full) to improve them.

To make it easy to update those data, I've added a new console command `intl:generate`, that allows updating the files using the current master of unicode-cldr/cldr-localenames-full.

### CODE REVIEW

**Comment by mattab** [comment]
Feedback:

 * Nice idea to reuse unicode-cldr I didn't know this existed and it looks useful! it's a really great added value to translators that they don't have to translate 250+ country names! :+1: 
 * Maybe the new command could be moved in `translations:generate-intl-data` instead of `intl:generate` 
 * Looks good to me

**Comment by sgiehl** [comment]
I'll rename the console command later. Guess we should also be able to use other parts of unicode-cldr. It also includes names of months & weekdays as well as time formats. I'll have a look at that within the next days

**Comment by sgiehl** [comment]
Should be finished so far. I'll add some more intl data like continents, day and month names, etc in another PR to keep them small.

**Comment by mnapoli** [comment]
Funnily enough [a UI test "broke"](http://builds-artifacts.piwik.org/ui-tests.i18n-data/12828.7/screenshot-diffs/singlediff.html?processed=../processed-ui-screenshots/UIIntegrationTest_dashboard2.png&expected=UIIntegrationTest_dashboard2.png&github=UIIntegrationTest_dashboard2.png) because `Russian Federation` became `Russia` :) (it's fine)

`AllTests` fails because of what seems to be no disk space left :/ Is it one of the random failures or something new?

Except the `AllTests` looks good to merge

**Comment by mnapoli** [comment]
By they way there is no way we download directly the original package (unicode-cldr/cldr-localenames-full) using a package manager? That would avoid having to update the translations if this could be handled by another system like Composer for example. And it would avoid to commit several megabytes in the repo.

They have npm or Bower integration, but I'm not sure it's a good idea for us (PHP project) to use this. But it seems there are other packages on Packagist that contain the same data.

The thing is: does it make sense to commit such data in Piwik's repository. The idea with [core/Intl/Resources](https://github.com/piwik/piwik/tree/master/core/Intl/Data/Resources) was to make it easier to eventually replace it with a 3rd party lib, because why would we maintain that ourselves?

**Comment by sgiehl** [comment]
For sure we could use the full dataset of `unicode-cldr/cldr-localenames-full`. But it contains a lot of languages and Piwik would only use a small part of it.
That would mean we include a big bunch of data without any use.
Additionally `unicode-cldr/cldr-localenames-full` only contains the language and country names, for month and day names we would also need `unicode-cldr/cldr-dates-full`

Small Note: We would only need to run the console command to update the intl data in two cases:
- a new language is added to piwik (which happens not so often)
- new `unicode-cldr/cldr-localenames-full` release (which happens twice a year, according to their release plan)

**Comment by mnapoli** [comment]
Ah OK you only fetch what we need, then :+1:

**Pull request merged**
