### PR TITLE
Use flex for sparkline text instead of block

### LINKED ISSUE #12451: Format sparklines better
for example instead of 
image

it would be possibly better to show it like this:

image

### PR DESCRIPTION
**Pull request by fdellwing**
Fixes #12451

### CODE REVIEW

**Comment by fdellwing** [comment]
Some things don’t look as expected. Will look into that.

**Comment by fdellwing** [comment]
I need to know there this card is created: https://builds-artifacts.piwik.org/matomo-org/matomo/3.x-dev/25726/UIIntegrationTest_visitors_locations_provider.png

The text needs to be spanned to work, it's a text node at the moment.

-----

For most of the other differences. Would it be possible to wrap everything besides the `` in the sparkline inside another `<div>`?

Where is this layout defined?

**Comment by fdellwing** [comment]
Travis did not upload the screenshots to https://builds-artifacts.piwik.org/matomo-org/matomo/3.x-dev/25728/

Can someone trigger the build again or do I need to push something?

**Comment by fdellwing** [comment]
Ok, thats a lot better. But Ecommerce is a problem, but I do not have an matomo instance where I can test this. Does anyone has an instance where I could test this widgets?

**Comment by mattab** [comment]
HI @fdellwing . Thanks for the PR. Here is my feedback/reiew:

* The flex seems to cause some of the sparklines images to shrink in width. See in the top left widget here: https://builds-artifacts.piwik.org/matomo-org/matomo/3.x-dev/25728/processed/UIIntegrationTest_dashboard4.png

* The Ecommerce data can be generated using the Visitor Generator: http://plugins.piwik.org/VisitorGenerator via both the UI provided, or the new console commands. (remember to activate Ecommerce for your website)

* The vertical alignment has changed in the PR. See in: https://builds-artifacts.piwik.org/matomo-org/matomo/3.x-dev/25728/UIIntegrationTest_visitors_overview.png where the text should stay at the same alignment

**Comment by fdellwing** [comment]
> The flex seems to cause some of the sparklines images to shrink in width.
This is just a problem in the UI Tests. In "real" the sparklines have the same width as always, I dont know why this happens in the test. Maybe because the placeholder grafic behaves different.

> The Ecommerce data can be generated using the Visitor Generator
Will look into this. But probably after the weekend as I'm quite busy at work with things I get paid for ;)

> The vertical alignment has changed in the PR. 
Thats a result in using flex instead of block. It is not really visible for the user, but I can fix that if wanted.

**Comment by fdellwing** [comment]
Something seems to be broken with Tests, I can not really check what my changes are.

It seems to have something to do with #12463.

Can you update the screens please and rerun the build? Will look into the results on monday.

**Comment by fdellwing** [comment]
@Findus23 Can you restart the build again please? I think the screens got updated.

**Comment by Findus23** [comment]
@fdellwing I think you’ll need to merge the latest 3.x-dev into your branch to fix the tests

**Comment by tsteur** [comment]
@mattab the smaller sparklines will be likely the same we experienced with Chromium and may be even a browser bug.

**Comment by fdellwing** [comment]
It seems like the rule to get the same align as before is not picked up by the UI tests.

```css
div.sparkline script+div {
    margin: 1px 0 0 1px;
}
```

Maybe there is no script tag?

What should I do? I could give every div inside a sparkline the padding, but that could have some other side effects. Please decide that as you wish.

From my side, this PR is finished. The placeholder of the sparklines behaves weird, but it would be an really ugly hack to fix that in UI tests only.

piwik2

Should I do a clean PR without all with garbage?

**Comment by mattab** [comment]
Hi @fdellwing - sorry for the delay getting back. Yes, it would be great if you could create a new PR or update this one and only have the few files changed that you propose. We will review it for inclusion then. Thanks!

**Comment by Findus23** [comment]
@fdellwing I wouldn't worry too much about the Sparkline placeholders in the UI tests.

In #12066 I am removing them as creating the real Sparklines in the UI tests seems to work.

**Comment by fdellwing** [comment]
I did a clean PR for this changes.

**Pull request closed without merging**
