### PR TITLE
Fix syntax of JSDoc annotations `@param`/`@returns` to enable type hinting in IDE

### PR DESCRIPTION
**Pull request by rr-it**
### Description:

Some functions are already somehow annotated via JSDoc. But the syntax especially for `type` does not follow JSDoc standards.

This PR fixes the JSDoc syntax of already annotated functions. Thereby IDEs apply correct type hinting.
No actual changes on the JavaScript code itself.

For JSDoc see:
[@param](https://jsdoc.app/tags-param.html)
[@returns](https://jsdoc.app/tags-returns.html)
[@type](https://jsdoc.app/tags-type.html)

### Applied changes:

--- 

#### Dev: fix JSDoc annotated `type` in `@param` and `@returns`

All changes done via Regex replacements:

Find:    `@return `
Replace: `@returns `

Find:    `(@param|@returns) array($| )`
Replace: `$1 {Array}$2`

Find:    `(@param|@returns) (.+\|)array($| )`
Replace: `$1 {$2Array}$3`

Find:    `(@param|@returns) bool($| )`
Replace: `$1 {boolean}$2`

Find:    `(@param|@returns) DOMElement($| )`
Replace: `$1 {Element}$2`

Find:    `(@param|@returns) function($| )`
Replace: `$1 {Function}$2`

Find:    `(@param|@returns) integer($| )`
Replace: `$1 {int}$2`

Find:    `(@param|@returns) mixed($| )`
Replace: `$1 {\*}$2`

Find:    `(@param|@returns) ((?:boolean|int|float|null|number|string|Array|Element|Function|Object)(?:\|(?:boolean|int|float|null|number|string|Array|Element|Function|Object))*)($| )`
Replace: `$1 {$2}$3`

Find:    `@returns (Tracker(?:\[\])?)($| )`
Replace: `@returns {$1}$2`

---

#### Dev: fix JSDoc annotated `@param` and `@return` statements

Manually fix:
- missing/wrong name of parameter
- `@param` used instead of `@returns`

---

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks for the contribution @rr-it, nice one! I'll let the test suites run and then look at merging these. Went over the diff and it all looks ok.

**Comment by michalkleiner** [comment]
Can you please commit the minified version of `piwik.js` as well? Some tests fail because of the minified version not matching the source.

**Comment by rr-it** [comment]
@michalkleiner Minified tracker js added.

**Review by sgiehl — APPROVED** [review]
looks good to me as well. relevant tests seem to be passing

**Pull request merged**
