### PR TITLE
[WIP] Added testomatio reporter for ui tests

### PR DESCRIPTION
**Pull request by DavertMik**
This PR adds Testoamt.io reporter to UI tests

* mocha updated to 8.x
* installed testomatio reporter

Reporter requires API key to be passed either as `TESTOMATIO` environment variable, so GitHub action should be updated to include that. Or set in configuration as it is shown on this PR. 

Tests should be executed like this:

```
TESTOMATIO=tstmt_{validAPiKey}  ./console tests:run-ui

```

### CODE REVIEW

**Comment by tsteur** [comment]
There should now be an action secret `TESTOMATIO` configured

**Review by sgiehl — DISMISSED** [review]
We can't easily update mocha. Looking at the test output, this now lacks any details which tests are running or failing. If a mocha update is required we might need a separate task to investigate the requirements and update mocha and maybe also chai...

**Comment by achakko** [comment]
> We can't easily update mocha. Looking at the test output, this now lacks any details which tests are running or failing. If a mocha update is required we might need a separate task to investigate the requirements and update mocha and maybe also chai...

Hi @sgiehl I will add this to backlog to likely prioritise in upcoming sprints.

**Comment by michalkleiner** [comment]
@achakko @DavertMik unfortunately our UI tests screenshots preview service currently can't handle branches with slashes in them, so we don't see what UI tests are failing.

I think it'd be best to close this PR and open a new one from a branch that doesn't contain one in its name. Also remove the WIP from the PR title if it's no longer WIP or make a draft one instead.

**Comment by sgiehl** [comment]
@michalkleiner Actually github isn't able to upload any screenshots for PRs coming from forks. So another branch name wouldn't help there. But as this requires a mocha/chai update, we won't be able to merge that anyway.

**Review by achakko — APPROVED** [review]
Moving pull request to internal branch

**Review by achakko — APPROVED** [review]
Moving pull request to internal branch

**Pull request merged**
