### PR TITLE
Remove director detection

### PR DESCRIPTION
**Pull request by pebosi**
Discussion on #15627 was to decide to remove detection of some plugin detections.

### CODE REVIEW

**Comment by tsteur** [comment]
fyi @pebosi same here as in the Gears we would also use a `0` in the fingerprint where director used to be used.

**Comment by tsteur** [comment]
Hi @pebosi are you still working on this?

**Comment by pebosi** [comment]
Will look into this, later this week

**Comment by sgiehl** [comment]
Will finish that in a new PR as well...

**Pull request closed without merging**
