### PR TITLE
fix for issue Improve look when no data #7092

### PR DESCRIPTION
**Pull request by saleemkce**
Fix for issue https://github.com/piwik/piwik/issues/7092

@tsteur I have updated the css and now it looks as aligned to left with 15px padded (If you have different suggestion, please change this padding value. It looks neat for now) to left. It now affects many core pages because all report sections based on this class **pk-emptyDataTable**  I have attached two screenshot how it looks after the update. I have checked throughout the site plus all widget sections. There is no css break. Please feel free to comment if it looks bad anywhere.

action_sitesearch

=> **Screenshot @ sitesearch section.**

---

visitor-location

=> **screenshot @ visition->location area**

### CODE REVIEW

**Comment by tsteur** [comment]
Should we maybe set the following?

```
.widget .pk-emptyDataTable {
padding-left: 15px;
}

.pk-emptyDataTable {
padding-left: 11px;
}
```

I'd also love to get rid of the `font-style: italic` but not sure how other people see it. On my screen it doesn't look nice and is not really helpful either. What do you think?

I'd be happy with this change with the new padding-left but I reckon some others might want to stick to the old centered version @mattab ?

:+1:  for me after changing to `padding-left: 11px` for normal widgets.

**Comment by mattab** [comment]
sounds good to align the "there is no data for this report." to the left :+1: (on your screenshot it seems too much to the right stlil and not perfectly aligned with title, I guess that's why @tsteur you suggest 11px instead of 15px)

**Comment by saleemkce** [comment]
@tsteur @mattab yea "padding-left: 11px" looks good too. I agree. Could you merge the branch and close down the issue if there is nothing more to discuss?

**Comment by mattab** [comment]
@saleemkce maybe you could make the change to 11px in your PR. 

> On my screen it doesn't look nice and is not really helpful either. What do you think?
+1 wondering what it looks like without italic?

**Comment by saleemkce** [comment]
Hi Matthieu, I will do both (without italic) & (padding to 11px) changes and show (screenshots) here possibly later today. I am a bit busy.

**Comment by saleemkce** [comment]
Here is the updated screenshot with padding-left:11px and italic removed,

css-alignment-updated-in-reports

I have committed these changes so as to avoid any conflicts or issues. If anything wrong, please suggest.

**Comment by mattab** [comment]
Hi @saleemkce 

I reckon this looks good now! well done.

I looked at "Files" tab in your pull request and as you can see it includes other commits. Could you try remove those extra commits from your pull request, or maybe create a new PR with only the commit that fixes the issue?

**Comment by saleemkce** [comment]
This pull has been moved here for your reference https://github.com/piwik/piwik/pull/7799

**Pull request closed without merging**
