### PR TITLE
Trim referrer url if needed

### PR DESCRIPTION
**Pull request by tsteur**
refs https://github.com/matomo-org/matomo/pull/16835#issuecomment-735466614

fyi @sgiehl

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by mattab** [comment]
fyi added to https://matomo.org/docs/data-limits/
Screenshot from 2020-11-30 11-53-34

**Comment by sgiehl** [comment]
@mattab 1500 bytes is actually not correct I guess. It's a VARCHAR(1500) so there are 1500 characters allowed. Depending on the collation one character can have up to 3 or 4 bytes. Might be better to write characters instead maybe

**Comment by mattab** [comment]
@sgiehl sounds good! updated to this:
Screenshot from 2020-12-07 09-47-05

**Comment by tsteur** [comment]
@mattab as mentioned in slack by default the referrer page url is also limited to 1024 characters but can be increased to 1500 through the same setting.

**Pull request merged**
