### PR TITLE
use RecordBuilders in VisitTime plugin

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off of #20720 which should be reviewed and merged first.**

Changes:
* Move archiving logic to RecordBuilders in VisitTime plugin.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
We might chain the PRs in the way they were done so that we only see the incremental changes. When the first one is merged the target branch would get automatically updated etc.

Having all the changes from all the other PRs make this quite hard to navigate.

**Comment by diosmosis** [comment]
@michalkleiner Please review/merge the original RecordBuilder PR first. This one does not have the Needs Review tag for a reason.

**Comment by michalkleiner** [comment]
Fair point, missed that missing tag. Sorry!

**Review by sgiehl — CHANGES_REQUESTED** [review]
@diosmosis there seems to be a related test failing. It works on 5.x-dev, so it seems to be connected to the changes in this PR.

**Comment by diosmosis** [comment]
@sgiehl should be fixed by latest commit. will fix the same issue for other PRs as well.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
