### PR TITLE
Replace all utf8 4-byte characters in tracked urls with �

### PR DESCRIPTION
**Pull request by sgiehl**
As described in #7766 all 4-byte characters in urls currently fail to be tracked.
As long as we won't switch the table layouts to utf8mb4 this "hack" makes it possible to track those urls, even if they are wrong afterwards, as some characters might get replaced.

### CODE REVIEW

**Comment by mattab** [comment]
IMHO, this is "nice hack" - if one can write this.

Feedback:

 * Can you add such URL in one  System test? (in a new test case or editing an existing one). it would be good to have both integration + system test, covering this use case.

**Comment by mattab** [comment]
@sgiehl I've added a system tests, once build is green will merge it :+1:

**Comment by sgiehl** [comment]
:+1

**Comment by saqib16** [comment]
Hi,

We have installed Piwik 3.0.2 and PHP 7.0.16 and getting following error:  .

Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0_\xD0\xBB\xD0\xB5...' for column 'name' at row 1 In query: INSERT INTO piwik_log_action (name, hash, type, url_prefix) VALUES (?,CRC32(?),?,?) Parameters: array (   0 => '/products/Ð¡Ñ‡ÐµÑ‚Ñ‡Ð¸ÐºÐ¸ Ð_Ð»ÐµÐºÑ‚Ñ€Ð¾Ñ_Ð½ÐµÑ€Ð³Ð¸Ð¸/?cid=91701',   1 => '/products/Ð¡Ñ‡ÐµÑ‚Ñ‡Ð¸ÐºÐ¸ Ð_Ð»ÐµÐºÑ‚Ñ€Ð¾Ñ_Ð½ÐµÑ€Ð³Ð¸Ð¸/?cid=91701',   2 => 1,   3 => 0, )

Any guess/solution appreciated?

**Comment by gmariani** [comment]
Still having this issue with 3.4.0 on PHP 7.2

[09-May-2018 14:11:33 UTC] Error in Matomo: Your Matomo version 3.4.0 is up to date.
[09-May-2018 14:11:43 UTC] Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8F\xA1 C...' for column 'name' at row 1 In query: INSERT INTO piwik_log_action (name, hash, type, url_prefix) VALUES (?,CRC32(?),?,?) Parameters: array (   0 => 'ðŸ¡ Chandler Arizona Luxury Homes | [John Cunningham 2018]',   1 => 'ðŸ¡ Chandler Arizona Luxury Homes | [John Cunningham 2018]',   2 => 4,   3 => NULL, )

**Comment by sgiehl** [comment]
@gmariani to be able to save utf8 4byte charaters correctly we need to do a schema change. As this will affect potentially very big tables we can do that with major release only. See #8790

**Comment by gmariani** [comment]
Ok, i get that the collation/schema needs to change to SUPPORT mb4. But I thought the solution was to modify the text as to avoid the need for mb4 in the first place? That the emoji would be replaced with the � character? Which would mean it's not doing it's job properly. Is that incorrect?

Looking at the error message closer, i do see the � in there, maybe it's not properly replacing the entirety of the emoji?

**Pull request merged**
