### PR TITLE
Reduce test run time

### PR DESCRIPTION
**Pull request by fabiocarneiro**
A test to see if the test run time can be reduced by removing composer installation on javascript tests.

EDIT: Composer itself made almost no difference. I'm not sure if this is cached, but if it is, it is he reason.

I removed the individual test suites, since they're also run in AllTests and apparently there is no setting difference.

**Total test time reduced from 1 hr 47 min 16 sec to 1 hr 19 min 57 sec.** 

**25% faster.**

### CODE REVIEW

**Comment by mnapoli** [comment]
The `AllTests` suite runs using MySQLi, whereas the other (separated) test suites run using PDO. So there's a reason why there are those test suites (they should be kept).

Regarding composer install it's not a bad idea but it will not improve the build time: what you reported is the total build time which is the sum of all jobs. However Travis runs jobs in parallel, so the real build time is roughly equal to the longest of all jobs (which is the UI tests).

**Comment by fabiocarneiro** [comment]
@mnapoli I understand that. But travis don't run all jobs at once. I don't know what plan you guys are using, but since I only saw 2 jobs running concurrently, my guess is that it's the startup plan. Even if piwik has the premium plan that has 10 concurrent jobs, having less jobs per build is still an advantage because if you have 4 jobs instead of 6, you would test 2,5 PR's Instead of 1,6. 

About composer, this is still valid even without removing the tests suites. This ignore composer seems to be a feature that was planned, but missing. When I said I didn't see any difference with that, i analyzed those javascript job times in particular, not the entire build. 

I can remove the last commit if that's ok for you, so it will contain only the composer part. But I still think it might be worth considering running it in pdo only. pdo is php > 5.1. Are you supporting envs older than that?

**Comment by mnapoli** [comment]
> I can remove the last commit if that's ok for you, so it will contain only the composer part.

Sounds good to me. You'll need to update the `travis.yml.twig` file too.

> But I still think it might be worth considering running it in pdo only. pdo is php > 5.1. Are you supporting envs older than that?

Supporting only 5.3+, but there's a chance to break either PDO or mysqli, last time we discussed this decision was made to keep building with both.

**Comment by tsteur** [comment]
We still want to run tests on PHP 5.3 (UI) and AllTests with mysqli

**Comment by fabiocarneiro** [comment]
@tsteur Already removed that commit. :+1:

**Comment by mnapoli** [comment]
looks good to me :+1:

**Pull request merged**
