### PR TITLE
Improve exception for inconvertible data structures

### LINKED ISSUE #18544: Field width 3356450096 is too long in core/DataTable.php
Error: {"type":1,"message":"Field width 3356450096 is too long","file":"\/var\/www\/html\/core\/DataTable.php","line":1586,"request_id":"2b6ce","backtrace":" on \/var\/www\/html\/core\/DataTable.php(1586)\n","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\MyPlugin\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(619): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(168): Piwik\\FrontController->doDispatch('MyPlugin', 'safemode', Array)\n#3 \/core\/FrontController.php(99): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(274): Piwik\\FrontController::(Array)\n#5 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError()\n#6 {main}"}

URL: https://example.matomo.org/index.php?date=previous24&period=month&expanded=1&filter_limit=-1&force_api_session=1&format=CSV&idSite=4&language=fr&method=API.getProcessedReport&apiModule=Referrers&apiAction=getReferrerType&module=API&period=month&segment=&translateColumnNames=1&convertToUnicode=0&token_auth=....

No referrer

GET: {"date":"previous24","period":"month","expanded":"1","filter_limit":"-1","force_api_session":"1","format":"CSV","idSite":"4","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","segment":"","translateColumnNames":"1","convertToUnicode":"0","token_auth":"....","format_metrics":"bc"}

POST: {"token_auth":"....","date":"previous24","period":"month","expanded":"1","filter_limit":"-1","force_api_session":"1","format":"CSV","idSite":"4","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","segment":"","translateColumnNames":"1","convertToUnicode":"0","format_metrics":"bc"}

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #18544 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by tsteur — COMMENTED** [review]
@sgiehl great to have more descriptive error messages and better understanding what was the issue 🎉 💯 

I'm wondering if it still makes sense to `var_export` the `$row` or in one case the `$subRow` for better understanding assuming it's not too big but if needed can also do without. 

In the tests we could maybe compare the entire error message to ensure the replace of placeholders work? Just a thought.

**Comment by sgiehl** [comment]
> I'm wondering if it still makes sense to var_export the $row or in one case the $subRow for better understanding assuming it's not too big but if needed can also do without.

I actually don't think that is needed. We would need to check if the part we want to print might not be too big, otherwise we run into the same problem as before. Also the error message advice this:

`Try to call this method with the parameters '&format=original&serialize=1'; you will get the original php data structure serialized.`

Doing that would give the whole structure and make it possible to identify the issues I think. At least for a developer.

**Comment by tsteur** [comment]
> Doing that would give the whole structure and make it possible to identify the issues I think. At least for a developer.

OK. It's just a bit painful and not so developer friendly. Especially when it's done by production apps (or tools lke big query) etc and then you get a message like `Found array value for column '1' in row '0'."`. And you maybe don't even easily have the reference to the request etc. It could just give more details with little risk assuming we're already lowering the length a lot by using only one row instead of many rows. Not too important though maybe.

**Comment by sgiehl** [comment]
@tsteur Ok. I'll add it back for now. If it still causes problems, we can consider fully removing it later as well.

**Review by tsteur — APPROVED** [review]
Nice one @sgiehl 👍

**Pull request merged**
