### PR TITLE
Fix capabilities weren't detected correctly

### PR DESCRIPTION
**Pull request by tsteur**

### CODE REVIEW

**Comment by diosmosis** [comment]
Should there be a test for this?

**Comment by tsteur** [comment]
I reckon it's fine. It is not really easily testable since in UI tests we mostly use FakeAccess for example. Could put it in a protected function or so if needed and test it possibly.

**Comment by diosmosis** [comment]
Could be in an integration test for Access? I haven't checked of course.

**Comment by tsteur** [comment]
Sorry somehow thought it was in a controller. Done

**Pull request merged**
