### PR TITLE
copy of the other PR

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

copy of 18672(https://github.com/matomo-org/matomo/pull/18672)

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
btw requires this a new vue build?

note: this refs https://github.com/matomo-org/matomo/pull/18672

**Comment by peterhashair** [comment]
@tsteur I think it does need a new VUE to build, it's part of the `CoreHome` ts file, the original had a random VUE build that failed stopped halfway.

**Comment by sgiehl** [comment]
@peterhashair be good to check if vue builds ran correctly before approving a PR. I'm actually wondering how you did some sort of testing in the UI for the other PR without building the vue files.

**Comment by peterhashair** [comment]
@sgiehl probably the complied js is already exist in the branch.

**Comment by sgiehl** [comment]
In this PR yes. But not in the one that was already merged to 4.x-dev

**Comment by peterhashair** [comment]
@sgiehl I mean `plugins/CoreHome/vue/dist/CoreHome.umd.js` this should be always exist, just not up to date. The UI just running the last version of commit I guess.

**Comment by sgiehl** [comment]
Sure. But without the update you won't see the changes in the ui

**Comment by sgiehl** [comment]
But actually that doesn't matter that much. If a PR changes something in a Vue or typescript file, it's in almost all cases needed that the built Vue files are updated. And if that isn't the case we shouldn't approve the PR or rerun the action before approving it to ensure the PR only will be merged with built files.

**Comment by peterhashair** [comment]
@sgiehl  sorry about that, just realise merge won't build vue it again.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
