### PR TITLE
Fixes #7912, add --force-idsegments parameter and --skip-all-segments parameter to core:archive command.

### LINKED ISSUE #7912: Allow CLI archiving for only specific segments
Goal of this issue is to give ability of processing only certain segments when running CLI archiver.
There are some cases when only couple of segments need to be re-processed (due to archiving failure or so). For this purpose it would be ideal to have new parameter for ex. --force-idsegments, that will allow passing id's of segments to archive. For sites with 20-30-40 segments it may be extremely inefficient to query for all segments.

Please let me know if you have any questions or want better justification for this request?

### PR DESCRIPTION
**Pull request by diosmosis**
As title.

Also includes a change to CronArchive/CronArchiveTest.php which allows using a mock CliMulti instance with CronArchive. Speeds CronArchiveTest.php by ~10s.

Refs #7912

### CODE REVIEW

**Comment by tsteur** [comment]
There are some tests failing? Do you mind having a look whether it is caused by this PR? Just for understanding: Was the only reason to add this to save 10 seconds or other things as well?

**Comment by diosmosis** [comment]
>  Was the only reason to add this to save 10 seconds or other things as well?

The issue is to fix #7912, that's the main reason for this PR.

The test change was just so my additional test wouldn't result in a longer test run.

Will look at the build failure now.

**Comment by diosmosis** [comment]
The build failure was due to a bug, should be fixed in the code I pushed.

**Comment by diosmosis** [comment]
@tsteur or @mattab, ping-ing for review; it's a pretty small change.

**Pull request merged**
