### PR TITLE
missing some code in #21232

### LINKED ISSUE #21283: Rowevolution is showing the ID instead label
We recently observed that a UI test, that was failing for CrashAnalytics plugin and it seems that rowEvolution now displays the id instead of the label

Screenshot from 2023-09-20 09-23-05

After checking out to Matomo `5.0.0-rc1` we can see the label correctly, looks like something changed post that
Screenshot from 2023-09-20 09-22-11

## Steps to Reproduce (for Bugs)
Check this demo2 [URL](https://demo2.matomo.org/index.php?module=CoreHome&action=index&idSite=82&period=day&date=yesterday#?period=day&date=yesterday&idSite=82&category=CrashAnalytics_Crashes&subcategory=CrashAnalytics_AllCrashes&popover=RowAction%243ARowEvolution%243ACrashAnalytics.getCrashMessages%243A%24257B%24257D%243A35)

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

As title.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Are there any tests that were failing before this? If not, should we add some to make sure it's covered?

**Comment by diosmosis** [comment]
@michalkleiner tests in CrashAnalytics. This part of Matomo isn't currently testable outside of a UI test, and only crash analytics uses this feature.

**Comment by sgiehl** [comment]
@AltamashShaikh are you able to confirm that this fixes the issue in crash analytics?

**Comment by AltamashShaikh** [comment]
@michalkleiner @sgiehl It fixes the issue for CrashAnalytics

**Pull request merged**
