### PR TITLE
Updating Angular to version 1.6

### PR DESCRIPTION
**Pull request by diosmosis**
This PR can be reviewed commit by commit.

Not sure if this can be merged, I wanted to use  `.component()` which isn't available in 1.4.

Changes:

* Updated angular & related packages to version 1.6.
* Updated ngDialog to latest version.

Notes:

* Had to make a manual change to kartograph.js (didn't make a PR since it is no longer maintained).
* Looking at the angular migration guide, I saw two items that might cause problems in plugins, but don't know of any actual instances where they would be:
  * https://docs.angularjs.org/guide/migration#directives-ngoptions-
  * https://github.com/angular/angular.js/commit/97bbf86a1979d099802f0d631c17c54b87563b40 (whitespace in attributes isn't automatically trimmed)

Angular 1.6 should be compatible w/ IE9+, but I haven't tested manually yet. If there's anything that should be tested manually on certain browsers, let me know.

### CODE REVIEW

**Comment by mattab** [comment]
UI tests are passing which is promising. @sgiehl maybe you have some feedback as well. we could merge this as soon as 3.0.5 is released and then cut a beta to check whether all plugins builds will pass?

**Comment by sgiehl** [comment]
@mattab Will have a closer look the next days, but let's merge after 3.0.5 as you suggested.

**Comment by diosmosis** [comment]
Did a quick check on a VM w/ IE9, seems broken on 3.x-dev, not sure why. (Also broken on demo.piwik.org).

Some pages don't load (like the dashboard), some look odd, like the visitors log. Known issues?

**Comment by diosmosis** [comment]
Noticed the screenshots aren't stored in LFS, need to fix that before this can be merged.

**Comment by tsteur** [comment]
FYI: We dropped IE9 support with Piwik 3

**Comment by diosmosis** [comment]
That's good, I'll check on ie10 :)

**Comment by diosmosis** [comment]
Looks like it's working on ie10. Did a cursory check of dialogs via row actions + a couple pages + the top controls.

**Comment by mattab** [comment]
Good to hear @diosmosis - we'll merge this in the coming days and cut a beta then

**Comment by mattab** [comment]
We just released 3.1.0 so now merging this PR so we have time to test in the beta cycle

**Pull request merged**
