### PR TITLE
remove feedback links

### LINKED ISSUE #18250: Remove review popup
We have a logic to show a popup like below to ask for a review on few review sites. The feature was added in https://github.com/matomo-org/matomo/pull/14432

image

We'd like to remove this feature as it's not much used. 

We're also removing the "refer us" feature in https://github.com/matomo-org/matomo/issues/18232

We're still asking for a review after a user rated a feature positive. We would keep this feature.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #18250 
remove feedback links. Be aware this plugin is already covert to the VUE solution. 

This PR is actually merged into #18262. They basically does similar thing Otherwise there will be conflicts.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — CHANGES_REQUESTED** [review]
@peterhashair If I set the `Feedback.needFeedbackReminder.root` database option to a date in the past then the 'Like Matomo?' popup is still shown on page refresh.

**Comment by peterhashair** [comment]
@bx80 thanks for pointing that out. Removed the popup.

**Comment by sgiehl** [comment]
@peterhashair If this one is integrated in another PR, shall we close it and only review the other one, when it's done. Or are you planning to rebase the other PR, once this one would be reviewed and merged?

**Comment by peterhashair** [comment]
@sgiehl yes, about to close that one.

**Pull request closed without merging**
