### PR TITLE
Check for super user access when cleaning visitor details.

### PR DESCRIPTION
**Pull request by letharion**
The comment for cleanVisitorDetails() says that the function checks for Super User or admin access, this adds the Super User check.

### CODE REVIEW

**Comment by sgiehl** [comment]
Not sure if the comment might be incorrect in this case. Removing those values for all users might have other results than expected. Without the visitorId / userid features like the visitorprofile might not work...

**Comment by letharion** [comment]
In my case, I was doing something like this:
```
Piwik::doAsSuperUser(function () {
  return \Piwik\API\Request::processRequest('Live.getLastVisitsDetails'
```

**Comment by letharion** [comment]
@mattab Thank you for your comment. I've made another attempt here: https://github.com/matomo-org/matomo/pull/12766 Is this the sort of check you meant?

**Comment by letharion** [comment]
I could update the comment instead then, in case it's incorrect, if that's desirable?

@sgiehl You said _Removing those values for all users_ but that appears to be a misunderstanding. I'm not removing the values for anyone, I'm making sure they _remain_ when the user has super access.

**Comment by mattab** [comment]
@letharion Yes I meant this :+1: https://github.com/matomo-org/matomo/pull/12766

**Pull request closed without merging**
