### PR TITLE
Dashboard selector listing all widgets is hidden once the scroll bar is used

### LINKED ISSUE #13489: Dashboard selector listing all widgets is hidden once the scroll bar is used
To reproduce:
* Click on the dashboard selector
* Scroll down using browser scroll bar
* Got: the dashboard selector closed
* Expected: the dashboard selector stays opened

(It's expected the selector closes when one clicks outside of it, but this should exclude the scrollbar area)

### PR DESCRIPTION
**Pull request by tsteur**
fix https://github.com/matomo-org/matomo/issues/13489

### CODE REVIEW

**Comment by diosmosis** [comment]
Tested on windows and it looks like it solves the problem in some cases but not all. Here's an example of it not working:

https://ufile.io/ores8

Didn't look into why exactly. Can probably merged though since it's not that big a bug.

**Comment by tsteur** [comment]
might just need a hire timeout maybe?

**Comment by diosmosis** [comment]
Maybe we could keep the scroll timeout going if the mouse is still pressed?

**Comment by diosmosis** [comment]
Think you detect if mouse is down, then in the timeout if it's down, schedule another 500ms timeout. When the mouse goes back up, the timeout gets cleared so even if the user pauses for a while while scrolling, it won't close the dropdown.

**Comment by tsteur** [comment]
done

**Comment by diosmosis** [comment]
Thanks, I realize it's probably not that important, but figured it was a simple change to apply.

**Review by sgiehl — APPROVED** [review]
Tested it in Chrome, Firefox and Opera. Seems to work as expected :+1:

**Pull request merged**
