### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by iMarkus**
You can't access this resource as it requires an 'admin' access for the website id = 1. -->  correct
You can't access this resource as it requires an 'view' access for the website id = 1. -->     incorrect

Please issue pull request against the `3.x-dev` branch only.

Piwik 2 is in LTS mode. This means we do not accept any pull request for 2.x except critical security bugs and major data loss bugs. 

If you need to create a pull request for 2.x, then please also create the pull request against the `3.x-dev` so we can merge both.

Happy hacking!

### CODE REVIEW

**Comment by mattab** [comment]
Thanks for the PR @iMarkus 

LGTM :+1:

**Comment by sgiehl** [comment]
This text occurs in various test files and needs to be updated there as well.

**Comment by sgiehl** [comment]
@iMarkus  are you able to update the PR?

**Comment by iMarkus** [comment]
@sgiehl sorry, what do you mean with update?

**Comment by sgiehl** [comment]
Some of the tests contain the changed text. Those files needs to be updated
as well.

**Comment by iMarkus** [comment]
Done

**Comment by sgiehl** [comment]
@iMarkus seems you accidentally added line endings to those files. I've pushed a commit to your branch to remove them. Let's see if tests passes now

**Comment by iMarkus** [comment]
@sgiehl I did the edit in firefox browser and just deleted the 'an'. Wondering why line endings appeared.

**Comment by sgiehl** [comment]
Github seems to do that "automatically" in online editor. Wasn't able to remove them their either.

**Pull request merged**
