### PR TITLE
Remove translation / badge count from admin plugins

### PR DESCRIPTION
**Pull request by caddoo**
### Description:

Currently on mobile the Plugins menu item is broken and unreadable, this removes the feature of adding the amount of plugin updates there are making the translation work.

In the future we can make the UI consistent and use a badge count for this menu.

https://github.com/matomo-org/matomo/issues/21204

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — CHANGES_REQUESTED** [review]
This works for me in testing and removes the new plugins count :+1: 

Since the original issue mentions other mobile menu items with missing translations, can we expand the UI screenshot tests here to cover all the mobile menu sub-menus? This way we can have more confidence that other issues haven't been missed and our test coverage will increase.

**Comment by bx80** [comment]
The view port might need to be [expanded](https://builds-artifacts.matomo.org/matomo-org/matomo/dev-17143-fix-translation-error-for-hamburger/6165833116/MobileMenu_mobileMenuPartial.png) to fit the entire expanded mobile menu.

**Comment by sgiehl** [comment]
Removing the count for the plugins menu only fixes that specific issue. There might be other plugins adding similar entries, which might then be displayed incorrectly as well. As mentioned somewhere else already it might make more sense to simply provide the already translated entries to the vue component. I can't see any benefit to let javascript translate them...
And to fully fix that, we would need to refactor/extend the menu class, so it's possible to set a sort of id for an entry (which currently is the translation key) and also a translation, that might differ from that.

**Comment by caddoo** [comment]
> Removing the count for the plugins menu only fixes that specific issue. There might be other plugins adding similar entries, which might then be displayed incorrectly as well. As mentioned somewhere else already it might make more sense to simply provide the already translated entries to the vue component. I can't see any benefit to let javascript translate them...
> And to fully fix that, we would need to refactor/extend the menu class, so it's possible to set a sort of id for an entry (which currently is the translation key) and also a translation, that might differ from that.

Now it is at least somewhat consistent for this one instance, the translations for the full width menu happen in Twig and the translations for the mobile menu happen in Vue, both from the view.

What you are suggesting about providing already translated strings to these views will have the same problem with other plugins we don't know about, they will still be sending the translation IDs while we are expecting a fully translated string.

For now this PR fixes the reported problem, with the default install of Matomo (or whatever the UI suite runs with), are you ok to leave it like this for now @sgiehl ?

**Review by bx80 — APPROVED** [review]

**Pull request merged**
