### PR TITLE
Fix for long report titles overflowing on PDF reports

### LINKED ISSUE #19693: Measurables with long names have name cutoff in PDF reports
The issue occurs when generating an email report for a long website title (as defined under Matomo >> All Website) 
example:  website name "A quite long name for a simple website which hopefully reproduces the issue" 

Now if we try to generate an email report for this website, the websites full name is cut from the PDF: 
image
see attached img. 

Is there a way we can get the website title to wrap around similar way to the description which allows longer strings to be displayed.

Tested on Matomo version 4.2.1 (older version of tcpdf) and latest, occurs on both. 

Related Forum ticket showing the same issue: https://forum.matomo.org/t/missing-line-breaks-in-mail-reporting-pdf/46244

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #19693

Quick fix for long PDF report titles overflowing off the header page.
Also crops the long title in the page footer (if necessary) so the page counter doesn't overflow.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sgiehl — CHANGES_REQUESTED** [review]
@bx80 Seems there are some regressions in the resulting PDFs. Had a look at the one report test that is failing for core tests. The front page changed like below (the new one is on the left):

image

**Comment by bx80** [comment]
@sgiehl I've improved the layout to more closely match the original and removed the title text justification.

**Comment by sgiehl** [comment]
@bx80 Seems like the PDFs are almost looking the same again. Nevertheless I guess our tests actually do not cover the reason why the changes have been made at all. Wondering if it might make sense to add an additional test case to prevent future regressions around too long report titles.

**Comment by sgiehl** [comment]
@bx80 I've pushed some adjustments for the tests, so they cover the case of a long site name as well as a long description. Feel free to have a quick look at the changes and merge the PR if they suit you.

**Comment by bx80** [comment]
Thanks @sgiehl, good to have the tests cover future regressions :+1:

**Pull request merged**
