### PR TITLE
Some translations might be displayed with encoded entities

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

The were various translations including a `&` or `>`. While this in general is fine, we currently have the problem that various translations of those strings now include a `&amp;` or `&gt;` instead, as weblate automatically escapes them due to the active `safe_html` filter. This can currently cause that the escaped chars are displayed in other languages.

I have now converted all `&` to `&amp;` in the english sources and updated all usages of those strings so they are used 'raw', to avoid double encoding.

@diosmosis I've also updated `ContentBlock.vue` so the title is included as `v-html`, can you quickly check if it's fine that way?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
Wouldn't it be better to just not escape them in weblate so they are escaped in twig/vue?

**Comment by sgiehl** [comment]
@diosmosis I guess we would need to disable the safe_html filter on weblate for that, which I would prefer not to do.
Imho we actually should in general "trust" translations not to contain bad html and use them raw & unescaped.

**Comment by diosmosis** [comment]
My personal opinion is that with a framework like Vue where it is, explicitly in the documentation, discouraged to ever use v-html, increased uses should be avoided. And it is much easier to simply assume all template text is unsafe and use innerText/textContent (indirectly by vue) than it is to have different classes of input where some is actually unsafe and some is maybe safe, and have to consciously remember them.

That said I am not in charge of this so will defer approval of the PR to someone else.

The TypeScript/Vue related changes look fine.

**Comment by sgiehl** [comment]
@Findus23 As you are also involved in the translations stuff. What is your opinion on that one?

**Comment by justinvelluppillai** [comment]
Happy for you to make the decision here @sgiehl

**Review by justinvelluppillai — APPROVED** [review]

**Comment by Findus23** [comment]
I didn't see this PR yet, but have to say that I don't have a strong opinion either way. Not using v-html (or raw) feels cleaner to me and should leave a lot less mental overhead in the whole process. But of course one needs to keep in mind that it is always possible for a translation to contain "special characters" that the English source string doesn't contain, so accidentally encoding twice can cause things like #19626

**Pull request merged**
