### PR TITLE
[4.x] No-data translations for Vue.js, Cloudflare and WordPress

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Backport of #20880 and #20897 to 4.x

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Waiting for the UI tests to finish to UI screenshots.

**Comment by michalkleiner** [comment]
I've included Ben's fix to the SEO test to make more test suits passing.

**Comment by bx80** [comment]
@michalkleiner Is the intention here to have full translations for these languages or just add the translation strings?

(I've ignored the react and SPA/PWA tabs as I understand there is more work to be done on those tabs?)

Testing in German :de:  and Dutch :netherlands: , I see the following text is not yet translated and still shows in English :us:/:uk:
 - Integrations tab: 'We provide step by step guides...'
 - Integrations tab: 'To setup Matomo on your system...'
 - Tracking code tab: The combined message 'Google analytic 3 & 4 and Klaro were detected....'
 - Tracking code tab: The 'Show Advanced Options' expander link
 - MTM tab: The intro text 'If you are embedding...'
 - MTM tab: The 'Matomo Configuration' link at the bottom of the page
 - Others tab: There are various sections not translated in German and Dutch.

GTM, Wordpress and Vue.js tabs all seem to be fully translated :+1:

**Comment by michalkleiner** [comment]
That's a good question @bx80, thanks for that!
We have an internal ticket DEV-16595 to QA/double-check all the remaining parts of the no-data screens to make sure it's all translated for all languages so I'll add your note to that ticket, however in this PR the change is only about the Vue.js, Cloudflare and Wordpress.

SPA/PWA is still in draft for 5.x-dev and will be reviewed and backported separately.

**Comment by sgiehl** [comment]
Had a rough look through the changes again and checked the results locally. Looks fine to me so far. Tests are passing as well. So I'll merge this one. The missing translations can be added any time later...

**Pull request merged**
