### PR TITLE
[Vue] utility function for creating angularjs adapters

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

The adapter code is pretty similar for most directives, so I created a utility function automatically define the angularjs adapter based on some configuration (as also suggested by @peterhashair). It works and in the long run can keep the asset size from getting too much bigger, and will potentially also cut down on time to migrate directives. But it's rather complex (mostly for directives like piwik-dialog that don't use an isolate scope), so I'm not sure how good an idea it is. @tsteur @sgiehl (or anyone else) do you have any opinions?

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
Looks generally good @diosmosis . It only requires some angular test fixes as they are failing now.

**Comment by diosmosis** [comment]
@tsteur this PR is based off of https://github.com/matomo-org/matomo/pull/18127, just to double check that code was reviewed as well, correct?

**Comment by tsteur** [comment]
@diosmosis yes that included the other PR as I only looked and tested this PR but not the other one specifically (there was no needs-review label)

**Comment by diosmosis** [comment]
@tsteur :+1: thanks for the reply, I closed the other PR and will merge this when the build passes.

**Pull request merged**
