### PR TITLE
[UI]update rocket icon to emoji

### LINKED ISSUE #18700: Wrong rocket icon used in no data page
Issue was created in https://github.com/matomo-org/matomo/issues/18458 to change the header and use the rocket icon 
image

But the rocket icon looks like this:

image

Is it possible to use the actual rocket emoji 🚀 maybe or is there an issue with this?

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18700 
update rocket icon to emoji. 
It seems like the emoji Character does not exist in the Travis, Exist in GitHub action. [see here](https://builds-artifacts.matomo.org/github/matomo-org/matomo/4.x-dev/1787464451/OneClickUpdate_login.png)[](https://github.com/peterhashair)

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
It seems like the emoji Character does not exist in the Tests. Not sure if that matters.

**Comment by sgiehl** [comment]
If the font icon isn't in use anymore, I guess we can also remove it again

**Comment by peterhashair** [comment]
@sgiehl it seems like there are lots of places using Rocket Icon. Do we want to replace all of them with emojis? Otherwise, I think removing the icon will break some parts, some js Tests has click event on ` .icon-rocket`

image

**Comment by sgiehl** [comment]
@tsteur Shall we replace all usages of the rocket icon with the emoji, or only that specific one?

**Comment by tsteur** [comment]
not needed for now @sgiehl

**Review by sgiehl — APPROVED** [review]
merged in the last changes from 4.x-dev. If related tests are passing, this should be good to merge.

**Pull request merged**
