### PR TITLE
[Vue] emit/broadcast on scope the method was called on not rootScope

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

AngularJS scopes inherit directly from their parent, so overwriting $emit/$broadcast on the $rootScope changes it for everyone. Which is a problem if the overwritten function uses $rootScope directly to broadcast, and not the given scope. ('$destroy' on a child scope for example can destroy many scopes it shouldn't).

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sgiehl — APPROVED** [review]

**Comment by tsteur** [comment]
Do we know what this breaks for the user? Generally we could merge it as long as we don't break anything else with it. 
For it to be in 4.6.2 we would need a PR against `next_release` branch

**Comment by sgiehl** [comment]
This caused at least the problem in ActivityLog, not sure if anything else is still undiscovered

**Comment by diosmosis** [comment]
Updated the base branch

**Comment by tsteur** [comment]
@diosmosis some UI tests are now failing, not sure if this is expected?

**Comment by diosmosis** [comment]
@tsteur no not expected, looking into it now

**Comment by diosmosis** [comment]
@tsteur most failures are random, the rest are due to database version being different in the screenshot. I updated those.

**Comment by tsteur** [comment]
👍  good to merge then

**Comment by tsteur** [comment]
it's probably not needed to update screenshots in `next_release` as it might be fixed then in 4.x-dev I would assume. Not sure what best flow is there

**Comment by diosmosis** [comment]
@tsteur ok, I won't update (I actually pushed them to the wrong branch)

**Pull request merged**
