### PR TITLE
Fix comparison trends might be displayed incorrect for certain languages

### LINKED ISSUE #18802: Bug in Swedish translation when displaying negative or zero values
Posting two screenshots:

Displayed in English (Correct)
matomo-bug-en

Displayed in Swedish (with some highlighted areas by me)
matomo-bug-sv

Bugs in Swedish version:
* Negative values should be red
* Negative values should have "-" (minus) not "+-" (plus and minus)
* Zero-value should be "grey-ish" just as in the English version.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #18802

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@tsteur I have simplified the PR. The additional columns will now only be requested by the sparkline visualization and thus won't occur in any API output.

**Comment by tsteur** [comment]
I've put it for now into 4.9. I had a quick look and it looks OK but I can't do a full review due to time. Be great for someone to do later a full review

**Review by peterhashair — APPROVED** [review]
Looks good to me.

**Comment by sgiehl** [comment]
@diosmosis It seems the test I had added to this PR starts failing after https://github.com/matomo-org/matomo/pull/18761 has been merged in. The sparklines lost their color. See https://builds-artifacts.matomo.org/matomo-org/matomo/fixcomparisontrend/54586/Comparison_visits_overview_widget_sv.png

I guess the javascript method to initialize the sparklines is called before the colormanager, which is in Vue, has been loaded fully. The sparline requests contain `"lineColor":[null,null]`
Would you mind having a look and maybe pushing a fix on this branch?

**Comment by diosmosis** [comment]
@sgiehl that's weird, ColorManager is still in vanilla JS. I'll take a look.

**Comment by diosmosis** [comment]
@sgiehl should be fixed

**Pull request merged**
