### PR TITLE
Changes for usage of DeviceDetector 3.0

### PR DESCRIPTION
**Pull request by sgiehl**
This PR aims to enable Piwik to use the new DeviceDetector 3.0, which will be released around 1st of February.

DeviceDetector 3.0 has some bigger changes:
- Caching was completely replaced
- new device type (portable media player)
- detection of windows was corrected

As part of the PR I've also adjusted the operating system information available for a visit, to match those available for browsers.

_Todos_

before merge:
- [x] set version in composer.json to `~3.0` as soon as it was released

after merge:
- [x] update screenshot tests - device type widgets will change due to new device type

### CODE REVIEW

**Comment by tsteur** [comment]
Looks good to me!

I noticed there is a breaking change in Live API because of renaming `operatingSystemCode` => `operatingSystemName`? Ideally we would deprecate it (having both properties for eg 2 months then remove the old one) but it might be ok in this case. It's up to you to deprecate or break it. Some other applications might depend on this property eg it could break Piwik Mobile if it would use that property https://github.com/piwik/piwik-mobile-2/blob/2.2.0/app/controllers/visitor.js#L262 (which it doesn't as we output OperatingSystem and BrowserName). There's a good chance other application use this property.

Do you mind documenting the changes in `CHANGELOG.md`? 
* The mentioned change either in "Breaking Changes" or "Deprecations"
* The update to 3.0 in "Library updates". It shouldn't matter as it is not a public API but it still good to document it just in case. Eg PRO plugins sometimes access libs directly (which they should not) but they don't in this case as I had a look at the repos 
* I think there are new properties in the Live API output such as `operatingSystemVersion`. This could go into "New features" or "New APIs". We do not really have a good category for this. Maybe we need a new one or a different structure? Reckon "New APIs" would be best otherwise

**Comment by sgiehl** [comment]
```operatingSystemCode``` still exists. I've added ```operatingSystemName``` and ```operatingSystemVersion``` so there are the same properties as for browsers. So there shouldn't be a problem.
I'll adjust the changelog later.

**Comment by tsteur** [comment]
Sorry now I see it, only the order changed :)

**Comment by sgiehl** [comment]
@tsteur I've updated the changelog. If everything is fine, feel free to merge

**Comment by mattab** [comment]
Nice to see the latest and greatest device detector 3.0.0 in Piwik!

**Pull request merged**
