### PR TITLE
Let plugins provide custom piwik.js tracker tests

### PR DESCRIPTION
**Pull request by tsteur**
Plugins could provide custom tracker tests by creating a file 'tests/javascript/index.php' within the plugin.

Won't be a documented feature for now but could add it to dev changelog if needed.

Content within the test file could be eg 

``` html
<script type="text/javascript">
test("MyPiwikTest", function() {
    expect(1);

    var tracker = Piwik.getTracker();

    equal(typeof tracker.trackGoal, 'function', 'trackGoal' );
});
</script>
```

ping @mattab

### CODE REVIEW

**Comment by mattab** [comment]
:+1:

**Comment by mattab** [comment]
> Won't be a documented feature for now but could add it to dev changelog if needed.

fyi: added to dev changelog in https://github.com/piwik/piwik/commit/0a0a01985ef1621357fc16cc9f42e8c1cdad0721

**Comment by tsteur** [comment]
Maybe we could remove it again? It's not properly tested yet and I might want to change the integration later.

**Comment by mattab** [comment]
Sure, removed

**Comment by tsteur** [comment]
Cheers, when this becomes more important we can add an example into an existing example plugin, create a generator for it and document the feature but maybe need another real use case for it that extends the Piwik JS tracker

**Pull request merged**
