### PR TITLE
Use safemode when running CLI commands

### PR DESCRIPTION
**Pull request by diosmosis**
This would allow the controller method in plugins to be used when an error or exception occurs during a CLI command (which should result in an email on cloud, but I haven't tested).

### CODE REVIEW

**Comment by mattab** [comment]
Is it possible to write a test for this @diosmosis ?

**Comment by diosmosis** [comment]
Maybe, I'll give it a shot.

**Comment by tsteur** [comment]
BTW Prefer to not have this in 3.x
We could always deploy it on cloud separately. or include it in next release. Just in case it maybe breaks something (eg around archiving, or in WP Matomo, etc)

**Comment by mattab** [comment]
moved to Matomo 4 milestone

**Pull request merged**
