### PR TITLE
Dev: git hook submodule update via yorkie

### LINKED ISSUE #21877: Dev: use git hook to update submodules on changes
## Summary
Submodules are not updated by default on git-checkout or git-merge.

So every now and then you must manually update the submodules:

See: https://developer.matomo.org/guides/git#cloning-a-repository
```bash
git submodule update --init 
```

May we run `git submodule update` automatically by git hook?

* For performance reasons only run it when it is neccessary e.g. the file `.gitmodules` has changed.
* Use [yorkie](https://github.com/yyx990803/yorkie) to hook into the git hooks. It is not a direct dependency right now, but already included because of sub-dependencies.
  See `cat .git/hooks/post-checkout`:
  ```bash
  #!/bin/sh
  #yorkie 2.0.0
  […]
  ```
* Use simple bash script to make it run on Linux, macOS and Windows.
  (git on windows supports some kind of unix bash: MINGW64 / `git-bash.exe`)

How does the use of git hooks influence the continuous integration, testing and packaging workflow? 

----

There is a new git config option `submodule.recurse`:
> See: https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
> Moreover, if you want to make Git always pull with --recurse-submodules, you can set the configuration option submodule.recurse to true (this works for git pull since Git 2.15). This option will make Git use the --recurse-submodules flag for all commands that support it (except clone).

However:
> See: https://stackoverflow.com/questions/1899792/why-is-git-submodule-not-updated-automatically-on-git-checkout/43854593#43854593
> `submodule.recurse` makes `git fetch` fetch all submodules every time
> This makes the option basically unusably slow, because the fetch happens even when the submodules are up to date, as it tries to fetch an branch updates from those submodules.

----

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

### PR DESCRIPTION
**Pull request by rr-it**
### Description:

This resolves https://github.com/matomo-org/matomo/issues/21877

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by rr-it** [comment]
This is based on https://gist.github.com/digitaljhelms/f74eaf56835262d6bf3f by @digitaljhelms
Thanks for this!

**Comment by sgiehl** [comment]
In general I like the approach, but this might cause problems on systems that don't have the nodejs stuff installed locally.
I'm for example using a virtual box, but the source code is located outside of it. 
So the nodejs dependencies are installed within the vm, while I'm using git on my host system. So the commit hook would fail, as nodejs isn't available.

Furthermore I'm wondering where the exact difference to using `git config submodule.recurse true` is.

**Comment by rr-it** [comment]
> where is the exact difference to using `git config submodule.recurse true`

See https://git-scm.com/book/en/v2/Git-Tools-Submodules
> This option will make Git use the --recurse-submodules flag **for all commands that support it** (except clone).

So any git command that supports `--recurse-submodules` will also run for submodules and therby take longer than neccessary.

**Comment by rr-it** [comment]
> don't have the nodejs stuff installed locally

Well now I checked how git on windows runs: git on windows supports some kind of unix bash (MINGW64 / `git-bash.exe`).
So it is sufficient to have a simple bash script only. And there is no need at all to provide the functionality by Node.js.

**Comment by michalkleiner** [comment]
I'm generally all for automation but with the submodules I feel I would prefer to update them manually as/when needed, or have a configuration option to specify which ones can update automatically and which ones shouldn't. I haven't yet encountered a situation where I would be scratching my head not having the latest submodules.

How would this work with a manual checkout of a different version of a submodule?

**Comment by sgiehl** [comment]
I'm tempted to agree with @michalkleiner on this. During development I sometimes have different submodule branches checked out on purpose, and don't want them to be changed automatically when I switch branches in matomo repo.

Keen to hear what others think about that. ping @matomo-org/core-reviewers

**Comment by bx80** [comment]
I think it depends on the specific case. Quickly switching to a different core branch and then finding things are broken in some obscure way because a sub-module is out of date can happen occasionally and be confusing if unfamiliar with the cause. So it could be helpful to have sub-modules automatically update on checkout for people not working on the code everyday, but for developers working on a few different things simultaneously automatic sub-module updates will likely cause more headaches than it solves.

Maybe a local environment variable could used to control this? Then auto updating the sub-modules could be the default behavior but easily be disabled locally as required.

`export NoAutoUpdateSubmodules=1;`

```
if [[ -z ${NoAutoUpdateSubmodules} ]] || [[ "$NoAutoUpdateSubmodules" != "1" ]]; then

    changedfiles=$(git diff-tree --no-commit-id --name-only HEAD@\{1\} HEAD 2> /dev/null)

    if [[ "${changedfiles[*]}" =~ \.gitmodules ]]; then
        echo "initializing & updating submodule(s)"
        git submodule update --init --recursive
        echo ""
    fi
fi

**Comment by sgiehl** [comment]
I'm tempted to say we shouldn't add that to our code base. Instead we could document how to add an automatic update in our documentation here: https://developer.matomo.org/guides/contributing-to-piwik-core#switching-between-branches
It already advises how to automatically update the dependencies when switching branches, so adding submodules there should be easy.

**Comment by michalkleiner** [comment]
Yep, that's a good idea. Then it's equal to having it controlled by the env variable, you either have the hook or don't.

**Comment by sgiehl** [comment]
Closing this, due to the reasons mentioned before.
Thanks anyway @rr-it for effort!

**Pull request closed without merging**
