### PR TITLE
Improve debugging via Vardumper overriding

### PR DESCRIPTION
**Pull request by ulcuber**
### Description:

Fixes regression of https://github.com/matomo-org/matomo/issues/6890
Same as https://github.com/matomo-org/matomo/commit/6130e7e86baff2979bb84bf979a13130124c1202

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by Findus23** [comment]
Hi,

Can you maybe explain a bit more why this change is needed? The linked PR and commit are nearly a decade old and we are currently more in the process of removing upgradephp (https://github.com/matomo-org/matomo/pull/16650)

**Comment by ulcuber** [comment]
@Findus23 currently `dump()` does nothing because it is defined as empty function in `libs/upgradephp/upgrade.php`. That definition must come after original var-dumper autoloading (via `require_once PIWIK_VENDOR_PATH . '/autoload.php';`)

**Comment by ulcuber** [comment]
@Findus23 we could move it in other place but I'm not sure where it should be

**Review by sgiehl — APPROVED** [review]
Hm. I guess this library has never been used by anyone, as no one yet reported that it didn't work as expected.
Your fix makes it work again, so I will merge it. Thanks for that 👍

**Pull request merged**
