### PR TITLE
Update CA bundle

### LINKED ISSUE #18089: [Console Archive] CURL: SSL certificate problem with expired certificate
Since the [DST Root CA X3 certificate expired yesterday](https://medium.com/geekculture/will-you-be-impacted-by-letsencrypt-dst-root-ca-x3-expiration-d54a018df257), I'm getting tons of errors from Matomos console archive process.
The command that is executed via shell is `console core:archive --url=https://matomo.domain.com/`

## Expected Behavior
No errors.

## Current Behavior

> ERROR [2021-10-01 15:58:52] 28630  Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=week&date=2021-09-27&format=json&trigger=archivephp: 'Got invalid response from API request: https://matomo.domain.com/?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=week&date=2021-09-27&format=json&trigger=archivephp&. Response was 'curl_exec: SSL certificate problem: certificate has expired. Hostname requested was: matomo.domain.com''

## Context
Running curl like `curl -v https://matomo.domain.com/?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=week&date=2021-09-27&format=json&trigger=archivephp&` doesn't produce any errors nor does executing such a test script:
```php
error_reporting(E_ALL);

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://matomo.domain.com/?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=week&date=2021-09-27&format=json&trigger=archivephp&");
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$output = curl_exec($ch);
curl_close($ch);
```

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: 7.2.18
* Server Operating System: Ubuntu 14.04 LTS

### LINKED ISSUE #18094: Update composer/ca-bundle package
To  1.2.11 or newer. We wouldn't update any other package.

When creating the PR please issue this PR against the `next_release` branch.

until we update composer/ca-bundle to 1.2.11, anyone making HTTP requests to Let's Encrypt sites (including archiving) will be broken for users with quite old servers (using openssl 1.0.2)

refs https://github.com/matomo-org/matomo/issues/18089

### PR DESCRIPTION
**Pull request by tsteur**
### Description:

fix https://github.com/matomo-org/matomo/issues/18094
fixes #18089

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@Findus23 I suppose this also fixes https://github.com/matomo-org/matomo/issues/18094 (which user partially fixed themselves now)?

**Comment by Findus23** [comment]
@tsteur Yes, this should also fix #18089 (added it to the description)

**Comment by tsteur** [comment]
great, thanks @Findus23

**Comment by tsteur** [comment]
Related test failures aren't due to this change.

**Review by justinvelluppillai — APPROVED** [review]

**Pull request merged**
