### PR TITLE
fixes notice in wordpress plugin in PHP 8.1

### LINKED ISSUE #19352: Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in app/plugins/Diagnostics/Diagnostic/PhpVersionCheck.php on line 66
there is a deprecated warning on php8.1 for a variable is null and should be a string

## Expected Behavior

No warning displayed when displaying the system report page within the wordpress plugin.

## Current Behavior

Screenshot from 2022-06-14 13-11-09
A warning is displayed when running with php8.1 the system report page

## Possible Solution

define the $piwik_minimumPHPVersion variable as global in the app/core/testMinimumPhpVersion.php solves this issue.

## Steps to Reproduce (for Bugs)

1.install the wordpress plugin 
2.switch to php8.1 version for your apache
3.open the wp-admin/admin.php?page=matomo-systemreport url 
4.views the warning
5.add global $piwik_minimumPHPVersion; in line 25 of the app/core/testMinimumPhpVersion.php
6. refresh the page
7. see the warning message has disappeared

## Your Environment

* Matomo Version: 4.10.0
* PHP Version: 8.1.7
* Server Operating System: Apache 2.4
* Additionally installed plugins:

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by mattmary**
Fixes #19352

### CODE REVIEW

**Comment by mattmary** [comment]
@sgiehl the build fails, but it looks like the screenshots need to be updated

**Comment by fabiocchetti** [comment]
Hi there 👋 Thank you all for your contributions and for fixing this issue.

I've been experiencing the same as #19352 after upgrading to PHP 8.1, so I was looking forward for this fix to be merged.
Just out of curiosity, any idea on when version 4.14 is planned for release?

Again — Thank for your time and efforts, and keep up the good work!

**Comment by mattmary** [comment]
Hello @fabiocchetti 

As this PR will not be available in the next release (4.13.1), I'll patch it during the release process to ensure that you won't have the problem any more (until we get it finally fixed in Matomo).

**Comment by sgiehl** [comment]
@mattmary this one should have be included in 4.13.1

**Comment by fabiocchetti** [comment]
Thank you, @mattmary!

@sgiehl I don't see `#20133` or `#19352` mentioned in [4.13.1 changelog](https://matomo.org/changelog/matomo-4-13-1/), but I noticed the _[not-in-changelog]_ label applied here so I'm not sure if that's expected — even if included in this release — or not.

**Comment by sgiehl** [comment]
Guess it was excluded from the changelog as the change actually does not have effect on Matomo itself

**Pull request merged**
