### PR TITLE
Improve donation message

### PR DESCRIPTION
**Pull request by tsteur**
Please issue pull request against the `3.x-dev` branch only.

Piwik 2 is in LTS mode. This means we do not accept any pull request for 2.x except critical security bugs and major data loss bugs. 

If you need to create a pull request for 2.x, then please also create the pull request against the `3.x-dev` so we can merge both.

Happy hacking!

### CODE REVIEW

**Comment by sgiehl** [comment]
Should we update it for 2.x LTS, as well?

**Comment by tsteur** [comment]
Nah, not needed

**Comment by sgiehl** [comment]
The change is fine, but the screenshots needs to be updated: http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22300/

**Comment by tsteur** [comment]
just pushed the fixed screenshots

**Pull request merged**
