### PR TITLE
add new ini config to enable/disable the php profiler feature

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

It is now required to set enable_php_profiler = 1 in order for the profiler to be enabled.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by flamisz — COMMENTED** [review]
Isn't it confusing this setting is under `[Development]` settings group?
How come the js files changed in this PR, but only the minified versions?

**Comment by diosmosis** [comment]
> Isn't it confusing this setting is under [Development] settings group?

Do you have another suggestion?

> How come the js files changed in this PR, but only the minified versions?

Committed by accident. If you have plugins enabled that have custom tracker code, the minified code is automatically changed when loading matomo.

**Comment by sgiehl** [comment]
Should we maybe add a note to the developer changelog?

**Comment by flamisz** [comment]
> > Isn't it confusing this setting is under [Development] settings group?
> 
> Do you have another suggestion?

We already have some profiler-related settings under `[Debug]`. Maybe there?
> 
> > How come the js files changed in this PR, but only the minified versions?
> 
> Committed by accident. If you have plugins enabled that have custom tracker code, the minified code is automatically changed when loading matomo.

👍

**Comment by diosmosis** [comment]
@sgiehl @flamisz applied review feedback

**Review by flamisz — APPROVED** [review]
👍

**Pull request merged**
