### PR TITLE
Fixes too large buttons padding for mobile

### PR DESCRIPTION
**Pull request by ulcuber**
### Description:

**Actual**

image

**Expected**

image

How to build plugin `Morpheus`?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@ulcuber building `*.less` files isn't needed. Those are parsed on the fly. It's only needed to build with changes to vue related files.

**Review by sgiehl — CHANGES_REQUESTED** [review]
@ulcuber Your changes are producing a couple of regression in the button width. See e.g.
https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/57310/Menus_mobile_top.png
or 
https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/57310/DashboardManager_small_screen.png

It seems you are trying to fix some specific buttons. If that's the case it might be better to apply changes to those specific button maybe, so when can avoid changes anywhere else.

**Comment by ulcuber** [comment]
@sgiehl Yes, this one too bad.
More specific: https://github.com/matomo-org/tag-manager/pull/508

**Comment by sgiehl** [comment]
@ulcuber Nice. Can we close this PR then?

**Comment by ulcuber** [comment]
@sgiehl Yes. Close this PR.

**Pull request closed without merging**
