### PR TITLE
Add Twilio SMSProvider

### PR DESCRIPTION
**Pull request by jamesbvaughan**
This branch adds a new SMS provider for Twilio. It is just two files, an image and `Twilio.php`, which is modelled after the existing SMS providers, `Clockwork.php` and `ASPSMS.php`.

The only SMSProvider method that I was unable to implement is `getCreditLeft()` because the Twilio API does not provide a way to check your current account balance.

### CODE REVIEW

**Comment by mattab** [comment]
Thanks for the PR! we will review in the next few weeks so it can be added to a release

**Comment by sgiehl** [comment]
@mattab a basic question regarding the sms providers:  Do we want to add various new SMS providers to core? It should be easy to handle such new SMS providers in plugins instead.

**Comment by mattab** [comment]
Hi guys,

@sgiehl You're right, we now prefer that new SMS providers are added as part of a plugin [published](http://developer.piwik.org/guides/distributing-your-plugin) on the Marketplace. This way everybody benefits and we the core Piwik team, do not have to officially support all new SMS providers.

@jamesbvaughan we kindly request that the Twilio SMS integration is included in Piwik via the Marketplace. Otherwise your code should be good to go :+1:

**Comment by mattab** [comment]
Hi @jamesbvaughan 

The next steps to get this into Piwik users are:
* [create a new plugin](https://developer.piwik.org/guides/getting-started-part-1#create-a-plugin) and 
* [release it on the Marketplace.](http://developer.piwik.org/guides/distributing-your-plugin)

Thank you for your contribution and we are looking forward to seeing it on the Marketplace :+1:

**Pull request closed without merging**
