### PR TITLE
Remove the symfony polyfill exclusions to allow roave/security-advisories to run

### PR DESCRIPTION
**Pull request by joelpittet**
### Description:
These exclusions don't do much since PHP 7 is required so only the polyfills on > PHP 7 will install, but the replacement causes conflicts on the roave security advisories package, which can make it tricky to keep track of security issues with downstream packages.

```
❯ composer require roave/security-advisories:dev-latest --dev
./composer.json has been updated
Running composer update roave/security-advisories
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - matomo/matomo is present at version dev-5.x-dev and cannot be modified by Composer
    - roave/security-advisories dev-latest conflicts with symfony/polyfill-php55 >=1,<1.10 (matomo/matomo dev-5.x-dev replaces symfony/polyfill-php55 *).
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]
This is ok from my perspective, what do other @matomo-org/core-reviewers think? I would potentially retarget this as `5.0.x-dev` as a technical debt change that could go out in a patch version.

**Comment by joelpittet** [comment]
Let me know if you'd like me to re-target it. Depending if there are other composer.json changes the lock file might need an update for that content hash

**Comment by mneudert** [comment]
Removing should be ok :thinking:

There is no dependency that requires any of those polyfills, so replacing should be a noop anyway. Once the PHP requirement is raised we might want to re-add some replacements, but that will depend on the dependencies required at that time.

**Comment by sgiehl** [comment]
Those polyfill replaces had been added in #16653. As they meanwhile seem no longer to be required anywhere it should indeed be safe to remove them.

**Comment by joelpittet** [comment]
Thanks everybody for the quick turn around! 

The original purpose of removing them seemed to be to avoid installing them... as you set a new PHP requirements that will also avoid installing to old ones. Adding them, though maybe undesired should have negligible consequences and it wasn't clear there were or still are any issues with installing them.

Thanks again for taking my first PR to this project!

**Pull request merged**
