### PR TITLE
Do not serialize every property of Periods which can appear in DataTable metadata.

### PR DESCRIPTION
**Pull request by diosmosis**
Since subperiods are created recursively and the Translator has all translations, serializing both of these properties massively inflates the API response when using php serialization.

@mattab / @tsteur would like to get this in 3.6.0

### CODE REVIEW

**Comment by tsteur** [comment]
Are we actually still supporting PHP serialisation? Does this have any side effects besides the API (probably not)? Be good to maybe have a test for this. No big opinion on the PR otherwise.

**Comment by diosmosis** [comment]
Test for the changes here? Or for php serialized responses?

**Comment by tsteur** [comment]
php serialized response

**Comment by tsteur** [comment]
I just realize if this format is API it would be a breaking change in theory as you maybe wouldn't be able to use the output of 3.6.0 in an older version of Matomo, eg 3.5? Shouldn't be too big of an issue though but can be a problem. Really don't know how much we support that format.

**Comment by diosmosis** [comment]
Tested locally from 3.5.1 => instance w/ these changes and it seems to work, the objects inflate. Only thing that doesn't work is getting a pretty string using a period in the datatable metadata. Not sure what kind of effect that would have.

**Comment by diosmosis** [comment]
^ CC @mattab

**Comment by mattab** [comment]
fyi we're planning to eventually deprecate this format in API responses: https://github.com/matomo-org/matomo/issues/8100

**Comment by mattab** [comment]
@diosmosis the builds are failing, can you please look into them? I'm merging anyway so we proceed with the RC release

**Comment by diosmosis** [comment]
@mattab if all the UI code is in angular & the PHP UI layer doesn't make API requests, then we won't need the original format. Otherwise it's the only way to proxy (that I can think of).

**Comment by mattab** [comment]
@diosmosis the issue #8100 is about removing format=php but we would still support format=original for internal API requests. Is there a problem with removing format=php do you think? if so please post a note in #8100

**Comment by diosmosis** [comment]
No issue w/ removing format=php, just format=original

**Pull request merged**
