### PR TITLE
New command to send test emails

### LINKED ISSUE #14302: New cli command to send test-mail to admin
See also #14455 for a description of this proposed feature.

Many bugs similar to #11534, #12634 (e-mail reports work when sent automatically, but not when sent regularily) have been reported in the last months and my current theory is that this is caused by servers where php mail is only set up correctly for the webserver, but broken in the php.ini read by php-cli.

One way to help debugging this (that would also be useful in other cases) would be a new `console` command that would send a testmail (or if it is easy a report selected by id) to the admin (or another address).

While I am not 100% sure if this will fix #11534 and co. it might be usefull for other people who want to make sure they have set up their Matomo instance correctly. (And getting e-mails to work is often one of the most complex parts as it totally depends on the server environment)

### PR DESCRIPTION
**Pull request by katebutler**
Fixes #14302

### CODE REVIEW

**Comment by diosmosis** [comment]
The suggested message/subject described in https://github.com/matomo-org/matomo/issues/14455 (linked in #14302) is a bit different than what's in this PR, can that be changed? Also it mentions sending an HTML email so `Maill::setWrappedHtmlBody()` would need to be used.

**Comment by katebutler** [comment]
Thanks @diosmosis, have updated with the content suggested on #14455

**Review by diosmosis — APPROVED** [review]
Looks good and works. Not sure if @mattab had any ideas regarding extra debug information, otherwise this can be merged.

**Review by Findus23 — APPROVED** [review]
Looking good.
I hope this helps debugging mail issues in the future.

**Comment by mattab** [comment]
Would be great to have more debug information but I don't know how that's possible. Merging for now :+1:

**Comment by mattab** [comment]
fyi Documented in: [ Emails from Matomo are not being sent, how do I troubleshoot and solve the issue?](https://matomo.org/faq/troubleshooting/faq_34856/)

**Pull request merged**
