### PR TITLE
Fix UI tests

### PR DESCRIPTION
**Pull request by mnapoli**
I played with this branch to try and fix the UI tests. In the end it turns out that updating Mocha fixes (at least in the builds I've seen) the segmentation fault. However the build output is all truncated here and there. At first I believed it was due to colors (non-ASCII characters in the output), but disabling it didn't change anything.

Feel free to push commits to this branch, or maybe we should merge it directly: at least we can get the screenshot diffs?

### CODE REVIEW

**Comment by diosmosis** [comment]
Explicitly allowing colors fixes the console writing issues. I will rebase and merge after a cursory check of the diffs.

**Comment by diosmosis** [comment]
Not merging yet, tests are remarkably slow. Need to investigate.

**Comment by diosmosis** [comment]
Can't reproduce slow tests locally.

**Comment by tsteur** [comment]
> Not merging yet, tests are remarkably slow. Need to investigate.

Is opcache disabled there maybe? I didn't follow whether we disabled it or not.

**Comment by diosmosis** [comment]
> Is opcache disabled there maybe? I didn't follow whether we disabled it or not.

No. It's disabled for me locally though. Currently building phantomjs w/ debug symbols to profile locally.

**Comment by diosmosis** [comment]
Merged in master via squashed merge. The slowness was random, didn't reoccur, though I suppose it will later. Probably due to travis.

**Comment by mnapoli** [comment]
> Explicitly allowing colors fixes the console writing issues

daaamn and here I was trying to force disable colors ;)

**Comment by diosmosis** [comment]
Yeah, don't ask me why :)

**Pull request closed without merging**
