### PR TITLE
with success -> successfully

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by sgiehl** [comment]
Before merging that, we should consider, that it would erase all translations available for this two keys - even if the sense stays the same, so I wouldn't see much benefit in doing it.

**Comment by mnapoli** [comment]
@sgiehl what is the correct way to edit an english translation if we don't want to loose other translations?

**Comment by sgiehl** [comment]
We would need to readd them on transifex after the source was updated

**Comment by sgiehl** [comment]
If we decide to merge that. We should do it right **after** the next release. Then I have enough time to do the required changes on transifex

**Comment by mattab** [comment]
Apparently `with success` is incorrect english, so +1 to merge it

**Comment by sgiehl** [comment]
OK. Then I'll do that. @mattab When will the next release be published?

**Comment by mattab** [comment]
When all issues in 2.14.0 are closed: https://github.com/piwik/piwik/milestones/Piwik%202.14.0 - maybe 2 weeks or bit more?

**Comment by sgiehl** [comment]
OK. Then I'll do it before

**Pull request merged**
