### PR TITLE
Typings and/or PHPDocs SettingsPiwik.php

### PR DESCRIPTION
**Pull request by tolbon**

### CODE REVIEW

**Comment by tsteur** [comment]
Thanks @tolbon Is there any particular reason for adding the typings and things we should look out for?

**Comment by tsteur** [comment]
@tolbon be great if you could have a look at previous comment

**Comment by tolbon** [comment]
Hi sorry for delay, I needed offscreen.
No no really, you target PHP 7.2. Php7.2 have typings...
It’s just a no critical class like Date. I think slowly move code with typing is a good things when you have big project like this. I can understand too.
Sometimes typing make appears some « bug » where PHPDoc say nothing. Like php docs say getSalt return a string but finally getSalt in test can return null (wrong test or wrong phpDocs ?).
I am totally open for suggestions/args 👍 I don’t have your vision or roadmap, Maybe you don’t target this (typing)

**Review by tsteur — CHANGES_REQUESTED** [review]
Left 1 comment. I think otherwise the definitions look good.

**Comment by tsteur** [comment]
Cheers @tolbon

**Pull request merged**
