### PR TITLE
Added LogViewer as submodule + format a multi line log message into multiple log messages for file handler

### LINKED ISSUE #7239: Improved diagnostics: LogViewer plugin
A plugin that allows users to view log entries from within the UI would be very helpful in quickly diagnosing some errors.

The plugin should handle both file + DB logs and allow searching through logs.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #7239  

Re formatting see https://github.com/piwik/piwik/issues/7239#issuecomment-139045034

It's not a good idea to log multi-line messages instead we log one message for each line.

### CODE REVIEW

**Comment by tsteur** [comment]
FYI: Will try to fix tests tmrw. Not sure why they fail but work in the LogViewer plugin itself

**Comment by diosmosis** [comment]
Since this will close the issue, I will try to fix the build.

**Comment by diosmosis** [comment]
The following changes will make LogTest.php pass:

```
diff --git a/plugins/Monolog/Formatter/LineMessageFormatter.php b/plugins/Monolog/Formatter/LineMessageFormatter.php
index 8224ff7..c9bff1e 100644
--- a/plugins/Monolog/Formatter/LineMessageFormatter.php
+++ b/plugins/Monolog/Formatter/LineMessageFormatter.php
@@ -40,7 +40,7 @@ class LineMessageFormatter implements FormatterInterface
         $class = isset($record['extra']['class']) ? $record['extra']['class'] : '';
         $date = $record['datetime']->format('Y-m-d H:i:s');
 
-        $message = $record['message'];
+        $message = trim($record['message']);
 
         if ($this->allowInlineLineBreaks) {
             $message  = str_replace("\n", "\n  ", $message); // intend lines
diff --git a/plugins/Monolog/tests/Integration/LogTest.php b/plugins/Monolog/tests/Integration/LogTest.php
index 97dc5e8..8de0250 100644
--- a/plugins/Monolog/tests/Integration/LogTest.php
+++ b/plugins/Monolog/tests/Integration/LogTest.php
@@ -201,6 +201,8 @@ class LogTest extends IntegrationTestCase
             $fileContents = file_get_contents(self::getLogFileLocation());
             $fileContents = $this->removePathsFromBacktrace($fileContents);
 
+            $expectedMessage = str_replace("\n ", "\n[Monolog]",$expectedMessage);
+
             $this->assertEquals($expectedMessage . "\n", $fileContents);
         } else if ($backend == 'database') {
             $queryLog = Db::isQueryLogEnabled();
```

& remove `plugins/LogViewer/config/test.php`.

The LogViewer tests seem to run against the 3.0 branch, so didn't go into those.

**Comment by tsteur** [comment]
> The LogViewer tests seem to run against the 3.0 branch, so didn't go into those.

That's not intended. Think I will remove the .travis.yml from LogViewer plugin once it is merged as a submodule as the tests should run with core already anyway. Does that make sense?

**Comment by diosmosis** [comment]
I wasn't referring to travis. I tried to fix the LogViewer tests and noticed the API output for the system tests includes errors for the 3.0 branch. Did you run the tests initially against 3.0? I wasn't sure, so I didn't look further.

**Comment by tsteur** [comment]
I get what you mean, yes that's expected. I created a sample log file that I configured to be used in tests via DI. The log file is simply a few lines extracted of my own log file. Will have a look at the tests

**Comment by tsteur** [comment]
Tests are fixed

**Comment by mattab** [comment]
Wanted to merge this PR but noticed the `AllTests` build on MysqlI fails for some reason:

```
There were 2 errors:
1) Piwik\Plugins\LogViewer\tests\Integration\LogReaderFactoryTest::test_make_shouldMakeRequested_LogReader
Exception: Specified path to log file does not exist: /home/travis/build/piwik/piwik/tmp/logs/piwik.log
/home/travis/build/piwik/piwik/plugins/LogViewer/Log/Reader/File.php:27
/home/travis/build/piwik/piwik/plugins/LogViewer/LogReaderFactory.php:31
/home/travis/build/piwik/piwik/plugins/LogViewer/tests/Integration/LogReaderFactoryTest.php:73
2) Piwik\Plugins\LogViewer\tests\Integration\LogReaderFactoryTest::test_make_shouldBeAbleToDetectSourceAutomatically_IfOnlyOneReaderConfiguredAndNoneSpecified
Exception: Specified path to log file does not exist: /home/travis/build/piwik/piwik/tmp/logs/piwik.log
/home/travis/build/piwik/piwik/plugins/LogViewer/Log/Reader/File.php:27
/home/travis/build/piwik/piwik/plugins/LogViewer/LogReaderFactory.php:31
/home/travis/build/piwik/piwik/plugins/LogViewer/tests/Integration/LogReaderFactoryTest.php:92
```

**Comment by tsteur** [comment]
Made a change that should fix this one. Will merge as soon as it passes

**Pull request merged**
