### PR TITLE
Update 2.14.0-b1.php

### PR DESCRIPTION
**Pull request by sebastianpiskorski**
Proposed fix for Update 2.14.0-b1.php

### CODE REVIEW

**Comment by tsteur** [comment]
Do I get it right that some people might still have it in `PluginsInstalled`? Weird it didn't work. I'm wondering if we should provide kinda the same update again in `2.15.0-b3` or `2.15.0`? Just to make sure it will be removed from all the places. I mean basically just copy/pasting it

**Comment by sebastianpiskorski** [comment]
Well I don't know if `UserSettings` was in `PluginsInstalled` at any time. I've assumed that if update suggests this, so it might be needed. I just wanted to make sure that plugin won't affect config as it disappears in 2.14.0b-1

**Comment by tsteur** [comment]
> I just wanted to make sure that plugin won't affect config as it disappears in 2.14.0b-1

What do you mean by that? `UserSettings` should disappear from config

**Comment by mattab** [comment]
as per discussion, don't think this is needed

**Pull request closed without merging**
