### PR TITLE
When User ID is used, set the first party cookie UUID to this User ID

### PR DESCRIPTION
**Pull request by jantlwoomy**
Store visitorID related to userID to cookies.
Please see https://github.com/piwik/piwik/pull/6838 to additional info

### CODE REVIEW

**Comment by mattab** [comment]
Thanks @jantlwoomy for the PR, i've made a little fix (added `.length`) but looks correct now. Do you mind testing 2.11.0-b5 which includes the fix in the minified piwik.js and confirm it works OK for you?


Also  @asafyish  maybe you could help us test the beta 5 and confirm it works?

**Comment by asafyish** [comment]
I will try to verify it today.

**Comment by asafyish** [comment]
It doesn't seem to work correctly.
This is what I did:
1. Visit page A and run setUserId with id 'asafyish'.
2. Visit page B and run setUserId with id 'asafyish'.
3. Refresh page B without running setUserId.
After steps 1 & 2 the situation was good, I had one unique visit.
After step 3, I had 2 visits, even though I already called setUserId in steps 1 & 2.
I expected that after step 3 I will still have just one unique visit.
If I am using https://github.com/piwik/piwik/pull/6838 then it works correctly.

Using piwik.js from 2.11.0-b7;

**Comment by mattab** [comment]
@asafyish I tested this and for me it works correctly, I see only one visit even after removing the call to set `setUserId` - if you still have issue with the latest beta, please attach the files to reproduce and i'll take a look!

**Pull request merged**
