### PR TITLE
[Vue] add test to make sure umd module files are production builds

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

To catch when someone pushes a development build of a UMD module (as I did in the alert PR).

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis would it make sense to also have a test that checks that the built vue files are up to date? Wondering if it otherwise could happen that someone changes a vue component but forgets to update or push the umd files. 🤔

**Comment by diosmosis** [comment]
@sgiehl That sounds like a good idea... I guess it could be done by checking if the diff w/ 4.x-dev has changes to `vue/src` files, and making sure there are also changes to `vue/dist`. But that wouldn't be foolproof since a dev could forget to compile after making an additional source code change.

Alternatively we could modify the travis-scripts to run the build command (after doing an npm install) and checking that nothing was modified. What do you think?

**Comment by sgiehl** [comment]
Not sure if adding that to travis is a good option. Personally I would prefer moving such stuff to a github action. Similar to the PHPCS the action could simply run building the vue js files and check if there would be any changes available. That way we could even enforce the check and a PR couldn't be merged anymore if the files aren't up to date.

**Comment by diosmosis** [comment]
@sgiehl ok, i'll look into using a github action.

**Comment by tsteur** [comment]
@diosmosis can we merge this already or do we need to wait for the github action?

**Comment by diosmosis** [comment]
@tsteur the github action will prevent more issues so I'll still look into that.

**Comment by diosmosis** [comment]
Closing in favor of https://github.com/matomo-org/matomo/pull/18080 which will rebuild vue files automatically.

**Pull request closed without merging**
