### PR TITLE
fixes single quote bug in rowevolution

### LINKED ISSUE #8393: apostrophe/single quote bug when showing 'row evolution' in 'page titles' section
Since my upgrade to v1.14.1, i cannot see the 'row evolution' when the page title have an apostrophe. The graph is shown but without any data and the page title is truncated. For example, "Qui fait quoi? - L'Aller-Retour" have an apostrophe and piwik only see "Qui fait quoi? - L". It's probably the reason why the graph is empty.

### PR DESCRIPTION
**Pull request by sgiehl**
unsanitize label for row evolution (fixes #8393)

the displayed label in row evolution is given as get param. Maybe due to changes in the history service it might be escaped now, so we need to unsanitize before using it.

### CODE REVIEW

**Comment by mattab** [comment]
Feedback:
 * Let's add a UI test to catch this regression in the future
(Row evolution for a label with `&` is a key functionnality of Piwik since most URLs will have ampersand :+1: )

**Comment by sgiehl** [comment]
I've added `'` and `"` to a fixture, so it will get used in the rowevolution ui test.
Unfortunately I was not able to easily update the OmniFixture. I used the command mentioned on https://github.com/piwik/piwik/tree/master/tests#keep-omnifixture-up-to-date
```
./console tests:setup-fixture OmniFixture --sqldump=OmniFixture-dump.sql
```

but it throws a fatal error. Tried to fix it, but that ended with some other exceptions...

@mattab @diosmosis would you mind checking why the command doesn't work anymore? It seems the Fixture classes are not loaded correctly...

**Comment by mattab** [comment]
@sgiehl there was already `&` in the UI test, does it mean this bug should have been caught (and was caught) by UI tests? did we maybe miss it when the screenshot changed?

**Comment by sgiehl** [comment]
No, the problem occurred with `'`. `&` was already covered.

**Comment by diosmosis** [comment]
This fixes the OmniFixture issues for me: https://github.com/piwik/piwik/pull/9262

**Comment by sgiehl** [comment]
Oh. Updating the OmniFixture makes a lot of UI tests fail... It's hard to check which ones are expected.

**Comment by mattab** [comment]
@sgiehl could you maybe update omnifixture in a separate PR and we can more easily check if changes are expected? I can help if needed

**Comment by sgiehl** [comment]
I'll do that tomorrow.

**Comment by sgiehl** [comment]
Reverted the Omnifixture update. Will create a separate PR for that soon. Guess this one can be merged then?

**Comment by mattab** [comment]
@sgiehl there is still changes to omnifixture in the PR, is it expected?

**Comment by sgiehl** [comment]
No. Need to remove that too...

**Comment by sgiehl** [comment]
Now it should be fine.

**Comment by mattab** [comment]
Works :+1:

**Pull request merged**
