### PR TITLE
allow multiple calls to enableLinkTracking

### PR DESCRIPTION
**Pull request by Findus23**
I am not sure if I understand the issue correctly, but I think it should be possible to call `enableLinkTracking` multiple times.

reported in https://forum.matomo.org/t/enablelinktracking-re-scan-dom-after-content-changes/40269

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
LGTM, would be good to have a test for it in tests/javascript/index.php

**Comment by tsteur** [comment]
build js

**Comment by tsteur** [comment]
👍 indeed it can be called multiple times

**Comment by Findus23** [comment]
It would be great if someone else could create the test as I don't have a great overview over tests/javascript/index.php and not enough time to more closely look into it.

**Comment by tsteur** [comment]
@Findus23 I reckon it's fine it wouldn't need a test and be quite hard to test actually

**Pull request merged**
