### PR TITLE
French translations update

### LINKED ISSUE #14607: French translation typo
On the fresh Matomo update the first feedback opening has some typo ([fr.json](https://github.com/matomo-org/matomo/blob/e8a67a8e1612d025acfcc9deb563bcb803e3ef69/plugins/Feedback/lang/fr.json#L33)).
After a quick search there is other typo in translations files

image

In [fr.sjon](https://github.com/matomo-org/matomo/blob/master/plugins/Feedback/lang/fr.json):
>**ReviewMatomoTitle**
> Vous coryez en Matomo?
> Vous croyez en Matomo ?

>**TopLinkTooltip**
>Dites nous ce que vous en pensez [...]
>Dites-nous ce que vous en pensez [...]

>**RateFeatureLeaveMessageDislike**
>[...] N'hésitez pas à nous dire comme nous pouvons améliorer.
>[...] N'hésitez pas à nous dire comment nous pouvons l'améliorer.

And many others punctuation or typing mistakes.
I'll try to check some files to fix some one.

### PR DESCRIPTION
**Pull request by JackNUMBER**
Fix #14607

Fix many punctuation or typing mistakes in french translation files.

Rules : 
- a space before and after these mark `:` `!` `?`
I use this regex `((?=\S)[^\"|http|https])([?!:])`
- accent on capital letters `Étape` `Êtes`
- a dash in many time for second-person `Assurez-vous` `Êtes-vous`

I hope this kind a of edit can help.

### CODE REVIEW

**Comment by Findus23** [comment]
Thanks for your PR. Unfortunately we can't merge PRs for translation files. Our translations are managed using transifex. Please get an account there in order to help us to improve the translations.

https://www.transifex.com/matomo/matomo/

**Comment by JackNUMBER** [comment]
@Findus23 I will not reproduce all these update in GUI, I use sed and grep to do it. It take some time for nothing, meh.

**Comment by bperel** [comment]
@JackNUMBER In Transifex, you can download the translation file, then do your changes using grep and sed, then upload the file containing your fixes :
image

**Comment by sgiehl** [comment]
@JackNUMBER would be awesome if you could do that on transifex as described by @bperel 
I don't want to uploaded your changed files from the PR, as they might be outdated compared to those on transifex.

**Comment by JackNUMBER** [comment]
@sgiehl @bperel Ok, let's try the JSON export, I'll try to do it faster this time and avoid to do it by hand as possible. I asked to join the translation team on Transiflex. No guarantee.

**Comment by JackNUMBER** [comment]
@sgiehl @bperel Done on Transifex.
The download of the **73 ressources** was easy with a crawl but the upload was a pain and time consuming. There is a transifex CLI but it definitely doesn't work has expected. 😭

**Comment by sgiehl** [comment]
@JackNUMBER  thanks, I will sync the update to github the coming days...

**Pull request closed without merging**
