### PR TITLE
Migrate sitesmanager controller and twig templates to Vue components

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off of #18562.**

Changes:
* Make MatomoUrl.urlQuery/hashQuery public readonly so they can be watched.
* Create ManageGlobalSettings vue component.
* Create SiteManagement vue component.
+ related changes.

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — COMMENTED** [review]
When you go setting->Websites->Manage->Add a new measurable->Roll-up 
some of the options are missing. See screen shot


image

image

**Comment by diosmosis** [comment]
@peterhashair if I understand correctly this should be fixed w/ the latest merge

**Comment by peterhashair** [comment]
@diosmosis just had another look it seems the Roll-up still missing some parts. Do I need to merge another PR before this one?

**Comment by diosmosis** [comment]
@peterhashair it looks the same to me on this branch as it does on 4.x-dev. What is missing for you?

**Comment by peterhashair** [comment]
@diosmosis I think some of the premium plugins append additional fields to the Site Manager. The first video is the current PR. The second is the 4.x-dev

https://user-images.githubusercontent.com/3783072/152099966-80b56ca9-1f9a-42e2-a6d7-bd791ac3acc5.mp4


https://user-images.githubusercontent.com/3783072/152100431-88ce6add-23ca-4375-86ae-913e0f4a0365.mp4

**Comment by diosmosis** [comment]
@peterhashair this is what I see locally on this branch:

**(adding)**
localhost_index php_module=SitesManager action=index idSite=1 period=range date=previous30

**(editing)**
localhost_index php_module=SitesManager action=index idSite=1 period=range date=previous30 (1)

Can you pull, rebuild and clear your cache?

**Comment by peterhashair** [comment]
@diosmosis ah, I did all those, but still no luck. I guess it may be some package missing. Will try more build.

**Comment by sgiehl** [comment]
@diosmosis another issue that might be good to fix in that one:
* It's possible to open the form for adding a measurable multiple times. But clicking a cancel button closes all of them at once. Imho we should simply close the previous form before opening a new one

**Comment by diosmosis** [comment]
@sgiehl it seems like the existing code was meant to hide the top button bar while a site is being edited/added, but it doesn't really work. I made it work and changed it to disable the bar while a site is being edited/added since it looked odd to simply remove it.

Allowing multiple add modals seemed more complicated.

**Comment by sgiehl** [comment]
@diosmosis hiding the button to add another one sounds fine as well 👍

**Review by sgiehl — APPROVED** [review]
Had another quick look through the code and the UI. Seems to work as expected.

**Pull request merged**
