### PR TITLE
Added possibility to create tracker automatically via paq after piwik…

### PR DESCRIPTION
**Pull request by tsteur**
refs https://github.com/piwik/piwik/issues/10878

To test use eg 
```html
<html>
<head></head>
<body>
<script type="text/javascript" src="//apache.piwik/piwik.js"></script>
</body>
</html>
```

Then initialize tracker after document was loaded via `_paq.push`. You will see tracker will be created etc. Also if someone else uses `Piwik.addTracker` the `_paq` will be correctly restored to use the trackerproxy. Automated test is not possible for this.

Will issue a PR for Piwik 3 where we log a message and not create the tracker

### CODE REVIEW

**Comment by mattab** [comment]
New features in Piwik 3 only

**Comment by tsteur** [comment]
FYI: This was a bug fix as it wasn't creating trackers anymore under circumstances. But totally fine to not merge

**Comment by dimitrispie** [comment]
We are using the following script to track events on Matomo 3.0.4


<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//trackerurl/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', xyz]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p></p></noscript>


We receive errors as follows in the browser’s console, although the activity is recorded properly. 

**“_paq.push() was used but Piwik tracker was not initialized before the piwik.js file was loaded.”**

**Comment by tsteur** [comment]
By any chance, is the tracking code also added maybe somewhere else? Not quite sure why this message would appear.

**Pull request closed without merging**
