### PR TITLE
Improving SR readabilty of users' menuitem in topBar

### PR DESCRIPTION
**Pull request by tassoman**
Refs #9148

### CODE REVIEW

**Comment by tsteur** [comment]
I'm not sure about this one. Clicking on the items someone actually lands on these pages so the tooltips you defined are correct, but from there one can also go to other "pages" within the "Personal section/area". Maybe we could name it somehow differently? I agree that `$login` as tooltip is not ideal and not very clear and should be changed. Maybe something like "Your profile"

**Comment by tassoman** [comment]
Screen readers are reading "anonymous" or "user's chosen alias", that's not really clear. So I've just tried to adhere to controller's methods in each case.

In first instance I've decided for "```UserManager_PersonalProfile```: ```$login```" but doesn't fit because anonymous session doesn't have any profile page. Only Email report settings or APIs if that module is disabled.

I didn't care of hypothetical 3rd parties plugins injecting menutems for the anonymous session, because they should implement own menuitem by extending the ```configureTopMenu()``` interface.

You see, the strings I've chosen are the title of the controller's page.

**Comment by tsteur** [comment]
Totally agree that `anonymous` is not good. @mattab do you have any preference after todays session re accessibility?

**Comment by tsteur** [comment]
I'll merge it now as it is definitely better than before. Thx for that :)

**Comment by tassoman** [comment]
Thank you @tsteur, :smile: glad to be helpful

**Comment by tassoman** [comment]
Grazie @tsteur , glad to be helpful :smile:

**Pull request merged**
