### PR TITLE
Fix for incorrect multisite dashboard Urls behind reverse proxy

### LINKED ISSUE #17945: MultiSites reverse proxy on subdir/path is broken
I'm trying to run Matomo behing a reverse proxy. I followed the https://matomo.org/faq/how-to-install/faq_98/ , but there are still some issues left. For example, the MultiSites plugin/All websites page links are broken.

## Expected Behavior

I expect the links to the websites to work. They don't. When I pick the website from the dropdown in the CoreHome, it work flawlessly.

## Current Behavior

**Incorrect** in MultiSites:

image

**Correct** in CoreHome:

image

## Possible Solution
Fix the urls in the MultiSites, so that they are either relative, or correctly absolute.

## Steps to Reproduce (for Bugs)
1. Run matomo behind a reverse proxy with a path different that just /
2. Go to 'All Websites' (top tight)
3. Click the name of a site
4. No correct link.

## Your Environment

* Matomo Version: 4.4.1
* Bitnami Docker image

nginx reverse proxy conf:

```
    location /matomo/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream http://matomo:8100;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Referer $http_referer;
        proxy_buffering off;

        proxy_pass $upstream;

        rewrite ^/matomo/(.*)$ /$1 break;
    }
```

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #17945 

When Matomo is running behind a reverse proxy server that forwards traffic to a directory path (eg. `proxy.com/matomo/`) but Matomo itself is installed in a different path (eg. `someotherhost.com/` or `someotherhost.com/differentpath`) then incorrect paths are used for links in the Multi Sites page, specifically: site selection, the evolution sparklines and add a new website.

This PR is a simple fix to remove the calculated piwik_url from these links and use relative paths instead.

Tested with three docker images: mariadb:latest, matomo:4.5.0 official docker and nginx:latest

nginx configured with
```
location /matomo/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Uri /matomo/;
        proxy_pass http://<matomo container ip>/;
        proxy_read_timeout 90;
    }
```
Matomo config.ini.php
```
[General]
assume_secure_protocol = 0
proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
trusted_hosts[] = "<nginx container ip>"
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
I'm not sure if removing the `piwik_url` from those urls is a good solution. Even though it might work, it would mean we need to adjust all twig templates that use the `{{ piwikUrl }}` variable for generating a url, as those urls would be incorrect as well. That means that likely the optout and other stuff might also not work.

@bx80 did you try if setting the config variable `[General] proxy_uri_header = 1` solves the issue?

**Comment by bx80** [comment]
@sgiehl I'd missed the `proxy_uri_header` option, yes that fixes the issue. This PR is therefore unnecessary. :man_facepalming:

**Comment by tsteur** [comment]
A lot of other links, even in twig templates, simply point to index.php. For example:

image


I think it be still an easy merge as it fixes it without having to configure something and AFAIK there's no downside to it? It doesn't mean we need to change all others now but the fix is there and it improves it quite a bit I would say.

**Comment by bx80** [comment]
Ok, I can merge these fixes and also mention the config setting in the original issue so there is an immediate solution for those affected.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
