### PR TITLE
Enable language Gujarati

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

The language Gujarati should meanwhile be translated good enough to enable it by default in the UI.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Just curious to understand better — is there a Github issue related to this, did someone request the addition or what is the process around deciding when a language is translated well enough to be included?

**Comment by sgiehl** [comment]
There is no official process around that. I had seen a lot of additions for that language in the last translation update PRs and checked the overall translation rate on weblate, which is already at around 30%. There are a lot languages already available with a lower rate, so there is imho no reason to not enable it.

**Review by michalkleiner — CHANGES_REQUESTED** [review]
Not sure what needs to get changed where but the [integration test failures](https://github.com/matomo-org/matomo/actions/runs/7423878735/job/20202285912?pr=21769#step:3:632) seem related.

**Comment by sgiehl** [comment]
A translator name needs to be set on weblate. Should be fixed with the next translation update...

**Review by michalkleiner — APPROVED** [review]
Failures in system tests for core and plugins are unrelated, this is good to go now.

**Pull request merged**
