### PR TITLE
fix ScheduledReports.sendReport API

### PR DESCRIPTION
**Pull request by Findus23**
It seems like no one (apart from @Chardonneaur) used that API in years as it always returns 
```json
{
  "result": "error",
  "message": "The period 'never' is not supported. Try any of the following instead: day, week, month, year, range"
}
```

even if the period is definitely not set to `'never'`. It seems like the wrong variable is used here, as `$report['period_param'] = $period;` is set above.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by sgiehl — APPROVED** [review]

**Comment by sgiehl** [comment]
Wondering why there actually is no test that failed because of that.

**Comment by Findus23** [comment]
I assume everything (apart from the HTTP API which isn't used by anyone) uses 
https://github.com/matomo-org/matomo/blob/fc2e8a5ea1d37a8db37e9e2330ba67faacdc71a2/plugins/ScheduledReports/ScheduledReports.php#L318
directly

**Comment by tsteur** [comment]
We're using this API in our app itself eg in the tasks to send every report etc. Also when clicking in the UI on "send report now" so would have assumed this worked before? Just wanting to make sure we won't regress anything

**Comment by diosmosis** [comment]
@tsteur the task only supplies the report ID, not an override period. I'm writing a quick test for it now.

**Comment by diosmosis** [comment]
Actually just seeing the angular controller uses the API directly w/ the period param...

**Comment by diosmosis** [comment]
I see, it happens if the report's email schedule is set to a value that doesn't map to a matomo period type. (We use the correct value when generating the report, but pass the wrong value to the sendReport event; but I don't think it's used much there.)

**Pull request merged**
