### PR TITLE
Website chooser may not work because of a whitespace problem

### PR DESCRIPTION
**Pull request by tsteur**
See https://twitter.com/Ravetracer/status/695236381556260864

### CODE REVIEW

**Comment by sgiehl** [comment]
Looks good.

**Comment by mattab** [comment]
@tsteur @sgiehl Maybe we can add a ReleaseChecklistTest integration test that looks for these "problematic" spaces in all JS files (and more as appropriate), so we can detect before the release, preventing this issue occuring again?

**Comment by SebaldJ** [comment]
Hello,
i have a smiliar Bug with the Version 2.16.0:
On the Dashboard, the Website chooser shows this html code:
`{{'CoreHome_ChangeCurrentWebsite' |translate: ((selectedSite.name ||))}} {{(Â model.firstSiteName) |htmldecode)}}`

More on the Piwik Forum:
http://forum.piwik.org/t/bug-after-update-to-piwik-2-16-0-dashboard-select-websites/17920/2

But, even after adding patch of space or the the whole line, has nothing changed, the error is still present.

Is there a workaround or bug fix?
I am grateful of any help.

Greets John

**Comment by tsteur** [comment]
You might need to clear the browser cache afterwards

**Comment by SebaldJ** [comment]
Hello tsteur,
the problem is unfortunately still present even after emptying the browser cache in Chrome.

**Comment by tsteur** [comment]
@mattab that should be possible. Maybe need to limit to html, twig and .php and js files without our files. Eg there are actually expected test files etc with this character (meaning our test DB may contain this whitespace)

**Comment by tsteur** [comment]
@SebaldJ please try to apply this patch as well https://github.com/piwik/piwik/pull/9729/files

**Comment by mattab** [comment]
New integration test to catch this problem pro-actively in the future  #9730

**Comment by SebaldJ** [comment]
@tsteur The Patch from https://github.com/piwik/piwik/pull/9729/files works fine!
I have changed the following files:
```
plugins/CoreHome/angularjs/siteselector/siteselector.directive.html (line 19 and 40)
plugins/ScheduledReports/API.php (line 736)
```

The bug is gone. Thank your for your help

**Comment by BSG2000** [comment]
@tsteur I was also successful - same patch as @SebaldJ . 
Thank you for support!

**Pull request merged**
