### PR TITLE
Merge user and admin menu to one single menu

### LINKED ISSUE #9354: New menu structure for Personal => Manage menu items
Currently, Goals, Tracking Code, Custom Variables (and if installed Custom Dimensions) can be configured in "Personal" section which is accessible by clicking on the "User icon" in the top right.

When writing eg a guide re how to configure Custom Dimensions it always feels wrong to write "Go to your personal section/area" to configure them. They are not really personal, they are rather website related. 

Idea would be to move them into the Administration section under a main category "Configure". As Custom Variables cannot be configured we would move them under "Diagnostic". 

image

Another idea could be maybe to have a dedicated "manage websites" area accessible via an icon in the top right menu. There one could manage all the websites (create new websites, edit urls etc, there would be a new menu item for the global website settings as well) showing the following links:
* Manage Websites
* Global Website Settings
* Goals
* Custom Variables
* Custom Dimensions
* Tracking code

This would also make the Manage websites screen easier as it currently combines two very different things (manage websites and global website settings). Problem: It might be a bit confusing with the "All Websites" link in the top menu as both links would be website related.

Any other ideas?

### PR DESCRIPTION
**Pull request by tsteur**
refs #9354

### CODE REVIEW

**Comment by tsteur** [comment]
This will be only a first version of the new menu structure. We will tweak it over time (eg in another branch there will be already 2 links "Plugin Settings" removed)

**Comment by tsteur** [comment]
See screenshots http://builds-artifacts.piwik.org/piwik/piwik/9354/18540/

The list for super user is currently very long and we will tweak this over time. Eg as mentioned in another pull request 2 plugin settings link will be already gone. I suggest we merge this, use it for a while and make further adjustments over time in the next weeks. 

For anonymous user and users with view users the menu is still very short. For admin menu it is also not too long. For super users is quite long but it'll become shorter. When testing locally make sure to disable development mode as these menu items are usually not shown.

**Comment by tsteur** [comment]
@mattab is it ok to merge for now and to make further changes over time? I'd kind of like to make the 3.x branch green soon and in order for this I need to merge this branch + the settings branch. It's otherwise hard to make it green re the plugin submodules and keeping them compatible

**Comment by mattab** [comment]
LGTM

**Pull request merged**
