### PR TITLE
Disable datatable PostProcessor for PrivacyManager.findDataSubjects API method

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

While testing the vue migration of the GDPR tools, my log was spammed with a lot warnings like
```
WARNING API[2022-04-05 16:36:18 UTC] [aae03] /srv/matomo/core/DataTable/Row.php(808): Trying to add two strings in DataTable\Row::sumRowArray
```

I'm pretty sure we already had a couple of issues on that one. Digging deeper into the code showed that a call to `PrivacyManager.findDataSubjects` applies the Datatable PostProcessor to the result. This also tries to generate a totals row by default, resulting in the warnings, as almost all columns are strings. 

I'm not sure if that is the most elegant solution, but disabling the PostProcessor for the API method fixes the issue. As `PrivacyManager.findDataSubjects` internally only calls `Live.getLastVisitsDetails`, which already applies the PostProcessor, it shouldn't be needed anyway.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by tsteur — CHANGES_REQUESTED** [review]
@sgiehl not sure if I'm looking right but couldn't find any test for this API. To make sure we're not regressing anything can we add a test for this API?

**Comment by sgiehl** [comment]
@tsteur I have added two tests for that method

**Review by tsteur — COMMENTED** [review]
Looks generally good. Could have been good to have a test where at least one visitor also has device / software information but not too important maybe. 

I tested it in the UI and it shows `null`. Not sure if that's a regression or always been there?
image

Well possible this was there before and I assume it's trying to show a city or region or something which I might not have in my DB

**Comment by sgiehl** [comment]
> I tested it in the UI and it shows null. Not sure if that's a regression or always been there?

That seems to have been a regression from 4.7.0 where it was migrated to vue. Just pushed a fix.

**Comment by tsteur** [comment]
👍  lgtm if tests pass

**Comment by sgiehl** [comment]
Test failures are unrelated to the changes here.

**Pull request merged**
