### PR TITLE
Hide widgets not working without internet connection if disabled in config

### PR DESCRIPTION
**Pull request by sgiehl**
Hide widgets when `enable_internet_features = 0` is set in config:
* SEO > SEO rankings
* About Piwik > Piwik Changelog
* About Piwik > Piwik.org Blog
* About Piwik > Latest Marketplace Updates
* About Piwik > Premium Features

refs #6324

### CODE REVIEW

**Comment by mattab** [comment]
We'd also need to hide the
* Premium features widget
* Latest Marketplace Updates widget

+ let's also test most screens in Admin, without internet, to check the feature really works, there are maybe a few remaining things to disable

**Comment by sgiehl** [comment]
@mattab  The two mentioned widgets are now removed as well. Everything else shouldn't be handled in this PR. It's only one step towards solving #6324. It's better to keep pull requests simple and small, so they can be easily merged. So maybe add your other comment in that issue.

**Comment by diosmosis** [comment]
Would it be possible to use `const`s for the widget categories/names? If the names change, these new changes might break.

**Comment by sgiehl** [comment]
I've updated the PR so it better handles possible name changes of the widgets

**Comment by diosmosis** [comment]
@mattab PR looks good, the UI test failures seem unrelated.

**Pull request merged**
