### PR TITLE
Hide date selector when viewing live visits (not as widget)

### LINKED ISSUE #14517: In Visitors > Real-time report, hide the calendar
In Visitors > Real-time report, the report is real-time and it's not possible to change the date, so let's hide the calendar. This will be consistent with how it works on Visitors>Real-time map report.

Screenshot from 2019-06-10 15-53-29

Screenshot from 2019-06-10 15-53-22

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #14517

### CODE REVIEW

**Comment by diosmosis** [comment]
Works for me. Only thing that worries me is if some error occurs and `_destroy()` isn't called. This would result in the period selector being hidden, which could be an annoying bug to track down.

**Comment by sgiehl** [comment]
@diosmosis would it be better like it's done in the real time map:
https://github.com/matomo-org/matomo/blob/8f77ece35b3058251c4450b6d15f3d73df8bd825/plugins/UserCountryMap/javascripts/realtime-map.js#L63-L71

**Comment by diosmosis** [comment]
Huh, I would expect that might cause problems w/ this change actually, since I think the event is never removed from `$rootScope`?

**Comment by sgiehl** [comment]
I actually didn't have problems with that while testing. Guess the `piwikPageChange` event is triggered before the widgets are created or destroyed. 
I'll try to implement something else, that simplifies both implementations....

**Comment by sgiehl** [comment]
@diosmosis tried to improve & simplify the code. Could you have another look?

**Review by diosmosis — APPROVED** [review]
haven't tested, but this looks great

**Pull request merged**
