### PR TITLE
Redesign of the marketplace

### LINKED ISSUE #7586: New design for Marketplace (in Administration)
The goal of this issue is to change the design of how Plugins are listed within the Piwik platform, to be more consistent with the existing [Marketplace design](http://plugins.piwik.org/)

## Current Marketplace design

marketplace

## New proposed Marketplace design

marketplace-new

Notes:
 * in design the Developer is not displayed in the listing of plugins. it's important information and we should still list the developer name.
 * the title, description, sort links and search bar should still be displayed at the top somehow

(I'll ask designers if possible to get updated mockup)

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7586

Redesigned the marketplace according to Rafa's mockups (see in #7586).

Additionally I cleaned up a lot of CSS rules and HTML, add some components (Bootstrap [panels](http://getbootstrap.com/components/#panels) and [navs](http://getbootstrap.com/components/#nav-pills), those are not documented so they are not API) plus merged the "browsePlugins" and "browseThemes" views into one because they were the same.
### Screenshots

Below are some screenshots but I think it's better to check out the branch and play with it if you want to get a real idea of the whole thing.

capture d ecran 2015-05-13 a 11 15 56

Plugins with a new version (clicking opens the popup):

capture d ecran 2015-05-13 a 11 16 08

### CODE REVIEW

**Comment by mattab** [comment]
@mnapoli  one file is missing in the branch, getting `The ui asset with 'href' = /home/matt/dev/piwik-master/libs/bower_components/jQuery.dotdotdot/src/js/jquery.dotdotdot.min.js is not readable`

**Comment by mnapoli** [comment]
ah right, @tsteur the bower dependencies should be committed? (I didn't think twice about that I was expecting a workflow a la composer)

**Comment by tsteur** [comment]
Yes, needs to be committed. I think this was to prevent that users have to install node.js / npm.... There is a php version for bower but it doesn't work properly.

**Comment by mnapoli** [comment]
OK thanks will do

**Comment by mnapoli** [comment]
I've committed the jquery plugin.

**Comment by mattab** [comment]
Code looks good! merging.

Note: as discussed within the team, we think the design could be better and less heavy, with hopefully  lines and a more flat design. This will be done in later stage (I need to talk to designers).

**Comment by mnapoli** [comment]
No problem it should be easy to change

**Pull request merged**
