### PR TITLE
Cross Domain linking in JavaScript tracking client piwik.js

### PR DESCRIPTION
**Pull request by tsteur**
To make feature work one has to 
1) Configure `setDomains()` 
2) Enable `enableCrossDomainLinking()`

If link is going to different domain that belongs to same Piwik website, it will add two URL parameters:

`pk_vid=900d0d1eb6714aa41484879482d2bb13`

Where we have 1) visitorId (16 char)  2) the current timestamp (10 char) and 3) a hashed combination of userAgent / platform to make sure when a user shares it, the visitorId won't be applied to another user. Timestamp is only valid for 45 seconds, and only works on same browser / platform when same browser features are enabled.

So far it works for clicks and right click open in new window (if this tracking feature is enabled).

It is important to enable "enableCrossDomainLinking" on the target page (different domain) as well.

Backend part is still missing and needs to be implement later. 

@mattab can you have a look when you have time?

### CODE REVIEW

**Comment by tsteur** [comment]
Actually I will be changing it to use only one parameter with then 32 characters and also add more validation so cookies cannot be injected

**Comment by tsteur** [comment]
done

**Comment by mattab** [comment]
Beautifully done, I'm impressed :tada:

**Comment by cemdev** [comment]
This is AMAZING. Such a useful feature.

**Pull request merged**
