### PR TITLE
Include non-sql migrations in update dry run output.

### LINKED ISSUE #13992: Number of database upgrades off
```
  Executing ALTER TABLE `matomo_user` ADD COLUMN `twofactor_secret` VARCHAR(40) NOT NULL DEFAULT '';... Done. [1 / 5]
  Executing CREATE TABLE `matomo_twofactor_recovery_code` (`idrecoverycode` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `login` VARCHAR(100) NOT NULL, `recovery_code` VARCHAR(40) NOT NULL, PRIMARY KEY ( `idrecoverycode` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;... Done. [2 / 5]
  Executing Activating plugin "TwoFactorAuth"... Done. [3 / 5]
  Executing Deactivating plugin "GoogleAuthenticator"... Done. [4 / 5]
  Executing CREATE TABLE `matomo_tracking_failure` (`idsite` BIGINT(20) UNSIGNED NOT NULL, `idfailure` SMALLINT UNSIGNED NOT NULL, `date_first_occurred` DATETIME NOT NULL, `request_url` MEDIUMTEXT NOT NULL, PRIMARY KEY ( `idsite`, `idfailure` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;... Done. [5 / 5]
  Executing CREATE TABLE `matomo_brute_force_log` (`id_brute_force_log` bigint(11) NOT NULL AUTO_INCREMENT, `ip_address` VARCHAR(60) DEFAULT NULL, `attempted_at` datetime NOT NULL, PRIMARY KEY ( `id_brute_force_log` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;... Done. [6 / 5]
  Executing ALTER TABLE `matomo_brute_force_log` ADD INDEX index_ip_address (`ip_address`);... Done. [7 / 5]
```

### PR DESCRIPTION
**Pull request by diosmosis**
Fixes #13992 (edit by @Findus23)

### CODE REVIEW

**Comment by fdellwing** [comment]
Fixes #13992

**Comment by tsteur** [comment]
We could maybe move this one to 3.9? It be nice to have all SQL updates grouped, and all other commands in a separate box. So it is easier to copy/paste etc. Also in the list of commands we could then add a `core:update`? may not be needed though I suppose

**Comment by diosmosis** [comment]
> It be nice to have all SQL updates grouped, and all other commands in a separate box. So it is easier to copy/paste etc.

Wouldn't this potentially cause problems related to order? Ie, one update activates plugin OurNewPlugin, next update assumes it's there and applies SQL on a table it assumes exists. If run separately, the SQL may not succeed.

**Comment by diosmosis** [comment]
Moving to 3.9.0.

**Comment by diosmosis** [comment]
Here's what it looks like w/ multiple boxes:

image

**Comment by tsteur** [comment]
Looks awesome!

**Pull request merged**
