### PR TITLE
World Map update (Lesotho, Palestine)

### PR DESCRIPTION
**Pull request by polyfloyd**
This update fixes the appearance of some countries in the UserCountryMap plugin.

The ISO3 codes for Gaza, West Bank and South Sudan have been updated so the number of visits are correctly displayed.
Additionally, Gaza and the West Bank have been merged into a single Palestine.

The enclaved country of Lesotho is still covered by South Africa, but will now be visible when visits have been recorded.

### CODE REVIEW

**Comment by sgiehl** [comment]
Did you fix/update the SVGs manually? We used to had a script for that, but it doesn't work anymore...

**Comment by polyfloyd** [comment]
Yes, I updated them manually.

Also, where can I find this script? Maybe I'm able to figure out why it doesn't work.

**Comment by sgiehl** [comment]
It's an old python script (https://github.com/piwik/piwik-map-generator). The used map data has changed. Tried to get it working with the new ones, but my knowledge about python, shapefiles and geodata is limited.

**Comment by polyfloyd** [comment]
The map generator seems to have been neglected for some time. The effort required for updating it will definitely exceed the cost of just manually fixing the small issues which currently exist in the map.

**Comment by sgiehl** [comment]
@polyfloyd thanks for having a look into it. I'll have a closer look at
your PR so we can merge it afterwards.

Btw. are you familiar with svg maps, shape files and stuff like that? Maybe
you would be keen to build a new tool with us to generate svg maps for
Piwik. If so please get in touch with us by mail hello@piwik.org
Would be awesome to have a new maintained tool for that!

**Comment by tsteur** [comment]
FYI: we would need to have this PR against the "3.x-dev" branch instead of "master" as we only merge critical bugfixes and security fixes into "master" as Piwik 2 is in LTS mode. I will close this but would be highly appreciated if you could issue the PR again. @sgiehl have you had a look at the maps already?

**Comment by polyfloyd** [comment]
So uh, does changing the base of this PR work or do you prefer me opening a new PR?

**Comment by sgiehl** [comment]
@polyfloyd Switching the base should be enough. 
@tsteur hadn't have enough time to have a closer look. Need to generate some fake visits for the countries that were changed, in order to check if everything is displayed correct then. Not sure when I will find some time for this, as there are some more important things on my to do...

**Comment by mattab** [comment]
@sgiehl Could you take a quick look at this PR and whether we can merge it in beta1/beta2?

**Comment by sgiehl** [comment]
Had a closer look at the changes. For me the changes look ok. But I'm not sure if the other occurrences of `GAZ` needs to be replaces with `PSE` in all other svgs, as well.

**Comment by polyfloyd** [comment]
IIRC those other GAZ'es are present in images where Gaza is outside of the SVG viewport, e.g. North and South America.

**Comment by sgiehl** [comment]
Ok. but wouldn't it be more consistent to change it everywhere?

**Comment by polyfloyd** [comment]
Good point. Although it seems that the remaining GAZ and WEB's were parts of Palestine that are displayed in the views of neighbouring countries. That's worth fixing.

**Comment by sgiehl** [comment]
ok fine. guess that should be good to merge then

**Pull request merged**
