### PR TITLE
Fix possible fatal error in VisitTime report

### LINKED ISSUE #21677: [Bug] mktime(): Argument #1 ($hour) must be of type int, string given in /mnt/efs/plugins/VisitTime/functions.php line 18
### What happened?

When opening the visitor time report for the current year, it breaks with this error message.

index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?period=year&date=2023-12-13&idSite=1&category=General_Visitors&subcategory=VisitTime_SubmenuTimes

mktime(): Argument #1 ($hour) must be of type int, string given in /mnt/efs/plugins/VisitTime/functions.php line 18

It works fine for day, week and monthly period for December but breaks in November.

I initialized my instance in November, so perhaps this is related.

### What should happen?

The report should work without issues.

### How can this be reproduced?

Go to Matomo -> click on visitors -> click on times and select the first month of your Matomo installation.

### Matomo version

4.16.0

### PHP version

8.1.26

### Server operating system

AWS ECS Docker php:8.1-apache

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Computer operating system

Mac

### Relevant log output

```shell
n/a
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #21677

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Is this covered by some tests somewhere?

**Comment by sgiehl** [comment]
Not as far as I know. But I actually also don't know how that could happen. Maybe report row truncation is set too low and the report has an others row...

**Review by bx80 — APPROVED** [review]
I was going to quickly add a unit test, but `plugins/VisitTime/functions.php` is not a proper class and is being directly included by several column classes in `CoreHome`, so it would be better to refactor these functions into a more appropriate class in `Core` or `CoreHome` and add unit tests there. Which is probably out of scope for this fix.

Maybe it would be good to raise a tech debt ticket to tidy this up at some point?

**Comment by sgiehl** [comment]
We will need to do that anyway. As some rules of PSR12 forbid global functions

**Pull request merged**
