### PR TITLE
Make it possible to limit the number of possible entries for field arrays and multi tuple fields

### LINKED ISSUE #20352: Add ability to limit no of rows in FieldConfig::UI_CONTROL_MULTI_TUPLE
If we use FieldConfig::UI_CONTROL_MULTI_TUPLE to create a setting it creates `n` no of rows and there is no way to limit the rows allowed.

Example: Below UI will keep adding rows and it cannot be restricted via any FieldConfig setting

Screenshot from 2023-02-13 18-20-26

It will be good to have a way to limit the rows or have a min and max no of rows that can be added

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

This will allow to limit the number of possible entries for field arrays and multi tuple fields by simply setting the `row` property

@AltamashShaikh Let me know if that matches your needs. If so I'm happy to merge, so you can use the new feature for plugins for Matomo 5.

fixes #20352 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@sgiehl It works if I test via Morpheus, but not if I am trying to create a `SystemSetting` 
```
$self = $this;
        return $this->makeSetting('rowOptions', $self->defaultRowOptions, FieldConfig::TYPE_ARRAY, function (FieldConfig $field) use ($self) {
            $field->title = 'Campaign Dimensions Combinations';
            $field->uiControl = FieldConfig::UI_CONTROL_MULTI_TUPLE;
            $field->rows = 3;
            $field1 = new FieldConfig\MultiPair('Period', 'period',
                FieldConfig::UI_CONTROL_TEXT);
            $configuration = new Configuration();
            $field1->availableValues = [7=>7,30=>30,60=>60,90=>90];
            $field1->uiControl = FieldConfig::UI_CONTROL_SINGLE_SELECT;

            $field2 = new FieldConfig\MultiPair('Top Level', 'topLevel',
                FieldConfig::UI_CONTROL_TEXT);
            $field2->availableValues = $self->getCampaignOptions();
            $field2->uiControl = FieldConfig::UI_CONTROL_SINGLE_SELECT;

            $field3 = new FieldConfig\MultiPair('Sub Level', 'subLevel',
                FieldConfig::UI_CONTROL_TEXT);
            $field3->availableValues = $self->getCampaignOptions();
            $field3->uiControl = FieldConfig::UI_CONTROL_SINGLE_SELECT;

            $field->uiControlAttributes['field1'] = $field1->toArray();
            $field->uiControlAttributes['field2'] = $field2->toArray();
            $field->uiControlAttributes['field3'] = $field3->toArray();
            $field->description = 'Configure the campaign dimensions combination';
        });
```

**Comment by sgiehl** [comment]
@AltamashShaikh it should work using `$field->uiControlAttributes['rows'] = 3;`

**Review by AltamashShaikh — APPROVED** [review]
@sgiehl This works :D :+1:

**Comment by sgiehl** [comment]
@AltamashShaikh Then feel free to use it in plugins for Matomo 5.

**Pull request merged**
