### PR TITLE
Add informational diagnostic for archive invalidations table.

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Adds a new informational diagnostic to get information about rows in the invalidations table. @tsteur do you see value in this? If so I will add a test.

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
@tsteur does this look useful to you?

**Comment by tsteur** [comment]
Yes that sounds good. Anything that will help us troubleshoot and understand things easier/quick is good 👍  Especially around archiving which is usually the most difficult one

**Review by sgiehl — APPROVED** [review]

**Comment by sgiehl** [comment]
@diosmosis  UI test needs to be updated before merging

**Comment by sgiehl** [comment]
@diosmosis the UI file you've added here is not on LFS

**Pull request merged**
