### PR TITLE
Removed Piwik\Registry and replaced its usage with the container

### PR DESCRIPTION
**Pull request by mnapoli**
Piwik\Registry was very similar to using a container and only contained 2 entries.

I've replaced all that with the container. Basically here is the changelog entry:

> - The `Piwik\Registry` class has been removed in favor of using the container:
>   - `Registry::get('auth')` is replaced by `StaticContainer::get('Piwik\Auth')`
>   - `Registry::set('auth', $auth)` is replaced by `StaticContainer::getContainer()->set('Piwik\Auth', $auth)`

I have not kept BC because I have updated (for now locally) all plugins that used it. I had a look in the marketplace but couldn't find any 3rd party plugin using it (its usage was restricted to authentication).

TODO after merge:
- [ ] update LoginAdmin
- [x] update LoginHttpAuth
- [x] update LoginLdap
- [x] update SSOAuth

### CODE REVIEW

**Comment by tsteur** [comment]
`Registry` is an API. Can we deprecate instead it for at least 2 or 3 months instead of breaking it? The class was there for a long time so there might be quite a few plugins out there who use it for whatever reasons. 

If we'd break it, it would also mean people will most likely have an error at some point. They won't be able to update the plugin to a newer version as it could break Piwik if StaticContainer is not there yet in the users Piwik version. If they update Piwik first it will fail as well as the plugin still uses the Registry. They would have to update both at the same time which we currently don't do unless someone does the update including all plugins manually at once.

Also there seems to be a backslash on the left https://github.com/piwik/piwik/pull/7124/files#diff-f10b4fc6b182e822204d929ace688f74R53

**Comment by mnapoli** [comment]
I restored `Registry` as a bridge to the container to keep BC, I missed the `@api` tag on the class.

The backslash is unrelated to the change (and is in a comment so doesn't affect code) I'll leave it there to keep the diff clean.

**Comment by mnapoli** [comment]
Merged with master.

**Comment by tsteur** [comment]
The changelog entry says the Registry has been removed but it is only deprecated and still there

**Comment by mnapoli** [comment]
Fixed

**Pull request merged**
