### PR TITLE
Display message why no reports are shown if there are no conversions

### LINKED ISSUE #9909: Goals without conversions has no Conversions Overview
I know that this in on purpose, but I think that there should be some information.

Here I have it:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-03-07#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2016-03-07

here I don't:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-03-05#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2016-03-05

For inexperienced user this might look like a bug of some sort. Just an empty space where 'some table' is expected.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #9909

### CODE REVIEW

**Comment by tsteur** [comment]
FYI: This needs to be rebuilt in Piwik 3

**Comment by tsteur** [comment]
It currently shows like this:

image

To be a bit more clear can we maybe write something like "Goal $goalName conversions by type of visit are not shown ..." and "Conversions overview by type of visit is not shown"

**Comment by tsteur** [comment]
Maybe we could even still show the headline as usual and below write "there is no data for this report because there were no conversions ... "

**Comment by sgiehl** [comment]
Now the headline should still be visible when the message is shown.

**Comment by tsteur** [comment]
:+1:

**Pull request merged**
