### PR TITLE
More visible row actions

### PR DESCRIPTION
**Pull request by tsteur**
The row actions are so powerful but they are barely visible. Instead it would be great if they got more attention and this way we give the brand color also more shine :)

Later might change it to some green or some other color we will see.

### CODE REVIEW

**Comment by mattab** [comment]
Really like the idea of making the row icons more visible.... But can't say that red icons work in this case. Could we use another color but not the red one?

**Comment by tsteur** [comment]
Yes we would have used a nice green but that creates complexity for themes etc. And as said we will likely change the color again indirectly once we possibly change the brand color.

**Comment by mattab** [comment]
Ok then let's wait for the change of color :+1: (these icons in red are not possible IMO)

**Comment by tsteur** [comment]
This was already done I Think

**Pull request closed without merging**
