### PR TITLE
Send 403 header on failed Login

### PR DESCRIPTION
**Pull request by pebosi**
Proposal for #14085

### CODE REVIEW

**Comment by Findus23** [comment]
Hi,

Thanks for the PR.
I don't think you can assume everyone is using `HTTP 1.0`.
Thankfully since PHP 5.4 there is a function for this: [`http_response_code()`](https://php.net/http-response-code).

**Comment by Findus23** [comment]
Or maybe use the exiting helper function:
https://github.com/matomo-org/matomo/blob/65b5523adf92c686f1448e858fa428b57d68a674/core/Common.php#L1196

@tsteur Is there any reason why there is a custom function?

**Comment by tsteur** [comment]
Looking at the content of the method it definitely seems like there's a reason fir it by the looks. But maybe `http_response_code()` was never used and that's why it was needed. Not sure.

**Comment by pebosi** [comment]
Changed to use http_response_code

**Comment by diosmosis** [comment]
Works for me, thanks for the contribution @pebosi!

**Pull request merged**
