### PR TITLE
[Vue] do not angularjs watcher in createAngularJsAdapter on first watch execution

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

As title.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — APPROVED** [review]
seems like vue build failed, but looks unrelated

**Comment by tsteur** [comment]
@sgiehl @peterhashair I believe this should go into `next_release` Otherwise the regression won't be fixed?

**Comment by peterhashair** [comment]
@tsteur ah, this is already merged to 4.x-dev. should I do a new PR copy of this to next_release ?

**Comment by tsteur** [comment]
be good. You'll probably want to do a `cherry-pick` for this merge so there won't be any merge conflicts later . Like create a new branch off `next_release` and then maybe do something like `git cherry-pick fc4109e79a79e29a75f0cee582eab1d23cbb9eb3`

**Pull request merged**
