### PR TITLE
Fix region mappings for map widget where possible

### PR DESCRIPTION
**Pull request by sgiehl**
Due to switching from FIPS to ISO with GeoIP2, almost all region maps are currently not showing any visits.
By adding the ISO codes to the existing maps (where an exact mapping is possible), the visits for regions should be shown for more regions again.
Some of the maps will still be broken or show incorrect data, as the iso codes can't be added everywhere.

refs #13347

### CODE REVIEW

**Comment by sgiehl** [comment]
This should fix/improve the region mappings for most countries. For some countries a proper mapping isn't possible as they were completely reorganized, they will still show no data for GeoIp2. For some others the new mapping might not be fully exact, but it should be at least better than having none.

**Comment by tsteur** [comment]
@sgiehl as the tests pass I reckon it's maybe good to merge? Or should we maybe wait to Matomo 4 since it's not a priority right now and the original issue is scheduled for matomo 4? Not sure how to test it so feel free to merge.

**Comment by sgiehl** [comment]
@tsteur  We still need to create completely new maps for Matomo 4. But as that might take some more time, I thought it might be useful to fix most of the region maps to work correctly with GeoIP2. It was not possible for all countries, as a mapping from FIPS to GeoIP2 ist not possible (e.g. for France).
To test that, you can simply generate some visits and check if the regions on the maps are highlighted. (Only US and CA were already working before this change)

**Comment by tsteur** [comment]
image
image

worked.

**Pull request merged**
