### PR TITLE
[Vue] convert remaining usersmanager controllers to Vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR is based off of https://github.com/matomo-org/matomo/pull/18583.**

Changes:
* Convert personal-settings controller and twig template parts to PersonalSettings.vue component and NewsletterSettings.vue component.
* Convert anonymous-settings controller and twig template parts to AnonymousSettings.vue.

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis guess this one is based on #18583, right?

**Comment by diosmosis** [comment]
@sgiehl yes, added the missing bit to the description.

**Review by peterhashair — COMMENTED** [review]
a couple of screenshots need an update.
`#currentUserPassword` is probably used twice on the user edit password page,  maybe consider changing from id to class.  
Other than that looks good to me.

**Comment by diosmosis** [comment]
@peterhashair fixed the build + maybe fixed a random test failure in https://github.com/matomo-org/plugin-CustomAlerts/pull/109. ok to merge both?

**Comment by peterhashair** [comment]
@diosmosis could be my cache. Still has the multiple HTML ID #currentUserPassword on one page. But other than that both looks good to me.

**Comment by diosmosis** [comment]
@peterhashair that was there before so I didn't look into it, but I'll see if I can fix it now.

**Comment by peterhashair** [comment]
@diosmosis right, don't waste too much time on it, it's not even an error just, warning, I will convert to a seperate issue.

**Comment by diosmosis** [comment]
@peterhashair oh i just fixed it :+1:

**Review by peterhashair — APPROVED** [review]
Once tests are passed, good to merge.

**Pull request merged**
