### PR TITLE
Improve responsive layout header

### LINKED ISSUE #9250: Improve responsive layout header to use less space and look better
My suggestion is to change this:

before

into this:

after

### PR DESCRIPTION
**Pull request by tsteur**
fixes #9250 as discussed making the selectors full width. We could do probably many more tweaks but for this we need https://github.com/piwik/piwik/issues/9100 etc

### CODE REVIEW

**Comment by mattab** [comment]
noticed a small possible regression: when website name is long, the website selector in Mobile resolution now displays `...` instead of the website name truncated:

website name shown as

**Comment by tsteur** [comment]
Yeah I know but it's not easily fixable. I tested this case as well and decided to not fix it as it's complicated. If this is a problem let's rather not merge this PR and move issue to different milestone

**Comment by mattab** [comment]
@tsteur I reverted this PR as noticed that the Segment names were not truncated anymore in the segment editor. This was causing the "Edit" button to be hidden and one could not edit the segment.

**Comment by tsteur** [comment]
In this case I suggest to move this issue out of the current milestone

**Pull request merged**
