### PR TITLE
Add tests for piwik/searchengine-and-social-list#14

### PR DESCRIPTION
**Pull request by piwikjapan**
Add tests for piwik/searchengine-and-social-list#14
Use kanji strings instead of just 'Piwik'.

### CODE REVIEW

**Comment by piwikjapan** [comment]
Maybe, mb_detect_encoding which indicated multiple Japanese encodes did not work on this environment.

**Comment by mattab** [comment]
Hi @piwikjapan 
Thanks for the pull request!

the build is failing on Travis CI - do the tests work for you locally?

**Comment by mattab** [comment]
@piwikjapan since the changes in https://github.com/piwik/searchengine-and-social-list/pull/14 were merged only few days ago, to have those changes included in your pull request, you must use the version ` 1.3.1 ` of this library (try running `composer update piwik/piwik/searchengine-and-social-list`)

**Comment by piwikjapan** [comment]
I updated to the version 1.3.1, and ./console tests:run ./plugins/Referrers/tests/Unit/SearchEngineTest.php shown below:

1) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #1 ('www.118700.se', array(array('q'), 'sok.aspx?q={k}', '118 700'))
www.118700.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

2) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #22 ('www.allaverksamheter.se', array(array('What'), 'SearchResult.aspx?What={k}', 'Allaverksamheter'))
www.allaverksamheter.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

3) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #332 ('www.isodelen.se', array(array('Keywords'), 'sokresultat?Keywords={k}', 'Isodelen'))
www.isodelen.se
Failed asserting that false is true.

/home/yamachan/piwik/plugins/Referrers/tests/Unit/SearchEngineTest.php:144

4) Piwik\Plugins\Referrers\tests\SearchEngineTest::testMissingSearchEngineIcons with data set #424 ('www.riksdelen.se', array(array('What'), 'SearchResult.aspx?What={k}', 'Riksdelen'))
www.riksdelen.se
Failed asserting that false is true.

but there are not essential and all my tests (that's I am asking to merge) were successful.

**Comment by sgiehl** [comment]
we need to add some icons for those new search engines. Btw. could you please undo the changes to the access mode of core/Tracker/PageUrl.php. You've changed it from 100644 → 100755

**Comment by piwikjapan** [comment]
I watched https://travis-ci.org/piwik/piwik/jobs/151990012 carefully,

Piwik\Plugins\Referrers\tests\SearchEngineTest::testExtractInformationFromUrl with data set #75
(Successfully with utf-8. Therefore, it does not show anything.)

l. 1158
3) Piwik\Plugins\Referrers\tests\SearchEngineTest::testExtractInformationFromUrl with data set #76
Unsuccessfully with Shift_JIS.

 Array (
     'name' => 'Yahoo! Japan Images'
-    'keywords' => '君の名は。'
+    'keywords' => '?n?̖??́b'
 )

l. 1171
4) Piwik\Plugins\Referrers\tests\SearchEngineTest::testExtractInformationFromUrl with data set #77
Unsuccessfully with EUC-JP.
 Array (
     'name' => 'Yahoo! Japan Images'
-    'keywords' => '君の名は。'
+    'keywords' => '????̾?ϡ?'
 )

On Travis CI,
I thought that all tests except UTF-8 fell. But another tests except UTF-8 (e.g. with EUC-KR) has been successfully.
Therefore, the problem shown when some charsets in SearchEngines.yml, the first charset will be successful, but the second and third will fail.

It means,

actual condition:

Yahoo! Japan Images:
  -
    urls:
      - image.search.yahoo.co.jp
    params:
      - p
    backlink: 'search?p={k}'
    charsets:
      - utf-8     -> success
      - euc-jp    -> fail
      - ms932     -> fail

my imagination:

    charsets:
      - ms932     -> will be successful
      - utf-8     -> will fail
      - euc-jp    -> will fail

or:

    charsets:
      - euc-jp    -> will be successful
      - ms932     -> will fail
      - utf-8     -> will fail

**Comment by sgiehl** [comment]
Travis won't use the new version of piwik/searchengine-and-social-list unless the composer.lock is changed here.

**Comment by mattab** [comment]
@piwikjapan try running `composer update piwik/piwik/searchengine-and-social-list` in your branch and push to the pull request, this may fix your issue?

**Pull request closed without merging**
