### PR TITLE
Add command to install or update a plugin from the marketplace

### LINKED ISSUE #21003: Add console plugin:install
Add a console command to install a plugin: 
`console plugin:install ...`

## Summary
The console can uninstall, activate and deactivate, but strangely, cannot install plugins.  The command `console plugin:install` would facilitate automated installs, and replace our current clumsy wget-unzip method.  The command should get the latest version of the plugin that is compatible with the currently-installed Matomo version, e.g. by parsing through https://plugins.matomo.org/api/2.0/plugins/:pluginname/info .  E.g. if you have Matomo 4.x and want the ExtraTools plugin (https://plugins.matomo.org/api/2.0/plugins/EXtraTools/info) you would get version "4.1.0-beta5" and not version "5.*".

## Your Environment
* Command line
* Matomo Version: any
* PHP Version: any
* Server Operating System: Linux

### PR DESCRIPTION
**Pull request by tsteur**
### Description:

fix https://github.com/matomo-org/matomo/issues/21003

Adds a new command `marketplace:install-or-update-plugin` to install or update a plugin from Marketplace.

Kept it consistent with `plugin:activate/deactivate` usage and output but decided to go for the `marketplace` namespace in the command name so it's more clear it'll download it rather than installing a plugin from a local zip file (which a `plugin:install` command might do). Could rename it though. In any case the command will only work if the Marketplace plugin is installed and activated.

#### Example usage:

```bash
./console marketplace:install-or-update-plugin IPReports
./console marketplace:install-or-update-plugin IPReports GoogleAnalyticsImporter
```

An error will be shown if plugin does not exist or no version is compatible or if directories aren't writable.

#### Additional fix

Added a check if the file is downloadable. If not, an error message will be shown. This happens when eg trying to install or update a premium feature but the license is missing or expired. Without this fix, it would just show a random error message that ZIP file failed to extract.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Hi @tsteur, thanks for the PR. Have you by chance seen https://github.com/matomo-org/matomo/pull/22640? There's a reasonable community PR for this already in progress, and it's also linked from the issue.

**Comment by tsteur** [comment]
Didn't see it! So sorry about that. Feel free to merge the other one if that's looking all good. Note: Need to make sure to check for config file being writable etc and to get proper error message when trying to install/update a premium feature without valid license.
Also should use DI there for there `PluginInstaller`. 
In case the person doesn't make the adjustments, can still look at this one.

**Comment by jsantos42** [comment]
@tsteur what do you mean DI?
Just checked my implementation and, indeed, when I try to install a paid plugin I get 
`Incompatible archive: PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`
I'll reuse your code of [422158b](https://github.com/matomo-org/matomo/pull/22669/commits/422158b6961852dbb05d67f1c2ffe5f22bd45399), thanks!

Also, do we really need to check that the config file is writable? I've had no errors with that.

**Comment by tsteur** [comment]
>  what do you mean DI?

I mean dependency injection with that. Basically below so that other plugins can hook into the "PluginInstaller" as required:

```php
$installer = StaticContainer::get(PluginInstaller::class);
```

Re config check: I've added because that's also what we're doing in https://github.com/matomo-org/matomo/blob/5.2.0-b4/plugins/Marketplace/Controller.php#L465 in the user interface and wanted to match this behaviour. Unsure if it's 100% needed, just wanted to play it safe.

**Comment by jsantos42** [comment]
> > what do you mean DI?
> 
> I mean dependency injection with that. Basically below so that other plugins can hook into the "PluginInstaller" as required:
> 
> ```
> $installer = StaticContainer::get(PluginInstaller::class);
> ```
> 
> Re config check: I've added because that's also what we're doing in https://github.com/matomo-org/matomo/blob/5.2.0-b4/plugins/Marketplace/Controller.php#L465 in the user interface and wanted to match this behaviour. Unsure if it's 100% needed, just wanted to play it safe.

Oh my bad, I thought it was some component on your codebase 😅

**Pull request closed without merging**
