### PR TITLE
merge 3.x to 4.x

### PR DESCRIPTION
**Pull request by diosmosis**

### CODE REVIEW

**Comment by diosmosis** [comment]
@tsteur the ArchiveCronTest failure on 3.x is back now, going to merge this, if it sticks around after #15117 then will look into fixing it.

**Comment by sgiehl** [comment]
@diosmosis  it might be better to push merges from 3.x-dev to 4.x-dev directly to the 4.x-dev branch, without using a PR. The problem with the PR is, that with our merge strategy all commits are squashed into one. That means, the next time some tries to merge 3.x-dev to 4.x-dev all commits in this PR will be tried to merge again, as they are not included in 4.x-dev. That doesn't happen when pushing the merge directly or if we would allow another merge strategy.

**Comment by diosmosis** [comment]
@sgiehl 👍 didn't think of that. Think it would be better to revert this and merge on the CLI manually?

**Comment by sgiehl** [comment]
not needed. Another merge from 3.x-dev to 4.x-dev should be enough as all commits should be tried to merge again, even if the changes have already been merged...

**Pull request merged**
