### PR TITLE
[Vue] provide change abort functionality for Fields via model modifiers

### LINKED ISSUE #19509: User Keyword Search
When I am writing the FAQ, I found the keyword search under user manage is quite bugged. I guess maybe we need to add a debounce on the key-up events.

 

https://user-images.githubusercontent.com/3783072/178173781-6bd205c5-142f-436f-8fa1-e82ecc9df364.mp4

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.11
* PHP Version: 8.0
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Fixes #19509

Original problem: some plugins need to prevent an input from changing, like Funnels which needs to prevent a checkbox from changing until the user deals w/ a modal, but Vue will not notice when a model value *doesn't* change, and won't reset the input value in the case the parent component doesn't update the model value.

Fixes that didn't work:

- resetting the input value before emitting update:modelValue. This reset the input state to what the modelValue was in case the parent didn't update the modelValue, but changing the input's value reset the text cursor position which makes editing the middle of an input/textarea very annoying.
- resetting the input after emitting update:modelValue. This ends up always resetting the value because there's no way to know when the emitted event is done being handled, causing a consistent flash/backspace when typing.

This solution (only other one I could come up with):

This PR adds an 'abortable' model modifier that can be used to specify a Field can have it's change aborted. In this case, the event sent to update:modelValue has an abort() function that will reset the input value. This way the input value is only reset if the event handler aborts it, so the text cursor position never changes and there is no weird flash/backspace when typing. It can't really be used like a normal model modifier (ie, `v-model.abortable`) since it changes the event value, but this functionality is used very rarely in Matomo so I don't think that's much of an issue.

Usage is like:

```
<Field :uicontrol="text" :model-value="value" :model-modifiers="{abortable:true}" @update:model-value="doUpdate($event)"/>

doUpdate(event: AbortableEvent<string>) {
    if (...) {
        event.abort();
        return;
    }

    this.value = event.value;
}
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — APPROVED** [review]
test UI working as expected

**Comment by sgiehl** [comment]
@diosmosis could you maybe send me a link to a PR where that abort modifier is being used? I would like to see that somewhere in action 🙈

**Comment by diosmosis** [comment]
@sgiehl you can look in pull request 93 in Funnels. The last commit adds it. I tested locally before pushing.

**Comment by sgiehl** [comment]
@diosmosis Even though the Funnel plugins seems to require the usage of the abort event in some other cases, it seems to work for the one case where you have implemented it. 👍

**Review by sgiehl — APPROVED** [review]

**Comment by diosmosis** [comment]
@sgiehl can you let me know on the Funnels pr which places so I can add them there?

**Pull request merged**
