### PR TITLE
Changed wording of YouAreOptedIn

### LINKED ISSUE #12954: Please change wording of "You are currently opted in."
When we added the opt-out iframe in the past we received a complaint that we were asserting consent where no consent had been given. This was due to the message in the opt out frame defaulting to "You are currently opted in." the first time it is displayed (before the user has had a chance to opt out).

While the wording doesn't have any impact in how we actually regard the data collection, it is now more important to communicate that we do not regard a lack of response as positive consent. (e.g. [GDPR section 32](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679) states "Silence, pre-ticked boxes or inactivity should not therefore constitute consent.")

Therefore I feel that is it safer to express the status (in english) as "not opted out" rather than "opted in".

```json
      'YouAreOptedIn' => 'You are not currently opted out.',
```

Related #12810

### PR DESCRIPTION
**Pull request by electric-paper**
fixes #12954

### CODE REVIEW

**Comment by fdellwing** [comment]
I'm not an english native, but shouldn't it be `You are currently not opted out.`?

**Comment by electric-paper** [comment]
Of course, you're right. Changed it to `You are currently not opted out.` 
My apologies.

**Comment by electric-paper** [comment]
Changed the key to `YouAreNotOptedOut` 
I'm not quite sure about the failing checks though, seems to be a normal thing?

**Comment by diosmosis** [comment]
I think the text here could be shortened to just "You are not opted out." 'currently' seems unnecessary here. What does everyone think?

**Comment by mattab** [comment]
sounds good @diosmosis

**Comment by tsteur** [comment]
To get this merged I would say easiest is to create a new PR with only the change in `optOut.twig` https://github.com/matomo-org/matomo/pull/13187/files#diff-51d31859e47190479808b5b0d8b89b87 and the change in `en.json` as we cannot merge any changes to other language files unfortunately. Would that be possible?

**Comment by tsteur** [comment]
Created the PR here: https://github.com/matomo-org/matomo/pull/13538 cheers @electric-paper for this change 👍

**Pull request closed without merging**
