### PR TITLE
Allow Geoip to auto-update geolocation databases ending with 'mmdb.gz'

### PR DESCRIPTION
**Pull request by mattab**
from https://github.com/piwik/piwik/issues/11049

### CODE REVIEW

**Comment by sgiehl** [comment]
LGTM, but I'm unsure if that really solves the issue correct.
As far as I've understood, the problem is that Piwik is unable to auto update a geoip2 database, which is not support by Piwik, but a third party plugin. maybe it would be better to create hooks, that make it possible for the third party plugin to extend those method?

**Comment by s1awa** [comment]
Download completes now, but Piwik does more checks to the file which fail. See: https://github.com/piwik/piwik/issues/11049#issuecomment-269145896

**Comment by mattab** [comment]
> maybe it would be better to create hooks, that make it possible for the third party plugin to extend those method?

I think it's supposed to already work this way. the code triggering the error is: https://github.com/piwik/piwik/blob/comment_match_implementation/plugins/UserCountry/GeoIPAutoUpdater.php#L506-511

as you can see it's calling `$provider->getLocation(array('ip' => GeoIp::TEST_IP));` which should use the GeoIP2 provider here. So i'm not sure what the error is... @sgiehl or @s1awa maybe you'd like to take a look...

**Comment by s1awa** [comment]
Might be related to the problem with the GeoIP2 Plugin: https://github.com/piwik/piwik/issues/11034

I'm not familiar with the Piwik code base. I need more time to dive in the code which I currently do not have. End of January I can contribute more than reporting issues.

**Comment by mattab** [comment]
Hi @s1awa 

Do you maybe have some time to take a look at this PR and making the geoip auto updater work?

**Comment by s1awa** [comment]
@mattab The plugin dev has not fixed his plugin yet. My guess is this PR would pass if the Plugin would work.
https://github.com/diabl0/piwik-geoip2/issues/3

**Comment by mattab** [comment]
@s1awa Sounds good! Maybe you have a bit of time to help the plugin developer make the plugin work?

**Pull request merged**
