### PR TITLE
Simplified the cache configuration

### PR DESCRIPTION
**Pull request by mnapoli**
A few simplifications for the cache config.

By the way why use the file cache in tests? I'm afraid of all the possible side-effects.

I also simplified the Translator cache config by simply getting the configured cache (hopefully the file cache in tests will not create problems)

ping @tsteur

### CODE REVIEW

**Comment by mattab** [comment]
A PR to review for you @tsteur

**Comment by tsteur** [comment]
I haven't tested it. Presume it works and can be merged.

**Comment by mattab** [comment]
Hi @mnapoli  feel free to merge after rebase

**Comment by mnapoli** [comment]
> By the way why use the file cache in tests?

**Comment by tsteur** [comment]
Yes, otherwise they don't pass and it improves test execution time

**Pull request merged**
