### PR TITLE
Provide various release channels, eg let user choose between latest stable and LTS version

### PR DESCRIPTION
**Pull request by tsteur**
**DO NOT MERGE**

refs #8549

Here is a screenshot: http://builds-artifacts.piwik.org/piwik/piwik/8549/15097/UIIntegrationTest_admin_settings_general
- [x] Test agains once changes in `api.piwik.org` are made
- [x] After merge update docs that mention `[Debug] allow_upgrades_to_beta` afterwards as it was changed to `[General]release_channel`

Plugins can now very easily provide their own custom release channels but we're not making it a public API as it won't be needed for now. The API might change once there is an actual use case for it. Eg right now they require that the latest available version number is checked via HTTP and that this API returns only a version number etc (not eg a JSON etc). Such things could be changed if it ever becomes API. 

Possible use cases for custom release channels in the future:
- Someone wants to provide a channel for nightly builds
- Someone wants to provide an intranet server that serves updates as the actual Piwik instances might not be connected to the Internet
- Someone wants to provide custom updates for users/clients. Eg we could have a central server and a  client's Piwik connects to this central server where we have a prepackaged update for them including custom Plugins etc.
- It will be easily possible to define new release channels for Piwik 4.X, Piwik 5.X, ...

Such things were kinda possible before but much harder to do.

### CODE REVIEW

**Comment by tsteur** [comment]
I added label needs review but we should not merge it yet as we need to wait for changes in `api.piwik.org` to be done

**Comment by diosmosis** [comment]
Code looks good, and +1000 for the concept.

**Comment by tsteur** [comment]
@mattab what's the current status of `api.piwik.org`? Are they made? Can we merge this one?

**Comment by mattab** [comment]
@tsteur Changes are made, and deployed, to api.piwik.org

**Comment by mattab** [comment]
For reference, API URLs for channels are:

 * Latest beta: http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_beta
 * Latest stable: http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_stable
 * Latest 2.X beta: http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_2x_beta
 * Latest 2.X stable: http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_2x_stable

**Comment by mattab** [comment]
@tsteur when merging this to 3.X branch, you can  assume we'll have the 3.X LTS channel. so maybe we just replace 2.X by 3.X in the UI in 3.0.0 branch?
and when merging it, feel free to issue PR in api.piwik.org to add the new `3x_` config settings...

**Comment by tsteur** [comment]
> so maybe we just replace 2.X by 3.X in the UI in 3.0.0 branch?

I think we might just add a 3.X_beta and declare it as experimental or actually I think we'll think about it as soon as we actually release a beta :)

**Comment by mattab** [comment]
> or actually I think we'll think about it as soon as we actually release a beta :)

Ok feel free to post any thought in #8836

**Comment by mattab** [comment]
>  After merge update docs that mention [Debug] allow_upgrades_to_beta afterwards as it was changed to [General]release_channel 

All good it wasnt documented anywhere

**Pull request merged**
