### PR TITLE
Auto zoom real time and visitor map

### LINKED ISSUE #4301: Visitor Profile - Zoom map as near as possible
Could be useful to use the map zoom to cover all locations as near as possible to see as many details as possible.

e.g. show only Germany if all visits are from this country.

Maybe it could be even possible to make the country names clickable and on click on the country name it displays/zooms the specific country?

### PR DESCRIPTION
**Pull request by tsteur**
Tested it locally and worked. 

Real-time map: Zooming into a country when all visits come from same country. Zooming into a continent when all visits come from same continent.

Visitor map: Zooming into a country when all visits come from same iso code... 

Not sure actually how often this happens in real life.

fix #4301

### CODE REVIEW

**Comment by fdellwing** [comment]
> Not sure actually how often this happens in real life.

We provide industry software, it happens every day for us ;)

**Comment by diosmosis** [comment]
tested locally, works well

**Comment by fdellwing** [comment]
Well I would have not merged it until #13691 is resolved, but ok. I guess there will be only a few questions why people are seeing an empty map.

**Comment by tsteur** [comment]
We could otherwise disable temporarily the zoom into country and only zoom into continent if that helps until the other issue is fixed...

**Pull request merged**
