### PR TITLE
Send the X-Frame-Options: SAMEORIGIN header for tracker responses

### LINKED ISSUE #20459: Matomo allows clickjacking - missing X-Frame-Options header
The response of GET /matomo.php is frameable, which allows potential clickjacking.

## Context

Matomo does not add all best practice headers in responses. An attacker can be loaded by an attacker within an iframe, allowing overlay attacks.  This technique allows the attacker to circumvent defenses against cross-site request forgery, and may result in unauthorized actions.

https://portswigger.net/web-security/clickjacking

## Expected Behavior

Set the X-Frame-Options either to DENY or SAMEORIGIN.
## Current Behavior

The X-Frame-Options are not set.
## Possible Solution

Set the X-Frame-Options either to DENY or SAMEORIGIN.
## Steps to Reproduce (for Bugs)

1.GET /matomo.php HTTP/1.1
2. look at the headers returned

## Your Environment

* Matomo Version: Matomo version 4.13.1
* PHP Version: PHP 8.1.14 
* Server Operating System: RedHat 8
* Additionally installed plugins:

* Browser:
* Operating System:

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #20459

This PR adds the `X-Frame-Options: SAMEORIGIN` header to all tracker responses.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Can we actually add this header? Wouldn't it prevent to use the tracking endpoint as a tracking image? Would that then fail to load if it's not on the same origin?

**Comment by bx80** [comment]
@sgiehl I ran some tests, with a tracking image loaded directly in the page with an `` tag there is no issue, but if the image is loaded with `<iframe src="matomo.php?..."></iframe>` then the tracking request will be processed by the server but upon receiving the response the browser will display a 'blocked' message instead of the transparent image.

Since we're supporting [tracking a page within an iframe](https://matomo.org/faq/how-to/how-do-i-track-a-website-within-an-iframe/) then it seems like we can't add this header by default without breaking iframed sites using image tracking.

I suppose we could add a config flag option to enable it for sites where it would be beneficial, what do you think?

**Comment by michalkleiner** [comment]
I think a set of config rules for this and other headers that people requested lately would be a good idea. In a way people can apply these already on self-hosted applications, but providing a Matomo way might be good as well, with the majority being optional.

**Comment by sgiehl** [comment]
Personally I wouldn't put too much effort into headers that are requested only a few times. People who need those headers, can also configure them in their webserver. In terms of security most headers imho don't matter much for the tracking endpoint. You can't prevent others from abusing a foreign tracking endpoint if they want to do that. 
And the X-Frame-Options will actually only deny others from using an "empty response" from the tracking endpoint within an iframe. 
I would vote against adding new config options around additional headers. It doesn't bring much benefit, but we will have the effort to maintain such stuff in the future. Matomo is already over-bloated with options that are barely used, we shouldn't go on with that.

**Comment by bx80** [comment]
Agreed, let's close this issue as `wontfix` since we can't add the header by default to the potential to break existing usage. Instead the header can be added by the web server if/when required.

**Pull request closed without merging**
