### PR TITLE
Issue #19850 removing couple columns which makes doesnt make sense

### PR DESCRIPTION
**Pull request by dzhibas**
### Description:

Just like mentioned in issue https://github.com/matomo-org/matomo/issues/19850 removing user amount and unique visitors from columns

image

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Hi @dzhibas, thank you for taking the time to contribute your code and opening the PR.

If you look at the SystemTestsCore, SystemTestsPlugins and UI tests failures, there are other areas of the codebase that need adjusting when removing columns from the Users data table.

Is it ok for you to have a look and adjust the tests as well?

**Comment by dzhibas** [comment]
sure will fix those

**Comment by michalkleiner** [comment]
Hi @dzhibas, are you still interesting in tweaking the tests? It's ok if not, just let us know and we can close the PR.

**Comment by sgiehl** [comment]
Closing for now due to inactivity. @dzhibas If you are keen to finish the work, feel free to do so and reopen the PR once your done.

**Pull request closed without merging**
