### PR TITLE
Don't hardcode plugins directory

### PR DESCRIPTION
**Pull request by tsteur**
Instead use the method that defines the plugin dir. No logic should change here. Doing this in preparation to potentially provide a way to define multiple plugin directories. But for this we first need to make sure that all code is using the same method when looking for plugin directory.

### CODE REVIEW

**Comment by diosmosis** [comment]
Not sure if these need to change, but seeing the `/plugins/` in other places like:

* core/testMinimumPhpVersion.php
* core/ReportRenderer/Pdf.php
* core/Tracker/Response.php
* core/FrontController.php
* plugins/CorePluginsAdmin/PluginInstaller.php
* plugins/CorePluginsAdmin/Controller.php
* LanguagesManager files
* plus other places

**Comment by tsteur** [comment]
cheers @diosmosis added it to more places where needed (didn't add it when they included/required specific files from a plugin)

**Comment by Findus23** [comment]
I guess this will (someday in the future) help with https://github.com/matomo-org/matomo/issues/12988 which allows easier docker images and similar things.

**Comment by tsteur** [comment]
Yes that can help with that. It may partially help us to at some point move the plugins directory somewhere else. May goal be likely to have it later possible to add more plugins directories while leaving the core plugins in the current place. After this exercise it seems likely too difficult though and I might fallback to symlinks instead. To be seen.

**Comment by Findus23** [comment]
@tsteur I think this docker image does use symlink tricks to get around this issue:
https://github.com/crazy-max/docker-matomo
https://github.com/crazy-max/docker-matomo/blob/master/entrypoint.sh

**Comment by diosmosis** [comment]
> didn't add it when they included/required specific files from a plugin

Will that be an issue if the plugins are located outside of PIWIK_INCLUDE_PATH . '/plugins'?

**Comment by tsteur** [comment]
> Will that be an issue if the plugins are located outside of PIWIK_INCLUDE_PATH . '/plugins'?

If all plugins were moved outside then yes. For my use case I'm not really planning on the possibility to move plugins in another directory. Only to pick up non-core plugins from a different directory. The core plugins be always in that path.

**Comment by diosmosis** [comment]
> If all plugins were moved outside then yes. For my use case I'm not really planning on the possibility to move plugins in another directory. Only to pick up non-core plugins from a different directory. The core plugins be always in that path.

Ah, I see, makes sense 👍

**Pull request merged**
