### PR TITLE
Recreates OmniFixture dump used for UI tests

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Many of our UI tests are using a prepared database dump to set up their fixture. This dump was last recreated somewhen before release of Matomo 4. So every test actually first performes an update from Matomo 3.16 to Matomo 5.
In addition that means that some data might not even be available for tests, like values for dimensions that had been added after the dump had been created.

This PR recreates the database dump and updates all screenshots accordingly.

There are a lot of changes in the screenshots. This is caused by the way our OmniFixture is created. It basically sets up all test fixtures that are defined in core tests at once. Due to many changes in such fixtures since Matomo 3.16, a lot of report data has changed now. I've looked through all the changes and too everything looked like a reasonable change in displayed report data only.

Some resulting screenshots in Treemap plugin also will need to be updated before merging this one.

Note: This will be required to run UI tests on TiDb

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Just out of curiosity, do we have some documentation on how to recreate the dump / omni fixture from a newer version?

**Comment by sgiehl** [comment]
@michalkleiner Yes. That's documented here: https://developer.matomo.org/guides/tests-system#omnifixture

**Review by mneudert — APPROVED** [review]
Do we need to give anyone a heads-up before merging this so they are aware that their test results could change?

**Comment by sgiehl** [comment]
@mneudert Any UI test that does not specify an own fixture by default uses this one. So it might affect certain plugins...

**Comment by sgiehl** [comment]
@matomo-org/plugin-reviewers We are going to update the dataset of UITestFixture with this PR. Any plugin UI test that relies on this fixture, might afterwards display different data, as there had been a lot changes since the fixture had been last updated. So if there are any tests not using a custom fixture, they might start failing afterwards.

**Pull request merged**
