### PR TITLE
Add a config option to improve admin page loading performance  in dev mode 

### PR DESCRIPTION
**Pull request by bx80**
### Story

AS A `Matomo developer`
I WANT `to avoid unnecessary slowness when testing thing in development`
SO THAT `I can deliver new features quicker`

### Description:

- When development mode is enabled most caching is disabled. This includes the caching of marketplace requests.
- Whenever an administration page is rendered the admin menu code will check for updated plugins and display the update count after the manage plugins menu entry, this works well when caching is enabled as it doesn't happen very often.
- With development mode enabled there is no caching for these checks and every administration page load makes API calls to `plugins.matomo.org` to check each plugin, this typically takes ~30 seconds for a page load.
- Although disabling the marketplace plugin avoids this problem, it isn't always feasible to do this when working on features related to the marketplace and cumulatively wastes a substantial amount of time waiting for very slow page loads.

This PR adds a DI config value `dev.disable_plugin_update_checks` which can be set in `config/environment/dev.php` as required which when enabled will avoid the admin menu plugin update check allowing pages load in 1-2 seconds instead of 25-39 seconds.

It should have no affect on normal usage and will only have any affect if enabled by a developer.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]
I can sense the preceding frustration from this PR :-D

I think it's a good addition, I had the same issue with slow page response as well but it didn't cross the line of wanting me to do something about it.

Is there anywhere we can reflect this in tests? E.g. for the number of updated plugins badge on the menu entry?

**Comment by sgiehl** [comment]
@bx80 Looks like this could be useful to be used for UI tests in general 👍 
We nevertheless should maybe try to avoid adding new config options for things that won't be used (much) outside of development.
I know we already have a lot of them, but we shouldn't try to blow the config up more and more. For that specific purpose I guess a simple DI config value should work the same, but wouldn't be shown in the config overview screen.

**Comment by bx80** [comment]
@sgiehl I've replaced the config.ini.php option with a DI environment config value :+1:
@michalkleiner It might be difficult to write reliable UI tests for this option at the moment, since it's not a user facing feature I don't think they're structly necessary here.

**Comment by sgiehl** [comment]
@bx80 I've pushed an additional commit to enable that option for UI tests in general. As no new test started to fail that should be fine and might even prevent future failures when a submodule plugin releases an update, but isn't updated yet. Before, the menu tests and plugin admin tests often started to fail in that case, as the update got visible.

**Review by sgiehl — APPROVED** [review]

**Pull request merged**
