### PR TITLE
Provide console command for adding a marketplace license key (#18070)

### LINKED ISSUE #18070: New console command "marketplace:add-license-key" which adds a marketplace license key
## Summary

Currently, it is not possible to add a license key to the Matomo installation via the console and one needs to log in to add it via the UI, which is cumbersome.

I'd like to have a `marketplace:add-license-key` command that adds a marketplace license key to the system. This comes in handy when automating things using the console for headless installs and updates.

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: 8.0.11
* Server Operating System: CentOS Stream
* Additionally installed plugins: CustomReports (v4.0.7), MediaAnalytics (v4.0.13)

### PR DESCRIPTION
**Pull request by ziegenberg**
### Description:

Adds a new console command marketplace:add-license-key which adds a marketplace license key (Fixes #18070)

This is the first draft. It does not implement any checks like it's done in the Marketplace API: https://github.com/matomo-org/matomo/blob/2ac2bc1aeaf8efce6bb9af92506311da99e1757f/plugins/Marketplace/API.php#L69-L95

I'd need some pointers for further implementing this, if checking the license key this is deemed necessary.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by ziegenberg** [comment]
The failing checks do not seem to be related to my change.

**Comment by tsteur** [comment]
@ziegenberg I see this PR is in draft. Not sure if that was you? Is that ready for a review?

**Comment by ziegenberg** [comment]
Hi @tsteur,

I left this in the draft state because it is most certainly not ready yet and I wanted to discuss my implementation before going to review. I suspect that I have misinterpreted the workflow here...

**Comment by tsteur** [comment]
@ziegenberg this looked all good to me. I would maybe just rename the command to be `set` license key instead of `add` license key.

**Comment by ziegenberg** [comment]
So you don't want to add any checks for validity while setting the license key?

**Comment by ziegenberg** [comment]
I quickly made the suggested changes and rebased onto current 4.x-dev

**Comment by tsteur** [comment]
@ziegenberg it depends what you are using the command for and how quick things need to go as the validation will take a bit of time. We have an API that you can use like `\Piwik\Plugins\Marketplace\Api::getInstance()->saveLicenseKey($licenseKey)` and then it will validate the license key and also invalidate caches. 

This API won't "remove/unset" the license key though. If an empty license key is provided, then you would need to call the API method `deleteLicenseKey()`. 

Overall this would be better indeed 👍

**Comment by ziegenberg** [comment]
@tsteur I added the checks using the API. Does this look good to you?

**Comment by tsteur** [comment]
Nice, that looks good and works nicely 👍  Thanks for that.

**Pull request merged**
