### PR TITLE
Make dashboard links working for all browsers

### LINKED ISSUE #12113: issue with Widgetized dashboards
hi

this issue is linked with https://github.com/piwik/piwik/issues/12014 (the second issue listed in is not fixed).

when I use widgetized dashboards, there is a link to my dashbord.
this link is following: `javascript:$('#dashboardWidgetsArea').dashboard('loadDashboard',%201);`
When I follow this link, there is an issue and I have only `[object Object]` displayed.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12113

### CODE REVIEW

**Comment by mattab** [comment]
IIRC this issue has happened before. 

* Could you add UI test to check this particular behavior?

**Comment by sgiehl** [comment]
No. Doesn't make much sense as it worked in chrome. This was a Firefox and
IE issue only.

**Comment by mattab** [comment]
ok :+1:

**Comment by mattab** [comment]
Works!

**Pull request merged**
