### PR TITLE
Ensure empty plugin settings are saved correctly

### LINKED ISSUE #22877: [Bug] SystemSetting not saving the settings for FieldConfig::TYPE_ARRAY if all options are unselected
### What happened?

We recently created a new `SystemSetting` called `anonymizeClickIds` for AdvertisingConversionExport plugin, below is the code to create the system setting.
```
$providers = AdvertisingConversionExport::getAvailableClickIdProviders();
        $defaultValues = [];
        $availableValues = [];
        foreach ($providers as $provider) {
            $defaultValues[] = $provider::ID;
            $availableValues[] = ['name' => 'anonymizeClickIds[]', 'value' => $provider->getName(), 'key' => $provider::ID];
        }
$this->makeSetting('anonymizeClickIds', $defaultValues, FieldConfig::TYPE_ARRAY, function (FieldConfig $field) use ($defaultValues, $availableValues) {
            $faqURL = Url::addCampaignParametersToMatomoLink(
                'https://matomo.org/faq/advertising-conversion-export/exported-clickids-have-value-as-anonymized/',
                null,
                null,
                'App.CoreAdminHome.generalSettings'
            );
            $field->introduction = Piwik::translate('AdvertisingConversionExport_AnonymiseClickIDSettingTitle');
            $field->inlineHelp = Piwik::translate(
                'AdvertisingConversionExport_AnonymiseClickIDSettingDescription',
                [
                    '<a target="_blank" rel="noreferrer noopener" href="' . $faqURL . '">',
                    '</a>',
                    '<br><br><strong>',
                    '</strong>',
                ]
            );
            $field->uiControl = FieldConfig::UI_CONTROL_CHECKBOX;
            $field->availableValues = $availableValues;
            $field->validate = function ($values) use ($defaultValues) {
                foreach ($values as $value) {
                    if (!in_array($value, $defaultValues)) {
                        throw new \Exception('Invalid value "' . $value . '"');
                    }
                }
            };
        });
```
This shows the setting correctly

image

But there is one error, if you unselect all the options and try to save the setting, the setting shows as saved successfully, but it reverts back to the last saved setting.

### What should happen?

We should be able to save the setting, with all the options as unselected.

### How can this be reproduced?

1. Activate `AdvertisingConversionExport` plugin.
2. Got to system settings, under Admin > System >GeneralSettings
3. Scroll down to AdvertisingConversionExport section
4. Unselect all the options for `Anonymise Click IDs` settings and press save
5. Refresh the page
6. Check the setting again.

### Matomo version

5.2.0

### PHP version

8.3

### Server operating system

Linux

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

Ubuntu 22.04

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

When an array setting was empty, it didn't get sent to the API for processing. We are using a custom empty value to signal that and the API to handle that here.

For Matomo 6 we may consider using json_encoded array instead though that would be a breaking change for now.

You can check that the integration test fails without the JS and PHP changes, and the original issue can also be reproduced by trying to unselect and save all the browsers in the ExampleSettingsPlugin.

Fixes https://github.com/matomo-org/matomo/issues/22877
Ref. DEV-18796

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
This should actually target `5.2.x-dev`. When it's available I can rebase that.

**Comment by michalkleiner** [comment]
I probably confused GH by the force-push and target branch change, so triggered the tests manually here — https://github.com/matomo-org/matomo/actions/runs/12415416589

**Comment by michalkleiner** [comment]
Force-pushed to re-trigger the tests.

**Review by caddoo — APPROVED** [review]
Tested and works ✅

**Pull request merged**
