### PR TITLE
Update to Kartograph 0.8.2

### LINKED ISSUE #8243: Visitor map NaN error in browser console
Hi, I found problem with visitor map, take a look on the screenshot:

zrzut ekranu 2015-06-29 o 17 10 00

Look at the console, we can see a lot of "NaN" errors. I think, this problem occur only if we will select Canada

### PR DESCRIPTION
**Pull request by barbushin**
Fixes #8243

### CODE REVIEW

**Comment by tsteur** [comment]
Nice, I thought about that last time but didn't think it would be that easy to upgrade Kartograph lib :+1:  It's quite a big version jump considering that it is `0.X.X`. We should probably test quite a bit whether everything still works? Do you know if there was changed a lot? Maybe it'd be better to include it in 2.14.1?

**Comment by barbushin** [comment]
I compared Piwik on Kartograph 0.8.2 with Piwik on Kartograph that was in master, and it looks like there is no difference how they works. But, anyway, it will be better if we do more tests, because I'm not so big expert in Piwik maps use cases :)

**Comment by mattab** [comment]
Looks good to me!

**Comment by mattab** [comment]
It seems the real time maps regressed, @barbushin can you reproduce this? let me know if not, cheers

**Pull request merged**
