### PR TITLE
In segment editor segment value input, bind to the actual value and not or condition object

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

In segment editor segment value input, bind to the actual value and not the OR condition object so it will update if the value changes w/o the OR condition instance changing.

Fixes: #PG-3021

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@diosmosis I can confirm this fixes the issue

**Review by sgiehl — APPROVED** [review]
Tested that locally, and it fixes the problem. Will trigger a re-run of the tests to be sure the related tests pass after building the vue files

**Comment by michalkleiner** [comment]
@AltamashShaikh can you link the issue this solves?

**Review by michalkleiner — APPROVED** [review]
Looks ok. UI test failures are unrelated.

**Comment by sgiehl** [comment]
@michalkleiner it fixes a regression that was reported for a plugin, but was actually caused by core.

**Comment by AltamashShaikh** [comment]
@michalkleiner #PG-3021 is the issue no.

**Pull request merged**
