### PR TITLE
Add postEvent for update site start and end

### PR DESCRIPTION
**Pull request by mikkeschiren**
### Description:

Sitesmanager is missing start and end hook for updating site. This pull requests add these.

### Review

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@mikkeschiren There are already generic events that can be used for any API method. e.g. `API.SitesManager.updateSite` and `API.SitesManager.updateSite.end`
See https://github.com/matomo-org/matomo/blob/1cbd6829992386587babf1a1ceba8542167aaee8/core/API/Proxy.php#L156-L348

**Comment by mikkeschiren** [comment]
Ok, saw that in docs now, but I am really unsure how to implement that from the docs.

Let say I have this in my plugin:

```php
    public function registerEvents()
    {
        return [
            'API.SitesManager.updateSite.end' => 'siteUpdated'
        ];
    }
    public function siteUpdated($endHookParams) {
        if (isset($endHookParams)) {
            $log = "value is $endHookParams";
        } else {
            $log = 'value is empty';
        }
       return $log
    }
```

The variable always return value is empty.

Do you have en example that uses the API method for `registerEvents()`?

**Comment by mikkeschiren** [comment]
Ok, found it, SiteManager had an example:

[recordWebsiteDataInCache](https://github.com/matomo-org/matomo/blob/89ba64ef2911890ffa100f88d093126450e2869f/plugins/SitesManager/SitesManager.php#L186)

See if I can help to update the docs on this.

**Comment by mikkeschiren** [comment]
No still a mystery how to do that... I post in the forum.

**Comment by mikkeschiren** [comment]
This was solved: https://forum.matomo.org/t/using-registerevents-for-api-methods/61611/2

**Comment by sgiehl** [comment]
Glad to hear you were already able to solve that. The first parameter for that `end-`event is the return value. For methods without any return value, that is always `null`.

**Pull request closed without merging**
