### PR TITLE
Updated library: jquery-3.6.1

### PR DESCRIPTION
**Pull request by tassoman**
### Description:

Actual library [jQuery 2.2.4 is suffering of 3 XSS vulnerabilities and a Prototype Pollution](https://security.snyk.io/package/npm/jquery/2.2.4).

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Hi @tassoman 
We most likely won't change that for Matomo 4 to avoid possible problems with Matomo plugins or Matomo for wordpress. We are currently preparing Matomo 5, where we might consider to also update jQuery (if it doesn't cause regressions with wordpress).
Would you mind to rebase/change your PR to target `5.x-dev` or create a new PR for that if that is easier.

**Comment by tassoman** [comment]
Wordpress [already has jQuery 3.6.0 ](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/js/jquery/jquery.js) in it since 2 years ago. 
They also have **jQuery Migration** already set. No worries for breaking.

I've already patched my Matomo 4.11.x package but file integrity checker gives back false positive error. 
So matomo installation couldn't be checked for integrity because of jquery.min.js substitution. 
This also is a security flaw in the system. We don't want to lower our security level in core system.

**Comment by sgiehl** [comment]
@tassoman We are commint all the npm libraries that are required for Matomo to run. I've therefor created a new PR, that contains all required jQuery files.
Closing this on in favor of #19989

**Comment by tassoman** [comment]
Awesome, thanks a lot!

**Pull request closed without merging**
